-- ═══════════════════════════════════════════════════════════
-- Fix sentences: BRAINY 7 (klasa 7, szkola podstawowa)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 354 unikalnych slowek z Brainy 7 (Macmillan).
--
-- Statystyki:
--   - 355 wpisow w data.js (8 unitow)
--   - 1 duplikat synonimu word_pl ('Czy mozesz wypelnic ten formularz?'
--     — Unit 2 'Can you fill in this form, please?' + Unit 7 'Could you
--     fill in this form, please?') — pominiete w SQL, UPSERT trzyma
--     jedna wartosc (synonim, brak straty informacji).
--   - 354 unikalnych zdan w word_sentences
--
-- Tematy unitow:
--   Unit 1 (33): film + kino + obsada + zaproszenia
--   Unit 2 (45): wyglad + materialy + przestepstwa
--   Unit 3 (40): podroze + zwiedzanie + transport
--   Unit 4 (50): zakupy + porównania + opinie
--   Unit 5 (47): sztuka + tworzenie + wyrazenia
--   Unit 6 (45): sport + miejsca + rozkazy + can/may
--   Unit 7 (45): hobby + przedmioty + szkola + would prefer
--   Unit 8 (50): jedzenie + zdrowa dieta + restauracja
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — Film, cinema, cast, invitations (33)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'obsada', 'Obsada filmu jest świetna.', 'The cast of the film is great.'),
('brainy7', 'reżyser', 'Reżyser zrobił świetny film.', 'The director made a great film.'),
('brainy7', 'statysta/statystka', 'W filmie było wielu statystów.', 'There were many extras in the film.'),
('brainy7', 'aktor grający główną rolę', 'Aktor grający główną rolę dostał nagrodę.', 'The lead actor got an award.'),
('brainy7', 'aktorka pierwszoplanowa', 'Aktorka pierwszoplanowa jest piękna.', 'The lead actress is beautiful.'),
('brainy7', 'główny bohater', 'Główny bohater ratuje świat.', 'The main character saves the world.'),
('brainy7', 'aktor drugoplanowy', 'Aktor drugoplanowy jest zabawny.', 'The supporting actor is funny.'),
('brainy7', 'aktorka drugoplanowa', 'Aktorka drugoplanowa jest mloda.', 'The supporting actress is young.'),
('brainy7', 'film akcji', 'Lubię filmy akcji.', 'I like action films.'),
('brainy7', 'film animowany', 'Mój brat lubi filmy animowane.', 'My brother likes animated films.'),
('brainy7', 'komedia', 'Komedia jest zabawna.', 'A comedy is funny.'),
('brainy7', 'film fantasy', 'Lubię filmy fantasy.', 'I like fantasy films.'),
('brainy7', 'horror, film grozy', 'Horror jest straszny.', 'A horror film is scary.'),
('brainy7', 'film muzyczny', 'Idziemy do teatru na musical.', 'We are going to the theatre to see a musical.'),
('brainy7', 'film o miłości', 'Mama lubi filmy o miłości.', 'Mum likes romantic films.'),
('brainy7', 'film science fiction', 'Lubię filmy science fiction.', 'I like science fiction films.'),
('brainy7', 'film sensacyjny, dreszczowiec', 'Tata lubi filmy sensacyjne.', 'Dad likes thrillers.'),
('brainy7', 'Może (kupię)...?', 'Może kupię ci napój?', 'Shall I buy you a drink?'),
('brainy7', 'Obejrzymy…? Może obejrzymy...?', 'Może obejrzymy film dziś wieczorem?', 'Shall we watch a film tonight?'),
('brainy7', 'Chciałbyś/Chciałabyś też coś do picia?', 'Chciałbyś też coś do picia?', 'Would you like something to drink as well?'),
('brainy7', 'Chciałbyś/Chciałabyś pójść dziś wieczorem do kina?', 'Chciałbyś pójść dziś wieczorem do kina?', 'Would you like to go to the cinema tonight?'),
('brainy7', 'Tak, bardzo!', 'Tak, bardzo chętnie!', 'Yes, I would love to!'),
('brainy7', 'widownia', 'Widownia była zachwycona.', 'The audience was delighted.'),
('brainy7', 'blockbuster, przebój kinowy', 'Ten film jest blockbusterem.', 'This film is a blockbuster.'),
('brainy7', 'wyjść, wchodzić do kin', 'Nowy film wyjdzie w piątek.', 'The new film will come out on Friday.'),
('brainy7', 'kostiumograf/-ka', 'Kostiumograf przygotowuje stroje.', 'The costume designer prepares costumes.'),
('brainy7', 'wizażysta/-ka', 'Wizażysta robi makijaż aktorom.', 'The make-up artist does the actors'' makeup.'),
('brainy7', 'fabuła', 'Fabuła filmu jest interesująca.', 'The plot of the film is interesting.'),
('brainy7', 'nagrywać ścieżkę dźwiękową', 'Reżyser nagrywa ścieżkę dźwiękową.', 'The director is recording the soundtrack.'),
('brainy7', 'nakręcić film', 'Chcą nakręcić nowy film latem.', 'They want to shoot a new film in summer.'),
('brainy7', 'napisy', 'Oglądamy film z napisami.', 'We are watching the film with subtitles.'),
('brainy7', 'napisać scenariusz', 'Pisarz musi napisać scenariusz.', 'The writer has to write a script.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — Appearance, materials, crime (45)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'plecak', 'Mój plecak jest ciężki.', 'My backpack is heavy.'),
('brainy7', 'broda', 'Mój dziadek ma siwą brodę.', 'My grandfather has a grey beard.'),
('brainy7', 'płaszcz', 'Załóż płaszcz, jest zimno.', 'Put on your coat, it is cold.'),
('brainy7', 'okulary', 'Noszę okulary do czytania.', 'I wear glasses for reading.'),
('brainy7', 'torebka', 'Mama ma czarną torebkę.', 'Mum has a black handbag.'),
('brainy7', 'bluza z kapturem', 'Lubię moją bluzę z kapturem.', 'I like my hoodie.'),
('brainy7', 'biżuteria', 'Anna nosi piękną biżuterię.', 'Anna is wearing beautiful jewellery.'),
('brainy7', 'średniego wzrostu', 'Mój brat jest średniego wzrostu.', 'My brother is medium height.'),
('brainy7', 'wąsy', 'Tata ma wąsy.', 'Dad has a moustache.'),
('brainy7', 'kucyk', 'Anna ma kucyka.', 'Anna has a ponytail.'),
('brainy7', 'krótki, niski', 'Mój brat jest krótki.', 'My brother is short.'),
('brainy7', 'szczupły', 'Anna jest szczupła.', 'Anna is slim.'),
('brainy7', 'wysoki', 'Mój tata jest wysoki.', 'My dad is tall.'),
('brainy7', 'dres', 'Noszę dres na wf.', 'I wear a tracksuit at PE.'),
('brainy7', 'dobrze zbudowany', 'Mój brat jest dobrze zbudowany.', 'My brother is well-built.'),
('brainy7', 'w kratę', 'Noszę koszulę w kratę.', 'I am wearing a checked shirt.'),
('brainy7', 'bawełna, bawełniany', 'Moja koszulka jest z bawełny.', 'My T-shirt is made of cotton.'),
('brainy7', 'dżinsowa', 'Mam dżinsową kurtkę.', 'I have a denim jacket.'),
('brainy7', 'złoto, złoty', 'Mam złoty pierścionek.', 'I have a gold ring.'),
('brainy7', 'skóra, skórzany', 'Tata ma skórzaną kurtkę.', 'Dad has a leather jacket.'),
('brainy7', 'bez wzoru, gładki', 'Mam gładki sweter.', 'I have a plain jumper.'),
('brainy7', 'plastikowy', 'Mam plastikową torbę.', 'I have a plastic bag.'),
('brainy7', 'srebro, srebrny', 'Anna ma srebrny łańcuszek.', 'Anna has a silver chain.'),
('brainy7', 'w paski', 'Noszę koszulkę w paski.', 'I am wearing a striped T-shirt.'),
('brainy7', 'wełna, wełniany', 'Mój sweter jest z wełny.', 'My jumper is made of wool.'),
('brainy7', 'włamać się do', 'Złodzieje włamali się do banku.', 'The thieves broke into the bank.'),
('brainy7', 'włamywacz', 'Włamywacz uciekł.', 'The burglar ran away.'),
('brainy7', 'pościg, gonić, ścigać', 'Policja goni złodzieja.', 'The police are chasing the thief.'),
('brainy7', 'popełnić przestępstwo', 'Popełnił przestępstwo.', 'He committed a crime.'),
('brainy7', 'uszkodzić, szkoda', 'Wandale uszkodzili samochód.', 'The vandals damaged the car.'),
('brainy7', 'iść do więzienia', 'Złodziej idzie do więzienia.', 'The thief is going to prison.'),
('brainy7', 'obrabować, okradać', 'Złodzieje okradli sklep.', 'The thieves robbed the shop.'),
('brainy7', 'bandyta, złodziej (napadający na banki)', 'Bandyta uciekł z bankiem.', 'The robber ran away with the money.'),
('brainy7', 'uciec', 'Złodziej uciekł.', 'The thief ran away.'),
('brainy7', 'złodziej sklepowy', 'Ochroniarz złapał złodzieja sklepowego.', 'The security guard caught the shoplifter.'),
('brainy7', 'ukraść', 'Ukradli mi rower.', 'They stole my bike.'),
('brainy7', 'złodziej', 'Złodziej uciekł z biżuterią.', 'The thief ran away with the jewellery.'),
('brainy7', 'wandal', 'Wandale namalowali graffiti.', 'The vandals painted graffiti.'),
('brainy7', 'Czy możesz wypełnić ten formularz?', 'Czy możesz wypełnić ten formularz?', 'Can you fill in this form, please?'),
('brainy7', 'Wczoraj straciłem zegarek.', 'Wczoraj straciłem zegarek.', 'I lost a watch yesterday.'),
('brainy7', 'Jest wykonany z wełny.', 'Jest wykonany z wełny.', 'It is made of wool.'),
('brainy7', 'O jej! Jak to wygląda?', 'O jej! Jak to wygląda?', 'Oh dear! What does it look like?'),
('brainy7', 'Skontaktujemy się z Tobą, jeśli go znajdziemy.', 'Skontaktujemy się z Tobą, jeśli go znajdziemy.', 'We will contact you if we find it.'),
('brainy7', 'Jaka to marka?', 'Jaka to marka?', 'What brand is it?'),
('brainy7', 'Z czego to jest zrobione?', 'Z czego to jest zrobione?', 'What is it made of?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 3 — Travel, sightseeing, transport (40)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'kupować pamiątki', 'Kupuję pamiątki dla rodziny.', 'I am buying souvenirs for my family.'),
('brainy7', 'zameldować się w hotelu', 'Zameldowaliśmy się w hotelu.', 'We checked in to a hotel.'),
('brainy7', 'wymeldować się z hotelu', 'Wymeldowaliśmy się z hotelu.', 'We checked out of a hotel.'),
('brainy7', 'wyruszyć na wędrówkę z plecakiem', 'Idziemy na wędrówkę z plecakiem.', 'We are going backpacking.'),
('brainy7', 'wyruszyć na pieszą wycieczkę', 'Wybieramy się na pieszą wycieczkę.', 'We are going hiking.'),
('brainy7', 'wyjechać na wakacje zorganizowane', 'Wyjeżdżamy na wakacje zorganizowane.', 'We are going on a package holiday.'),
('brainy7', 'rozbić namiot', 'Rozbijamy namiot w lesie.', 'We are putting up a tent in the forest.'),
('brainy7', 'zwiedzać', 'Lubimy zwiedzać miasta.', 'We like to see the sights.'),
('brainy7', 'nocować w pensjonacie ze śniadaniami', 'Nocujemy w pensjonacie ze śniadaniami.', 'We are staying at a B&B.'),
('brainy7', 'nocować w schronisku dla młodzieży', 'Nocujemy w schronisku dla młodzieży.', 'We are staying at a youth hostel.'),
('brainy7', 'opalać się', 'Latem opalam się na plaży.', 'I sunbathe on the beach in summer.'),
('brainy7', 'peron', 'Pociąg odjeżdża z peronu trzeciego.', 'The train leaves from platform three.'),
('brainy7', 'bilet powrotny', 'Poproszę bilet powrotny.', 'A return ticket, please.'),
('brainy7', 'bilet w jedną stronę', 'Poproszę bilet w jedną stronę.', 'A single ticket, please.'),
('brainy7', 'kasa biletowa', 'Kupuję bilet w kasie biletowej.', 'I am buying a ticket at the ticket office.'),
('brainy7', 'rozkład jazdy', 'Sprawdź rozkład jazdy.', 'Check the timetable.'),
('brainy7', 'stacja kolejowa', 'Stacja kolejowa jest blisko.', 'The train station is near.'),
('brainy7', 'Czy mogę kupić tutaj bilet?', 'Czy mogę kupić tutaj bilet?', 'Can I buy a ticket here?'),
('brainy7', 'Czy wie Pan, gdzie to jest?', 'Czy wie Pan, gdzie to jest?', 'Do you know where it is?'),
('brainy7', 'Przepraszam, szukam stacji kolejowej.', 'Przepraszam, szukam stacji kolejowej.', 'Excuse me, I am looking for the train station.'),
('brainy7', 'Przepraszam, o której odjeżdża następny pociąg do Londynu?', 'Przepraszam, o której odjeżdża następny pociąg do Londynu?', 'Excuse me, what time is the next train to London?'),
('brainy7', 'Czy to daleko?', 'Czy to daleko?', 'Is it far?'),
('brainy7', 'To tylko pięć minut piechotą.', 'To tylko pięć minut piechotą.', 'It is just a five-minute walk.'),
('brainy7', 'Peron 4, o tam.', 'Peron 4, o tam.', 'Platform 4, over there.'),
('brainy7', 'W takim razie to będzie 15 funtów.', 'W takim razie to będzie 15 funtów.', 'That is 15 pounds then.'),
('brainy7', 'Musi Pan skręcić tutaj w lewo, a potem pójść prosto.', 'Musi Pan skręcić tutaj w lewo, a potem pójść prosto.', 'Turn left here, then go straight on.'),
('brainy7', 'Poproszę dwa bilety w jedną stronę.', 'Poproszę dwa bilety w jedną stronę.', 'Two singles, please.'),
('brainy7', 'Skąd odjeżdża?', 'Skąd odjeżdża?', 'Where does it leave from?'),
('brainy7', 'Nie da się go przegapić!', 'Nie da się go przegapić!', 'You cannot miss it!'),
('brainy7', 'przybyć', 'Przybyliśmy o ósmej.', 'We arrived at eight.'),
('brainy7', 'wrócić', 'Wracam jutro.', 'I will come back tomorrow.'),
('brainy7', 'wsiąść do', 'Wsiadam do pociągu.', 'I am getting on the train.'),
('brainy7', 'wysiąść z', 'Wysiadamy z autobusu.', 'We are getting off the bus.'),
('brainy7', 'wyjść z', 'Wychodzę z domu o ósmej.', 'I get out of the house at eight.'),
('brainy7', 'wylądować', 'Samolot wylądował o trzeciej.', 'The plane landed at three.'),
('brainy7', 'wyjechać', 'Wyjeżdżamy jutro.', 'We are leaving tomorrow.'),
('brainy7', 'wyruszyć', 'Wyruszyliśmy o świcie.', 'We set off at dawn.'),
('brainy7', 'wystartować', 'Samolot wystartował.', 'The plane took off.'),
('brainy7', 'zarezerwować swój lot', 'Zarezerwowałem lot do Hiszpanii.', 'I booked a flight to Spain.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 4 — Shopping, comparisons, opinions (50)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'za połowę ceny', 'Buty są za połowę ceny.', 'The shoes are 50% off.'),
('brainy7', 'okazja', 'To prawdziwa okazja!', 'It is a real bargain!'),
('brainy7', '"Dwa w cenie jednego"', 'Mamy promocję "Dwa w cenie jednego".', 'We have a "buy one, get one free" promotion.'),
('brainy7', 'klient', 'Klient zawsze ma rację.', 'The customer is always right.'),
('brainy7', 'zniżka, rabat', 'Mam 10% zniżki.', 'I have a 10% discount.'),
('brainy7', 'karta podarunkowa', 'Dostałem kartę podarunkową na urodziny.', 'I got a gift card for my birthday.'),
('brainy7', 'w promocji (w ofercie specjalnej)', 'Te buty są w promocji.', 'These shoes are on special offer.'),
('brainy7', 'kieszonkowe', 'Dostaję kieszonkowe od taty.', 'I get pocket money from dad.'),
('brainy7', 'sprzedawca', 'Sprzedawca jest miły.', 'The shop assistant is nice.'),
('brainy7', 'centrum handlowe', 'Idziemy do centrum handlowego.', 'We are going to the shopping mall.'),
('brainy7', 'bazar uliczny, uliczny stragan', 'Lubię bazary uliczne.', 'I like street markets.'),
('brainy7', 'wyprzedaże', 'W styczniu są wyprzedaże.', 'There are the sales in January.'),
('brainy7', 'bankomat', 'Wypłacam pieniądze z bankomatu.', 'I am withdrawing money from the cash machine.'),
('brainy7', 'reszta, zmiana', 'Daj mi resztę.', 'Give me the change.'),
('brainy7', 'płacić kartą', 'Mama płaci kartą.', 'Mum is paying by card.'),
('brainy7', 'płacić gotówką', 'Płacę gotówką.', 'I am paying in cash.'),
('brainy7', 'płacić zbliżeniowo', 'Płacę zbliżeniowo telefonem.', 'I am paying contactless with my phone.'),
('brainy7', 'paragon', 'Proszę o paragon.', 'A receipt, please.'),
('brainy7', 'zupełnie nowy', 'Mój telefon jest zupełnie nowy.', 'My phone is brand new.'),
('brainy7', 'źle wykonane', 'Te buty są źle wykonane.', 'These shoes are badly made.'),
('brainy7', 'wygodny', 'Moje buty są wygodne.', 'My shoes are comfortable.'),
('brainy7', 'modny', 'Ten plecak jest modny.', 'This backpack is fashionable.'),
('brainy7', 'ręcznie robiony', 'Mam ręcznie robioną torbę.', 'I have a handmade bag.'),
('brainy7', 'nowoczesny, najnowocześniejszy', 'Mam nowoczesny telefon.', 'I have a high tech phone.'),
('brainy7', 'staroświecki, staromodny', 'Babcia ma staroświecki telefon.', 'Grandma has an old-fashioned phone.'),
('brainy7', 'niezawodny, solidny', 'Ten samochód jest niezawodny.', 'This car is reliable.'),
('brainy7', 'używany (z drugiej ręki)', 'Mam używany rower.', 'I have a second-hand bike.'),
('brainy7', 'zawodny', 'Ta drukarka jest zawodna.', 'This printer is unreliable.'),
('brainy7', 'przydatny, użyteczny', 'Ten nóż jest przydatny.', 'This knife is useful.'),
('brainy7', 'bezużyteczny', 'Ta zabawka jest bezużyteczna.', 'This toy is useless.'),
('brainy7', 'dobrze zrobiony', 'Ten zegarek jest dobrze zrobiony.', 'This watch is well-made.'),
('brainy7', 'bezprzewodowy', 'Mam bezprzewodowe słuchawki.', 'I have wireless headphones.'),
('brainy7', 'bad - worse - the worst', 'zły - gorszy - najgorszy', 'bad - worse - the worst'),
('brainy7', 'good - better - the best', 'dobry - lepszy - najlepszy', 'good - better - the best'),
('brainy7', 'far - further - the furthest', 'daleko - dalej - najdalej', 'far - further - the furthest'),
('brainy7', 'lepszy', 'Mój wynik jest lepszy.', 'My score is better.'),
('brainy7', 'gorszy', 'Ten test jest gorszy.', 'This test is worse.'),
('brainy7', 'najgorszy', 'To najgorszy dzień.', 'It is the worst day.'),
('brainy7', 'najlepszy', 'To najlepszy film.', 'This is the best film.'),
('brainy7', 'tak dobry jak', 'Mój wynik jest tak dobry jak twój.', 'My score is as good as yours.'),
('brainy7', 'Czy mogę zapłacić zbliżeniowo?', 'Czy mogę zapłacić zbliżeniowo?', 'Can I pay contactless?'),
('brainy7', 'Proszę, to Pana/Pani reszta i paragon.', 'Proszę, to Pana reszta i paragon.', 'Here is your change and receipt.'),
('brainy7', 'Poproszę też jeden taki notatnik.', 'Poproszę też jeden taki notatnik.', 'I would like one of those notebooks as well.'),
('brainy7', 'Chciałbym/Chciałabym zapłacić za te słuchawki.', 'Chciałbym zapłacić za te słuchawki.', 'I would like to pay for these headphones, please.'),
('brainy7', 'Poproszę ten mały niebieski.', 'Poproszę ten mały niebieski.', 'I will take the small, blue one, please.'),
('brainy7', 'Mam banknot 20-funtowy.', 'Mam banknot 20-funtowy.', 'I have got a 20 pounds note.'),
('brainy7', 'Przykro mi, nie przyjmujemy kart.', 'Przykro mi, nie przyjmujemy kart.', 'Sorry, we do not take cards.'),
('brainy7', 'Te duże są po 2,99 funta, a te małe po 1,99 funta.', 'Te duże są po 2,99 funta, a te małe po 1,99 funta.', 'The big ones are two pounds ninety-nine pence and the small ones are one pound ninety-nine.'),
('brainy7', 'Który?', 'Który?', 'Which one?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 5 — Art, creation, expressions (47)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'tworzyć', 'Lubię tworzyć obrazy.', 'I like to create paintings.'),
('brainy7', 'tworzenie, dzieło', 'To moje najnowsze dzieło.', 'This is my latest creation.'),
('brainy7', 'projekt, projektować', 'Projektuję plakat.', 'I am designing a poster.'),
('brainy7', 'odkryć', 'Odkryłem nową książkę.', 'I discovered a new book.'),
('brainy7', 'odkrycie', 'Wielkie odkrycie naukowe.', 'A great scientific discovery.'),
('brainy7', 'wystawiać', 'Artysta wystawia obrazy.', 'The artist is exhibiting paintings.'),
('brainy7', 'wystawa', 'Idziemy na wystawę sztuki.', 'We are going to an art exhibition.'),
('brainy7', 'polepszyć', 'Chcę polepszyć moje wyniki.', 'I want to improve my results.'),
('brainy7', 'ulepszenie', 'To duże ulepszenie.', 'This is a big improvement.'),
('brainy7', 'instalować', 'Instaluję nową aplikację.', 'I am installing a new app.'),
('brainy7', 'instalacja', 'Instalacja jest gotowa.', 'The installation is ready.'),
('brainy7', 'wynaleźć', 'Edison wynalazł żarówkę.', 'Edison invented the light bulb.'),
('brainy7', 'wynalazek', 'Telefon to ważny wynalazek.', 'The phone is an important invention.'),
('brainy7', 'produkować', 'Fabryka produkuje samochody.', 'The factory produces cars.'),
('brainy7', 'produkcja', 'Produkcja samochodów spada.', 'Car production is falling.'),
('brainy7', 'model', 'Mam model samolotu.', 'I have a model plane.'),
('brainy7', 'fotografia', 'Zrobiłem piękną fotografię.', 'I took a beautiful photograph.'),
('brainy7', 'rzeźba', 'W muzeum jest piękna rzeźba.', 'There is a beautiful sculpture in the museum.'),
('brainy7', 'skarb', 'Znaleźli skarb w jaskini.', 'They found a treasure in the cave.'),
('brainy7', 'obraz', 'Ten obraz jest piękny.', 'This painting is beautiful.'),
('brainy7', 'osiągnięcie', 'To duże osiągnięcie.', 'It is a great achievement.'),
('brainy7', 'architekt', 'Architekt projektuje budynki.', 'An architect designs buildings.'),
('brainy7', 'architektura', 'Lubię włoską architekturę.', 'I like Italian architecture.'),
('brainy7', 'galeria sztuki', 'Idziemy do galerii sztuki.', 'We are going to the art gallery.'),
('brainy7', 'projektowanie mody', 'Anna studiuje projektowanie mody.', 'Anna studies fashion design.'),
('brainy7', 'projektant mody', 'Ona jest sławną projektantką mody.', 'She is a famous fashion designer.'),
('brainy7', 'graficiarz', 'Graficiarz maluje na ścianach.', 'The graffiti artist paints on walls.'),
('brainy7', 'graffiti', 'Graffiti jest na ścianie.', 'There is graffiti art on the wall.'),
('brainy7', 'pejzaż', 'Maluję pejzaż.', 'I am painting a landscape.'),
('brainy7', 'zrobić rzeźbę', 'Lubię zrobić rzeźbę z gliny.', 'I like to make a sculpture from clay.'),
('brainy7', 'namalować obraz', 'Lubię namalować obraz.', 'I like to paint a picture.'),
('brainy7', 'malarz', 'Mój brat jest malarzem.', 'My brother is a painter.'),
('brainy7', 'fotograf', 'Fotograf robi zdjęcia ślubne.', 'The photographer is taking wedding photos.'),
('brainy7', 'rzeźbiarz', 'Rzeźbiarz tworzy posągi.', 'The sculptor creates statues.'),
('brainy7', 'posąg', 'Posąg jest wysoki.', 'The statue is tall.'),
('brainy7', 'robić zdjęcie', 'Lubię robić zdjęcia.', 'I like to take photos.'),
('brainy7', 'dzieło sztuki', 'To prawdziwe dzieło sztuki.', 'It is a real work of art.'),
('brainy7', 'Ale to niezwykłe!', 'Ale to niezwykłe!', 'How amazing!'),
('brainy7', 'Ale to straszne!', 'Ale to straszne!', 'How awful!'),
('brainy7', 'Ale to fajne!', 'Ale to fajne!', 'How cool!'),
('brainy7', 'Co za beznadziejny pomysł!', 'Co za beznadziejny pomysł!', 'What a bad idea!'),
('brainy7', 'Co za wspaniałe osiągnięcie!', 'Co za wspaniałe osiągnięcie!', 'What a great achievement!'),
('brainy7', 'Ale świetny pomysł!', 'Ale świetny pomysł!', 'What an amazing idea!'),

-- ═══════════════════════════════════════════════════════════
-- Unit 6 — Sport, places, can/may (45)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'zranić się', 'Uważaj, żeby się nie zranić!', 'Be careful not to get hurt!'),
('brainy7', 'utrzymywać formę/kondycję', 'Trenuję, żeby utrzymywać formę.', 'I train to keep fit.'),
('brainy7', 'iść na trening', 'Idę na trening trzy razy w tygodniu.', 'I go to sports practice three times a week.'),
('brainy7', 'ćwiczyć technikę', 'Ćwiczę technikę gry w tenisa.', 'I practise my tennis technique.'),
('brainy7', 'zapobiegać kontuzjom', 'Rozgrzewka pomaga zapobiegać kontuzjom.', 'Warming up helps prevent injury.'),
('brainy7', 'rozciągać się', 'Rozciągam się przed treningiem.', 'I stretch before training.'),
('brainy7', 'brać udział w wydarzeniu', 'Biorę udział w wydarzeniu sportowym.', 'I take part in a sports event.'),
('brainy7', 'trenować', 'Trenuję trzy razy w tygodniu.', 'I train three times a week.'),
('brainy7', 'rozgrzać się', 'Rozgrzewam się przed meczem.', 'I warm up before the match.'),
('brainy7', 'kort tenisowy, boisko do koszykówki', 'Gramy na korcie tenisowym.', 'We are playing on the tennis court.'),
('brainy7', 'boisko do piłki nożnej', 'Mecz odbywa się na boisku do piłki nożnej.', 'The match is on the football pitch.'),
('brainy7', 'boisko do gry w baseball, futbol amerykański', 'Gramy na boisku do baseballu.', 'We are playing on the baseball field.'),
('brainy7', 'lodowisko', 'Idziemy na lodowisko.', 'We are going to the ice rink.'),
('brainy7', 'bieżnia, tor wyścigowy', 'Trenuję na bieżni.', 'I am training on the track.'),
('brainy7', 'zbocze, stok', 'Jeździmy na nartach po stoku.', 'We are skiing down the slope.'),
('brainy7', 'W porządku', 'W porządku, zgadzam się.', 'OK, fine, I agree.'),
('brainy7', 'Mogę pożyczyć twoją rakietkę tenisową?', 'Mogę pożyczyć twoją rakietkę tenisową?', 'Can I borrow your tennis racket?'),
('brainy7', 'Mógłbyś oddać mi go/ją wieczorem?', 'Mógłbyś oddać mi go wieczorem?', 'Could you give it back this evening?'),
('brainy7', 'Czy mogę wyjść z zajęć wcześniej?', 'Czy mogę wyjść z zajęć wcześniej?', 'May I leave class early today?'),
('brainy7', 'Tak, oczywiście, że możesz.', 'Tak, oczywiście, że możesz.', 'Yes, of course you can.'),
('brainy7', 'Tak, możesz. Z jakiego powodu?', 'Tak, możesz. Z jakiego powodu?', 'Yes, you may. Why?'),
('brainy7', 'pobić, pokonać', 'Pobiliśmy ich w meczu.', 'We beat them in the match.'),
('brainy7', 'łamać zasady', 'Nie wolno łamać zasad.', 'You must not break rules.'),
('brainy7', 'pobić rekord', 'On pobił rekord świata.', 'He broke a world record.'),
('brainy7', 'łapać, chwytać, chwyt', 'Łapię piłkę.', 'I catch the ball.'),
('brainy7', 'mistrzostwa', 'Mistrzostwa odbywają się w lipcu.', 'The championship is in July.'),
('brainy7', 'remis, zremisować', 'Mecz zakończył się remisem.', 'The match ended in a draw.'),
('brainy7', 'fan, kibic', 'Jestem fanem tej drużyny.', 'I am a fan of this team.'),
('brainy7', 'faul, sfaulować, przewinienie', 'Sędzia gwizdał za faul.', 'The referee whistled for a foul.'),
('brainy7', 'bramka, gol', 'On strzelił bramkę!', 'He scored a goal!'),
('brainy7', 'przeciwnik', 'Mój przeciwnik jest silny.', 'My opponent is strong.'),
('brainy7', 'grać według zasad', 'Trzeba grać według zasad.', 'You have to play by the rules.'),
('brainy7', 'gracz', 'Ten gracz jest najlepszy.', 'This player is the best.'),
('brainy7', 'punkt', 'Mam dziesięć punktów.', 'I have ten points.'),
('brainy7', 'wyścig, ścigać się', 'Wygrałem wyścig.', 'I won the race.'),
('brainy7', 'arbiter, sędzia (w piłce nożnej)', 'Sędzia gwizdał.', 'The referee blew the whistle.'),
('brainy7', 'obronić, obrona', 'Bramkarz obronił strzał.', 'The goalkeeper made a save.'),
('brainy7', 'zdobyć punkt, wynik', 'Zdobyliśmy trzy punkty.', 'We scored three points.'),
('brainy7', 'ustanowić rekord', 'Ustanowił nowy rekord.', 'He set a new record.'),
('brainy7', 'kibic', 'Jestem kibicem Lecha Poznań.', 'I am a Lech Poznan supporter.'),
('brainy7', 'rzut, rzucać', 'Rzucam piłkę do kosza.', 'I am throwing the ball at the basket.'),
('brainy7', 'turniej, zawody', 'Wygraliśmy turniej.', 'We won the tournament.'),
('brainy7', 'trofeum, puchar', 'Dostaliśmy trofeum.', 'We got a trophy.'),
('brainy7', 'wygrać, zwycięstwo', 'Chcę wygrać turniej.', 'I want to win the tournament.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 7 — Hobbies, school subjects, would prefer (45)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'sztuka i rzemiosło', 'Lubię sztukę i rzemiosło.', 'I like arts and crafts.'),
('brainy7', 'próba zespołu muzycznego', 'Mamy próbę zespołu muzycznego.', 'We have band practice.'),
('brainy7', 'szachy', 'Lubię grać w szachy.', 'I like to play chess.'),
('brainy7', 'programowanie', 'Uczę się programowania.', 'I am learning coding.'),
('brainy7', 'gotowanie', 'Gotowanie to moje hobby.', 'Cookery is my hobby.'),
('brainy7', 'taniec', 'Lubię taniec.', 'I like dance.'),
('brainy7', 'teatr dramatyczny', 'Chodzę na teatr dramatyczny.', 'I go to drama club.'),
('brainy7', 'projektowanie graficzne', 'Studiuję projektowanie graficzne.', 'I study graphic design.'),
('brainy7', 'ścianka wspinaczkowa', 'Lubię ściankę wspinaczkową.', 'I like indoor climbing.'),
('brainy7', 'dołączyć do kółka zainteresowań', 'Chcę dołączyć do kółka zainteresowań.', 'I want to join a club.'),
('brainy7', 'robotyka', 'Mam zajęcia z robotyki.', 'I have robotics classes.'),
('brainy7', 'język migowy', 'Uczę się języka migowego.', 'I am learning sign language.'),
('brainy7', 'zapisać się na', 'Chcę zapisać się na karate.', 'I want to sign up for karate.'),
('brainy7', 'wolontariat', 'Robię wolontariat w schronisku.', 'I do voluntary work at the shelter.'),
('brainy7', 'projektowanie stron www', 'Lubię projektowanie stron www.', 'I like web design.'),
('brainy7', 'chemia', 'Lubię chemię.', 'I like chemistry.'),
('brainy7', 'szermierka', 'Trenuję szermierkę.', 'I do fencing.'),
('brainy7', 'pierwsza pomoc', 'Mam kurs pierwszej pomocy.', 'I have a first aid course.'),
('brainy7', 'język francuski', 'Uczę się języka francuskiego.', 'I am learning French.'),
('brainy7', 'język niemiecki', 'Uczę się języka niemieckiego.', 'I am learning German.'),
('brainy7', 'judo', 'Mój brat trenuje judo.', 'My brother does judo.'),
('brainy7', 'fizyka', 'Fizyka jest trudna.', 'Physics is difficult.'),
('brainy7', 'język hiszpański', 'Mówię trochę po hiszpańsku.', 'I speak a little Spanish.'),
('brainy7', 'Może też do niego dołączę.', 'Może też do niego dołączę.', 'I might join that one too.'),
('brainy7', 'Chciałbym się zapisać do kółka tanecznego.', 'Chciałbym się zapisać do kółka tanecznego.', 'I would like to sign up for the dance club, please.'),
('brainy7', 'Wolałbym chodzić w środy.', 'Wolałbym chodzić w środy.', 'I would prefer to go on Wednesdays.'),
('brainy7', 'Wolałbym dołączyć do kółka tanecznego.', 'Wolałbym dołączyć do kółka tanecznego.', 'I would rather join the dance club.'),
('brainy7', 'Nie przepadam za jazdą na rowerze.', 'Nie przepadam za jazdą na rowerze.', 'I am not keen on cycling.'),
('brainy7', 'Uwielbiam sztukę widowiskową.', 'Uwielbiam sztukę widowiskową.', 'I am really into performing arts.'),
('brainy7', 'To brzmi fajnie.', 'To brzmi fajnie.', 'That sounds fun.'),
('brainy7', 'Co wolałbyś robić?', 'Co wolałbyś robić?', 'What would you rather do?'),
('brainy7', 'Chciałbyś dołączyć ze mną do kółka naprawy rowerów?', 'Chciałbyś dołączyć ze mną do kółka naprawy rowerów?', 'Would you like to join the bike maintenance club with me?'),
('brainy7', 'Wolałbyś chodzić w poniedziałki czy środy?', 'Wolałbyś chodzić w poniedziałki czy środy?', 'Would you prefer to go on Mondays or Wednesdays?'),
('brainy7', 'być nieobecnym w szkole', 'Wczoraj byłem nieobecny w szkole.', 'I was absent from school yesterday.'),
('brainy7', 'wychowawca klasy', 'Mój wychowawca klasy jest miły.', 'My form tutor is nice.'),
('brainy7', 'dostać 5 z matematyki', 'Dostałem 5 z matematyki.', 'I got a 5 in maths.'),
('brainy7', 'za karę zostać w szkole po lekcjach', 'Tom dostał za karę zostać w szkole po lekcjach.', 'Tom got detention.'),
('brainy7', 'dostać oceny końcowe / świadectwo', 'Dostałem dziś świadectwo.', 'I got my report today.'),
('brainy7', 'zdać do klasy 8', 'Zdałem do klasy 8.', 'I went into Year 8.'),
('brainy7', 'iść na apel', 'Idziemy na apel rano.', 'We go to assembly in the morning.'),
('brainy7', 'oddać pracę domową', 'Muszę oddać pracę domową jutro.', 'I have to hand in my homework tomorrow.'),
('brainy7', 'dyrektor szkoły', 'Dyrektor szkoły jest surowy.', 'The head teacher is strict.'),
('brainy7', 'ukończyć szkołę', 'Ukończę szkołę w czerwcu.', 'I will leave school in June.'),
('brainy7', 'zostawiać rzeczy w szafce', 'Zostawiam rzeczy w szafce.', 'I leave things in my locker.'),
('brainy7', 'semestr', 'Mamy dwa semestry w roku.', 'We have two school terms a year.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 8 — Food, healthy diet, restaurant (50)
-- ═══════════════════════════════════════════════════════════
('brainy7', 'kalorie', 'Liczę kalorie.', 'I count calories.'),
('brainy7', 'węglowodany', 'Makaron to węglowodany.', 'Pasta is carbohydrates.'),
('brainy7', 'frytki', 'Frytki są słone.', 'Chips are salty.'),
('brainy7', 'czipsy', 'Lubię czipsy.', 'I like crisps.'),
('brainy7', 'nabiał', 'Mleko i ser to nabiał.', 'Milk and cheese are dairy products.'),
('brainy7', 'tłuszcz', 'Tłuszcz jest niezbędny w diecie.', 'Fat is essential in your diet.'),
('brainy7', 'błonnik', 'Owoce i warzywa zawierają błonnik.', 'Fruit and vegetables contain fibre.'),
('brainy7', 'soczewica', 'Soczewica jest źródłem białka.', 'Lentils are a source of protein.'),
('brainy7', 'orzechy', 'Lubię orzechy włoskie.', 'I like walnuts.'),
('brainy7', 'olej', 'Smażę jajka na oleju.', 'I am frying eggs in oil.'),
('brainy7', 'białko', 'Mięso to białko.', 'Meat is protein.'),
('brainy7', 'cukier', 'Za dużo cukru jest niezdrowe.', 'Too much sugar is unhealthy.'),
('brainy7', 'witaminy', 'Owoce mają dużo witamin.', 'Fruits have a lot of vitamins.'),
('brainy7', 'pełnoziarnisty', 'Jem pełnoziarnisty chleb.', 'I eat wholegrain bread.'),
('brainy7', 'być uczulonym na', 'Jestem uczulony na orzechy.', 'I am allergic to nuts.'),
('brainy7', 'bezglutenowy', 'Mój brat je bezglutenowy chleb.', 'My brother eats gluten free bread.'),
('brainy7', 'organiczny, ekologiczny', 'Kupuję organiczne warzywa.', 'I buy organic vegetables.'),
('brainy7', 'wegański', 'Mój kuzyn jest wegański.', 'My cousin is vegan.'),
('brainy7', 'wegetariański', 'Anna jest wegetarianką.', 'Anna is vegetarian.'),
('brainy7', 'deser', 'Na deser jest ciasto.', 'There is a cake for dessert.'),
('brainy7', 'napoje', 'Co macie do picia?', 'What drinks do you have?'),
('brainy7', 'danie główne', 'Co weźmiesz na danie główne?', 'What will you have for the main course?'),
('brainy7', 'dodatek do dania głównego', 'Frytki to dodatek do dania głównego.', 'Chips are a side dish.'),
('brainy7', 'dania dnia', 'Jakie macie dania dnia?', 'What are the specials?'),
('brainy7', 'przystawki', 'Co weźmiesz na przystawki?', 'What will you have for starters?'),
('brainy7', 'Jakieś przystawki?', 'Jakieś przystawki?', 'Any side dishes?'),
('brainy7', 'Czy są państwo gotowi złożyć zamówienie?', 'Czy są państwo gotowi złożyć zamówienie?', 'Are you ready to order?'),
('brainy7', 'smacznego', 'Smacznego!', 'Bon appétit!'),
('brainy7', 'Czy podać coś jeszcze?', 'Czy podać coś jeszcze?', 'Can I get you anything else?'),
('brainy7', 'Smacznego!', 'Smacznego!', 'Enjoy your meal!'),
('brainy7', 'Czy możemy prosić o rachunek?', 'Czy możemy prosić o rachunek?', 'Excuse me, could we have the bill?'),
('brainy7', 'Poproszę koktajl mleczny.', 'Poproszę koktajl mleczny.', 'I would like a milkshake.'),
('brainy7', 'Przyniosę menu.', 'Przyniosę menu.', 'I will bring the menus.'),
('brainy7', 'Poproszę ... na przystawkę.', 'Poproszę zupę na przystawkę.', 'I will have soup for starter.'),
('brainy7', 'Nie, to wszystko.', 'Nie, to wszystko.', 'No, that is all.'),
('brainy7', 'Usiąść, zająć miejsce.', 'Usiąść, zająć miejsce.', 'Take a seat.'),
('brainy7', 'Czego chciałbyś się napić?', 'Czego chciałbyś się napić?', 'What would you like to drink?'),
('brainy7', 'To było pyszne.', 'To było pyszne.', 'It was delicious.'),
('brainy7', 'szaszłyk z kurczaka', 'Lubię szaszłyk z kurczaka.', 'I like chicken kebab.'),
('brainy7', 'szef kuchni', 'Szef kuchni jest świetny.', 'The chef is great.'),
('brainy7', 'kucharz', 'Kucharz przygotowuje obiad.', 'The cook is preparing dinner.'),
('brainy7', 'jeść w domu', 'Wolimy jeść w domu.', 'We prefer to eat in.'),
('brainy7', 'jeść poza domem', 'Czasami jemy poza domem.', 'We sometimes eat out.'),
('brainy7', 'food truck', 'Idziemy do food trucka.', 'We are going to the food van.'),
('brainy7', 'iść na targ kulinarny', 'Idziemy na targ kulinarny.', 'We are going to a food fair.'),
('brainy7', 'grillować, piec coś na grillu', 'Lubię grillować mięso.', 'I like to grill meat.'),
('brainy7', 'urządzać grilla', 'Latem urządzamy grilla.', 'In summer we have a barbecue.'),
('brainy7', 'organizować zjazd rodzinny', 'Organizujemy zjazd rodzinny.', 'We are organising a family get-together.'),
('brainy7', 'zaprosić znajomych (na obiad/kolację)', 'Zapraszamy znajomych na kolację.', 'We are inviting friends round for dinner.'),
('brainy7', 'kotlet jagnięcy', 'Lubię kotlet jagnięcy.', 'I like lamb chop.'),
('brainy7', 'zostawić napiwek', 'Zostawiamy napiwek kelnerowi.', 'We leave a tip for the waiter.'),
('brainy7', 'lokalne stoiska z jedzeniem', 'Lokalne stoiska z jedzeniem są świetne.', 'The local food stalls are great.'),
('brainy7', 'zamówić jedzenie na wynos', 'Zamawiamy jedzenie na wynos.', 'We are ordering a takeaway.'),
('brainy7', 'kotlet wieprzowy', 'Tata robi kotlet wieprzowy.', 'Dad is making a pork chop.'),
('brainy7', 'próbować tradycyjnych dań', 'Lubimy próbować tradycyjnych dań.', 'We like to try traditional dishes.'),
('brainy7', 'kelner', 'Kelner przyjmuje zamówienie.', 'The waiter is taking an order.'),
('brainy7', 'kelnerka', 'Kelnerka przynosi rachunek.', 'The waitress is bringing the bill.')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Brainy 7: 354 unikalnych zdan zaktualizowanych/dodanych w word_sentences (355 wpisow w data.js, 1 duplikat synonimu Czy mozesz wypelnic ten formularz? zdedupedowany przez UPSERT).';
END $$;
