-- ═══════════════════════════════════════════════════════════
-- Fix sentences: STEPS PLUS 4 (klasa 4, szkola podstawowa)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 672 unikalnych slowek z Steps Plus 4 (Pearson).
--
-- Statystyki:
--   - 678 wpisow w data.js (8 unitow x ~85 entries srednio)
--   - 4 pary roznych znaczen (miasto, skakac, godzina, przed) zostaly
--     rozdzielone w data.js przez disambiguacje nawiasem (np.
--     'miasto (duze)' / 'miasto (male)') — oba zachowane w SQL.
--   - 6 duplikatow word_pl o identycznym/synonimicznym znaczeniu →
--     pominiete w SQL (UPSERT trzymalby ostatnia wartosc).
--   - 672 unikalnych zdan w word_sentences (4 pary disambiguacji
--     dolozyly 4 wpisy do poprzednich 668).
--
-- Tematy unitow:
--   Unit 1 (84): rodzina + znajomi + kraje + zawody
--   Unit 2 (68): szkola + przedmioty + przybory
--   Unit 3 (80): dom + pokoje + przyimki + adres
--   Unit 4 (105): sport + czynnosci ruchowe + wf
--   Unit 5 (89): zwierzeta dzikie + domowe + opisy
--   Unit 6 (75): osoba + cechy + osobowosc + wyglad
--   Unit 7 (104): rutyna + jedzenie + dni + transport
--   Unit 8 (64): czas wolny + plaza + zwierzeta wiejskie
--
-- Disambiguacja nawiasem (data.js zaktualizowany — oba znaczenia zachowane):
--   1. 'miasto (duze)' (city, Unit 1) + 'miasto (male)' (town, Unit 1)
--   2. 'skakac (krotko)' (hop, Unit 4) + 'skakac (wysoko)' (jump, Unit 4)
--   3. 'godzina (zegar)' (o'clock, Unit 2) + 'godzina (jednostka)' (hour, Unit 4)
--   4. 'przed (miejsce)' (in front of, Unit 3) + 'przed (czas)' (before, Unit 7)
--
-- Pominiete duplikaty word_pl (PostgreSQL nie pozwala na duplikat klucza
-- w jednym INSERT z ON CONFLICT; UPSERT trzymalby ostatnia wartosc.
-- Te przypadki to synonimy lub powtorzenia tego samego EN — bez straty info):
--   1. 'krotki' Unit 2 (short) + Unit 5 (short) → tylko Unit 2 [ten sam EN]
--   2. 'ogromny' Unit 3 (enormous) + Unit 5 (huge) → tylko Unit 3 [synonim]
--   3. 'telewizor' Unit 3 (TV) + Unit 4 (television) → tylko Unit 3 [synonim]
--   4. 'plywac' Unit 4 (swim) + Unit 7 (go swimming) → tylko Unit 4 [synonim]
--   5. 'szybko' Unit 3 (quickly) + Unit 7 (quickly) → tylko Unit 3 [ten sam EN]
--   6. 'zaczynac' Unit 4 (begin) + Unit 7 (start) → tylko Unit 4 [synonim]
--
-- Konwencje:
--   - Krotkie zdania, 5-12 slow EN, poziom A1/A2 (klasa 4).
--   - Naturalnie uzywaja target slowa w zdaniach tematycznych.
--   - Pelnie zdaniowe entries -> echo, EN tlumaczenie naturalne.
--   - Apostrof escapowany jako '' (PostgreSQL).
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — Family and friends (84, po skipnieciu 'miasto' x2)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'po', 'Spotkamy się po szkole.', 'We will meet after school.'),
('stepsplus4', 'wiek', 'Jaki jest twój wiek?', 'What is your age?'),
('stepsplus4', 'przez cały czas', 'Padał deszcz przez cały czas.', 'It was raining all along.'),
('stepsplus4', 'cały czas', 'On się uczy cały czas.', 'He studies all the time.'),
('stepsplus4', 'zawsze', 'Zawsze chodzę do szkoły rano.', 'I always go to school in the morning.'),
('stepsplus4', 'miłośnik zwierząt', 'Mój brat jest miłośnikiem zwierząt.', 'My brother is an animal lover.'),
('stepsplus4', 'sztuka', 'Lubię sztukę nowoczesną.', 'I like modern art.'),
('stepsplus4', 'ciotka', 'Moja ciotka mieszka w Krakowie.', 'My aunt lives in Krakow.'),
('stepsplus4', 'najlepszy przyjaciel', 'Tom jest moim najlepszym przyjacielem.', 'Tom is my best friend.'),
('stepsplus4', 'duży', 'Mam duży pokój.', 'I have a big room.'),
('stepsplus4', 'narzucający swoją wolę', 'Mój brat jest narzucający swoją wolę.', 'My brother is bossy.'),
('stepsplus4', 'chłopiec', 'Ten chłopiec to mój kuzyn.', 'This boy is my cousin.'),
('stepsplus4', 'kawiarnia', 'Idziemy do kawiarni na ciasto.', 'We are going to the café for cake.'),
('stepsplus4', 'kamerzysta', 'Kamerzysta nagrywa film.', 'The cameraman is filming.'),
('stepsplus4', 'kot', 'Mój kot jest czarny.', 'My cat is black.'),
('stepsplus4', 'ser', 'Lubię żółty ser.', 'I like yellow cheese.'),
('stepsplus4', 'dziecko (dzieci)', 'Dziecko śpi.', 'The child is sleeping.'),
-- 'miasto (duże)' / 'miasto (małe)' — disambiguacja nawiasem (data.js)
('stepsplus4', 'miasto (duże)', 'Mieszkam w dużym mieście.', 'I live in a big city.'),
('stepsplus4', 'szczękać', 'Łańcuchy szczękały.', 'The chains were clanking.'),
('stepsplus4', 'klasa', 'Nasza klasa jest bardzo miła.', 'Our class is very nice.'),
('stepsplus4', 'sala lekcyjna', 'Sala lekcyjna jest jasna.', 'The classroom is bright.'),
('stepsplus4', 'konkurs', 'Wygrałem konkurs plastyczny.', 'I won an art competition.'),
('stepsplus4', 'kraj', 'Polska to mój kraj.', 'Poland is my country.'),
('stepsplus4', 'kuzyn', 'Mój kuzyn ma 12 lat.', 'My cousin is 12 years old.'),
('stepsplus4', 'córka', 'Anna jest córką pani Kowalskiej.', 'Anna is Mrs Kowalska''s daughter.'),
('stepsplus4', 'reżyser', 'Reżyser robi filmy.', 'The director makes films.'),
('stepsplus4', 'pies', 'Mój pies jest przyjazny.', 'My dog is friendly.'),
('stepsplus4', 'łatwy', 'To zadanie jest łatwe.', 'This task is easy.'),
('stepsplus4', 'rodzina', 'Moja rodzina jest duża.', 'My family is big.'),
('stepsplus4', 'sławny', 'On jest sławnym piosenkarzem.', 'He is a famous singer.'),
('stepsplus4', 'ulubiony', 'To mój ulubiony film.', 'This is my favourite film.'),
('stepsplus4', 'jedzenie', 'Pizza to moje ulubione jedzenie.', 'Pizza is my favourite food.'),
('stepsplus4', 'ogród', 'W ogrodzie są kwiaty.', 'There are flowers in the garden.'),
('stepsplus4', 'geografia', 'Lubię geografię.', 'I like geography.'),
('stepsplus4', 'dziewczyna', 'Ta dziewczyna to moja siostra.', 'This girl is my sister.'),
('stepsplus4', 'Dobrze cię widzieć.', 'Dobrze cię widzieć.', 'Good to see you.'),
('stepsplus4', 'dziadziuś', 'Mój dziadziuś ma 75 lat.', 'My grandad is 75 years old.'),
('stepsplus4', 'wnuczka', 'Babcia kocha swoją wnuczkę.', 'Grandma loves her granddaughter.'),
('stepsplus4', 'babcia', 'Moja babcia piecze ciasta.', 'My grandma bakes cakes.'),
('stepsplus4', 'dziadkowie', 'Moi dziadkowie mieszkają na wsi.', 'My grandparents live in the countryside.'),
('stepsplus4', 'wnuk', 'Dziadek bawi się z wnukiem.', 'Grandad is playing with his grandson.'),
('stepsplus4', 'Świetny pomysł!', 'Świetny pomysł!', 'Great idea!'),
('stepsplus4', 'Wszystkiego najlepszego z okazji urodzin', 'Wszystkiego najlepszego z okazji urodzin!', 'Happy birthday!'),
('stepsplus4', 'Pomóż mi!', 'Pomóż mi!', 'Help me!'),
('stepsplus4', 'zdjęcie', 'Zrób mi zdjęcie.', 'Take a photo of me.'),
('stepsplus4', 'pizza', 'Lubię pizzę z pieczarkami.', 'I like pizza with mushrooms.'),
('stepsplus4', 'gwiazda muzyki pop', 'Ona jest gwiazdą muzyki pop.', 'She is a pop star.'),
('stepsplus4', 'książę', 'Książę mieszka w zamku.', 'The prince lives in a castle.'),
('stepsplus4', 'księżniczka', 'Księżniczka ma długie włosy.', 'The princess has long hair.'),
('stepsplus4', 'nagroda', 'Wygrał nagrodę w konkursie.', 'He won a prize in the competition.'),
('stepsplus4', 'królowa', 'Królowa Anglii ma koronę.', 'The Queen of England has a crown.'),
('stepsplus4', 'pytanie', 'Mam pytanie do nauczyciela.', 'I have a question for the teacher.'),
('stepsplus4', 'królik', 'Mój królik je marchewki.', 'My rabbit eats carrots.'),
('stepsplus4', 'religia', 'W szkole mamy religię.', 'We have RE at school.'),
('stepsplus4', 'prawdziwy', 'To prawdziwa historia.', 'This is a real story.'),
('stepsplus4', 'restauracja', 'Jemy obiad w restauracji.', 'We are having lunch at the restaurant.'),
('stepsplus4', 'królewski', 'Pałac królewski jest duży.', 'The royal palace is big.'),
('stepsplus4', 'powiedzieć', 'Co chcesz mi powiedzieć?', 'What do you want to say?'),
('stepsplus4', 'straszny', 'Ten film jest straszny.', 'This film is scary.'),
('stepsplus4', 'przedmiot ścisły', 'Lubię przedmioty ścisłe.', 'I like science.'),
('stepsplus4', 'piosenkarz', 'On jest dobrym piosenkarzem.', 'He is a good singer.'),
('stepsplus4', 'syn', 'Pani Kowalska ma jednego syna.', 'Mrs Kowalska has one son.'),
('stepsplus4', 'wkrótce', 'Wkrótce wracam do domu.', 'I am coming home soon.'),
('stepsplus4', 'gwiazda filmowa', 'Tom Hanks to gwiazda filmowa.', 'Tom Hanks is a film star.'),
('stepsplus4', 'silny', 'Mój brat jest silny.', 'My brother is strong.'),
('stepsplus4', 'surfować po Internecie', 'Lubię surfować po Internecie.', 'I like to surf the Internet.'),
('stepsplus4', 'brać', 'Możesz brać moją książkę.', 'You can take my book.'),
('stepsplus4', 'nauczyciel', 'Mój nauczyciel jest miły.', 'My teacher is nice.'),
('stepsplus4', 'Internet', 'Codziennie używam Internetu.', 'I use the Internet every day.'),
('stepsplus4', 'wtedy', 'Wtedy poszliśmy do parku.', 'Then we went to the park.'),
('stepsplus4', 'dziś', 'Dziś jest piękny dzień.', 'Today is a beautiful day.'),
('stepsplus4', 'też', 'Ja też lubię koty.', 'I like cats too.'),
('stepsplus4', 'miasto (małe)', 'Idę do miasta jutro.', 'I am going to the town tomorrow.'),
('stepsplus4', 'bliźniak', 'On i jego bliźniak są podobni.', 'He and his twin look alike.'),
('stepsplus4', 'wujek', 'Mój wujek pracuje w fabryce.', 'My uncle works in a factory.'),
('stepsplus4', 'bardzo', 'Jestem bardzo szczęśliwy.', 'I am very happy.'),
('stepsplus4', 'nagranie wideo', 'Oglądam nagranie wideo.', 'I am watching a video.'),
('stepsplus4', 'strona internetowa', 'To moja ulubiona strona internetowa.', 'This is my favourite website.'),
('stepsplus4', 'A ty?', 'A ty?', 'What about you?'),
('stepsplus4', 'Co się stało?', 'Co się stało?', 'What is the matter?'),
('stepsplus4', 'kiedy', 'Kiedy idziesz do domu?', 'When are you going home?'),
('stepsplus4', 'Kiedy masz urodziny?', 'Kiedy masz urodziny?', 'When is your birthday?'),
('stepsplus4', 'z', 'Idę z tatą do parku.', 'I am going to the park with dad.'),
('stepsplus4', 'O rany!', 'O rany! Jaki piękny widok!', 'Wow! What a beautiful view!'),
('stepsplus4', 'rok', 'Mam dziewięć lat.', 'I am nine years old.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — School (68)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'afrykański', 'Lubię afrykańską muzykę.', 'I like African music.'),
('stepsplus4', 'amerykański', 'On ma amerykański paszport.', 'He has an American passport.'),
('stepsplus4', 'plastyka', 'Plastyka to mój ulubiony przedmiot.', 'Art is my favourite subject.'),
('stepsplus4', 'brytyjski', 'On jest brytyjskim aktorem.', 'He is a British actor.'),
('stepsplus4', 'brązowy', 'Mam brązowe oczy.', 'I have brown eyes.'),
('stepsplus4', 'płyta kompaktowa', 'Słucham płyty kompaktowej.', 'I am listening to a CD.'),
('stepsplus4', 'odtwarzacz płyt kompaktowych', 'Mam stary odtwarzacz płyt kompaktowych.', 'I have an old CD player.'),
('stepsplus4', 'koło zainteresowań', 'Należę do koła zainteresowań.', 'I am in a club.'),
('stepsplus4', 'płaszcz', 'Załóż płaszcz, jest zimno.', 'Put on your coat, it is cold.'),
('stepsplus4', 'komentarz', 'Napisz komentarz pod postem.', 'Write a comment under the post.'),
('stepsplus4', 'firma', 'Tata pracuje w firmie.', 'Dad works for a company.'),
('stepsplus4', 'Super!', 'Super! To świetna wiadomość!', 'Cool! That is great news!'),
('stepsplus4', 'dzień', 'Dzisiaj jest piękny dzień.', 'Today is a beautiful day.'),
('stepsplus4', 'ławka', 'Moja ławka jest przy oknie.', 'My desk is near the window.'),
('stepsplus4', 'słownik', 'Sprawdź słowo w słowniku.', 'Check the word in a dictionary.'),
('stepsplus4', 'drzwi', 'Zamknij drzwi, proszę.', 'Close the door, please.'),
('stepsplus4', 'fantastyczny', 'Ta książka jest fantastyczna.', 'This book is fantastic.'),
('stepsplus4', 'flamaster', 'Mam czerwony flamaster.', 'I have a red felt tip pen.'),
('stepsplus4', 'podłoga', 'Podłoga jest czysta.', 'The floor is clean.'),
('stepsplus4', 'przyjazny', 'Mój pies jest przyjazny.', 'My dog is friendly.'),
('stepsplus4', 'klej', 'Potrzebuję klej do plakatu.', 'I need glue for the poster.'),
('stepsplus4', 'złoty', 'Mam złoty zegarek.', 'I have a golden watch.'),
('stepsplus4', 'wpół do (pierwszej)', 'Jest wpół do pierwszej.', 'It is half past twelve.'),
('stepsplus4', 'chomik', 'Mój chomik jest mały.', 'My hamster is small.'),
('stepsplus4', 'Nie wiem.', 'Nie wiem.', 'I do not know.'),
('stepsplus4', 'Jestem spóźniony/spóźniona na lekcję.', 'Jestem spóźniony na lekcję.', 'I am late for my lesson.'),
('stepsplus4', 'Czy już jest czas na lekcje?', 'Czy już jest czas na lekcje?', 'Is it time for lessons now?'),
('stepsplus4', 'Historia jest po obiedzie.', 'Historia jest po obiedzie.', 'It is history after lunch.'),
('stepsplus4', 'Jest w marcu.', 'Jest w marcu.', 'It is in March.'),
('stepsplus4', 'Jest godzina ...', 'Jest godzina trzecia.', 'It is three o''clock.'),
('stepsplus4', 'spóźniony', 'Jestem spóźniony.', 'I am late.'),
('stepsplus4', 'lekcja', 'Lekcja zaczyna się o dziewiątej.', 'The lesson starts at nine.'),
('stepsplus4', 'światło', 'Włącz światło.', 'Turn on the light.'),
('stepsplus4', 'mający szczęście', 'Jestem mający szczęście dzisiaj.', 'I am lucky today.'),
('stepsplus4', 'lunch', 'Jemy lunch o pierwszej.', 'We have lunch at one.'),
('stepsplus4', 'matematyka', 'Lubię matematykę.', 'I like maths.'),
('stepsplus4', 'większość', 'Większość uczniów lubi szkołę.', 'Most students like school.'),
('stepsplus4', 'prawie', 'Prawie skończyłem pracę.', 'I have nearly finished my work.'),
('stepsplus4', 'zeszyt', 'Otwórz zeszyt do matematyki.', 'Open your maths notebook.'),
('stepsplus4', 'godzina (zegar)', 'Jest piąta godzina.', 'It is five o''clock.'),
('stepsplus4', 'oczywiście', 'Oczywiście, że pomogę ci.', 'Of course I will help you.'),
('stepsplus4', 'na / włączony', 'Telewizor jest włączony.', 'The TV is on.'),
('stepsplus4', 'spinacz', 'Daj mi spinacz, proszę.', 'Give me a paper clip, please.'),
('stepsplus4', 'wf', 'Mam wf w środę.', 'I have PE on Wednesday.'),
('stepsplus4', 'dzwonek', 'Dzwonek dzwoni.', 'The phone is ringing.'),
('stepsplus4', 'wysłany', 'List został wysłany.', 'The letter was posted.'),
('stepsplus4', 'szkoła podstawowa', 'Chodzę do szkoły podstawowej.', 'I go to primary school.'),
('stepsplus4', 'plecak szkolny', 'Mój plecak szkolny jest ciężki.', 'My school bag is heavy.'),
('stepsplus4', 'mundurek szkolny', 'Noszę mundurek szkolny.', 'I wear a school uniform.'),
('stepsplus4', 'tajemnica', 'Powiem ci tajemnicę.', 'I will tell you a secret.'),
('stepsplus4', 'nożyczki', 'Potrzebuję nożyczki do papieru.', 'I need scissors for the paper.'),
('stepsplus4', 'Do zobaczenia.', 'Do zobaczenia później.', 'See you later.'),
('stepsplus4', 'temperówka', 'Temperówka jest w piórniku.', 'The sharpener is in the pencil case.'),
('stepsplus4', 'półka', 'Książki są na półce.', 'The books are on the shelf.'),
('stepsplus4', 'krótki', 'Mój brat ma krótkie włosy.', 'My brother has short hair.'),
('stepsplus4', 'mały', 'Mój kotek jest mały.', 'My kitten is small.'),
('stepsplus4', 'sport', 'Lubię różne sporty.', 'I like different sports.'),
('stepsplus4', 'zszywacz', 'Zszywacz jest na biurku.', 'The stapler is on the desk.'),
('stepsplus4', 'Przestań!', 'Przestań! Boli mnie!', 'Stop it! It hurts!'),
('stepsplus4', 'uczeń', 'Jestem uczniem klasy czwartej.', 'I am a student in class four.'),
('stepsplus4', 'przedmiot', 'Matematyka to mój ulubiony przedmiot.', 'Maths is my favourite subject.'),
('stepsplus4', 'pod', 'Kot jest pod stołem.', 'The cat is under the table.'),
('stepsplus4', 'nagrywać wideo / wideo', 'Lubię nagrywać wideo.', 'I like to make videos.'),
('stepsplus4', 'czekać', 'Czekam na autobus.', 'I am waiting for the bus.'),
('stepsplus4', 'ściana', 'Plakat jest na ścianie.', 'The poster is on the wall.'),
('stepsplus4', 'Która jest godzina?', 'Która jest godzina?', 'What is the time?'),
('stepsplus4', 'gdzie', 'Gdzie jest mój zeszyt?', 'Where is my notebook?'),
('stepsplus4', 'tablica biała', 'Nauczyciel pisze na tablicy białej.', 'The teacher writes on the whiteboard.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 3 — My home (80)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'akcja', 'Akcja filmu jest interesująca.', 'The action of the film is interesting.'),
('stepsplus4', 'adres', 'Jaki jest twój adres?', 'What is your address?'),
('stepsplus4', 'zły', 'Mój brat jest zły dzisiaj.', 'My brother is angry today.'),
('stepsplus4', 'jakiś / żadny', 'Czy masz jakiś zeszyt?', 'Do you have any notebooks?'),
('stepsplus4', 'apartament', 'Mieszkam w małym apartamencie.', 'I live in a small apartment.'),
('stepsplus4', 'Jesteś gotowy?', 'Jesteś gotowy do szkoły?', 'Are you ready for school?'),
('stepsplus4', 'strych', 'Stare pudła są na strychu.', 'Old boxes are in the attic.'),
('stepsplus4', 'aleja', 'Idę aleją do parku.', 'I am walking down the avenue to the park.'),
('stepsplus4', 'balkon', 'Mam kwiaty na balkonie.', 'I have flowers on the balcony.'),
('stepsplus4', 'piwnica', 'Stare rzeczy są w piwnicy.', 'Old things are in the basement.'),
('stepsplus4', 'łazienka', 'Łazienka jest na górze.', 'The bathroom is upstairs.'),
('stepsplus4', 'piękny', 'Ona jest piękną dziewczyną.', 'She is a beautiful girl.'),
('stepsplus4', 'stolik nocny', 'Lampa jest na stoliku nocnym.', 'The lamp is on the bedside table.'),
('stepsplus4', 'za', 'Kot jest za sofą.', 'The cat is behind the sofa.'),
('stepsplus4', 'ptak', 'Ptak siedzi na drzewie.', 'A bird is sitting on the tree.'),
('stepsplus4', 'łóżko piętrowe', 'Mam łóżko piętrowe z bratem.', 'I share a bunk bed with my brother.'),
('stepsplus4', 'zajęty', 'Jestem zajęty teraz.', 'I am busy now.'),
('stepsplus4', 'Czy mogę ...?', 'Czy mogę wyjść?', 'Can I go out?'),
('stepsplus4', 'stolica', 'Warszawa to stolica Polski.', 'Warsaw is the capital of Poland.'),
('stepsplus4', 'samochód', 'Tata ma czerwony samochód.', 'Dad has a red car.'),
('stepsplus4', 'zamek', 'Zamek jest stary.', 'The castle is old.'),
('stepsplus4', 'komoda', 'Ubrania są w komodzie.', 'The clothes are in the chest of drawers.'),
('stepsplus4', 'kino', 'Idziemy do kina w sobotę.', 'We are going to the cinema on Saturday.'),
('stepsplus4', 'ubrania', 'Moje ubrania są w szafie.', 'My clothes are in the wardrobe.'),
('stepsplus4', 'wieszak na okrycia', 'Powieś płaszcz na wieszaku na okrycia.', 'Hang your coat on the coat stand.'),
('stepsplus4', 'kolorowy', 'Mam kolorowy plecak.', 'I have a colourful backpack.'),
('stepsplus4', 'Wejdź!', 'Wejdź! Drzwi są otwarte.', 'Come in! The door is open.'),
('stepsplus4', 'ciemny', 'Pokój jest ciemny.', 'The room is dark.'),
('stepsplus4', 'jadalnia', 'Jemy obiad w jadalni.', 'We eat lunch in the dining room.'),
('stepsplus4', 'loch', 'W zamku jest loch.', 'There is a dungeon in the castle.'),
('stepsplus4', 'ogromny', 'Słoń jest ogromny.', 'The elephant is enormous.'),
('stepsplus4', 'pierwsze piętro', 'Mieszkam na pierwszym piętrze.', 'I live on the first floor.'),
('stepsplus4', 'mieszkanie', 'Mam małe mieszkanie.', 'I have a small flat.'),
('stepsplus4', 'żaba', 'Żaba potrafi skakać.', 'A frog can jump.'),
('stepsplus4', 'garaż', 'Samochód jest w garażu.', 'The car is in the garage.'),
('stepsplus4', 'duch', 'W zamku jest duch.', 'There is a ghost in the castle.'),
('stepsplus4', 'iść', 'Idę do szkoły o ósmej.', 'I go to school at eight.'),
('stepsplus4', 'przedpokój', 'Buty są w przedpokoju.', 'The shoes are in the hall.'),
('stepsplus4', 'przed (miejsce)', 'Auto jest przed domem.', 'The car is in front of the house.'),
('stepsplus4', 'w środku', 'Pies jest w środku domu.', 'The dog is inside the house.'),
('stepsplus4', 'interesujący', 'Ta książka jest interesująca.', 'This book is interesting.'),
('stepsplus4', 'pokój dzienny', 'Telewizor jest w pokoju dziennym.', 'The TV is in the living room.'),
('stepsplus4', 'dużo', 'Mam dużo zabawek.', 'I have lots of toys.'),
('stepsplus4', 'człowiek / mężczyzna', 'Ten człowiek to mój sąsiad.', 'This man is my neighbour.'),
('stepsplus4', 'materac', 'Mój materac jest miękki.', 'My mattress is soft.'),
('stepsplus4', 'członek', 'Jestem członkiem klubu.', 'I am a member of the club.'),
('stepsplus4', 'karta członkowska', 'Mam kartę członkowską.', 'I have a membership card.'),
('stepsplus4', 'obok', 'Lampa jest obok łóżka.', 'The lamp is next to the bed.'),
('stepsplus4', 'Miło mi cię poznać!', 'Miło mi cię poznać!', 'Nice to meet you!'),
('stepsplus4', 'teraz', 'Teraz robię lekcje.', 'I am doing homework now.'),
('stepsplus4', 'biuro', 'Tata pracuje w biurze.', 'Dad works in an office.'),
('stepsplus4', 'Nie!', 'Nie! To niemożliwe!', 'Oh no! That is impossible!'),
('stepsplus4', 'Ojej!', 'Ojej! Upuściłem szklankę.', 'Oops! I dropped the glass.'),
('stepsplus4', 'na zewnątrz', 'Pies jest na zewnątrz.', 'The dog is outside.'),
('stepsplus4', 'piekarnik', 'Ciasto jest w piekarniku.', 'The cake is in the oven.'),
('stepsplus4', 'kod pocztowy', 'Jaki jest twój kod pocztowy?', 'What is your postcode?'),
('stepsplus4', 'więźniowie', 'Więźniowie są w lochu.', 'The prisoners are in the dungeon.'),
('stepsplus4', 'Połóż to na ...', 'Połóż to na stole.', 'Put it on the table.'),
('stepsplus4', 'szybko', 'Biegnę szybko.', 'I am running quickly.'),
('stepsplus4', 'naprawdę', 'Naprawdę lubię tę książkę.', 'I really like this book.'),
('stepsplus4', 'droga', 'Droga do szkoły jest długa.', 'The road to school is long.'),
('stepsplus4', 'biec', 'Lubię biec w parku.', 'I like to run in the park.'),
('stepsplus4', 'drugi', 'Mieszkam na drugim piętrze.', 'I live on the second floor.'),
('stepsplus4', 'Przepraszam!', 'Przepraszam! Nie chciałem.', 'Sorry! I did not mean to.'),
('stepsplus4', 'schody', 'Schody są drewniane.', 'The stairs are wooden.'),
('stepsplus4', 'opowieść', 'Babcia opowiada opowieści.', 'Grandma tells stories.'),
('stepsplus4', 'basen', 'Pływam w basenie.', 'I swim in the swimming pool.'),
('stepsplus4', 'prezydent', 'Prezydent mieszka w pałacu.', 'The President lives in the palace.'),
('stepsplus4', 'jest / są', 'Jest dom obok parku.', 'There is a house next to the park.'),
('stepsplus4', 'Są tam.', 'Są tam, w ogrodzie.', 'They are over there, in the garden.'),
('stepsplus4', 'trzeci', 'Mieszkam na trzecim piętrze.', 'I live on the third floor.'),
('stepsplus4', 'toaleta', 'Toaleta jest obok łazienki.', 'The toilet is next to the bathroom.'),
('stepsplus4', 'wieże', 'Zamek ma trzy wieże.', 'The castle has three towers.'),
('stepsplus4', 'drzewo', 'W ogrodzie jest drzewo.', 'There is a tree in the garden.'),
('stepsplus4', 'telewizor', 'Telewizor jest w salonie.', 'The TV is in the living room.'),
('stepsplus4', 'program telewizyjny', 'Oglądam program telewizyjny.', 'I am watching a TV programme.'),
('stepsplus4', 'pralka', 'Pralka jest w łazience.', 'The washing machine is in the bathroom.'),
('stepsplus4', 'Jaki/Jaka/Jakie jest twój/twoja/twoje ...?', 'Jaki jest twój adres?', 'What is your address?'),
('stepsplus4', 'Kim jesteś?', 'Kim jesteś?', 'Who are you?'),
('stepsplus4', 'dlaczego', 'Dlaczego jesteś smutny?', 'Why are you sad?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 4 — Get moving! (105, po skipnieciu duplikatow)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'zajęcie', 'Pływanie to moje ulubione zajęcie.', 'Swimming is my favourite activity.'),
('stepsplus4', 'wszyscy / cały', 'Wszyscy uczniowie są w klasie.', 'All the students are in the classroom.'),
('stepsplus4', 'baseball', 'W Ameryce lubią baseball.', 'They like baseball in America.'),
('stepsplus4', 'Uważaj!', 'Uważaj! Samochód!', 'Be careful! A car!'),
('stepsplus4', 'zaczynać', 'Zaczynam pracę o ósmej.', 'I begin work at eight.'),
('stepsplus4', 'między', 'Książka jest między dwoma zeszytami.', 'The book is between two notebooks.'),
('stepsplus4', 'Czy mogę / możemy ...?', 'Czy mogę wyjść?', 'Can I go out?'),
('stepsplus4', 'łapać piłkę', 'Potrafię łapać piłkę.', 'I can catch a ball.'),
('stepsplus4', 'mistrz', 'On jest mistrzem szachów.', 'He is a chess champion.'),
('stepsplus4', 'mistrzostwa', 'Wygraliśmy mistrzostwa.', 'We won the championship.'),
('stepsplus4', 'wspinać się', 'Małpy potrafią się wspinać.', 'Monkeys can climb.'),
('stepsplus4', 'Chodźże!', 'Chodźże! Spóźnimy się!', 'Come on! We will be late!'),
('stepsplus4', 'liczyć', 'Potrafię liczyć do stu.', 'I can count to one hundred.'),
('stepsplus4', 'czołgać się', 'Niemowlę potrafi się czołgać.', 'The baby can crawl.'),
('stepsplus4', 'krykiet', 'Anglicy lubią krykiet.', 'The English like cricket.'),
('stepsplus4', 'puchar', 'Dostał puchar za pierwsze miejsce.', 'He got a cup for first place.'),
('stepsplus4', 'tańczyć', 'Lubię tańczyć z mamą.', 'I like to dance with mum.'),
('stepsplus4', 'trudny', 'Ten test jest trudny.', 'This test is difficult.'),
('stepsplus4', 'nurkować', 'Lubię nurkować w morzu.', 'I like to dive in the sea.'),
('stepsplus4', 'robić salto', 'Potrafię robić salto.', 'I can do a somersault.'),
('stepsplus4', 'prowadzić', 'Mama prowadzi samochód.', 'Mum is driving the car.'),
('stepsplus4', 'koniec', 'To koniec książki.', 'It is the end of the book.'),
('stepsplus4', 'nawet', 'Nawet mój brat lubi sport.', 'Even my brother likes sport.'),
('stepsplus4', 'każdy', 'Każdy może grać.', 'Every person can play.'),
('stepsplus4', 'każdy, wszyscy', 'Każdy w klasie jest mily.', 'Everybody in class is nice.'),
('stepsplus4', 'szybki', 'Mój rower jest szybki.', 'My bike is fast.'),
('stepsplus4', 'latać', 'Ptaki potrafią latać.', 'Birds can fly.'),
('stepsplus4', 'stopa (stopy)', 'Boli mnie stopa.', 'My foot hurts.'),
('stepsplus4', 'piłka nożna (gra)', 'Piłka nożna to mój ulubiony sport.', 'Football is my favourite sport.'),
('stepsplus4', 'Formuła 1', 'Lubię oglądać Formułę 1.', 'I like to watch Formula 1.'),
('stepsplus4', 'zabawa', 'Mamy dużo zabawy w parku.', 'We have a lot of fun in the park.'),
('stepsplus4', 'zabawny', 'Mój kuzyn jest zabawny.', 'My cousin is funny.'),
('stepsplus4', 'przyszły', 'Przyszły rok będzie lepszy.', 'Next year will be better.'),
('stepsplus4', 'bramka', 'Strzelił bramkę!', 'He scored a goal!'),
('stepsplus4', 'gokart', 'Lubię jeździć gokartem.', 'I like to drive a go-kart.'),
('stepsplus4', 'dobry w (czymś)', 'Jestem dobry w matematyce.', 'I am good at maths.'),
('stepsplus4', 'Dobry pomysł!', 'Dobry pomysł!', 'Good idea!'),
('stepsplus4', 'goryl', 'Goryl jest silny.', 'A gorilla is strong.'),
('stepsplus4', 'wykres', 'Spójrz na wykres.', 'Look at the graph.'),
('stepsplus4', 'gitara', 'Gram na gitarze.', 'I play the guitar.'),
('stepsplus4', 'kapelusz', 'Mam słomkowy kapelusz.', 'I have a straw hat.'),
('stepsplus4', 'hokej', 'Hokej to twardy sport.', 'Hockey is a tough sport.'),
('stepsplus4', 'skakać (krótko)', 'Króliki potrafią skakać.', 'Rabbits can hop.'),
('stepsplus4', 'godzina (jednostka)', 'Czekam już godzinę.', 'I have been waiting for an hour.'),
('stepsplus4', 'Chyba tak.', 'Chyba tak.', 'I think so.'),
('stepsplus4', 'Tak mi przykro.', 'Tak mi przykro.', 'I am really sorry.'),
('stepsplus4', 'ważny', 'To ważny dzień.', 'This is an important day.'),
('stepsplus4', 'instruktor', 'Mój instruktor pływania jest miły.', 'My swimming instructor is nice.'),
('stepsplus4', 'kurtka', 'Mam nową kurtkę.', 'I have a new jacket.'),
('stepsplus4', 'żonglować', 'Klaun potrafi żonglować.', 'The clown can juggle.'),
('stepsplus4', 'skakać (wysoko)', 'Potrafię skakać wysoko.', 'I can jump high.'),
('stepsplus4', 'kangur', 'Kangur skacze wysoko.', 'A kangaroo jumps high.'),
('stepsplus4', 'karate', 'Trenuję karate.', 'I do karate.'),
('stepsplus4', 'kick-boxing', 'Mój brat trenuje kick-boxing.', 'My brother does kick-boxing.'),
('stepsplus4', 'uczyć się', 'Uczę się angielskiego.', 'I am learning English.'),
('stepsplus4', 'Zacznijmy.', 'Zacznijmy lekcję.', 'Let us begin the lesson.'),
('stepsplus4', 'lubić', 'Lubię szkołę.', 'I like school.'),
('stepsplus4', 'sztuki walki', 'Sztuki walki są popularne.', 'Martial arts are popular.'),
('stepsplus4', 'mecz', 'Oglądamy mecz piłki nożnej.', 'We are watching a football match.'),
('stepsplus4', 'góra', 'W górach jest pięknie.', 'It is beautiful in the mountains.'),
('stepsplus4', 'netball', 'Netball to brytyjski sport.', 'Netball is a British sport.'),
('stepsplus4', 'Nie, nie możesz.', 'Nie, nie możesz wyjść.', 'No, you cannot go out.'),
('stepsplus4', 'w porządku', 'W porządku, zgadzam się.', 'OK, I agree.'),
('stepsplus4', 'tylko', 'Mam tylko jednego brata.', 'I only have one brother.'),
('stepsplus4', 'Oj!', 'Oj! Boli!', 'Ow! It hurts!'),
('stepsplus4', 'park', 'Bawię się w parku.', 'I play in the park.'),
('stepsplus4', 'grać we frisbee', 'Lubię grać we frisbee.', 'I like to play frisbee.'),
('stepsplus4', 'proszę', 'Daj mi książkę, proszę.', 'Give me the book, please.'),
('stepsplus4', 'wyścig', 'Wygrałem wyścig.', 'I won the race.'),
('stepsplus4', 'samochód wyścigowy', 'On ma samochód wyścigowy.', 'He has a racing car.'),
('stepsplus4', 'jeździć (na rowerze)', 'Lubię jeździć na rowerze.', 'I like to ride a bike.'),
('stepsplus4', 'jeździć na rolkach', 'Potrafię jeździć na rolkach.', 'I can roller skate.'),
('stepsplus4', 'rugby', 'Rugby to twardy sport.', 'Rugby is a tough sport.'),
('stepsplus4', 'kanapka', 'Jem kanapkę z serem.', 'I am eating a cheese sandwich.'),
('stepsplus4', 'uczeń (uczniowie)', 'Każdy uczeń ma plecak.', 'Every schoolchild has a backpack.'),
('stepsplus4', 'strzelać / wynik', 'On strzelił trzy bramki.', 'He scored three goals.'),
('stepsplus4', 'śpiewać', 'Lubię śpiewać.', 'I like to sing.'),
('stepsplus4', 'jeździć na nartach', 'Zimą jeżdżę na nartach.', 'I ski in winter.'),
('stepsplus4', 'skakać na nartach', 'On potrafi skakać na nartach.', 'He can ski jump.'),
('stepsplus4', 'skakać przez skakankę', 'Lubię skakać przez skakankę.', 'I like to skip.'),
('stepsplus4', 'wąż', 'Wąż jest długi.', 'A snake is long.'),
('stepsplus4', 'niektóry / trochę', 'Mam trochę pieniędzy.', 'I have some money.'),
('stepsplus4', 'sportowiec', 'Robert Lewandowski to sportowiec.', 'Robert Lewandowski is a sportsman.'),
('stepsplus4', 'stać na głowie', 'Potrafię stać na głowie.', 'I can stand on my head.'),
('stepsplus4', 'gwiazda', 'Gwiazda świeci na niebie.', 'A star is shining in the sky.'),
('stepsplus4', 'sonda / ankieta', 'Robimy sondę w klasie.', 'We are doing a survey in class.'),
('stepsplus4', 'pływać', 'Pływam w basenie.', 'I swim in the pool.'),
('stepsplus4', 'huśtać się', 'Lubię się huśtać w parku.', 'I like to swing in the park.'),
('stepsplus4', 'rozmawiać', 'Lubię rozmawiać z mamą.', 'I like to talk to mum.'),
('stepsplus4', 'drużyna', 'Moja drużyna wygrała.', 'My team won.'),
-- 'telewizor' Unit 4 (television) — pominiete (duplikat klucza z Unit 3)
('stepsplus4', 'powiedz mi', 'Powiedz mi, co się stało.', 'Tell me what happened.'),
('stepsplus4', 'tenis', 'Lubię grać w tenisa.', 'I like to play tennis.'),
('stepsplus4', 'świat', 'Świat jest piękny.', 'The world is beautiful.'),
('stepsplus4', 'rzucać piłkę', 'Potrafię rzucać piłkę daleko.', 'I can throw a ball far.'),
('stepsplus4', 'tygrys', 'Tygrys jest pomarańczowy.', 'A tiger is orange.'),
('stepsplus4', 'dotykać', 'Nie dotykaj tego!', 'Do not touch this!'),
('stepsplus4', 'tradycyjny', 'To tradycyjny taniec.', 'This is a traditional dance.'),
('stepsplus4', 'podkoszulek', 'Noszę żółty podkoszulek.', 'I am wearing a yellow T-shirt.'),
('stepsplus4', 'siatkówka', 'Lubię grać w siatkówkę.', 'I like to play volleyball.'),
('stepsplus4', 'chodzić', 'Lubię chodzić w górach.', 'I like to walk in the mountains.'),
('stepsplus4', 'oglądać', 'Lubię oglądać telewizję.', 'I like to watch TV.'),
('stepsplus4', 'tydzień', 'Mam dużo planów na ten tydzień.', 'I have a lot of plans for this week.'),
('stepsplus4', 'Co cię tak rozbawiło?', 'Co cię tak rozbawiło?', 'What is so funny?'),
('stepsplus4', 'gwizdać', 'Tata potrafi gwizdać.', 'Dad can whistle.'),
('stepsplus4', 'Tak, możesz.', 'Tak, możesz wyjść.', 'Yes, you can go out.'),
('stepsplus4', 'joga', 'Lubię ćwiczyć jogę.', 'I like to do yoga.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 5 — Animals (89, po skipnieciu 'krotki' i 'ogromny')
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'grać / działać', 'Lubię grać w teatrze.', 'I like to act in the theatre.'),
('stepsplus4', 'aktor', 'On jest dobrym aktorem.', 'He is a good actor.'),
('stepsplus4', 'dorosły', 'Mój tata jest dorosły.', 'My dad is an adult.'),
('stepsplus4', 'agencja', 'Mama pracuje w agencji.', 'Mum works for an agency.'),
('stepsplus4', 'wszędzie', 'Zabawki są wszędzie.', 'Toys are all over the place.'),
('stepsplus4', 'niedźwiedź', 'Niedźwiedź żyje w lesie.', 'A bear lives in the forest.'),
('stepsplus4', 'pszczoła', 'Pszczoła robi miód.', 'A bee makes honey.'),
('stepsplus4', 'papużka falista', 'Mam papużkę falistą.', 'I have a budgie.'),
('stepsplus4', 'motyl', 'Motyl jest piękny.', 'The butterfly is beautiful.'),
('stepsplus4', 'W czym mogę pomóc?', 'W czym mogę pomóc?', 'Can I help you?'),
('stepsplus4', 'szympans', 'Szympans jest mądry.', 'A chimpanzee is clever.'),
('stepsplus4', 'obroża', 'Mój pies ma niebieską obrożę.', 'My dog has a blue collar.'),
('stepsplus4', 'Wracaj!', 'Wracaj! Już późno!', 'Come back! It is late!'),
('stepsplus4', 'Chodź tu!', 'Chodź tu, mój piesku!', 'Come here, my dog!'),
('stepsplus4', 'zboże', 'Krowy jedzą zboże.', 'Cows eat corn.'),
('stepsplus4', 'krokodyl', 'Krokodyl ma ostre zęby.', 'A crocodile has sharp teeth.'),
('stepsplus4', 'młode zwierzę', 'To młode zwierzę to lwiątko.', 'This cub is a baby lion.'),
('stepsplus4', 'opis', 'Napisz opis swojego psa.', 'Write a description of your dog.'),
('stepsplus4', 'brudny', 'Moje buty są brudne.', 'My shoes are dirty.'),
('stepsplus4', 'ucho', 'Boli mnie ucho.', 'My ear hurts.'),
('stepsplus4', 'oko', 'Mam zielone oczy.', 'I have green eyes.'),
('stepsplus4', 'pióro', 'To pióro jest kolorowe.', 'This feather is colourful.'),
('stepsplus4', 'fretka', 'Mam małą fretkę.', 'I have a small ferret.'),
('stepsplus4', 'zapominać', 'Nie zapominaj o lekcjach.', 'Do not forget about the lessons.'),
('stepsplus4', 'futro', 'Kot ma miękkie futro.', 'The cat has soft fur.'),
('stepsplus4', 'złota rybka', 'Moja złota rybka jest mała.', 'My goldfish is small.'),
('stepsplus4', 'Dobry chłopiec!', 'Dobry chłopiec! Siad!', 'Good boy! Sit!'),
('stepsplus4', 'świnka morska', 'Mam świnkę morską.', 'I have a guinea pig.'),
('stepsplus4', 'włosy', 'Mam długie włosy.', 'I have long hair.'),
('stepsplus4', 'owłosiony', 'Pies jest owłosiony.', 'The dog is hairy.'),
('stepsplus4', 'hobby', 'Czytanie to moje hobby.', 'Reading is my hobby.'),
-- 'ogromny' Unit 5 (huge) — pominiete (duplikat klucza z Unit 3 'enormous')
('stepsplus4', 'zmyślony', 'To zmyślona historia.', 'This is an imaginary story.'),
('stepsplus4', 'owad', 'Owad lata.', 'The insect is flying.'),
('stepsplus4', 'Czy mój ... tu jest?', 'Czy mój pies tu jest?', 'Is my dog here?'),
('stepsplus4', 'żart', 'Dobry żart!', 'Good joke!'),
('stepsplus4', 'koala', 'Koala je liście eukaliptusa.', 'A koala eats eucalyptus leaves.'),
('stepsplus4', 'liść (liście)', 'Liść spadł z drzewa.', 'A leaf fell from the tree.'),
('stepsplus4', 'noga', 'Skaleczyłem nogę.', 'I cut my leg.'),
('stepsplus4', 'Chodźmy stąd!', 'Chodźmy stąd, jest nudno.', 'Let us get out of here, it is boring.'),
('stepsplus4', 'jasny', 'Pokój jest jasny.', 'The room is light.'),
('stepsplus4', 'jaszczurka', 'Jaszczurka mieszka na pustyni.', 'A lizard lives in the desert.'),
('stepsplus4', 'długi', 'Żyrafa ma długą szyję.', 'A giraffe has a long neck.'),
('stepsplus4', 'mapa', 'Spójrz na mapę.', 'Look at the map.'),
('stepsplus4', 'mięso', 'Lwy jedzą mięso.', 'Lions eat meat.'),
('stepsplus4', 'melon', 'Melon jest słodki.', 'A melon is sweet.'),
('stepsplus4', 'milion', 'On ma milion zabawek.', 'He has a million toys.'),
('stepsplus4', 'małpa', 'Małpa lubi banany.', 'A monkey likes bananas.'),
('stepsplus4', 'usta', 'Otwórz usta.', 'Open your mouth.'),
('stepsplus4', 'szyja', 'Boli mnie szyja.', 'My neck hurts.'),
('stepsplus4', 'Nie ma mowy!', 'Nie ma mowy! Nie zrobię tego!', 'No way! I will not do it!'),
('stepsplus4', 'hałaśliwy', 'Mój brat jest hałaśliwy.', 'My brother is noisy.'),
('stepsplus4', 'nos', 'Mam mały nos.', 'I have a small nose.'),
('stepsplus4', 'struś', 'Struś nie potrafi latać.', 'An ostrich cannot fly.'),
('stepsplus4', 'pantera', 'Pantera jest czarna.', 'A panther is black.'),
('stepsplus4', 'papuga', 'Moja papuga mówi.', 'My parrot talks.'),
('stepsplus4', 'pingwin', 'Pingwin nie potrafi latać.', 'A penguin cannot fly.'),
('stepsplus4', 'zwierzę domowe', 'Mój pies to zwierzę domowe.', 'My dog is a pet.'),
('stepsplus4', 'telefon', 'Mam nowy telefon.', 'I have a new phone.'),
('stepsplus4', 'popularny', 'Piłka nożna jest popularna.', 'Football is popular.'),
('stepsplus4', 'własność / posiadać', 'Posiadam dwa koty.', 'I possess two cats.'),
('stepsplus4', 'prezent', 'Dostałem prezent na urodziny.', 'I got a present for my birthday.'),
('stepsplus4', 'szczenię', 'Moje szczenię jest małe.', 'My puppy is small.'),
('stepsplus4', 'dosyć', 'Jestem dosyć zmęczony.', 'I am quite tired.'),
('stepsplus4', 'szczur', 'Szczur mieszka w piwnicy.', 'A rat lives in the basement.'),
('stepsplus4', 'gad', 'Krokodyl to gad.', 'A crocodile is a reptile.'),
('stepsplus4', 'przestraszony', 'Jestem przestraszony.', 'I am scared.'),
('stepsplus4', 'koszula', 'Tata nosi białą koszulę.', 'Dad is wearing a white shirt.'),
-- 'krótki' Unit 5 (short) — pominiete (duplikat klucza z Unit 2)
('stepsplus4', 'spać', 'Lubię spać do późna.', 'I like to sleep late.'),
('stepsplus4', 'leniwiec', 'Leniwiec jest powolny.', 'A sloth is slow.'),
('stepsplus4', 'kosmos', 'Kosmos jest ogromny.', 'Space is huge.'),
('stepsplus4', 'pająk', 'Pająk ma osiem nóg.', 'A spider has eight legs.'),
('stepsplus4', 'plamka', 'Mam plamkę na koszuli.', 'I have a spot on my shirt.'),
('stepsplus4', 'patyczak', 'Patyczak wygląda jak gałązka.', 'A stick insect looks like a twig.'),
('stepsplus4', 'Jasne!', 'Jasne, że pomogę!', 'Sure, I will help!'),
('stepsplus4', 'zaskoczony', 'Jestem zaskoczony.', 'I am surprised.'),
('stepsplus4', 'ogon', 'Małpa ma długi ogon.', 'A monkey has a long tail.'),
('stepsplus4', 'dziękuję', 'Dziękuję bardzo.', 'Thank you very much.'),
('stepsplus4', 'ząb (zęby)', 'Mam biały ząb.', 'I have a white tooth.'),
('stepsplus4', 'żółw', 'Mój żółw jest powolny.', 'My tortoise is slow.'),
('stepsplus4', 'zabawka', 'Mam ulubioną zabawkę.', 'I have a favourite toy.'),
('stepsplus4', 'tresowany', 'Mój pies jest tresowany.', 'My dog is trained.'),
('stepsplus4', 'żółw morski', 'Żółw morski pływa w oceanie.', 'A turtle swims in the ocean.'),
('stepsplus4', 'niezwykły', 'To niezwykły kolor.', 'That is an unusual colour.'),
('stepsplus4', 'weterynarz', 'Weterynarz leczy zwierzęta.', 'A vet treats animals.'),
('stepsplus4', 'zdrowy / dobrze', 'Czuję się zdrowo.', 'I feel well.'),
('stepsplus4', 'dziki', 'Dziki tygrys jest niebezpieczny.', 'A wild tiger is dangerous.'),
('stepsplus4', 'skrzydło', 'Ptak ma duże skrzydło.', 'A bird has a big wing.'),
('stepsplus4', 'młody', 'Mój brat jest młody.', 'My brother is young.'),
('stepsplus4', 'zoo', 'Idziemy do zoo.', 'We are going to the zoo.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 6 — People (75)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'przymiotnik', 'Duży to przymiotnik.', 'Big is an adjective.'),
('stepsplus4', 'popołudnie', 'Spotkamy się po południu.', 'We will meet in the afternoon.'),
('stepsplus4', 'zadziwiający', 'Ten widok jest zadziwiający.', 'This view is amazing.'),
('stepsplus4', 'wysportowany', 'Mój brat jest wysportowany.', 'My brother is athletic.'),
('stepsplus4', 'niemowlę', 'Moja siostra to niemowlę.', 'My sister is a baby.'),
('stepsplus4', 'mały brat / mała siostra', 'Mam małego brata.', 'I have a baby brother.'),
('stepsplus4', 'niewidomy', 'Niewidomy człowiek używa laski.', 'A blind person uses a stick.'),
('stepsplus4', 'kość', 'Pies lubi kość.', 'A dog likes a bone.'),
('stepsplus4', 'autobus', 'Czekam na autobus.', 'I am waiting for the bus.'),
('stepsplus4', 'przystanek autobusowy', 'Przystanek autobusowy jest blisko.', 'The bus stop is near.'),
('stepsplus4', 'telewizja kablowa', 'Mamy telewizję kablową.', 'We have cable TV.'),
('stepsplus4', 'karnawał', 'W lutym jest karnawał.', 'There is a carnival in February.'),
('stepsplus4', 'szachy', 'Lubię grać w szachy.', 'I like to play chess.'),
('stepsplus4', 'Chiny', 'Chiny to duży kraj.', 'China is a big country.'),
('stepsplus4', 'chiński', 'Uczę się chińskiego.', 'I am learning Chinese.'),
('stepsplus4', 'czysty', 'Mój pokój jest czysty.', 'My room is clean.'),
('stepsplus4', 'niezdarny', 'Jestem niezdarny dzisiaj.', 'I am clumsy today.'),
('stepsplus4', 'kostiumy', 'Aktorzy noszą kostiumy.', 'The actors wear costumes.'),
('stepsplus4', 'kultura', 'Lubię chińską kulturę.', 'I like Chinese culture.'),
('stepsplus4', 'kręcony', 'Mam kręcone włosy.', 'I have curly hair.'),
('stepsplus4', 'ciemne (włosy)', 'Anna ma ciemne włosy.', 'Anna has dark hair.'),
('stepsplus4', 'data', 'Jaka jest dzisiejsza data?', 'What is today''s date?'),
('stepsplus4', 'różnica', 'Jaka jest różnica?', 'What is the difference?'),
('stepsplus4', 'codziennie', 'Codziennie chodzę do szkoły.', 'I go to school every day.'),
('stepsplus4', 'gruby', 'Mój kot jest gruby.', 'My cat is fat.'),
('stepsplus4', 'sztuczne ognie', 'W Sylwester są sztuczne ognie.', 'There are fireworks on New Year''s Eve.'),
('stepsplus4', 'Chwileczkę!', 'Chwileczkę! Zaraz wracam.', 'Hang on! I will be right back.'),
('stepsplus4', 'Czy masz / macie (jakieś) ...?', 'Czy masz jakieś zwierzę?', 'Have you got any pets?'),
('stepsplus4', 'wzrost', 'Jaki jest twój wzrost?', 'What is your height?'),
('stepsplus4', 'jej', 'To jej książka.', 'This is her book.'),
('stepsplus4', 'Hongkong', 'Hongkong to duże miasto.', 'Hong Kong is a big city.'),
('stepsplus4', 'inteligentny', 'Mój brat jest inteligentny.', 'My brother is intelligent.'),
('stepsplus4', 'Tak myślę.', 'Tak myślę.', 'I think so.'),
('stepsplus4', 'Nie jestem pewny / pewna.', 'Nie jestem pewny.', 'I am not sure.'),
('stepsplus4', 'Mam ...', 'Mam dwa koty.', 'I have got two cats.'),
('stepsplus4', 'sok', 'Piję sok pomarańczowy.', 'I drink orange juice.'),
('stepsplus4', 'język', 'Polski to mój język.', 'Polish is my language.'),
('stepsplus4', 'leniwy', 'Mój kot jest leniwy.', 'My cat is lazy.'),
('stepsplus4', 'pamięć', 'Mam dobrą pamięć.', 'I have a good memory.'),
('stepsplus4', 'mleko', 'Piję mleko codziennie.', 'I drink milk every day.'),
('stepsplus4', 'motocykl', 'Tata ma motocykl.', 'Dad has a motorbike.'),
('stepsplus4', 'wielokulturowy', 'Londyn to wielokulturowe miasto.', 'London is a multicultural city.'),
('stepsplus4', 'Nowy Rok', 'Wszystkiego najlepszego z okazji Nowego Roku!', 'Happy New Year!'),
('stepsplus4', 'rzeczownik', 'Pies to rzeczownik.', 'Dog is a noun.'),
('stepsplus4', 'stary', 'Mój rower jest stary.', 'My bike is old.'),
('stepsplus4', 'nasz', 'To nasz dom.', 'This is our house.'),
('stepsplus4', 'paczka', 'Dostałem paczkę od babci.', 'I got a parcel from grandma.'),
('stepsplus4', 'osobowość', 'On ma fajną osobowość.', 'He has a cool personality.'),
('stepsplus4', 'woleć', 'Wolę herbatę od kawy.', 'I prefer tea to coffee.'),
('stepsplus4', 'problem', 'Mam mały problem.', 'I have a small problem.'),
('stepsplus4', 'cichy', 'Klasa jest cicha.', 'The class is quiet.'),
('stepsplus4', 'Naprawdę?', 'Naprawdę? Nie wiedziałem.', 'Really? I did not know.'),
('stepsplus4', 'niegrzeczny', 'Mój brat jest niegrzeczny.', 'My brother is rude.'),
('stepsplus4', 'dzielić (się)', 'Lubię dzielić się zabawkami.', 'I like to share toys.'),
('stepsplus4', 'wolny', 'Żółw jest wolny.', 'A tortoise is slow.'),
('stepsplus4', 'coś', 'Chcę coś jeść.', 'I want to eat something.'),
('stepsplus4', 'blaszane bębenki', 'Słyszę blaszane bębenki.', 'I can hear the steel drums.'),
('stepsplus4', 'prosty', 'Mam proste włosy.', 'I have straight hair.'),
('stepsplus4', 'ulica', 'Moja ulica jest długa.', 'My street is long.'),
('stepsplus4', 'wymienić', 'Wymienimy się kartami.', 'Let us swap cards.'),
('stepsplus4', 'cukierek / słodki', 'Lubię słodkie cukierki.', 'I like sweet candies.'),
('stepsplus4', 'talent', 'Mój brat ma talent muzyczny.', 'My brother has a musical talent.'),
('stepsplus4', 'wysoki', 'Mój tata jest wysoki.', 'My dad is tall.'),
('stepsplus4', 'rozmowny', 'Moja siostra jest rozmowna.', 'My sister is talkative.'),
('stepsplus4', 'wiadomość tekstowa', 'Wysłałem wiadomość tekstową.', 'I sent a text message.'),
('stepsplus4', 'To miłe.', 'To miłe z twojej strony.', 'That is nice of you.'),
('stepsplus4', 'ich', 'To ich dom.', 'This is their house.'),
('stepsplus4', 'te / tamte', 'Te książki są moje.', 'These books are mine.'),
('stepsplus4', 'chudy', 'Mój brat jest chudy.', 'My brother is thin.'),
('stepsplus4', 'rzecz', 'Mam dużo rzeczy.', 'I have a lot of things.'),
('stepsplus4', 'próżny', 'On jest próżny.', 'He is vain.'),
('stepsplus4', 'zegarek', 'Mam nowy zegarek.', 'I have a new watch.'),
('stepsplus4', 'Jaki / jaka / jakie jest ...?', 'Jaki jest twój brat?', 'What is your brother like?'),
('stepsplus4', 'kobieta', 'Ta kobieta to moja mama.', 'This woman is my mum.'),
('stepsplus4', 'twój', 'To twój zeszyt.', 'This is your notebook.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 7 — My day (104, po skipnieciu duplikatow)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'bar (kanapkowy)', 'Idę do baru kanapkowego.', 'I am going to the sandwich bar.'),
('stepsplus4', 'o', 'Rozmawiamy o szkole.', 'We are talking about school.'),
('stepsplus4', 'Akcja!', 'Akcja! Kamera!', 'Action! Camera!'),
('stepsplus4', 'potem', 'Najpierw lekcje, potem zabawa.', 'First lessons, after that fun.'),
('stepsplus4', 'tak czy inaczej', 'Tak czy inaczej, idę do parku.', 'Anyway, I am going to the park.'),
('stepsplus4', 'przybywać', 'Przybywam do szkoły o ósmej.', 'I arrive at school at eight.'),
('stepsplus4', 'o (godzinie)', 'Spotkamy się o piątej.', 'We will meet at five.'),
('stepsplus4', 'badminton', 'Lubię grać w badmintona.', 'I like to play badminton.'),
('stepsplus4', 'przed (czas)', 'Spotkamy się przed lekcją.', 'We will meet before the lesson.'),
('stepsplus4', 'kierowca autobusu', 'Kierowca autobusu jest miły.', 'The bus driver is nice.'),
('stepsplus4', 'dzwonić', 'Telefon dzwoni.', 'The phone is ringing.'),
('stepsplus4', 'stołówka', 'Jemy obiad w stołówce.', 'We have lunch in the canteen.'),
('stepsplus4', 'reszta', 'Daj mi resztę.', 'Give me the change.'),
('stepsplus4', 'bohater', 'Spider-Man jest moim bohaterem.', 'Spider-Man is my hero.'),
('stepsplus4', 'centrum miasta', 'Idziemy do centrum miasta.', 'We are going to the city centre.'),
('stepsplus4', 'zbierać', 'Lubię zbierać znaczki.', 'I like to collect stamps.'),
('stepsplus4', 'kolekcjonować rzeczy', 'Lubię kolekcjonować rzeczy.', 'I like to collect things.'),
('stepsplus4', 'bilet dzienny', 'Kupiłem bilet dzienny.', 'I bought a day pass.'),
('stepsplus4', 'odrobić pracę domową', 'Muszę odrobić pracę domową.', 'I have to do my homework.'),
('stepsplus4', 'lekarz', 'Lekarz pracuje w szpitalu.', 'The doctor works at the hospital.'),
('stepsplus4', 'delfin', 'Delfin jest mądry.', 'A dolphin is clever.'),
('stepsplus4', 'napój', 'Mój ulubiony napój to sok.', 'My favourite drink is juice.'),
('stepsplus4', 'wcześnie', 'Wstaję wcześnie rano.', 'I get up early in the morning.'),
('stepsplus4', 'jeść', 'Lubię jeść owoce.', 'I like to eat fruit.'),
('stepsplus4', 'osiemdziesiąt pięć', 'Mam osiemdziesiąt pięć kredek.', 'I have eighty-five crayons.'),
('stepsplus4', 'wieczór', 'Wieczorem oglądam telewizję.', 'I watch TV in the evening.'),
('stepsplus4', 'co', 'Co lubisz robić?', 'What do you like to do?'),
('stepsplus4', 'pięćdziesiąt', 'Mam pięćdziesiąt książek.', 'I have fifty books.'),
('stepsplus4', 'kończyć', 'Lekcje kończą się o trzeciej.', 'Lessons finish at three.'),
('stepsplus4', 'czterdzieści', 'Tata ma czterdzieści lat.', 'Dad is forty years old.'),
('stepsplus4', 'ubrać się', 'Ubieram się szybko.', 'I get dressed quickly.'),
('stepsplus4', 'wstawać', 'Wstaję o siódmej.', 'I get up at seven.'),
('stepsplus4', 'dawać', 'Daj mi tę książkę.', 'Give me that book.'),
('stepsplus4', 'jechać samochodem', 'Jadę samochodem do szkoły.', 'I go to school by car.'),
('stepsplus4', 'jeździć na rowerze', 'Jeżdżę na rowerze codziennie.', 'I go cycling every day.'),
('stepsplus4', 'chodzić potańczyć', 'Lubię chodzić potańczyć.', 'I like to go dancing.'),
-- 'pływać' Unit 7 (go swimming) — pominiete (duplikat klucza z Unit 4 'swim')
('stepsplus4', 'iść spać', 'Idę spać o dziewiątej.', 'I go to bed at nine.'),
('stepsplus4', 'iść do szkoły', 'Idę do szkoły o ósmej.', 'I go to school at eight.'),
('stepsplus4', 'iść do parku', 'Lubię iść do parku.', 'I like to go to the park.'),
('stepsplus4', 'fryzjer', 'Idę do fryzjera.', 'I am going to the hairdresser''s.'),
('stepsplus4', 'wykąpać się', 'Wieczorem lubię się wykąpać.', 'I like to have a bath in the evening.'),
('stepsplus4', 'brać prysznic', 'Biorę prysznic rano.', 'I have a shower in the morning.'),
('stepsplus4', 'jeść śniadanie', 'Jem śniadanie z mamą.', 'I have breakfast with mum.'),
('stepsplus4', 'jeść obiad', 'Jemy obiad o pierwszej.', 'We have dinner at one.'),
('stepsplus4', 'jeść lunch', 'Jemy lunch w szkole.', 'We have lunch at school.'),
('stepsplus4', 'pomagać mamie', 'Pomagam mamie w kuchni.', 'I help my mum in the kitchen.'),
('stepsplus4', 'Proszę.', 'Proszę, oto twoja książka.', 'Here you are, your book.'),
('stepsplus4', 'To ... reszty.', 'To trzy złote reszty.', 'Here is three zlotys change.'),
('stepsplus4', 'Hej, ty!', 'Hej, ty! Chodź tu!', 'Hey, you! Come here!'),
('stepsplus4', 'szpital', 'Lekarz pracuje w szpitalu.', 'A doctor works at the hospital.'),
('stepsplus4', 'Ile (to kosztuje)?', 'Ile to kosztuje?', 'How much is it?'),
('stepsplus4', 'Pospiesz się!', 'Pospiesz się! Spóźnimy się!', 'Hurry up! We will be late!'),
('stepsplus4', 'Wiem.', 'Wiem, gdzie to jest.', 'I know where it is.'),
('stepsplus4', 'na czas / po południu', 'Spotkamy się po południu.', 'We will meet in the afternoon.'),
('stepsplus4', 'praca', 'Tata ma dobrą pracę.', 'Dad has a good job.'),
('stepsplus4', 'śmiać się', 'Lubię się śmiać.', 'I like to laugh.'),
('stepsplus4', 'słuchać muzyki', 'Lubię słuchać muzyki.', 'I like to listen to music.'),
('stepsplus4', 'kochać', 'Kocham mamę.', 'I love my mum.'),
('stepsplus4', 'czasopismo', 'Czytam czasopismo.', 'I am reading a magazine.'),
('stepsplus4', 'charakteryzacja / makijaż', 'Aktorka robi makijaż.', 'The actress is doing make-up.'),
('stepsplus4', 'spotykać się z przyjaciółmi', 'Lubię spotykać się z przyjaciółmi.', 'I like to meet my friends.'),
('stepsplus4', 'pieniądze', 'Oszczędzam pieniądze.', 'I am saving money.'),
('stepsplus4', 'rano', 'Rano jem śniadanie.', 'I have breakfast in the morning.'),
('stepsplus4', 'odtwarzacz MP3', 'Mam nowy odtwarzacz MP3.', 'I have a new MP3 player.'),
('stepsplus4', 'instrument muzyczny', 'Gitara to instrument muzyczny.', 'A guitar is a musical instrument.'),
('stepsplus4', 'nigdy', 'Nigdy nie spóźniam się do szkoły.', 'I am never late for school.'),
('stepsplus4', 'pielęgniarka', 'Pielęgniarka pomaga lekarzowi.', 'The nurse helps the doctor.'),
('stepsplus4', 'często', 'Często chodzę do parku.', 'I often go to the park.'),
('stepsplus4', 'rodzic', 'Mój rodzic mnie kocha.', 'My parent loves me.'),
('stepsplus4', 'makaron', 'Lubię makaron z serem.', 'I like pasta with cheese.'),
('stepsplus4', 'pens', 'Mam dziesięć pensów.', 'I have ten pence.'),
('stepsplus4', 'grać w gry komputerowe', 'Lubię grać w gry komputerowe.', 'I like to play computer games.'),
('stepsplus4', 'bawić się z przyjaciółmi', 'Lubię bawić się z przyjaciółmi.', 'I like to play with my friends.'),
('stepsplus4', 'kieszonkowe', 'Dostaję kieszonkowe od taty.', 'I get pocket money from dad.'),
('stepsplus4', 'funt', 'Książka kosztuje pięć funtów.', 'The book costs five pounds.'),
-- 'szybko' Unit 7 (quickly) — pominiete (duplikat klucza z Unit 3)
('stepsplus4', 'czytać', 'Lubię czytać książki.', 'I like to read books.'),
('stepsplus4', 'czasopisma', 'Lubię czytać czasopisma.', 'I like to read magazines.'),
('stepsplus4', 'pamiętać', 'Pamiętam twoje urodziny.', 'I remember your birthday.'),
('stepsplus4', 'zasady', 'Znam zasady gry.', 'I know the rules of the game.'),
('stepsplus4', 'kiełbasa', 'Lubię kiełbasę z chlebem.', 'I like sausage with bread.'),
('stepsplus4', 'oszczędzać', 'Oszczędzam na rower.', 'I am saving for a bike.'),
('stepsplus4', 'nauka', 'Lubię naukę w szkole.', 'I like schoolwork.'),
('stepsplus4', 'opera mydlana', 'Mama ogląda operę mydlaną.', 'Mum is watching a soap opera.'),
('stepsplus4', 'czasami', 'Czasami chodzę do kina.', 'I sometimes go to the cinema.'),
('stepsplus4', 'wyjątkowy', 'To wyjątkowy dzień.', 'This is a special day.'),
('stepsplus4', 'wydawać', 'Wydaję mało pieniędzy.', 'I spend little money.'),
-- 'zaczynać' Unit 7 (start) — pominiete (duplikat klucza z Unit 4 'begin')
('stepsplus4', 'Przestań rozmawiać!', 'Przestań rozmawiać w klasie!', 'Stop talking in class!'),
('stepsplus4', 'studio', 'Pracuje w studio.', 'He works in a studio.'),
('stepsplus4', 'wynieść śmiecie', 'Wynieś śmiecie, proszę.', 'Take the rubbish out, please.'),
('stepsplus4', 'taksówka', 'Jadę taksówką do domu.', 'I am going home by taxi.'),
('stepsplus4', 'To żart!', 'To żart! Nie martw się!', 'That is a joke! Do not worry!'),
('stepsplus4', 'Trzy bilety na ...', 'Trzy bilety na film, proszę.', 'Three tickets for the film, please.'),
('stepsplus4', 'bilet', 'Mam bilet na pociąg.', 'I have a ticket for the train.'),
('stepsplus4', 'porządkować', 'Lubię porządkować pokój.', 'I like to tidy my room.'),
('stepsplus4', 'sprzątać swój pokój', 'Sprzątam swój pokój w sobotę.', 'I tidy my room on Saturday.'),
('stepsplus4', 'dworzec', 'Pociąg odjeżdża z dworca.', 'The train leaves from the station.'),
('stepsplus4', 'wyprowadzać psa', 'Wyprowadzam psa rano.', 'I walk the dog in the morning.'),
('stepsplus4', 'garderoba', 'Moje ubrania są w garderobie.', 'My clothes are in the wardrobe.'),
('stepsplus4', 'myć', 'Myję ręce przed obiadem.', 'I wash my hands before lunch.'),
('stepsplus4', 'oglądać telewizję', 'Wieczorem oglądam telewizję.', 'I watch TV in the evening.'),
('stepsplus4', 'dzień powszedni', 'W dzień powszedni chodzę do szkoły.', 'I go to school on a weekday.'),
('stepsplus4', 'weekend', 'W weekend odpoczywam.', 'I rest at the weekend.'),
('stepsplus4', 'Który autobus jedzie do ...?', 'Który autobus jedzie do centrum?', 'Which bus goes to the centre?'),
('stepsplus4', 'bez', 'Idę bez płaszcza.', 'I am going without a coat.'),
('stepsplus4', 'pracować', 'Tata pracuje w biurze.', 'Dad works in an office.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 8 — Free time (64)
-- ═══════════════════════════════════════════════════════════
('stepsplus4', 'piłka', 'Mam czerwoną piłkę.', 'I have a red ball.'),
('stepsplus4', 'plaża', 'Latem chodzę na plażę.', 'I go to the beach in summer.'),
('stepsplus4', 'diabelskie koło', 'Diabelskie koło jest wysokie.', 'The big wheel is tall.'),
('stepsplus4', 'dzik', 'Dzik mieszka w lesie.', 'A boar lives in the forest.'),
('stepsplus4', 'wycieczka łodzią', 'Idziemy na wycieczkę łodzią.', 'We are going on a boat trip.'),
('stepsplus4', 'biwakować', 'Lubimy biwakować w lesie.', 'We like camping in the forest.'),
('stepsplus4', 'gotowanie', 'Gotowanie to moje hobby.', 'Cooking is my hobby.'),
('stepsplus4', 'krowa', 'Krowa daje mleko.', 'A cow gives milk.'),
('stepsplus4', 'śliczny', 'Twój kot jest śliczny.', 'Your cat is cute.'),
('stepsplus4', 'dyskoteka', 'Idziemy na dyskotekę.', 'We are going to the disco.'),
('stepsplus4', 'trenować balet', 'Anna trenuje balet.', 'Anna does ballet.'),
('stepsplus4', 'układać puzzle', 'Lubię układać puzzle.', 'I like to do jigsaws.'),
('stepsplus4', 'e-mail', 'Wysłałem e-mail.', 'I sent an email.'),
('stepsplus4', 'podekscytowany', 'Jestem podekscytowany!', 'I am excited!'),
('stepsplus4', 'gospodarstwo rolne', 'Mieszkam na gospodarstwie rolnym.', 'I live on a farm.'),
('stepsplus4', 'karmić', 'Karmię psa codziennie.', 'I feed my dog every day.'),
('stepsplus4', 'czas wolny', 'Mam dużo czasu wolnego.', 'I have a lot of free time.'),
('stepsplus4', 'park rozrywki', 'Idziemy do parku rozrywki.', 'We are going to the fun park.'),
('stepsplus4', 'pojeździć na rowerze', 'Lubię pojeździć na rowerze.', 'I like to go cycling.'),
('stepsplus4', 'iść na koncert', 'Idziemy na koncert.', 'We are going to a concert.'),
('stepsplus4', 'iść źle', 'Coś poszło źle.', 'Something went wrong.'),
('stepsplus4', 'koza', 'Koza je trawę.', 'A goat eats grass.'),
('stepsplus4', 'rosnąć / uprawiać', 'Mama uprawia kwiaty.', 'Mum grows flowers.'),
('stepsplus4', 'zdarzać się', 'Co się zdarza?', 'What is happening?'),
('stepsplus4', 'hipopotam', 'Hipopotam mieszka w rzece.', 'A hippo lives in the river.'),
('stepsplus4', 'zainteresowania', 'Mam dużo zainteresowań.', 'I have a lot of hobbies.'),
('stepsplus4', 'bezdomny', 'Pomagamy bezdomnym ludziom.', 'We help homeless people.'),
('stepsplus4', 'Nie mam nic przeciwko temu.', 'Nie mam nic przeciwko temu.', 'I do not mind.'),
('stepsplus4', 'Lubię ...', 'Lubię tańczyć.', 'I like dancing.'),
('stepsplus4', 'jazda na łyżwach', 'Lubię jazdę na łyżwach.', 'I like ice skating.'),
('stepsplus4', 'To katastrofa!', 'To katastrofa! Wszystko zepsute!', 'It is a disaster! Everything is broken!'),
('stepsplus4', 'klawiatura', 'Klawiatura jest na biurku.', 'The keyboard is on the desk.'),
('stepsplus4', 'owca / jagnię', 'Jagnię jest małe.', 'A lamb is small.'),
('stepsplus4', 'lemoniada', 'Lubię zimną lemoniadę.', 'I like cold lemonade.'),
('stepsplus4', 'lama', 'Lama mieszka w Andach.', 'A llama lives in the Andes.'),
('stepsplus4', 'jezioro', 'Pływamy w jeziorze.', 'We swim in the loch.'),
('stepsplus4', 'opiekować się', 'Lubię opiekować się psem.', 'I like to look after my dog.'),
('stepsplus4', 'północ', 'Polska jest na północy Europy.', 'Poland is in the north of Europe.'),
('stepsplus4', 'albo', 'Wybierz: pizza albo kanapka.', 'Choose: pizza or sandwich.'),
('stepsplus4', 'malować obraz', 'Lubię malować obrazy.', 'I like to paint pictures.'),
('stepsplus4', 'świnia', 'Świnia mieszka na farmie.', 'A pig lives on a farm.'),
('stepsplus4', 'grać w szachy', 'Tata gra w szachy.', 'Dad plays chess.'),
('stepsplus4', 'grać w piłkę nożną', 'Lubimy grać w piłkę nożną.', 'We like to play football.'),
('stepsplus4', 'woleć ...', 'Wolę herbatę niż kawę.', 'I prefer tea to coffee.'),
('stepsplus4', 'Odpocznij!', 'Odpocznij! Jesteś zmęczony.', 'Relax! You are tired.'),
('stepsplus4', 'szkocki', 'On jest szkockim sportowcem.', 'He is a Scottish sportsman.'),
('stepsplus4', 'wybrzeże', 'Latem jedziemy na wybrzeże.', 'We go to the seaside in summer.'),
('stepsplus4', 'wysłać', 'Wysłałem list do babci.', 'I sent a letter to grandma.'),
('stepsplus4', 'pokaz', 'Idziemy na pokaz.', 'We are going to a show.'),
('stepsplus4', 'mówić', 'Mówię po polsku.', 'I speak Polish.'),
('stepsplus4', 'surfować', 'Lubię surfować w morzu.', 'I like to surf in the sea.'),
('stepsplus4', 'okropny', 'Pogoda jest okropna.', 'The weather is terrible.'),
('stepsplus4', 'tytuł', 'Jaki jest tytuł książki?', 'What is the title of the book?'),
('stepsplus4', 'prawda / prawdziwy', 'To prawda.', 'That is true.'),
('stepsplus4', 'zwykle', 'Zwykle wstaję o siódmej.', 'I usually get up at seven.'),
('stepsplus4', 'wieś', 'Babcia mieszka na wsi.', 'Grandma lives in a village.'),
('stepsplus4', 'odwiedzać', 'Odwiedzam babcię w niedzielę.', 'I visit grandma on Sunday.'),
('stepsplus4', 'sport wodny', 'Surfowanie to sport wodny.', 'Surfing is a watersport.'),
('stepsplus4', 'oglądać mecz piłki nożnej', 'Lubię oglądać mecz piłki nożnej.', 'I like to watch a football match.'),
('stepsplus4', 'obejrzeć program / pokaz', 'Wieczorem oglądamy pokaz.', 'We watch a show in the evening.'),
('stepsplus4', 'mokry', 'Mój sweter jest mokry.', 'My jumper is wet.'),
('stepsplus4', 'Jak uważasz?', 'Jak uważasz? Dobry pomysł?', 'What do you think? Good idea?'),
('stepsplus4', 'O rety!', 'O rety! Upadłem!', 'Whoops! I fell!'),
('stepsplus4', 'zwycięzca', 'Jesteś zwycięzcą!', 'You are the winner!')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Steps Plus 4: 672 unikalnych zdan zaktualizowanych/dodanych w word_sentences (678 wpisow w data.js, 4 pary roznych znaczen rozdzielone disambiguacja nawiasem, 6 synonimicznych duplikatow zdedupedowanych przez UPSERT).';
END $$;
