-- ═══════════════════════════════════════════════════════════
-- Fix sentences: TOGETHER 5 (klasa 5, szkola podstawowa)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 327 unikalnych slowek z Together 5 (Macmillan).
--
-- Tematy unitow:
--   Unit 1 (34): szkola + miejsca w szkole + must/mustn't
--   Unit 2 (39): kuchnia + przyrzady + jedzenie + prosby
--   Unit 3 (37): zdrowy styl zycia + obowiazki domowe
--   Unit 4 (35): cialo + emocje + rady (should/shouldn't)
--   Unit 5 (53): zwierzeta + przymiotniki + ciala + opinie
--   Unit 6 (59): miesiace + liczebniki porzadkowe + zawody + zyczenia
--   Unit 7 (47): wydarzenia + transport + past simple
--   Unit 8 (40): pogoda + pory roku + geografia + zaproszenia
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — School subjects, places, must/mustn't (34)
-- ═══════════════════════════════════════════════════════════
('together5', 'przedmioty szkolne', 'Lubię różne przedmioty szkolne.', 'I like different school subjects.'),
('together5', 'plastyka, sztuka', 'Plastyka to mój ulubiony przedmiot.', 'Art is my favourite subject.'),
('together5', 'biologia', 'Biologia jest interesująca.', 'Biology is interesting.'),
('together5', 'informatyka', 'Mam informatykę w środy.', 'I have computing on Wednesday.'),
('together5', 'język obcy', 'Angielski to mój język obcy.', 'English is my foreign language.'),
('together5', 'geografia', 'Lubię geografię.', 'I like geography.'),
('together5', 'historia', 'Historia opowiada o przeszłości.', 'History tells about the past.'),
('together5', 'matematyka', 'Lubię matematykę.', 'I like maths.'),
('together5', 'wychowanie fizyczne', 'Mam wf w środę.', 'I have PE on Wednesday.'),
('together5', 'nauki ścisłe (przyroda, chemia, fizyka)', 'Nauki ścisłe są trudne.', 'Science is difficult.'),
('together5', 'technika', 'Lubię lekcje techniki.', 'I like technology lessons.'),
('together5', 'sala komputerowa', 'Mamy lekcje w sali komputerowej.', 'We have lessons in the computer room.'),
('together5', 'sala gimnastyczna, siłownia', 'Ćwiczę w sali gimnastycznej.', 'I exercise in the gym.'),
('together5', 'laboratorium', 'Mamy laboratorium chemiczne.', 'We have a chemistry lab.'),
('together5', 'biblioteka', 'Czytam w bibliotece.', 'I read at the library.'),
('together5', 'hol szkoły', 'Spotykamy się w holu szkoły.', 'We meet in the main hall.'),
('together5', 'boiska', 'Gramy na boiskach.', 'We play on the playing fields.'),
('together5', 'stołówka', 'Jemy obiad w stołówce.', 'We have lunch in the canteen.'),
('together5', 'klasa, sala lekcyjna', 'Nasza sala lekcyjna jest jasna.', 'Our classroom is bright.'),
('together5', 'szatnia', 'Zostawiam płaszcz w szatni.', 'I leave my coat in the cloakroom.'),
('together5', 'korytarz', 'Korytarz jest długi.', 'The corridor is long.'),
('together5', 'dziedziniec (przed szkołą), plac zabaw', 'Bawimy się na placu zabaw.', 'We play in the playground.'),
('together5', 'sekretariat szkoły', 'Sekretariat jest na parterze.', 'The school office is on the ground floor.'),
('together5', 'toaleta', 'Toaleta jest po lewej.', 'The toilet is on the left.'),
('together5', 'sklepik szkolny', 'Kupuję kanapkę w sklepiku szkolnym.', 'I buy a sandwich at the tuck shop.'),
('together5', 'Pośpiesz się! Jesteśmy spóźnieni!', 'Pośpiesz się! Jesteśmy spóźnieni!', 'Hurry up! We are late!'),
('together5', 'Zaczekaj na mnie!', 'Zaczekaj na mnie!', 'Wait for me!'),
('together5', 'Pewnie!/Oczywiście!', 'Pewnie! Oczywiście!', 'You bet!'),
('together5', 'Musimy utrzymać porządek', 'Musimy utrzymać porządek.', 'We must keep it tidy.'),
('together5', 'Musimy wrzucać śmieci do kosza.', 'Musimy wrzucać śmieci do kosza.', 'We must put litter in the bin.'),
('together5', 'Musimy jutro przynieść ubrania sportowe.', 'Musimy jutro przynieść ubrania sportowe.', 'We must bring sports clothes tomorrow.'),
('together5', 'Nie wolno jeść w klasie.', 'Nie wolno jeść w klasie.', 'We must not eat in our classroom.'),
('together5', 'Nie wolno się spóźniać.', 'Nie wolno się spóźniać.', 'We must not be late.'),
('together5', 'Nie wolno używać telefonów w klasie.', 'Nie wolno używać telefonów w klasie.', 'We must not use our phones in class.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — Kitchen, cooking, healthy food (39)
-- ═══════════════════════════════════════════════════════════
('together5', 'miska', 'Mama wsypuje płatki do miski.', 'Mum is pouring cereal into the bowl.'),
('together5', 'puszka (np. na napój)', 'Otwieram puszkę z colą.', 'I am opening a can of cola.'),
('together5', 'karton', 'Mleko jest w kartonie.', 'The milk is in a carton.'),
('together5', 'patelnia', 'Smażę jajka na patelni.', 'I am frying eggs in the frying pan.'),
('together5', 'słoik', 'Mam słoik z dżemem.', 'I have a jar of jam.'),
('together5', 'kubek', 'Piję herbatę z kubka.', 'I am drinking tea from a mug.'),
('together5', 'talerz', 'Talerz jest na stole.', 'The plate is on the table.'),
('together5', 'puszka (np. na konserwę)', 'Otwieram puszkę z fasolą.', 'I am opening a tin of beans.'),
('together5', 'dodawać', 'Dodaj sól do zupy.', 'Add salt to the soup.'),
('together5', 'gotować', 'Gotuję wodę na herbatę.', 'I am boiling water for tea.'),
('together5', 'siekać', 'Siekam cebulę.', 'I am chopping the onion.'),
('together5', 'smażyć', 'Smażę jajka na śniadanie.', 'I am frying eggs for breakfast.'),
('together5', 'mieszać', 'Mieszaj sałatkę.', 'Mix the salad.'),
('together5', 'kroić', 'Kroję chleb.', 'I am slicing the bread.'),
('together5', 'gotować na parze', 'Gotuję warzywa na parze.', 'I am steaming the vegetables.'),
('together5', 'węglowodany', 'Makaron i ryż to węglowodany.', 'Pasta and rice are carbs.'),
('together5', 'nabiał', 'Mleko i ser to nabiał.', 'Milk and cheese are dairy.'),
('together5', 'owoc lub warzywo pięć razy dziennie', 'Jem owoc lub warzywo pięć razy dziennie.', 'I have five-a-day.'),
('together5', 'olej i tłuszcz', 'Olej i tłuszcz są kaloryczne.', 'Oil and fat are caloric.'),
('together5', 'białko', 'Mięso to białko.', 'Meat is protein.'),
('together5', 'ciecierzyca', 'Ciecierzyca jest w humusie.', 'There are chickpeas in hummus.'),
('together5', 'suszone owoce', 'Lubię suszone owoce.', 'I like dried fruit.'),
('together5', 'śmieciowe jedzenie', 'Śmieciowe jedzenie jest niezdrowe.', 'Fast food is unhealthy.'),
('together5', 'tłuste jedzenie', 'Tłuste jedzenie jest niezdrowe.', 'Fatty food is unhealthy.'),
('together5', 'napój gazowany', 'Lubię napoje gazowane.', 'I like fizzy drinks.'),
('together5', 'zioło', 'Bazylia to zioło.', 'Basil is a herb.'),
('together5', 'humus', 'Lubię humus z chlebem.', 'I like hummus with bread.'),
('together5', 'cukierek, słodycz', 'Lubię słodkie cukierki.', 'I like sweet candies.'),
('together5', 'tofu', 'Tofu to białko roślinne.', 'Tofu is a plant protein.'),
('together5', 'Brzmi dobrze!', 'Brzmi dobrze!', 'Sounds good!'),
('together5', 'Ostrożnie!', 'Ostrożnie! Nóż jest ostry!', 'Careful! The knife is sharp!'),
('together5', 'Genialny pomysł!', 'Genialny pomysł!', 'Brilliant idea!'),
('together5', 'Czy możesz (przynieść ciasto)?', 'Czy możesz przynieść ciasto?', 'Can you bring a cake?'),
('together5', 'Tak, oczywiście.', 'Tak, oczywiście.', 'Yes, sure.'),
('together5', 'Czy mógłbyś/mogłabyś (kupić dużą kartę urodzinową)?', 'Czy mógłbyś kupić dużą kartę urodzinową?', 'Could you buy a big birthday card?'),
('together5', 'Żaden problem.', 'Żaden problem.', 'No problem.'),
('together5', 'Czy miałbyś/miałabyś coś przeciwko (zrobieniu kanapek na przyjęcie)?', 'Czy miałbyś coś przeciwko zrobieniu kanapek?', 'Would you mind making sandwiches?'),
('together5', 'Przepraszam, ale myślę, że to nie jest dobry pomysł.', 'Przepraszam, ale myślę, że to nie jest dobry pomysł.', 'Sorry, but I do not think that is a good idea.'),
('together5', 'Przepraszam, ale nie mogę.', 'Przepraszam, ale nie mogę.', 'I am sorry, but I cannot.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 3 — Healthy lifestyle, chores, suggestions (37)
-- ═══════════════════════════════════════════════════════════
('together5', 'spać odpowiednio długo', 'Powinieneś spać odpowiednio długo.', 'You should get enough sleep.'),
('together5', 'mieć pasję i regularnie ją rozwijać', 'Ważne jest mieć pasję i regularnie ją rozwijać.', 'It is important to have a passion and do it regularly.'),
('together5', 'mieć dobrze zbilansowaną dietę', 'Trzeba mieć dobrze zbilansowaną dietę.', 'You should have a well-balanced diet.'),
('together5', 'ograniczać swój czas w sieci', 'Powinieneś ograniczać swój czas w sieci.', 'You should limit your time online.'),
('together5', 'wygospodarować czas na odpoczynek', 'Trzeba wygospodarować czas na odpoczynek.', 'You should make time to relax.'),
('together5', 'zarządzać swoim czasem', 'Naucz się zarządzać swoim czasem.', 'Learn to manage your time.'),
('together5', 'spędzać czas na świeżym powietrzu', 'Lubię spędzać czas na świeżym powietrzu.', 'I like to spend time outdoors.'),
('together5', 'spędzać czas z rodziną', 'Lubię spędzać czas z rodziną.', 'I like to spend time with my family.'),
('together5', 'uczyć się pilnie', 'Trzeba uczyć się pilnie.', 'You should study hard.'),
('together5', 'myć', 'Myję ręce przed obiadem.', 'I clean my hands before lunch.'),
('together5', 'sprzątnąć ze stołu', 'Sprzątam ze stołu po obiedzie.', 'I clear the table after lunch.'),
('together5', 'pozmywać naczynia', 'Pomagam pozmywać naczynia.', 'I help do the washing-up.'),
('together5', 'nakarmić zwierzę domowe', 'Karmię mojego psa codziennie.', 'I feed my pet every day.'),
('together5', 'włożyć naczynia do zmywarki', 'Wkładam naczynia do zmywarki.', 'I load the dishwasher.'),
('together5', 'opiekować się bratem', 'Opiekuję się bratem w sobotę.', 'I look after my brother on Saturday.'),
('together5', 'opiekować się siostrą', 'Opiekuję się siostrą.', 'I look after my sister.'),
('together5', 'posłać łóżko', 'Posłałem łóżko rano.', 'I made my bed in the morning.'),
('together5', 'sprzątnąć ubrania', 'Sprzątam ubrania do szafy.', 'I put my clothes away.'),
('together5', 'nakryć do stołu', 'Nakrywam do stołu.', 'I set the table.'),
('together5', 'wyprowadzić psa na spacer', 'Wyprowadzam psa na spacer rano.', 'I take the dog for a walk in the morning.'),
('together5', 'wynieść śmieci', 'Wynoszę śmieci wieczorem.', 'I take the rubbish out in the evening.'),
('together5', 'wyjąć naczynia ze zmywarki', 'Wyjmuję naczynia ze zmywarki.', 'I unload the dishwasher.'),
('together5', 'odkurzyć', 'Odkurzam dywan.', 'I am vacuuming the carpet.'),
('together5', 'umyć samochód', 'Tata umył samochód.', 'Dad washed the car.'),
('together5', 'podlać rośliny', 'Podlewam rośliny w niedzielę.', 'I water the plants on Sunday.'),
('together5', 'Potrzebuję Twojej pomocy.', 'Potrzebuję Twojej pomocy.', 'I need your help.'),
('together5', 'Chodźmy!', 'Chodźmy do parku!', 'Come on, let us go to the park!'),
('together5', 'Zaczekaj! Potrzebuję mojego telefonu.', 'Zaczekaj! Potrzebuję mojego telefonu.', 'Hold on! I need my phone.'),
('together5', 'Co słychać?', 'Co słychać u was?', 'What is up guys?'),
('together5', 'A może spędzisz trochę czasu na świeżym powietrzu?', 'A może spędzisz trochę czasu na świeżym powietrzu?', 'Why do not you spend some time outdoors?'),
('together5', 'Dzięki, ale to nie jest dobry pomysł.', 'Dzięki, ale to nie jest dobry pomysł.', 'Thanks, but that is not a good idea.'),
('together5', 'Co Ty na to, aby pójść do lodziarni?', 'Co Ty na to, aby pójść do lodziarni?', 'How about going to the ice cream shop?'),
('together5', 'Przepraszam, ale wolałbym nie.', 'Przepraszam, ale wolałbym nie.', 'I am sorry, but I would rather not.'),
('together5', 'Dzięki, z przyjemnością!', 'Dzięki, z przyjemnością!', 'Thanks, I would love to!'),
('together5', 'Możemy spotkać się z Rafaelem i Aną.', 'Możemy spotkać się z Rafaelem i Aną.', 'We can meet Rafael and Ana.'),
('together5', 'To brzmi dobrze. Świetny pomysł!', 'To brzmi dobrze. Świetny pomysł!', 'That sounds nice. Great idea!'),
('together5', 'Zagrajmy w piłkę nożną w parku.', 'Zagrajmy w piłkę nożną w parku.', 'Let us play football in the park.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 4 — Body, emotions, should/shouldn't (35)
-- ═══════════════════════════════════════════════════════════
('together5', 'ręka', 'Boli mnie ręka.', 'My arm hurts.'),
('together5', 'plecy', 'Bolą mnie plecy.', 'My back hurts.'),
('together5', 'ciało', 'Moje ciało jest silne.', 'My body is strong.'),
('together5', 'łokieć', 'Skaleczyłem łokieć.', 'I cut my elbow.'),
('together5', 'palec u ręki', 'Skaleczyłem palec.', 'I cut my finger.'),
('together5', 'stopa', 'Boli mnie stopa.', 'My foot hurts.'),
('together5', 'dłoń', 'Myję dłonie.', 'I wash my hands.'),
('together5', 'głowa', 'Boli mnie głowa.', 'My head hurts.'),
('together5', 'kolano', 'Skaleczyłem kolano.', 'I cut my knee.'),
('together5', 'noga', 'Skaleczyłem nogę.', 'I cut my leg.'),
('together5', 'szyja', 'Boli mnie szyja.', 'My neck hurts.'),
('together5', 'ramię', 'Boli mnie ramię.', 'My shoulder hurts.'),
('together5', 'palec u stopy', 'Boli mnie palec u stopy.', 'My toe hurts.'),
('together5', 'zły', 'Mój brat jest zły dzisiaj.', 'My brother is angry today.'),
('together5', 'poirytowany', 'Jestem poirytowany hałasem.', 'I am annoyed by the noise.'),
('together5', 'znudzony', 'Jestem znudzony.', 'I am bored.'),
('together5', 'pewny siebie', 'Anna jest pewna siebie.', 'Anna is confident.'),
('together5', 'podekscytowany', 'Jestem podekscytowany!', 'I am excited!'),
('together5', 'samotny', 'Czuję się samotny.', 'I feel lonely.'),
('together5', 'zdenerwowany', 'Jestem zdenerwowany przed testem.', 'I am nervous before the test.'),
('together5', 'dumny', 'Jestem dumny z brata.', 'I am proud of my brother.'),
('together5', 'przestraszony', 'Jestem przestraszony.', 'I am scared.'),
('together5', 'zestresowany', 'Jestem zestresowany przed egzaminem.', 'I am stressed before the exam.'),
('together5', 'zaskoczony', 'Jestem zaskoczony prezentem.', 'I am surprised by the present.'),
('together5', 'nieszczęśliwy', 'Czuję się nieszczęśliwy.', 'I feel unhappy.'),
('together5', 'poddenerwowany', 'Jestem poddenerwowany.', 'I am upset.'),
('together5', 'Zaczekaj chwilę. Pomogę Ci.', 'Zaczekaj chwilę. Pomogę Ci.', 'Wait a second. I will help you.'),
('together5', 'Skończone! Wszystko gotowe!', 'Skończone! Wszystko gotowe!', 'That is it! All done!'),
('together5', 'Nic się nie dzieje.', 'Nic się nie dzieje.', 'Nothing is happening.'),
('together5', 'Coś jest nie tak.', 'Coś jest nie tak.', 'Something is wrong.'),
('together5', 'Wszystko w porządku. Jestem tylko trochę znudzony.', 'Wszystko w porządku. Jestem tylko trochę znudzony.', 'I am OK. I am just a bit bored.'),
('together5', 'Nie powinieneś wpatrywać się w swój telefon cały dzień.', 'Nie powinieneś wpatrywać się w swój telefon cały dzień.', 'You should not look at your phone all day.'),
('together5', 'A może spędzisz trochę czasu z przyjaciółmi?', 'A może spędzisz trochę czasu z przyjaciółmi?', 'What about spending more time with friends?'),
('together5', 'Powinieneś poprosić panią Adams o pomoc.', 'Powinieneś poprosić panią Adams o pomoc.', 'You should ask Ms Adams for help.'),
('together5', 'Wiem, ale jestem trochę zdenerwowany.', 'Wiem, ale jestem trochę zdenerwowany.', 'I know, but I am a bit nervous.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 5 — Animals, descriptions, opinions (53)
-- ═══════════════════════════════════════════════════════════
('together5', 'alpaka', 'Alpaka jest puszysta.', 'An alpaca is fluffy.'),
('together5', 'kapibara', 'Kapibara to duży gryzoń.', 'A capybara is a big rodent.'),
('together5', 'delfin', 'Delfin jest mądry.', 'A dolphin is clever.'),
('together5', 'osioł', 'Osioł ma długie uszy.', 'A donkey has long ears.'),
('together5', 'świnka morska', 'Mam świnkę morską.', 'I have a guinea pig.'),
('together5', 'lew', 'Lew jest królem dżungli.', 'A lion is the king of the jungle.'),
('together5', 'jaszczurka', 'Jaszczurka mieszka na pustyni.', 'A lizard lives in the desert.'),
('together5', 'surykatka', 'Surykatka żyje w grupie.', 'A meerkat lives in a group.'),
('together5', 'sowa', 'Sowa lata w nocy.', 'An owl flies at night.'),
('together5', 'owca', 'Owca daje wełnę.', 'A sheep gives wool.'),
('together5', 'pająk', 'Pająk ma osiem nóg.', 'A spider has eight legs.'),
('together5', 'tygrys', 'Tygrys jest pomarańczowy.', 'A tiger is orange.'),
('together5', 'żółw', 'Mój żółw jest powolny.', 'My tortoise is slow.'),
('together5', 'piękny', 'Ona jest piękną dziewczyną.', 'She is a beautiful girl.'),
('together5', 'uroczy', 'Twój kotek jest uroczy.', 'Your kitten is cute.'),
('together5', 'niebezpieczny', 'Krokodyl jest niebezpieczny.', 'A crocodile is dangerous.'),
('together5', 'zagrożony', 'Tygrysy są zagrożone.', 'Tigers are endangered.'),
('together5', 'wiejski, rolny', 'To zwierzę wiejskie.', 'It is a farm animal.'),
('together5', 'inteligentny', 'Delfiny są inteligentne.', 'Dolphins are intelligent.'),
('together5', 'jadowity', 'Niektóre pająki są jadowite.', 'Some spiders are poisonous.'),
('together5', 'przerażający', 'Ten film jest przerażający.', 'This film is scary.'),
('together5', 'powolny', 'Żółw jest powolny.', 'A tortoise is slow.'),
('together5', 'brzydki', 'Ten owad jest brzydki.', 'This insect is ugly.'),
('together5', 'dziki', 'Dziki tygrys jest niebezpieczny.', 'A wild tiger is dangerous.'),
('together5', 'dziób', 'Ptak ma dziób.', 'A bird has a beak.'),
('together5', 'pazur', 'Lew ma ostre pazury.', 'A lion has sharp claws.'),
('together5', 'pióro', 'To pióro jest kolorowe.', 'This feather is colourful.'),
('together5', 'płetwa', 'Ryba ma płetwy.', 'A fish has fins.'),
('together5', 'futro', 'Kot ma miękkie futro.', 'The cat has soft fur.'),
('together5', 'łapa', 'Pies ma cztery łapy.', 'A dog has four paws.'),
('together5', 'łuska', 'Wąż ma łuski.', 'A snake has scales.'),
('together5', 'skorupa', 'Żółw ma skorupę.', 'A tortoise has a shell.'),
('together5', 'ogon', 'Małpa ma długi ogon.', 'A monkey has a long tail.'),
('together5', 'język', 'Pies ma różowy język.', 'A dog has a pink tongue.'),
('together5', 'wąs, wibrys', 'Kot ma długie wąsy.', 'A cat has long whiskers.'),
('together5', 'skrzydło', 'Ptak ma duże skrzydło.', 'A bird has a big wing.'),
('together5', 'Jesteśmy na miejscu.', 'Jesteśmy na miejscu.', 'Here we are.'),
('together5', 'Czy wiedziałeś, że…?', 'Czy wiedziałeś, że delfiny są mądre?', 'Did you know that dolphins are clever?'),
('together5', 'Ojej!', 'Ojej! To był huk!', 'Oh my gosh! That was loud!'),
('together5', 'A nie mówiłem?', 'A nie mówiłem?', 'I told you!'),
('together5', 'Myślę, że świnki morskie są urocze.', 'Myślę, że świnki morskie są urocze.', 'I think guinea pigs are cute.'),
('together5', 'Zgadzam się.', 'Zgadzam się.', 'I agree.'),
('together5', 'Nie jestem pewien, że to dobry pomysł.', 'Nie jestem pewien, że to dobry pomysł.', 'I am not sure it is a good idea.'),
('together5', 'Co myślisz o książce o krokodylach?', 'Co myślisz o książce o krokodylach?', 'What do you think about the book about crocodiles?'),
('together5', 'Czy to Ci pasuje?', 'Czy to Ci pasuje?', 'Are you OK with it?'),
('together5', 'Nie sądzę.', 'Nie sądzę.', 'I do not think so.'),
('together5', 'Masz rację!', 'Masz rację!', 'You are right!'),
('together5', 'Czy to jest w porządku?', 'Czy to jest w porządku?', 'Is that OK?'),
('together5', 'Tak, to jest w porządku.', 'Tak, to jest w porządku.', 'Yes, that is fine.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 6 — Months, ordinals, jobs, wishes (59)
-- ═══════════════════════════════════════════════════════════
('together5', 'styczeń', 'W styczniu jest zimno.', 'It is cold in January.'),
('together5', 'luty', 'W lutym pada śnieg.', 'It snows in February.'),
('together5', 'marzec', 'W marcu zaczyna się wiosna.', 'Spring starts in March.'),
('together5', 'kwiecień', 'W kwietniu często pada deszcz.', 'It often rains in April.'),
('together5', 'maj', 'Moje urodziny są w maju.', 'My birthday is in May.'),
('together5', 'czerwiec', 'W czerwcu kończy się szkoła.', 'School ends in June.'),
('together5', 'lipiec', 'W lipcu jadę nad morze.', 'I go to the sea in July.'),
('together5', 'sierpień', 'W sierpniu jest gorąco.', 'It is hot in August.'),
('together5', 'wrzesień', 'We wrześniu zaczyna się szkoła.', 'School starts in September.'),
('together5', 'październik', 'W październiku liście spadają.', 'Leaves fall in October.'),
('together5', 'listopad', 'W listopadzie jest chłodno.', 'It is cool in November.'),
('together5', 'grudzień', 'W grudniu są święta.', 'Christmas is in December.'),
('together5', 'pierwszy', 'On był pierwszy w wyścigu.', 'He was first in the race.'),
('together5', 'drugi', 'Mam drugie miejsce.', 'I am in second place.'),
('together5', 'trzeci', 'Mieszkam na trzecim piętrze.', 'I live on the third floor.'),
('together5', 'czwarty', 'Mam czwarty rower.', 'I have my fourth bike.'),
('together5', 'piąty', 'To moja piąta lekcja.', 'It is my fifth lesson.'),
('together5', 'szósty', 'Szósty zmysł to intuicja.', 'The sixth sense is intuition.'),
('together5', 'siódmy', 'To siódmy dzień tygodnia.', 'It is the seventh day of the week.'),
('together5', 'ósmy', 'Mam ósmego brata.', 'I have eighth brother.'),
('together5', 'dziewiąty', 'Dziewiąty miesiąc to wrzesień.', 'The ninth month is September.'),
('together5', 'dziesiąty', 'Dziesiąty zawodnik wygrał.', 'The tenth player won.'),
('together5', 'jedenasty', 'Mój brat ma jedenaste urodziny.', 'My brother has his eleventh birthday.'),
('together5', 'dwunasty', 'Grudzień to dwunasty miesiąc.', 'December is the twelfth month.'),
('together5', 'dwudziesty', 'Dwudziesty wiek był ważny.', 'The twentieth century was important.'),
('together5', 'dwudziesty pierwszy', 'Dwudziesty pierwszy wiek to dziś.', 'The twenty-first century is today.'),
('together5', 'dwudziesty drugi', 'Dwudziesty drugi grudnia to mój dzień.', 'The twenty-second of December is my day.'),
('together5', 'rok tysiąc siedemsetny', 'Mozart urodził się w roku tysiąc siedemsetnym.', 'Mozart was born in seventeen hundred.'),
('together5', 'rok tysiąc osiemset sześćdziesiąty piąty', 'To był rok tysiąc osiemset sześćdziesiąty piąty.', 'It was eighteen sixty-five.'),
('together5', 'rok tysiąc dziewięćset piąty', 'W roku tysiąc dziewięćset piątym...', 'In nineteen oh five...'),
('together5', 'rok dwa tysiące piąty', 'W roku dwa tysiące piątym byłem mały.', 'In two thousand and five I was little.'),
('together5', 'astronauta', 'Astronauta lata w kosmos.', 'An astronaut flies into space.'),
('together5', 'astronom', 'Astronom obserwuje gwiazdy.', 'An astronomer observes the stars.'),
('together5', 'kompozytor', 'Mozart był kompozytorem.', 'Mozart was a composer.'),
('together5', 'lekarz', 'Lekarz pracuje w szpitalu.', 'A doctor works at the hospital.'),
('together5', 'odkrywca', 'Kolumb był odkrywcą.', 'Columbus was an explorer.'),
('together5', 'wynalazca', 'Edison był wynalazcą.', 'Edison was an inventor.'),
('together5', 'pielęgniarka', 'Pielęgniarka pomaga pacjentom.', 'A nurse helps patients.'),
('together5', 'malarz', 'Picasso był malarzem.', 'Picasso was a painter.'),
('together5', 'pilot', 'Pilot lata samolotem.', 'A pilot flies a plane.'),
('together5', 'poeta', 'Mickiewicz był poetą.', 'Mickiewicz was a poet.'),
('together5', 'naukowiec', 'Naukowiec robi eksperymenty.', 'A scientist does experiments.'),
('together5', 'pisarz', 'Pisarz pisze książki.', 'A writer writes books.'),
('together5', 'Twoja kolej.', 'Twoja kolej.', 'It is your turn.'),
('together5', 'Nie poddawaj się!', 'Nie poddawaj się!', 'Do not give up!'),
('together5', 'Daj z siebie wszystko!', 'Daj z siebie wszystko!', 'Give it your best shot!'),
('together5', 'Mistrzowie!', 'Mistrzowie!', 'The champions!'),
('together5', 'Wszystkiego najlepszego z okazji urodzin!', 'Wszystkiego najlepszego z okazji urodzin!', 'Happy birthday!'),
('together5', 'Dzięki za pamięć.', 'Dzięki za pamięć.', 'Thanks for remembering.'),
('together5', 'Wspaniałe wieści, dobra robota!', 'Wspaniałe wieści, dobra robota!', 'That is great news, well done!'),
('together5', 'Dzięki. To miło z twojej strony.', 'Dzięki. To miło z twojej strony.', 'Thanks. That is nice of you.'),
('together5', 'Gratulacje, tak trzymać!', 'Gratulacje, tak trzymać!', 'Congratulations, way to go!'),
('together5', 'Powodzenia w sobotę!', 'Powodzenia w sobotę!', 'Good luck on Saturday!'),
('together5', 'Jesteś dobrym przyjacielem.', 'Jesteś dobrym przyjacielem.', 'You are a good friend.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 7 — Events, transport, past simple (47)
-- ═══════════════════════════════════════════════════════════
('together5', 'targi książki', 'Idę na targi książki w sobotę.', 'I am going to the book fair on Saturday.'),
('together5', 'wymiana ubrań', 'Organizujemy wymianę ubrań.', 'We are organising a clothes swap.'),
('together5', 'warsztaty ekologiczne', 'Lubię warsztaty ekologiczne.', 'I like conservation workshops.'),
('together5', 'turniej e-sportowy', 'Idę na turniej e-sportowy.', 'I am going to the esports tournament.'),
('together5', 'wciągające doświadczenie VR', 'Próbowałem wciągającego doświadczenia VR.', 'I tried an immersive VR experience.'),
('together5', 'warsztaty teatralne', 'Lubię warsztaty teatralne.', 'I like theatre workshops.'),
('together5', 'poszukiwanie skarbu', 'Bawiliśmy się w poszukiwanie skarbu.', 'We played a treasure hunt.'),
('together5', 'lekcja jogi', 'Mam lekcję jogi w środę.', 'I have a yoga class on Wednesday.'),
('together5', 'przyjechać', 'Przyjechałem o ósmej.', 'I arrived at eight.'),
('together5', 'odkryć', 'Odkryłem nową grę.', 'I discovered a new game.'),
('together5', 'podążać', 'Podążajcie za mną.', 'Follow me.'),
('together5', 'sadzić', 'Sadzimy drzewa wiosną.', 'We are planting trees in spring.'),
('together5', 'transmitować na żywo', 'Mecz jest transmitowany na żywo.', 'The match is being streamed live.'),
('together5', 'wymienić', 'Wymieńmy się kartami.', 'Let us swap cards.'),
('together5', 'autobus', 'Czekam na autobus.', 'I am waiting for the bus.'),
('together5', 'samochód', 'Tata ma czerwony samochód.', 'Dad has a red car.'),
('together5', 'autokar', 'Jedziemy autokarem na wycieczkę.', 'We are going on a trip by coach.'),
('together5', 'prom', 'Przepłynęliśmy promem.', 'We sailed by ferry.'),
('together5', 'helikopter', 'Helikopter leci nad miastem.', 'A helicopter is flying over the city.'),
('together5', 'motocykl', 'Tata ma motocykl.', 'Dad has a motorbike.'),
('together5', 'pieszo', 'Idę pieszo do szkoły.', 'I go to school on foot.'),
('together5', 'samolot', 'Lecimy samolotem do Hiszpanii.', 'We are flying to Spain by plane.'),
('together5', 'taksówka', 'Jedziemy taksówką.', 'We are going by taxi.'),
('together5', 'pociąg', 'Pociąg odjeżdża o piątej.', 'The train leaves at five.'),
('together5', 'tramwaj', 'Jedziemy tramwajem.', 'We are going by tram.'),
('together5', 'metro', 'W Warszawie jest metro.', 'There is an underground in Warsaw.'),
('together5', 'To najfajniejsza koszulka, jaką widziałem!', 'To najfajniejsza koszulka, jaką widziałem!', 'That is the coolest T-shirt ever!'),
('together5', 'To było super!', 'To było super!', 'It was so cool!'),
('together5', 'Brzmi fajnie!', 'Brzmi fajnie!', 'That sounds like fun!'),
('together5', 'Cześć! Jak się masz?', 'Cześć! Jak się masz?', 'Morning! How are you?'),
('together5', 'Jestem zmęczony!', 'Jestem zmęczony!', 'I am tired!'),
('together5', 'Co robiłeś w weekend?', 'Co robiłeś w weekend?', 'What did you do at the weekend?'),
('together5', 'Poszedłem na turniej e-sportowy wczoraj.', 'Poszedłem na turniej e-sportowy wczoraj.', 'I went to an esports tournament yesterday.'),
('together5', 'Jak było?', 'Jak było?', 'What was it like?'),
('together5', 'Było wspaniale!', 'Było wspaniale!', 'It was amazing!'),
('together5', 'Gdzie się odbywał?', 'Gdzie się odbywał?', 'Where was it?'),
('together5', 'Odbywał się w hali głównej w centrum miasta.', 'Odbywał się w hali głównej w centrum miasta.', 'It was in Main Hall in the town centre.'),
('together5', 'W jaki sposób tam dotarłeś?', 'W jaki sposób tam dotarłeś?', 'How did you get there?'),
('together5', 'Autobusem.', 'Autobusem.', 'By bus.'),
('together5', 'O której godzinie się zaczęło?', 'O której godzinie się zaczęło?', 'What time did it start?'),
('together5', 'Zaczęło się o drugiej po południu w sobotę.', 'Zaczęło się o drugiej po południu w sobotę.', 'It started at two o''clock on Saturday afternoon.'),
('together5', 'Jak Tobie upłynął weekend?', 'Jak Tobie upłynął weekend?', 'How was your weekend?'),
('together5', 'Robiłeś coś fajnego?', 'Robiłeś coś fajnego?', 'Did you do anything fun?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 8 — Weather, seasons, geography, invitations (40)
-- ═══════════════════════════════════════════════════════════
('together5', 'pochmurny', 'Dzień jest pochmurny.', 'It is a cloudy day.'),
('together5', 'suchy', 'Klimat jest suchy w pustyni.', 'The climate is dry in the desert.'),
('together5', 'mglisty', 'Rano było mglisto.', 'It was foggy in the morning.'),
('together5', 'mroźny', 'W styczniu jest mroźno.', 'It is freezing in January.'),
('together5', 'śnieżny', 'Zimą jest śnieżnie.', 'It is snowy in winter.'),
('together5', 'burzowy', 'Jest burzowo, zostań w domu.', 'It is stormy, stay at home.'),
('together5', 'ciepły', 'Wiosną jest ciepło.', 'It is warm in spring.'),
('together5', 'mokry', 'Mój sweter jest mokry.', 'My jumper is wet.'),
('together5', 'wietrzny', 'Jest wietrzno, weź czapkę.', 'It is windy, take a cap.'),
('together5', 'wiosna', 'Wiosną kwitną kwiaty.', 'Flowers bloom in spring.'),
('together5', 'lato', 'Latem chodzę na plażę.', 'I go to the beach in summer.'),
('together5', 'jesień', 'Jesienią liście spadają.', 'Leaves fall in autumn.'),
('together5', 'zima', 'Zimą lepimy bałwana.', 'We make a snowman in winter.'),
('together5', 'plaża', 'Latem chodzę na plażę.', 'I go to the beach in summer.'),
('together5', 'klif', 'Klif jest wysoki.', 'The cliff is tall.'),
('together5', 'wieś', 'Babcia mieszka na wsi.', 'Grandma lives in the countryside.'),
('together5', 'pustynia', 'Wielbłądy żyją na pustyni.', 'Camels live in the desert.'),
('together5', 'wyspa', 'Mieszkam na wyspie.', 'I live on an island.'),
('together5', 'dżungla', 'Tygrysy żyją w dżungli.', 'Tigers live in the jungle.'),
('together5', 'jezioro', 'Pływamy w jeziorze.', 'We swim in the lake.'),
('together5', 'góra', 'W górach jest pięknie.', 'It is beautiful in the mountains.'),
('together5', 'ocean', 'Wieloryby żyją w oceanie.', 'Whales live in the ocean.'),
('together5', 'rzeka', 'Krokodyle żyją w rzece.', 'Crocodiles live in the river.'),
('together5', 'wulkan', 'Wulkan wybuchnął wczoraj.', 'The volcano erupted yesterday.'),
('together5', 'wodospad', 'Wodospad jest piękny.', 'The waterfall is beautiful.'),
('together5', 'Zobaczmy.', 'Zobaczmy, co tam jest.', 'Let me see what is there.'),
('together5', 'Żartujesz?', 'Żartujesz? Naprawdę?', 'Are you kidding? Really?'),
('together5', 'Poczekaj.', 'Poczekaj chwilkę.', 'Hang on a moment.'),
('together5', 'Nie wierzę!', 'Nie wierzę!', 'I cannot believe it!'),
('together5', 'Czy możesz przyjść na piknik z okazji końca semestru?', 'Czy możesz przyjść na piknik z okazji końca semestru?', 'Can you come to the end-of-term class picnic?'),
('together5', 'Obawiam się, że nie mogę.', 'Obawiam się, że nie mogę.', 'I am afraid, I cannot.'),
('together5', 'Świetnie! W takim razie mogę przyjść.', 'Świetnie! W takim razie mogę przyjść.', 'Great, then I can come.'),
('together5', 'Czy chciałbyś przyjść na nasz piknik klasowy?', 'Czy chciałbyś przyjść na nasz piknik klasowy?', 'Would you like to come to our class picnic?'),
('together5', 'Przepraszam, ale jestem wtedy zajęty.', 'Przepraszam, ale jestem wtedy zajęty.', 'I am really sorry, but I am busy then.'),
('together5', 'Czy jesteś wolny po południu?', 'Czy jesteś wolny po południu?', 'Are you free in the afternoon?'),
('together5', 'Tak, jestem. Z chęcią przyjdę. Dziękuję za zaproszenie.', 'Tak, jestem. Z chęcią przyjdę.', 'Yes, I am. I would love to go.')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Together 5: 327 unikalnych zdan zaktualizowanych/dodanych w word_sentences (327 wpisow w data.js, brak duplikatow).';
END $$;
