-- ═══════════════════════════════════════════════════════════
-- Fix sentences: IMPULS 3 (klasa 2, szkola srednia)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 249 unikalnych slowek z Impuls 3 (szkola srednia, klasa 2).
--
-- Tematy unitow:
--   Unit 1 (118): osobowosc + relacje + przyjazn + wyglad zewnetrzny
--   Unit 2 (131): muzyka + emocje + koncerty + nauka + zdrowie
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — Osobowosc, relacje, wyglad (118)
-- ═══════════════════════════════════════════════════════════
('impuls3', 'znajomy', 'On jest tylko moim znajomym.', 'He is just an acquaintance.'),
('impuls3', 'najlepszy przyjaciel', 'Tom jest moim najlepszym przyjacielem.', 'Tom is my best friend.'),
('impuls3', 'kolega z klasy', 'Anna jest moją koleżanką z klasy.', 'Anna is my classmate.'),
('impuls3', 'bliski przyjaciel', 'Mam bliskiego przyjaciela.', 'I have a close friend.'),
('impuls3', 'współpracownik', 'Mój współpracownik jest miły.', 'My colleague is nice.'),
('impuls3', 'szczery', 'Bądź ze mną szczery.', 'Be honest with me.'),
('impuls3', 'nieszczery', 'On jest nieszczery.', 'He is dishonest.'),
('impuls3', 'lojalny', 'Mój pies jest lojalny.', 'My dog is loyal.'),
('impuls3', 'nielojalny', 'Nielojalny przyjaciel to nie przyjaciel.', 'A disloyal friend is not a friend.'),
('impuls3', 'wróg', 'Nie chcę mieć wrogów.', 'I do not want to have enemies.'),
('impuls3', 'współlokator', 'Mój współlokator jest cichy.', 'My flatmate is quiet.'),
('impuls3', 'dojrzały', 'Mój brat jest dojrzały.', 'My brother is mature.'),
('impuls3', 'niedojrzały', 'On czasami zachowuje się niedojrzale.', 'He sometimes acts immature.'),
('impuls3', 'cierpliwy', 'Trzeba być cierpliwym z dziećmi.', 'You have to be patient with children.'),
('impuls3', 'niecierpliwy', 'Jestem niecierpliwy w kolejce.', 'I am impatient in the queue.'),
('impuls3', 'uprzejmy', 'Bądź uprzejmy dla starszych.', 'Be polite to elders.'),
('impuls3', 'nieuprzejmy', 'Nie bądź nieuprzejmy.', 'Do not be impolite.'),
('impuls3', 'wrażliwy', 'Ona jest wrażliwą osobą.', 'She is a sensitive person.'),
('impuls3', 'niewrażliwy', 'On jest niewrażliwy na uczucia innych.', 'He is insensitive to others'' feelings.'),
('impuls3', 'tolerancyjny', 'Bądź tolerancyjny dla innych.', 'Be tolerant of others.'),
('impuls3', 'nietolerancyjny', 'Nie bądź nietolerancyjny.', 'Do not be intolerant.'),
('impuls3', 'odpowiedzialny', 'Jestem odpowiedzialny za psa.', 'I am responsible for the dog.'),
('impuls3', 'nieodpowiedzialny', 'To nieodpowiedzialne zachowanie.', 'It is irresponsible behaviour.'),
('impuls3', 'sąsiad przez ścianę', 'Mój sąsiad przez ścianę jest miły.', 'My next-door neighbour is nice.'),
('impuls3', 'przeciwnik', 'Mój przeciwnik jest silny.', 'My opponent is strong.'),
('impuls3', 'krewny', 'Mam dalekiego krewnego w Anglii.', 'I have a distant relative in England.'),
('impuls3', 'rywal', 'Wygrałem z moim rywalem.', 'I won against my rival.'),
('impuls3', 'rodzeństwo', 'Mam dwoje rodzeństwa.', 'I have two siblings.'),
('impuls3', 'nieznajomy', 'Nigdy nie rozmawiaj z nieznajomymi.', 'Never talk to strangers.'),
('impuls3', 'kolega z drużyny', 'Mój kolega z drużyny strzelił bramkę.', 'My teammate scored a goal.'),
('impuls3', 'kompan', 'Mam fajnego kompana podróży.', 'I have a great travel buddy.'),
('impuls3', 'przyjazny', 'Nasi sąsiedzi są przyjaźni.', 'Our neighbours are friendly.'),
('impuls3', 'nieprzyjazny', 'On jest nieprzyjazny dla obcych.', 'He is unfriendly to strangers.'),
('impuls3', 'pomysłowy', 'Mój brat jest pomysłowy.', 'My brother is imaginative.'),
('impuls3', 'mało pomysłowy', 'To mało pomysłowe rozwiązanie.', 'It is an unimaginative solution.'),
('impuls3', 'życzliwy', 'Mama jest życzliwą osobą.', 'Mum is a kind person.'),
('impuls3', 'nieżyczliwy', 'Nie bądź nieżyczliwy.', 'Do not be unkind.'),
('impuls3', 'rzetelny', 'On jest rzetelnym pracownikiem.', 'He is a reliable worker.'),
('impuls3', 'nierzetelny', 'Ten samochód jest nierzetelny.', 'This car is unreliable.'),
('impuls3', 'towarzyski', 'Anna jest bardzo towarzyska.', 'Anna is very sociable.'),
('impuls3', 'nietowarzyski', 'Mój brat jest nietowarzyski.', 'My brother is unsociable.'),
('impuls3', 'broda', 'Mój dziadek ma siwą brodę.', 'My grandfather has a grey beard.'),
('impuls3', 'blond włosy', 'Anna ma blond włosy.', 'Anna has blond hair.'),
('impuls3', 'ciemne włosy', 'Tata ma ciemne włosy.', 'Dad has dark hair.'),
('impuls3', 'więź', 'Mam silną więź z bratem.', 'I have a strong bond with my brother.'),
('impuls3', 'przypadkowy', 'To było przypadkowe spotkanie.', 'It was a casual meeting.'),
('impuls3', 'podbródek', 'Mam delikatny podbródek.', 'I have a delicate chin.'),
('impuls3', 'sobowtór', 'Spotkałem swojego sobowtóra.', 'I met my doppelganger.'),
('impuls3', 'dubler', 'On jest dublerem aktora.', 'He is the actor''s double.'),
('impuls3', 'rysy twarzy', 'Ona ma piękne rysy twarzy.', 'She has beautiful facial features.'),
('impuls3', 'jasna karnacja', 'Mam jasną karnację.', 'I have fair skin.'),
('impuls3', 'pełne usta', 'Anna ma pełne usta.', 'Anna has full lips.'),
('impuls3', 'wąskie usta', 'On ma wąskie usta.', 'He has thin lips.'),
('impuls3', 'rudy', 'Mój kuzyn jest rudy.', 'My cousin is ginger.'),
('impuls3', 'fryzura', 'Lubię twoją nową fryzurę.', 'I like your new hairstyle.'),
('impuls3', 'mocny makijaż', 'Anna ma mocny makijaż.', 'Anna has heavy make-up.'),
('impuls3', 'pasujące stroje', 'Mamy pasujące stroje.', 'We have matching outfits.'),
('impuls3', 'owalny', 'Stół jest owalny.', 'The table is oval-shaped.'),
('impuls3', 'blady', 'Jestem blady po chorobie.', 'I am pale after the illness.'),
('impuls3', 'wygląd zewnętrzny', 'Wygląd zewnętrzny nie jest wszystkim.', 'Physical appearance is not everything.'),
('impuls3', 'kucyk', 'Anna ma kucyk.', 'Anna has a ponytail.'),
('impuls3', 'związać włosy', 'Związałam włosy.', 'I put my hair up.'),
('impuls3', 'podobny', 'Jesteśmy podobni do mamy.', 'We are similar to mum.'),
('impuls3', 'grube brwi', 'Mam grube brwi.', 'I have thick eyebrows.'),
('impuls3', 'nosić rozpuszczone włosy', 'Lubię nosić rozpuszczone włosy.', 'I like to wear my hair loose.'),
('impuls3', 'szeroki uśmiech', 'Anna ma szeroki uśmiech.', 'Anna has a wide smile.'),
('impuls3', 'denerwować', 'Hałas mnie denerwuje.', 'The noise annoys me.'),
('impuls3', 'przepraszać', 'Przepraszam za spóźnienie.', 'I apologise for being late.'),
('impuls3', 'zdenerwować się na kogoś', 'Zdenerwowałam się na brata.', 'I was annoyed with my brother.'),
('impuls3', 'być w dobrych relacjach z kimś', 'Jesteśmy w dobrych relacjach.', 'We are on good terms.'),
('impuls3', 'zachowanie', 'Twoje zachowanie jest dziwne.', 'Your behaviour is strange.'),
('impuls3', 'najlepszy przyjaciel na zawsze', 'Anna jest moim najlepszym przyjacielem na zawsze.', 'Anna is my best friend forever.'),
('impuls3', 'dziecinny', 'Nie bądź dziecinny.', 'Do not be childish.'),
('impuls3', 'kompromis', 'Musimy zawrzeć kompromis.', 'We have to find a compromise.'),
('impuls3', 'przekonać', 'Przekonałam brata.', 'I convinced my brother.'),
('impuls3', 'nie zgadzać się', 'Nie zgadzam się z tobą.', 'I disagree with you.'),
('impuls3', 'wybaczyć', 'Wybaczyłam mu.', 'I forgave him.'),
('impuls3', 'pokłócić się', 'Pokłóciliśmy się o drobiazg.', 'We got into a fight over a trifle.'),
('impuls3', 'spiąć się', 'Spinam się przed egzaminem.', 'I get nervous before the exam.'),
('impuls3', 'denerwować kogoś', 'Mój brat działa mi na nerwy.', 'My brother gets on my nerves.'),
('impuls3', 'ustąpić', 'W końcu ustąpiłem.', 'In the end I gave in.'),
('impuls3', 'radzić sobie', 'Radzę sobie ze stresem.', 'I handle stress.'),
('impuls3', 'nie zgadzać się z czymś', 'Nie zgadzam się z tą decyzją.', 'I have a disagreement about this decision.'),
('impuls3', 'mieć dość', 'Mam dość tego hałasu.', 'I have had enough of this noise.'),
('impuls3', 'zranić', 'Nie chcę cię zranić.', 'I do not want to hurt you.'),
('impuls3', 'przykry', 'To było przykre doświadczenie.', 'It was a hurtful experience.'),
('impuls3', 'poirytowany', 'Jestem poirytowany hałasem.', 'I am irritated by the noise.'),
('impuls3', 'zaprzyjaźnić się', 'Zaprzyjaźniłam się z Anną.', 'I made friends with Anna.'),
('impuls3', 'pogodzić się z kimś', 'Pogodziłem się z bratem.', 'I made up with my brother.'),
('impuls3', 'relacja', 'Mamy dobrą relację.', 'We have a good relationship.'),
('impuls3', 'ufać', 'Ufam mojej najlepszej przyjaciółce.', 'I trust my best friend.'),
('impuls3', 'unikać', 'Unikam stresu.', 'I avoid stress.'),
('impuls3', 'najlepsza przyjaciółka', 'Ona jest moją najlepszą przyjaciółką.', 'She is my bestie.'),
('impuls3', 'brutalnie szczery', 'On jest brutalnie szczery.', 'He is brutally honest.'),
('impuls3', 'rozweselić kogoś', 'Próbuję rozweselić brata.', 'I am trying to cheer my brother up.'),
('impuls3', 'strefa komfortu', 'Wyjdź ze strefy komfortu.', 'Get out of your comfort zone.'),
('impuls3', 'pomysłowy (sprytny)', 'On jest pomysłowy.', 'He is crafty.'),
('impuls3', 'zachęcać', 'Zachęcam cię do nauki.', 'I encourage you to study.'),
('impuls3', 'nieprawdziwy', 'To była nieprawdziwa historia.', 'It was a fake story.'),
('impuls3', 'pokłócić się z kimś', 'Pokłóciłam się z koleżanką.', 'I fell out with my friend.'),
('impuls3', 'przyjaźń', 'Cenię naszą przyjaźń.', 'I value our friendship.'),
('impuls3', 'dogadywać się z kimś', 'Dobrze dogaduję się z bratem.', 'I get on well with my brother.'),
('impuls3', 'spędzać z kimś czas', 'Lubię spędzać z nim czas.', 'I like to hang out with him.'),
('impuls3', 'oceniać', 'Nie oceniaj książki po okładce.', 'Do not judge a book by its cover.'),
('impuls3', 'być w kontakcie', 'Jesteśmy w kontakcie.', 'We keep in touch.'),
('impuls3', 'warstwa', 'Załóż dodatkową warstwę.', 'Put on an extra layer.'),
('impuls3', 'zawieść kogoś', 'Nie chcę cię zawieść.', 'I do not want to let you down.'),
('impuls3', 'kłamać', 'Nie kłam.', 'Do not lie.'),
('impuls3', 'rozśmieszyć kogoś', 'On potrafi mnie rozśmieszyć.', 'He can make me laugh.'),
('impuls3', 'po prostu', 'Po prostu chcę spać.', 'I plain want to sleep.'),
('impuls3', 'wspólne zainteresowania', 'Mamy wspólne zainteresowania.', 'We have shared interests.'),
('impuls3', 'wspierać', 'Rodzina mnie wspiera.', 'My family supports me.'),
('impuls3', 'mówić prawdę', 'Zawsze mówię prawdę.', 'I always tell the truth.'),
('impuls3', 'dusza towarzystwa', 'Anna jest duszą towarzystwa.', 'Anna is the life and soul of the party.'),
('impuls3', 'ze znajomościami', 'Jest osobą ze znajomościami.', 'He is well-connected.'),
('impuls3', 'para', 'Są piękną parą.', 'They are a beautiful couple.'),
('impuls3', 'w świecie realnym', 'Spotykam ich w świecie realnym.', 'I meet them in real life.'),
('impuls3', 'wzór', 'Lubię ten wzór tkaniny.', 'I like this fabric pattern.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — Music, emotions, learning, health (131)
-- ═══════════════════════════════════════════════════════════
('impuls3', 'wzmacniacz', 'Gitara jest podłączona do wzmacniacza.', 'The guitar is connected to the amplifier.'),
('impuls3', 'widownia', 'Widownia była zachwycona.', 'The audience was delighted.'),
('impuls3', 'przesłuchanie', 'Mam przesłuchanie do zespołu.', 'I have an audition for the band.'),
('impuls3', 'rytm', 'Czuję rytm tej piosenki.', 'I feel the beat of this song.'),
('impuls3', 'buczeć', 'Tłum zaczął buczeć.', 'The crowd started to boo.'),
('impuls3', 'wiolonczela', 'Anna gra na wiolonczeli.', 'Anna plays the cello.'),
('impuls3', 'wiwatować', 'Kibice wiwatowali.', 'The fans cheered.'),
('impuls3', 'muzyka klasyczna', 'Lubię muzykę klasyczną.', 'I like classical music.'),
('impuls3', 'komponować', 'Beethoven komponował symfonie.', 'Beethoven composed symphonies.'),
('impuls3', 'kompozytor', 'Mozart był kompozytorem.', 'Mozart was a composer.'),
('impuls3', 'dyrygent', 'Dyrygent prowadzi orkiestrę.', 'The conductor leads the orchestra.'),
('impuls3', 'DJ', 'DJ gra na imprezie.', 'The DJ is playing at the party.'),
('impuls3', 'ściągać z Internetu', 'Ściągam muzykę z Internetu.', 'I download music from the Internet.'),
('impuls3', 'flet', 'Anna gra na flecie.', 'Anna plays the flute.'),
('impuls3', 'słuchawki', 'Mam nowe słuchawki.', 'I have new headphones.'),
('impuls3', 'popularny album', 'To popularny album zespołu.', 'It is the band''s hit album.'),
('impuls3', 'zainspirować', 'Ten film mnie zainspirował.', 'This film inspired me.'),
('impuls3', 'mikrofon', 'Mówię do mikrofonu.', 'I am speaking into the mike.'),
('impuls3', 'redukujący hałas', 'Mam słuchawki redukujące hałas.', 'I have noise-cancelling headphones.'),
('impuls3', 'perkusja', 'Mój brat gra na perkusji.', 'My brother plays the percussion.'),
('impuls3', 'playlista', 'Mam playlistę ulubionych piosenek.', 'I have a playlist of favourite songs.'),
('impuls3', 'czytać nuty', 'Uczę się czytać nuty.', 'I am learning to read music.'),
('impuls3', 'próba', 'Mamy próbę zespołu w sobotę.', 'We have rehearsal on Saturday.'),
('impuls3', 'repertuar', 'Zespół ma duży repertuar.', 'The band has a large repertoire.'),
('impuls3', 'rytm (rhythm)', 'Ta piosenka ma dobry rytm.', 'This song has a good rhythm.'),
('impuls3', 'rytmiczny', 'Ta muzyka jest bardzo rytmiczna.', 'This music is very rhythmical.'),
('impuls3', 'śpiewać karaoke', 'Lubię śpiewać karaoke.', 'I like to sing karaoke.'),
('impuls3', 'autor piosenek', 'On jest autorem piosenek.', 'He is a songwriter.'),
('impuls3', 'inżynier dźwięku', 'Inżynier dźwięku pracuje w studiu.', 'The sound engineer works in the studio.'),
('impuls3', 'nagłośnienie', 'Sala ma świetne nagłośnienie.', 'The hall has a great sound system.'),
('impuls3', 'ścieżka dźwiękowa', 'Lubię ścieżkę dźwiękową tego filmu.', 'I like the soundtrack of this film.'),
('impuls3', 'głośnik', 'Włącz głośnik.', 'Turn on the speaker.'),
('impuls3', 'streamować', 'Streamuję mecz na żywo.', 'I am streaming the match live.'),
('impuls3', 'utalentowany', 'Anna jest utalentowaną muzykantką.', 'Anna is a talented musician.'),
('impuls3', 'motyw muzyczny', 'Lubię motyw muzyczny tego filmu.', 'I like the theme music of this film.'),
('impuls3', 'trąbka', 'Mój brat gra na trąbce.', 'My brother plays the trumpet.'),
('impuls3', 'ściszyć', 'Ścisz muzykę, proszę.', 'Turn the volume down, please.'),
('impuls3', 'podgłośnić', 'Podgłośnij telewizor.', 'Turn the volume up.'),
('impuls3', 'chór', 'Anna śpiewa w chórze.', 'Anna sings in the choir.'),
('impuls3', 'być mentorem', 'Lubię być mentorem dla młodszych.', 'I like to mentor younger ones.'),
('impuls3', 'producent muzyczny', 'On jest sławnym producentem muzycznym.', 'He is a famous music producer.'),
('impuls3', 'rap psychodeliczny', 'Lubię rap psychodeliczny.', 'I like psychedelic rap.'),
('impuls3', 'aktywować', 'Aktywowałem konto.', 'I activated the account.'),
('impuls3', 'czujny', 'Bądź czujny na drodze.', 'Be alert on the road.'),
('impuls3', 'uczęszczać', 'Uczęszczam na lekcje muzyki.', 'I attend music classes.'),
('impuls3', 'związek chemiczny', 'Woda to związek chemiczny.', 'Water is a chemical compound.'),
('impuls3', 'koncentrować się', 'Trudno mi się koncentrować.', 'It is hard for me to concentrate.'),
('impuls3', 'rozpraszać', 'Hałas mnie rozprasza.', 'The noise distracts me.'),
('impuls3', 'dopamina', 'Sport zwiększa poziom dopaminy.', 'Sport increases dopamine levels.'),
('impuls3', 'wydajnie', 'Pracuję wydajnie.', 'I work efficiently.'),
('impuls3', 'naprawić', 'Tata naprawił rower.', 'Dad fixed the bike.'),
('impuls3', 'skupić się', 'Trudno mi się skupić.', 'It is hard for me to focus.'),
('impuls3', 'polepszyć (się)', 'Moje wyniki się polepszyły.', 'My results have improved.'),
('impuls3', 'wiedza', 'Wiedza to potęga.', 'Knowledge is power.'),
('impuls3', 'umiejętności językowe', 'Doskonalę swoje umiejętności językowe.', 'I am improving my language abilities.'),
('impuls3', 'nauka przez całe życie', 'Wierzę w naukę przez całe życie.', 'I believe in lifelong learning.'),
('impuls3', 'pamięć', 'Mam dobrą pamięć.', 'I have a good memory.'),
('impuls3', 'ruch', 'Codzienny ruch jest ważny.', 'Daily movement is important.'),
('impuls3', 'przetwarzać', 'Mózg przetwarza informacje.', 'The brain processes information.'),
('impuls3', 'postanowienie', 'Mam noworoczne postanowienie.', 'I have a New Year''s resolution.'),
('impuls3', 'powtarzać do egzaminu', 'Powtarzam do egzaminu.', 'I am revising for the exam.'),
('impuls3', 'umiejętności', 'Rozwijam swoje umiejętności.', 'I am developing my skills.'),
('impuls3', 'rozwiązać', 'Rozwiązałem problem.', 'I solved the problem.'),
('impuls3', 'stymulować', 'Muzyka stymuluje mózg.', 'Music stimulates the brain.'),
('impuls3', 'wzmacniać', 'Sport wzmacnia mięśnie.', 'Sport strengthens muscles.'),
('impuls3', 'melodia', 'Lubię tę melodię.', 'I like this tune.'),
('impuls3', 'balet', 'Anna trenuje balet.', 'Anna does ballet.'),
('impuls3', 'artysta uliczny', 'Widziałem artystę ulicznego.', 'I saw a busker.'),
('impuls3', 'chwytliwa melodia', 'Ta piosenka ma chwytliwą melodię.', 'This song has a catchy melody.'),
('impuls3', 'sala koncertowa', 'Koncert odbywa się w sali koncertowej.', 'The concert is in the concert hall.'),
('impuls3', 'współczesny', 'Lubię współczesną muzykę.', 'I like contemporary music.'),
('impuls3', 'przeróbka muzyczna', 'Lubię tę przeróbkę muzyczną.', 'I like this cover version.'),
('impuls3', 'bieżący', 'To bieżące wydarzenia.', 'These are current events.'),
('impuls3', 'zabawiać', 'On lubi zabawiać ludzi.', 'He likes to entertain people.'),
('impuls3', 'zespół ludowy', 'Lubimy zespół ludowy.', 'We like the folk band.'),
('impuls3', 'przebój', 'Ta piosenka to przebój.', 'This song is a hit.'),
('impuls3', 'główny wokalista', 'On jest głównym wokalistą zespołu.', 'He is the lead singer of the band.'),
('impuls3', 'album koncertowy', 'Słucham albumu koncertowego.', 'I am listening to a live album.'),
('impuls3', 'koncert', 'Idę na koncert w sobotę.', 'I am going to a live performance on Saturday.'),
('impuls3', 'na trasie koncertowej', 'Zespół jest na trasie koncertowej.', 'The band is on tour.'),
('impuls3', 'festiwal na wolnym powietrzu', 'Idziemy na festiwal na wolnym powietrzu.', 'We are going to an open-air festival.'),
('impuls3', 'orkiestra', 'Słucham orkiestry symfonicznej.', 'I am listening to the symphony orchestra.'),
('impuls3', 'występować', 'Lubię występować na scenie.', 'I like to perform on stage.'),
('impuls3', 'lista utworów', 'Mam długą listę utworów.', 'I have a long playlist.'),
('impuls3', 'nagrywać', 'Zespół nagrywa nowy album.', 'The band is recording a new album.'),
('impuls3', 'wypuszczać na rynek', 'Wypuszczają nowy album w piątek.', 'They are releasing a new album on Friday.'),
('impuls3', 'wyprzedać', 'Bilety są wyprzedane.', 'The tickets are sold out.'),
('impuls3', 'śpiewać razem', 'Lubię śpiewać razem z innymi.', 'I like to sing along with others.'),
('impuls3', 'tekst piosenki', 'Znam tekst tej piosenki.', 'I know the lyrics of this song.'),
('impuls3', 'jakość dźwięku', 'Jakość dźwięku jest świetna.', 'The sound quality is great.'),
('impuls3', 'podróżować', 'Lubię podróżować.', 'I like to tour.'),
('impuls3', 'głos', 'Anna ma piękny głos.', 'Anna has a beautiful voice.'),
('impuls3', 'gniew', 'Czuję wielki gniew.', 'I feel great anger.'),
('impuls3', 'zdenerwowany', 'Jestem zdenerwowany.', 'I am angry.'),
('impuls3', 'znudzony', 'Jestem znudzony.', 'I am bored.'),
('impuls3', 'nuda', 'Czuję nudę.', 'I feel boredom.'),
('impuls3', 'spokojny', 'Jestem spokojny.', 'I am calm.'),
('impuls3', 'spokój', 'Lubię spokój w lesie.', 'I like calmness in the forest.'),
('impuls3', 'zadowolony (content)', 'Jestem zadowolony z wyniku.', 'I am content with the result.'),
('impuls3', 'zadowolenie (contentment)', 'Czuję zadowolenie.', 'I feel contentment.'),
('impuls3', 'zawstydzony', 'Jestem zawstydzony.', 'I am embarrassed.'),
('impuls3', 'wstyd', 'Czuję wstyd.', 'I feel embarrassment.'),
('impuls3', 'strach', 'Boję się ciemności, mam strach.', 'I am afraid of the dark, I have fear.'),
('impuls3', 'szczęście', 'Życzę ci szczęścia.', 'I wish you happiness.'),
('impuls3', 'szczęśliwy', 'Jestem szczęśliwy z rodziną.', 'I am happy with my family.'),
('impuls3', 'zazdrosny', 'Nie bądź zazdrosny.', 'Do not be jealous.'),
('impuls3', 'zazdrość', 'Zazdrość to zła emocja.', 'Jealousy is a bad emotion.'),
('impuls3', 'radość', 'Czuję wielką radość.', 'I feel great joy.'),
('impuls3', 'radosny', 'Jestem radosny dzisiaj.', 'I am joyful today.'),
('impuls3', 'życzliwy (kind)', 'Mama jest życzliwa.', 'Mum is kind.'),
('impuls3', 'życzliwość', 'Doceniam twoją życzliwość.', 'I appreciate your kindness.'),
('impuls3', 'samotność', 'Cierpię na samotność.', 'I suffer from loneliness.'),
('impuls3', 'samotny', 'Czuję się samotny.', 'I feel lonely.'),
('impuls3', 'optymizm', 'Mam dużo optymizmu.', 'I have a lot of optimism.'),
('impuls3', 'optymistyczny', 'Jestem optymistyczny.', 'I am optimistic.'),
('impuls3', 'pesymizm', 'Pesymizm nie pomaga.', 'Pessimism does not help.'),
('impuls3', 'pesymistyczny', 'Nie bądź pesymistyczny.', 'Do not be pessimistic.'),
('impuls3', 'smutny', 'Jestem smutny dzisiaj.', 'I am sad today.'),
('impuls3', 'smutek', 'Czuję wielki smutek.', 'I feel great sadness.'),
('impuls3', 'zadowolenie (satisfaction)', 'Czuję zadowolenie z pracy.', 'I feel satisfaction from work.'),
('impuls3', 'zadowolony (satisfied)', 'Jestem zadowolony z wyniku.', 'I am satisfied with the result.'),
('impuls3', 'wystraszony', 'Jestem wystraszony.', 'I am scared.'),
('impuls3', 'niespodzianka', 'To miła niespodzianka!', 'It is a nice surprise!'),
('impuls3', 'zaskoczony', 'Jestem zaskoczony tą wiadomością.', 'I am surprised by this news.'),
('impuls3', 'współczujący', 'Bądź współczujący dla innych.', 'Be sympathetic to others.'),
('impuls3', 'współczucie', 'Czuję współczucie dla nich.', 'I feel sympathy for them.'),
('impuls3', 'lekki', 'Czuję się lekki jak piórko.', 'I feel weightless like a feather.'),
('impuls3', 'równowaga', 'Trudno utrzymać równowagę.', 'It is hard to keep balance.'),
('impuls3', 'melodia wpadająca w ucho', 'Mam melodię wpadającą w ucho.', 'I have an earworm.'),
('impuls3', 'stanie na rękach', 'Potrafię stać na rękach.', 'I can do a handstand.'),
('impuls3', 'mazurek', 'Chopin komponował mazurki.', 'Chopin composed mazurkas.')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Impuls 3: 249 unikalnych zdan zaktualizowanych/dodanych w word_sentences (249 wpisow w data.js, brak duplikatow).';
END $$;
