-- ═══════════════════════════════════════════════════════════
-- Fix sentences: BRAINY 6 (klasa 6, szkola podstawowa)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 502 unikalnych slowek z Brainy 6 (Macmillan).
--
-- Tematy unitow:
--   Unit 1 (75): zawody + miejsca pracy + opinie + have to
--   Unit 2 (84): meble + sprzety AGD + present continuous + adverbs
--   Unit 3 (47): wydarzenia zyciowe + szkola + opinie + will/won't
--   Unit 4 (87): zwierzeta + ciala + opisy + comparatives + zaimki dzierzawcze
--   Unit 5 (68): jedzenie + przybory + smaki + gotowanie + was/were
--   Unit 6 (44): zdrowie + dolegliwosci + past simple
--   Unit 7 (59): komputery + emocje + present perfect
--   Unit 8 (52): aktywnosci + ekologia + present perfect vs past simple
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — Jobs, workplaces, have to (75)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'kasjer/kasjerka', 'Kasjerka pracuje w sklepie.', 'The cashier works in a shop.'),
('brainy6', 'inżynier/inżynierka', 'Mój tata jest inżynierem.', 'My dad is an engineer.'),
('brainy6', 'rolnik / rolniczka', 'Rolnik uprawia rośliny.', 'A farmer grows crops.'),
('brainy6', 'pielęgniarz / pielęgniarka', 'Pielęgniarka pomaga lekarzowi.', 'The nurse helps the doctor.'),
('brainy6', 'prawnik / prawniczka', 'Prawnik pracuje w kancelarii.', 'A lawyer works in a law firm.'),
('brainy6', 'naukowiec', 'Naukowiec robi eksperymenty.', 'A scientist does experiments.'),
('brainy6', 'hydraulik / hydrauliczka', 'Hydraulik naprawił mi kran.', 'The plumber fixed my tap.'),
('brainy6', 'kierownik / kierowniczka centrum sportowego', 'Kierownik centrum sportowego organizuje zajęcia.', 'The sports centre manager organises classes.'),
('brainy6', 'budować mosty', 'Inżynierowie budują mosty.', 'Engineers build bridges.'),
('brainy6', 'przeprowadzać eksperymenty', 'Naukowcy przeprowadzają eksperymenty.', 'Scientists do experiments.'),
('brainy6', 'naprawiać rury', 'Hydraulicy naprawiają rury.', 'Plumbers fix leaks.'),
('brainy6', 'wydawać polecenia', 'Kierownik wydaje polecenia pracownikom.', 'The manager gives instructions to workers.'),
('brainy6', 'wydawać klientom resztę', 'Kasjerzy wydają klientom resztę.', 'Cashiers give change to customers.'),
('brainy6', 'uprawiać rośliny i doić krowy', 'Rolnicy uprawiają rośliny i doją krowy.', 'Farmers grow crops and milk cows.'),
('brainy6', 'pomagać w kwestiach prawnych', 'Prawnicy pomagają w kwestiach prawnych.', 'Lawyers help people with the law.'),
('brainy6', 'opiekować się pacjentami', 'Pielęgniarki opiekują się pacjentami.', 'Nurses look after patients.'),
('brainy6', 'lotnisko', 'Samolot ląduje na lotnisku.', 'The plane lands at the airport.'),
('brainy6', 'bank', 'Mama pracuje w banku.', 'Mum works at the bank.'),
('brainy6', 'fabryka', 'Tata pracuje w fabryce.', 'Dad works in a factory.'),
('brainy6', 'farma', 'Krowy mieszkają na farmie.', 'Cows live on a farm.'),
('brainy6', 'remiza (strażacka)', 'Strażacy pracują w remizie.', 'Firefighters work at the fire station.'),
('brainy6', 'szpital', 'Lekarze pracują w szpitalu.', 'Doctors work at the hospital.'),
('brainy6', 'biuro', 'Tata pracuje w biurze.', 'Dad works in an office.'),
('brainy6', 'komisariat / posterunek', 'Policjanci pracują na komisariacie.', 'Police officers work at the police station.'),
('brainy6', 'budynek poczty', 'Wysyłam list w budynku poczty.', 'I send a letter at the post office.'),
('brainy6', 'zakład segregacji odpadów', 'Plastik trafia do zakładu segregacji odpadów.', 'Plastic goes to the recycling centre.'),
('brainy6', 'ratusz / urząd miejski', 'Mama pracuje w ratuszu.', 'Mum works in the town hall.'),
('brainy6', 'magazyn', 'Towary są w magazynie.', 'The goods are in the warehouse.'),
('brainy6', 'Śpieszymy się', 'Śpieszymy się, jest późno.', 'We are in a rush, it is late.'),
('brainy6', 'Do zobaczenia wkrótce!', 'Do zobaczenia wkrótce!', 'See you soon!'),
('brainy6', 'Przepraszam za spóźnienie', 'Przepraszam za spóźnienie.', 'Sorry I am late.'),
('brainy6', 'Uwielbiam...', 'Uwielbiam grać w piłkę.', 'I love playing football.'),
('brainy6', 'Lubię...', 'Lubię pływać.', 'I like swimming.'),
('brainy6', 'Nie przeszkadza mi...', 'Nie przeszkadza mi sprzątanie.', 'I do not mind cleaning.'),
('brainy6', 'Nie lubię...', 'Nie lubię ostrego jedzenia.', 'I do not like spicy food.'),
('brainy6', 'Nienawidzę...', 'Nienawidzę wstawać wcześnie.', 'I hate getting up early.'),
('brainy6', 'Tak, naprawdę lubię', 'Tak, naprawdę lubię tę książkę.', 'Yes, I really do like this book.'),
('brainy6', 'Tak, lubię', 'Tak, lubię.', 'Yes, I do.'),
('brainy6', 'Nie mam nic przeciwko', 'Nie mam nic przeciwko.', 'I do not mind it.'),
('brainy6', 'Nie, nie za bardzo', 'Nie, nie za bardzo.', 'No, not really.'),
('brainy6', 'Nie, nienawidzę tego', 'Nie, nienawidzę tego.', 'No, I hate it.'),
('brainy6', 'Naukowcy przeprowadzają eksperymenty.', 'Naukowcy przeprowadzają eksperymenty.', 'Scientists do experiments.'),
('brainy6', 'Hydraulicy naprawiają cieknące rury', 'Hydraulicy naprawiają cieknące rury.', 'Plumbers fix leaks.'),
('brainy6', 'Kasjerzy wydają klientom resztę', 'Kasjerzy wydają klientom resztę.', 'Cashiers give change to customers.'),
('brainy6', 'Pielęgniarki opiekują się pacjentami.', 'Pielęgniarki opiekują się pacjentami.', 'Nurses look after patients.'),
('brainy6', 'Rolnicy uprawiają rośliny i doją krowy.', 'Rolnicy uprawiają rośliny i doją krowy.', 'Farmers grow crops and milk cows.'),
('brainy6', 'Inżynierowie budują mosty', 'Inżynierowie budują mosty.', 'Engineers build bridges.'),
('brainy6', 'Kierownicy centrum sportowego wydają polecenia innym pracownikom.', 'Kierownicy centrum sportowego wydają polecenia.', 'Sports centre managers give instructions.'),
('brainy6', 'Prawnicy pomagają ludziom w kwestiach prawnych.', 'Prawnicy pomagają ludziom w kwestiach prawnych.', 'Lawyers help people with the law.'),
('brainy6', 'Naukowcy muszą przeprowadzać eksperymenty', 'Naukowcy muszą przeprowadzać eksperymenty.', 'Scientists have to do experiments.'),
('brainy6', 'Hydraulicy muszą naprawiać cieknące rury', 'Hydraulicy muszą naprawiać cieknące rury.', 'Plumbers have to fix leaks.'),
('brainy6', 'Kasjerzy muszą wydawać klientom resztę', 'Kasjerzy muszą wydawać klientom resztę.', 'Cashiers have to give change to customers.'),
('brainy6', 'Pielęgniarki muszą opiekować się pacjentami', 'Pielęgniarki muszą opiekować się pacjentami.', 'Nurses have to look after patients.'),
('brainy6', 'Rolnicy muszą uprawiać rośliny i doić krowy', 'Rolnicy muszą uprawiać rośliny i doić krowy.', 'Farmers have to grow crops and milk cows.'),
('brainy6', 'Inżynierowie muszą budować mosty', 'Inżynierowie muszą budować mosty.', 'Engineers have to build bridges.'),
('brainy6', 'Kierownicy centrum sportowego muszą wydawać polecenia innym pracownikom.', 'Kierownicy centrum sportowego muszą wydawać polecenia.', 'Sports centre managers have to give instructions.'),
('brainy6', 'Prawnicy muszą pomagać ludziom w kwestiach prawnych.', 'Prawnicy muszą pomagać ludziom w kwestiach prawnych.', 'Lawyers have to help people with the law.'),
('brainy6', 'Naukowcy nie muszą budować mostów', 'Naukowcy nie muszą budować mostów.', 'Scientists do not have to build bridges.'),
('brainy6', 'Hydraulicy nie muszą przeprowadzać eksperymentów', 'Hydraulicy nie muszą przeprowadzać eksperymentów.', 'Plumbers do not have to do experiments.'),
('brainy6', 'Kasjerzy nie muszą naprawiać wycieków', 'Kasjerzy nie muszą naprawiać wycieków.', 'Cashiers do not have to fix leaks.'),
('brainy6', 'Pielęgniarki nie muszą wydawać klientom reszty', 'Pielęgniarki nie muszą wydawać klientom reszty.', 'Nurses do not have to give change to customers.'),
('brainy6', 'Rolnicy nie muszą wydawać poleceń innym pracownikom', 'Rolnicy nie muszą wydawać poleceń.', 'Farmers do not have to give instructions to other workers.'),
('brainy6', 'Inżynierowie nie muszą uprawiać roślin i doić krów.', 'Inżynierowie nie muszą uprawiać roślin i doić krów.', 'Engineers do not have to grow crops and milk cows.'),
('brainy6', 'Kierownicy centrum sportowego nie muszą pomagać ludziom w kwestiach prawnych', 'Kierownicy centrum sportowego nie muszą pomagać w kwestiach prawnych.', 'Sports centre managers do not have to help people with the law.'),
('brainy6', 'Prawnicy nie muszą opiekować się pacjentami', 'Prawnicy nie muszą opiekować się pacjentami.', 'Lawyers do not have to look after patients.'),
('brainy6', 'Moja mama pracuje dla miasta w ratuszu.', 'Moja mama pracuje dla miasta w ratuszu.', 'My mum works for the city in the town hall.'),
('brainy6', 'Uwielbiam grać w piłkę nożną.', 'Uwielbiam grać w piłkę nożną.', 'I love playing football.'),
('brainy6', 'Lubię pływać.', 'Lubię pływać.', 'I like swimming.'),
('brainy6', 'Nie przeszkadza mi oglądanie horrorów.', 'Nie przeszkadza mi oglądanie horrorów.', 'I do not mind watching horror films.'),
('brainy6', 'Nie lubię pić herbaty cytrynowej.', 'Nie lubię pić herbaty cytrynowej.', 'I do not like drinking lemon tea.'),
('brainy6', 'Nienawidzę naprawiać cieknących rur.', 'Nienawidzę naprawiać cieknących rur.', 'I hate fixing leaks.'),
('brainy6', 'Kiedy musisz wstać?', 'Kiedy musisz wstać?', 'When do you have to get up?'),
('brainy6', 'Co musisz zrobić w sobotę?', 'Co musisz zrobić w sobotę?', 'What do you have to do on Saturday?'),
('brainy6', 'Gdzie ona musi iść?', 'Gdzie ona musi iść?', 'Where does she have to go?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — Furniture, appliances, present continuous (84)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'fotel', 'Tata siedzi w fotelu.', 'Dad is sitting in the armchair.'),
('brainy6', 'rolety, żaluzje', 'Zamykam rolety.', 'I am closing the blinds.'),
('brainy6', 'biblioteczka', 'Książki są na biblioteczce.', 'The books are on the bookcase.'),
('brainy6', 'szafka', 'Talerze są w szafce.', 'The plates are in the cupboard.'),
('brainy6', 'zasłony', 'Mama zasuwa zasłony.', 'Mum is closing the curtains.'),
('brainy6', 'poduszka ozdobna', 'Mam ozdobną poduszkę.', 'I have a decorative cushion.'),
('brainy6', 'poduszka do spania', 'Moja poduszka jest miękka.', 'My pillow is soft.'),
('brainy6', 'lustro', 'Lustro jest w łazience.', 'The mirror is in the bathroom.'),
('brainy6', 'dywanik', 'Dywanik leży przed łóżkiem.', 'The rug is in front of the bed.'),
('brainy6', 'półka', 'Książka jest na półce.', 'The book is on the shelf.'),
('brainy6', 'półki', 'Mam dużo półek na książki.', 'I have a lot of shelves for books.'),
('brainy6', 'kanapa', 'Kot śpi na kanapie.', 'The cat is sleeping on the sofa.'),
('brainy6', 'ręcznik', 'Daj mi czysty ręcznik.', 'Give me a clean towel.'),
('brainy6', 'szafa', 'Ubrania są w szafie.', 'The clothes are in the wardrobe.'),
('brainy6', 'umywalka', 'Myję ręce w umywalce.', 'I wash my hands in the basin.'),
('brainy6', 'wanna', 'Lubię gorącą kąpiel w wannie.', 'I like a hot bath in the bath.'),
('brainy6', 'zmywarka', 'Wkładam naczynia do zmywarki.', 'I am loading the dishwasher.'),
('brainy6', 'kuchenka', 'Mama gotuje na kuchence.', 'Mum is cooking on the cooker.'),
('brainy6', 'zamrażarka', 'Lody są w zamrażarce.', 'The ice cream is in the freezer.'),
('brainy6', 'lodówka', 'Mleko jest w lodówce.', 'The milk is in the fridge.'),
('brainy6', 'grzejnik', 'Grzejnik jest gorący.', 'The heater is hot.'),
('brainy6', 'kaloryfer', 'Włącz kaloryfer, jest zimno.', 'Turn on the radiator, it is cold.'),
('brainy6', 'prysznic', 'Biorę prysznic rano.', 'I have a shower in the morning.'),
('brainy6', 'zlew', 'Naczynia są w zlewie.', 'The dishes are in the sink.'),
('brainy6', 'kran', 'Zakręć kran.', 'Turn off the tap.'),
('brainy6', 'pralka', 'Pralka pierze ubrania.', 'The washing machine is washing clothes.'),
('brainy6', 'nie mam pojęcia', 'Nie mam pojęcia, gdzie to jest.', 'I have no idea where it is.'),
('brainy6', 'Biedactwo!', 'Biedactwo! Płacze.', 'Poor little thing! It is crying.'),
('brainy6', 'coś podejrzanego się tu dzieje.', 'Coś podejrzanego się tu dzieje.', 'There is something fishy going on.'),
('brainy6', 'Co oni kombinują?', 'Co oni kombinują?', 'What are they up to?'),
('brainy6', 'Czy potrzebujesz pomocy?', 'Czy potrzebujesz pomocy?', 'Do you need any help?'),
('brainy6', 'Pomóc ci?', 'Pomóc ci?', 'Do you want a hand?'),
('brainy6', 'Pewnie, nie ma sprawy.', 'Pewnie, nie ma sprawy.', 'Sure, no problem.'),
('brainy6', 'Dziękuję, bardzo mi pomożesz.', 'Dziękuję, bardzo mi pomożesz.', 'Thanks, that is a great help.'),
('brainy6', 'Dziękuję, to bardzo miło z twojej strony.', 'Dziękuję, to bardzo miło z twojej strony.', 'Thanks, that is very good of you.'),
('brainy6', 'zasunąć zasłonki', 'Zasuwam zasłonki wieczorem.', 'I close the curtains in the evening.'),
('brainy6', 'włożyć naczynia do zmywarki', 'Wkładam naczynia do zmywarki.', 'I load the dishwasher.'),
('brainy6', 'rozsunąć zasłonki', 'Rozsuwam zasłonki rano.', 'I open the curtains in the morning.'),
('brainy6', 'włożyć pranie do pralki', 'Wkładam pranie do pralki.', 'I put the washing in the washing machine.'),
('brainy6', 'wyjąć pranie z pralki', 'Wyjmuję pranie z pralki.', 'I take the washing out of the washing machine.'),
('brainy6', 'zmniejszyć temperaturę na kaloryferze', 'Zmniejsz temperaturę na kaloryferze.', 'Turn the radiator down.'),
('brainy6', 'wyłączyć kaloryfer', 'Wyłącz kaloryfer.', 'Turn the radiator off.'),
('brainy6', 'włączyć kaloryfer', 'Włącz kaloryfer.', 'Turn the radiator on.'),
('brainy6', 'zwiększyć temperaturę na kaloryferze', 'Zwiększ temperaturę na kaloryferze.', 'Turn the radiator up.'),
('brainy6', 'wypakować naczynia ze zmywarki', 'Wypakowuję naczynia ze zmywarki.', 'I am unloading the dishwasher.'),
('brainy6', 'teraz', 'Teraz robię lekcje.', 'I am doing homework now.'),
('brainy6', 'już teraz', 'Wracam już teraz.', 'I am coming back right now.'),
('brainy6', 'w tym momencie', 'W tym momencie nie pracuję.', 'I am not working at the moment.'),
('brainy6', 'Mark czyta teraz książkę.', 'Mark czyta teraz książkę.', 'Mark is reading a book now.'),
('brainy6', 'Adam w tej chwili nie gra w piłkę nożną.', 'Adam w tej chwili nie gra w piłkę nożną.', 'Adam is not playing football at the moment.'),
('brainy6', 'Czy Marta pływa teraz?', 'Czy Marta pływa teraz?', 'Is Marta swimming now?'),
('brainy6', 'dzisiaj', 'Dzisiaj jest piątek.', 'Today is Friday.'),
('brainy6', 'w tym tygodniu', 'W tym tygodniu mam dużo lekcji.', 'I have a lot of lessons this week.'),
('brainy6', 'w tym miesiącu', 'W tym miesiącu są wakacje.', 'There are holidays this month.'),
('brainy6', 'Tom i Bob czytają książki w tym tygodniu.', 'Tom i Bob czytają książki w tym tygodniu.', 'Tom and Bob are reading books this week.'),
('brainy6', 'w następnym tygodniu', 'W następnym tygodniu mam test.', 'I have a test next week.'),
('brainy6', 'w następnym miesiącu', 'W następnym miesiącu wyjeżdżamy.', 'We are going away next month.'),
('brainy6', 'w następnym roku', 'W następnym roku idę do gimnazjum.', 'I am going to middle school next year.'),
('brainy6', '12 lipca', 'Spotkamy się 12 lipca.', 'We will meet on 12th July.'),
('brainy6', 'w poniedziałek', 'W poniedziałek mam matematykę.', 'I have maths on Monday.'),
('brainy6', 'w kwietniu', 'W kwietniu często pada deszcz.', 'It often rains in April.'),
('brainy6', 'w 2025 r.', 'W 2025 r. będę miał 12 lat.', 'In 2025 I will be 12 years old.'),
('brainy6', 'Bob rozpoczyna nową pracę w poniedziałek.', 'Bob rozpoczyna nową pracę w poniedziałek.', 'Bob is starting a new job on Monday.'),
('brainy6', 'nigdy', 'Nigdy nie spóźniam się do szkoły.', 'I am never late for school.'),
('brainy6', 'prawie nigdy', 'Prawie nigdy nie oglądam telewizji.', 'I hardly ever watch TV.'),
('brainy6', 'czasami', 'Czasami chodzę do kina.', 'I sometimes go to the cinema.'),
('brainy6', 'zazwyczaj', 'Zazwyczaj wstaję o siódmej.', 'I usually get up at seven.'),
('brainy6', 'zawsze', 'Zawsze chodzę do szkoły rano.', 'I always go to school in the morning.'),
('brainy6', 'codziennie', 'Codziennie ćwiczę.', 'I do exercise every day.'),
('brainy6', 'co tydzień', 'Co tydzień gram w tenisa.', 'I play tennis every week.'),
('brainy6', 'każdego miesiąca', 'Każdego miesiąca dostaję kieszonkowe.', 'I get pocket money every month.'),
('brainy6', 'raz w tygodniu', 'Raz w tygodniu chodzę na basen.', 'I go to the pool once a week.'),
('brainy6', 'dwa razy w tygodniu', 'Dwa razy w tygodniu mam wf.', 'I have PE twice a week.'),
('brainy6', 'trzy razy w tygodniu', 'Trzy razy w tygodniu trenuję.', 'I train three times a week.'),
('brainy6', 'Gram w piłkę nożną co miesiąc.', 'Gram w piłkę nożną co miesiąc.', 'I play football every month.'),
('brainy6', 'Bob codziennie gra w piłkę nożną.', 'Bob codziennie gra w piłkę nożną.', 'Bob plays football every day.'),
('brainy6', 'Sue czasami pływa w morzu.', 'Sue czasami pływa w morzu.', 'Sue sometimes swims in the sea.'),
('brainy6', 'Tina nigdy nie gra w tenisa.', 'Tina nigdy nie gra w tenisa.', 'Tina never plays tennis.'),
('brainy6', 'Bob i Tom nie czytają nudnych książek.', 'Bob i Tom nie czytają nudnych książek.', 'Bob and Tom do not read boring books.'),
('brainy6', 'Czy Tom gra w piłkę nożną dwa razy w tygodniu?', 'Czy Tom gra w piłkę nożną dwa razy w tygodniu?', 'Does Tom play football twice a week?'),
('brainy6', 'Co teraz robisz?', 'Co teraz robisz?', 'What are you doing now?'),
('brainy6', 'Co zwykle robisz w poniedziałki?', 'Co zwykle robisz w poniedziałki?', 'What do you usually do on Mondays?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 3 — Life events, school, opinions, will/won't (47)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'stać się znanym', 'Chcę stać się znanym piosenkarzem.', 'I want to become famous as a singer.'),
('brainy6', 'zakochać się', 'Zakochałem się w Annie.', 'I fell in love with Anna.'),
('brainy6', 'dostać pracę', 'Tata dostał nową pracę.', 'Dad got a new job.'),
('brainy6', 'rozwieść się', 'Moi rodzice są małżeństwem, nie rozwiedli się.', 'My parents are married, they did not get divorced.'),
('brainy6', 'ożenić się, wyjść za mąż', 'Wujek ożenił się latem.', 'My uncle got married in summer.'),
('brainy6', 'stać się bogatym', 'Chcę stać się bogatym.', 'I want to get rich.'),
('brainy6', 'iść na uniwersytet', 'Po szkole pójdę na uniwersytet.', 'After school I will go to university.'),
('brainy6', 'kłócić się', 'Czasami kłócę się z bratem.', 'I sometimes have an argument with my brother.'),
('brainy6', 'mieć operację', 'Tata miał operację w zeszłym roku.', 'Dad had an operation last year.'),
('brainy6', 'mieć dzieci', 'Oni mają trójkę dzieci.', 'They have children — three of them.'),
('brainy6', 'pogodzić się', 'Pogodziłem się z bratem.', 'I made up with my brother.'),
('brainy6', 'przeprowadzić się', 'Przeprowadziliśmy się do Krakowa.', 'We moved house to Krakow.'),
('brainy6', 'ściągać na sprawdzianie', 'Nigdy nie ściągam na sprawdzianie.', 'I never cheat in a test.'),
('brainy6', 'poprawiać błędy', 'Nauczycielka poprawia błędy w zeszycie.', 'The teacher corrects mistakes in the notebook.'),
('brainy6', 'zrobić świetny projekt', 'Zrobiłem świetny projekt z biologii.', 'I did a brilliant project in biology.'),
('brainy6', 'nie zaliczyć sprawdzianu', 'Nie zaliczyłem sprawdzianu z matematyki.', 'I failed the maths test.'),
('brainy6', 'dostać dobrą ocenę', 'Dostałem dobrą ocenę z angielskiego.', 'I got a good mark in English.'),
('brainy6', 'dostać niską ocenę', 'Dostałem niską ocenę z testu.', 'I got a low mark in the test.'),
('brainy6', 'robić błędy', 'Każdy robi błędy.', 'Everyone makes mistakes.'),
('brainy6', 'zaliczyć sprawdzian', 'Zaliczyłem sprawdzian z biologii.', 'I passed the biology test.'),
('brainy6', 'uważać na lekcji', 'Powinieneś uważać na lekcji.', 'You should pay attention in class.'),
('brainy6', 'powtarzać do sprawdzianu', 'Powtarzam do sprawdzianu z geografii.', 'I am revising for the geography test.'),
('brainy6', 'napisać znakomite wypracowanie', 'Napisałem znakomite wypracowanie.', 'I wrote an excellent essay.'),
('brainy6', 'Baw się dobrze!', 'Baw się dobrze na imprezie!', 'Have a good time at the party!'),
('brainy6', 'Złapię ich na gorącym uczynku.', 'Złapię ich na gorącym uczynku.', 'I will catch them red-handed.'),
('brainy6', 'Jaki to ma sens?', 'Jaki to ma sens?', 'What is the point?'),
('brainy6', 'Zgadzam się z Tobą.', 'Zgadzam się z Tobą.', 'I agree with you.'),
('brainy6', 'Nie mogę w to uwierzyć.', 'Nie mogę w to uwierzyć.', 'I cannot believe that.'),
('brainy6', 'Nie zgadzam się.', 'Nie zgadzam się.', 'I do not agree.'),
('brainy6', 'Nie chcę być niegrzeczny, ale czy jesteś pewien, że to prawda?', 'Nie chcę być niegrzeczny, ale czy jesteś pewien?', 'I do not mean to be rude, but are you sure that is right?'),
('brainy6', 'Brzmi OK.', 'Brzmi OK.', 'That sounds right.'),
('brainy6', 'To bzdura.', 'To bzdura.', 'That is rubbish.'),
('brainy6', 'On mnie lubi.', 'On mnie lubi.', 'He likes me.'),
('brainy6', 'Lubię cię.', 'Lubię cię.', 'I like you.'),
('brainy6', 'Lubię go.', 'Lubię go.', 'I like him.'),
('brainy6', 'Lubię ją.', 'Lubię ją.', 'I like her.'),
('brainy6', 'Lubię to.', 'Lubię to.', 'I like it.'),
('brainy6', 'On nas lubi.', 'On nas lubi.', 'He likes us.'),
('brainy6', 'Oni lubią was.', 'Oni lubią was.', 'They like you.'),
('brainy6', 'Lubię ich.', 'Lubię ich.', 'I like them.'),
('brainy6', 'Moja siostra wzbogaci się w 2052 roku.', 'Moja siostra wzbogaci się w 2052 roku.', 'My sister will get rich in 2052.'),
('brainy6', 'Mój kuzyn pójdzie na uniwersytet w przyszłym roku.', 'Mój kuzyn pójdzie na uniwersytet w przyszłym roku.', 'My cousin will go to university next year.'),
('brainy6', 'Adam nie będzie miał dzieci w 2045 r.', 'Adam nie będzie miał dzieci w 2045 r.', 'Adam will not have children in 2045.'),
('brainy6', 'Dylan nie przeprowadzi się w przyszłym roku.', 'Dylan nie przeprowadzi się w przyszłym roku.', 'Dylan will not move house next year.'),
('brainy6', 'Czy Rob będzie miał operację w 2049 r.?', 'Czy Rob będzie miał operację w 2049 r.?', 'Will Rob have an operation in 2049?'),
('brainy6', 'Myślę, że Kevin dostanie dobrą robotę, ale nie wzbogaci się.', 'Myślę, że Kevin dostanie dobrą robotę, ale nie wzbogaci się.', 'I think Kevin will get a good job but he will not get rich.'),
('brainy6', 'Myślę, że Kate nie będzie miała dzieci i się rozwiedzie.', 'Myślę, że Kate nie będzie miała dzieci i się rozwiedzie.', 'I think Kate will not have children and she will get divorced.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 4 — Animals, descriptions, comparatives (87)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'nietoperz', 'Nietoperz lata w nocy.', 'A bat flies at night.'),
('brainy6', 'bóbr', 'Bóbr buduje tamy.', 'A beaver builds dams.'),
('brainy6', 'wielbłąd', 'Wielbłąd żyje na pustyni.', 'A camel lives in the desert.'),
('brainy6', 'szympans', 'Szympans jest mądry.', 'A chimpanzee is clever.'),
('brainy6', 'krab', 'Krab ma czerwoną skorupę.', 'A crab has a red shell.'),
('brainy6', 'kangur', 'Kangur skacze wysoko.', 'A kangaroo jumps high.'),
('brainy6', 'ośmiornica', 'Ośmiornica ma osiem ramion.', 'An octopus has eight arms.'),
('brainy6', 'struś', 'Struś nie potrafi latać.', 'An ostrich cannot fly.'),
('brainy6', 'sowa', 'Sowa lata w nocy.', 'An owl flies at night.'),
('brainy6', 'pingwin', 'Pingwin nie potrafi latać.', 'A penguin cannot fly.'),
('brainy6', 'niedźwiedź polarny', 'Niedźwiedź polarny ma białe futro.', 'A polar bear has white fur.'),
('brainy6', 'rekin', 'Rekin ma ostre zęby.', 'A shark has sharp teeth.'),
('brainy6', 'uroczy', 'Twój kotek jest uroczy.', 'Your kitten is cute.'),
('brainy6', 'zagrożony', 'Tygrysy są zagrożone.', 'Tigers are endangered.'),
('brainy6', 'inteligentny', 'Delfiny są inteligentne.', 'Dolphins are intelligent.'),
('brainy6', 'jadowity', 'Niektóre węże są jadowite.', 'Some snakes are poisonous.'),
('brainy6', 'straszny', 'Ten film jest straszny.', 'This film is scary.'),
('brainy6', 'brzydki', 'Ten owad jest brzydki.', 'This insect is ugly.'),
('brainy6', 'dziób', 'Ptak ma dziób.', 'A bird has a beak.'),
('brainy6', 'pazury', 'Lew ma ostre pazury.', 'A lion has sharp claws.'),
('brainy6', 'pióra', 'Papugi mają kolorowe pióra.', 'Parrots have colourful feathers.'),
('brainy6', 'płetwa', 'Ryba ma płetwy.', 'A fish has fins.'),
('brainy6', 'sierść', 'Pies ma miękką sierść.', 'A dog has soft fur.'),
('brainy6', 'łapa', 'Pies ma cztery łapy.', 'A dog has four paws.'),
('brainy6', 'skorupa, muszla', 'Żółw ma skorupę.', 'A tortoise has a shell.'),
('brainy6', 'ogon', 'Małpa ma długi ogon.', 'A monkey has a long tail.'),
('brainy6', 'wąsy (u zwierząt)', 'Kot ma długie wąsy.', 'A cat has long whiskers.'),
('brainy6', 'skrzydło', 'Ptak ma duże skrzydło.', 'A bird has a big wing.'),
('brainy6', 'klatka', 'Mam papugę w klatce.', 'I have a parrot in a cage.'),
('brainy6', 'legowisko dla psa', 'Pies ma swoje legowisko.', 'The dog has its own dog bed.'),
('brainy6', 'przysmaki dla psa', 'Daję psu przysmaki.', 'I give the dog dog biscuits.'),
('brainy6', 'smycz dla psa', 'Wyprowadzam psa na smyczy.', 'I walk the dog on a dog lead.'),
('brainy6', 'szampon dla psa', 'Myję psa szamponem dla psa.', 'I wash the dog with dog shampoo.'),
('brainy6', 'pokarm dla rybek', 'Karmię rybki pokarmem dla rybek.', 'I feed the fish with fish food.'),
('brainy6', 'buda', 'Pies śpi w budzie.', 'The dog sleeps in a kennel.'),
('brainy6', 'nasiona', 'Karmię ptaki nasionami.', 'I feed the birds with seeds.'),
('brainy6', 'akwarium', 'Mam rybki w akwarium.', 'I have fish in a tank.'),
('brainy6', 'Czy mogę o coś zapytać?', 'Czy mogę o coś zapytać?', 'Can I ask you something?'),
('brainy6', 'Czy powinienem wyprowadzać go codziennie?', 'Czy powinienem wyprowadzać go codziennie?', 'Should I walk it every day?'),
('brainy6', 'Jak często powinienem myć miskę psa?', 'Jak często powinienem myć miskę psa?', 'How often should I wash the dog''s bowl?'),
('brainy6', 'Dziękuję za pomoc.', 'Dziękuję za pomoc.', 'Thanks for your help.'),
('brainy6', 'Myślę o kupieniu psa.', 'Myślę o kupieniu psa.', 'I am thinking of buying a dog.'),
('brainy6', 'Nic mnie to nie obchodzi!', 'Nic mnie to nie obchodzi!', 'I could not care less!'),
('brainy6', 'Trafiony w dziesiątkę!', 'Trafiony w dziesiątkę!', 'Spot on!'),
('brainy6', 'Proszę.', 'Proszę.', 'There you are.'),
('brainy6', 'Tygrys ma pomarańczowe futro i długi ogon.', 'Tygrys ma pomarańczowe futro i długi ogon.', 'A tiger has got orange fur and a long tail.'),
('brainy6', 'Tygrys ma mocne łapy.', 'Tygrys ma mocne łapy.', 'A tiger has got strong paws.'),
('brainy6', 'Tygrys ma długie wąsy.', 'Tygrys ma długie wąsy.', 'A tiger has got long whiskers.'),
('brainy6', 'Sowa ma silny dziób i dwa skrzydła.', 'Sowa ma silny dziób i dwa skrzydła.', 'An owl has got a strong beak and two wings.'),
('brainy6', 'Ptaki mają pióra i pazury.', 'Ptaki mają pióra i pazury.', 'Birds have got feathers and claws.'),
('brainy6', 'Delfiny mają płetwy.', 'Delfiny mają płetwy.', 'Dolphins have got fins.'),
('brainy6', 'Kraby mają skorupy.', 'Kraby mają skorupy.', 'Crabs have got shells.'),
('brainy6', 'Strusie mieszkają w Afryce.', 'Strusie mieszkają w Afryce.', 'Ostriches live in Africa.'),
('brainy6', 'Wielbłądy żyją na pustyni.', 'Wielbłądy żyją na pustyni.', 'Camels live in the desert.'),
('brainy6', 'Niedźwiedzie polarne mają białe futro.', 'Niedźwiedzie polarne mają białe futro.', 'Polar bears have got white fur.'),
('brainy6', 'Kangury podskakują w górę.', 'Kangury podskakują w górę.', 'Kangaroos jump up.'),
('brainy6', 'Widzimy szympansy w zoo.', 'Widzimy szympansy w zoo.', 'We can see chimpanzees in the zoo.'),
('brainy6', 'Ośmiornice są brzydkie.', 'Ośmiornice są brzydkie.', 'Octopuses are ugly.'),
('brainy6', 'Bobry są bardziej inteligentne niż sowy.', 'Bobry są bardziej inteligentne niż sowy.', 'Beavers are more intelligent than owls.'),
('brainy6', 'Pingwiny są ładniejsze niż rekiny.', 'Pingwiny są ładniejsze niż rekiny.', 'Penguins are cuter than sharks.'),
('brainy6', 'Nietoperz nie jest tak przerażający jak krab.', 'Nietoperz nie jest tak przerażający jak krab.', 'A bat is not as scary as a crab.'),
('brainy6', 'Węże są jadowite/trujące.', 'Węże są jadowite.', 'Snakes are poisonous.'),
('brainy6', 'Pandy są zwierzętami zagrożonymi wyginięciem.', 'Pandy są zwierzętami zagrożonymi wyginięciem.', 'Pandas are endangered animals.'),
('brainy6', 'zły - gorszy - najgorszy', 'zły - gorszy - najgorszy', 'bad - worse - the worst'),
('brainy6', 'dobry - lepszy - najlepszy', 'dobry - lepszy - najlepszy', 'good - better - the best'),
('brainy6', 'Rekiny są bardziej niebezpieczne niż delfiny.', 'Rekiny są bardziej niebezpieczne niż delfiny.', 'Sharks are more dangerous than dolphins.'),
('brainy6', 'Szympans jest bardziej inteligentny niż kangur.', 'Szympans jest bardziej inteligentny niż kangur.', 'A chimpanzee is more intelligent than a kangaroo.'),
('brainy6', 'Panda jest tak słodka jak kotek.', 'Panda jest tak słodka jak kotek.', 'A panda is as cute as a kitten.'),
('brainy6', 'Rekin nie jest tak inteligentny jak delfin.', 'Rekin nie jest tak inteligentny jak delfin.', 'A shark is not as intelligent as a dolphin.'),
('brainy6', 'Płetwal błękitny jest największym zwierzęciem.', 'Płetwal błękitny jest największym zwierzęciem.', 'The blue whale is the biggest animal.'),
('brainy6', 'Szympans jest najbardziej inteligentnym zwierzęciem.', 'Szympans jest najbardziej inteligentnym zwierzęciem.', 'The chimpanzee is the most intelligent animal.'),
('brainy6', 'lepszy', 'Mój wynik jest lepszy.', 'My score is better.'),
('brainy6', 'najlepszy', 'To najlepszy film.', 'This is the best film.'),
('brainy6', 'gorszy', 'Ten test jest gorszy.', 'This test is worse.'),
('brainy6', 'najgorszy', 'To najgorszy dzień.', 'This is the worst day.'),
('brainy6', 'To jest moje', 'To jest moje.', 'It is mine.'),
('brainy6', 'To jest twoje / wasze.', 'To jest twoje.', 'It is yours.'),
('brainy6', 'To jest jego.', 'To jest jego.', 'It is his.'),
('brainy6', 'To jest jej.', 'To jest jej.', 'It is hers.'),
('brainy6', 'To jest nasze.', 'To jest nasze.', 'It is ours.'),
('brainy6', 'To jest ich.', 'To jest ich.', 'It is theirs.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 5 — Food, utensils, taste, was/were (68)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'gulasz wołowy', 'Gulasz wołowy jest pyszny.', 'The beef stew is delicious.'),
('brainy6', 'brokuły', 'Brokuły są zielone.', 'Broccoli is green.'),
('brainy6', 'masło', 'Smażę jajka na maśle.', 'I am frying eggs in butter.'),
('brainy6', 'rosół z makaronem', 'Babcia gotuje rosół z makaronem.', 'Grandma is cooking chicken noodle soup.'),
('brainy6', 'tłuczone ziemniaki', 'Lubię tłuczone ziemniaki.', 'I like mashed potatoes.'),
('brainy6', 'groszek', 'Groszek jest zielony.', 'Peas are green.'),
('brainy6', 'kotlet schabowy', 'Tata robi kotlet schabowy.', 'Dad is making a pork chop.'),
('brainy6', 'bułki', 'Bułki są świeże.', 'The rolls are fresh.'),
('brainy6', 'pieczony łosoś', 'Pieczony łosoś jest zdrowy.', 'A salmon steak is healthy.'),
('brainy6', 'sałatka z tuńczyka', 'Robię sałatkę z tuńczyka.', 'I am making a tuna salad.'),
('brainy6', 'zapiekanka z indykiem', 'Mama gotuje zapiekankę z indykiem.', 'Mum is cooking turkey pie.'),
('brainy6', 'gorzki', 'Czarna kawa jest gorzka.', 'Black coffee is bitter.'),
('brainy6', 'świeży', 'Chleb jest świeży.', 'The bread is fresh.'),
('brainy6', 'słony', 'Frytki są słone.', 'Chips are salty.'),
('brainy6', 'ostry', 'Ten kebab jest ostry.', 'This kebab is spicy.'),
('brainy6', 'czerstwy', 'Chleb jest czerstwy.', 'The bread is stale.'),
('brainy6', 'słodki', 'Ciasto jest słodkie.', 'The cake is sweet.'),
('brainy6', 'mikser', 'Mama miksuje koktajl w mikserze.', 'Mum is mixing the smoothie in the blender.'),
('brainy6', 'miska', 'Sałatka jest w misce.', 'The salad is in the bowl.'),
('brainy6', 'deska do krojenia', 'Kroję chleb na desce do krojenia.', 'I am cutting bread on the chopping board.'),
('brainy6', 'filiżanka', 'Mama pije kawę z filiżanki.', 'Mum is drinking coffee from a cup.'),
('brainy6', 'widelec', 'Jem makaron widelcem.', 'I eat pasta with a fork.'),
('brainy6', 'patelnia', 'Smażę jajka na patelni.', 'I am frying eggs in a frying pan.'),
('brainy6', 'szklanka', 'Piję wodę ze szklanki.', 'I am drinking water from a glass.'),
('brainy6', 'nóż', 'Kroję chleb nożem.', 'I am cutting bread with a knife.'),
('brainy6', 'talerz', 'Talerz jest na stole.', 'The plate is on the table.'),
('brainy6', 'rondel', 'Gotuję zupę w rondlu.', 'I am cooking soup in a saucepan.'),
('brainy6', 'łyżka stołowa', 'Jem zupę łyżką stołową.', 'I eat soup with a spoon.'),
('brainy6', 'łyżeczka', 'Mieszam herbatę łyżeczką.', 'I am stirring tea with a teaspoon.'),
('brainy6', 'dodawać', 'Dodaj sól do zupy.', 'Add salt to the soup.'),
('brainy6', 'gotować (np. wodę)', 'Gotuję wodę na herbatę.', 'I am boiling water for tea.'),
('brainy6', 'siekać', 'Siekam cebulę.', 'I am chopping the onion.'),
('brainy6', 'gotować (jedzenie)', 'Mama gotuje obiad.', 'Mum is cooking dinner.'),
('brainy6', 'smażyć', 'Smażę jajka na śniadanie.', 'I am frying eggs for breakfast.'),
('brainy6', 'mieszać', 'Mieszaj sałatkę.', 'Mix the salad.'),
('brainy6', 'podawać, serwować', 'Kelner podaje obiad.', 'The waiter is serving dinner.'),
('brainy6', 'kroić w plasterki', 'Kroję chleb w plasterki.', 'I am slicing the bread.'),
('brainy6', 'Jak to się robi?', 'Jak to się robi?', 'How do I make it?'),
('brainy6', 'Ile czasu potrzeba na zrobienie tego dania?', 'Ile czasu potrzeba na zrobienie tego dania?', 'How long does it take to make?'),
('brainy6', 'Jakich składników potrzebuję?', 'Jakich składników potrzebuję?', 'What ingredients do I need?'),
('brainy6', 'Na początku, ...', 'Na początku, posiekaj cebulę.', 'First, chop the onion.'),
('brainy6', 'Następnie, ...', 'Następnie, dodaj wodę.', 'Then, add water.'),
('brainy6', 'Na końcu, ...', 'Na końcu, podaj na talerzu.', 'Finally, serve on a plate.'),
('brainy6', 'Mogę ci pomóc.', 'Mogę ci pomóc.', 'I can give you a hand.'),
('brainy6', 'Ale mnie to wkurza!', 'Ale mnie to wkurza!', 'It makes me mad!'),
('brainy6', 'Tylko się uspokój!', 'Tylko się uspokój!', 'Just calm down!'),
('brainy6', 'Na niewiele się zdadzą.', 'Na niewiele się zdadzą.', 'They are not much use.'),
('brainy6', 'Ta sałatka nie jest świeża.', 'Ta sałatka nie jest świeża.', 'This salad is not fresh.'),
('brainy6', 'To jabłko jest trochę słodkie.', 'To jabłko jest trochę słodkie.', 'This apple is a bit sweet.'),
('brainy6', 'Ten gulasz wołowy jest słony.', 'Ten gulasz wołowy jest słony.', 'This beef stew is salty.'),
('brainy6', 'To jest bardzo pikantne.', 'To jest bardzo pikantne.', 'This is very spicy.'),
('brainy6', 'Bułki są czerstwe.', 'Bułki są czerstwe.', 'The rolls are stale.'),
('brainy6', 'Te pomarańcze są gorzkie.', 'Te pomarańcze są gorzkie.', 'These oranges are bitter.'),
('brainy6', 'Byłem w szkole.', 'Byłem w szkole.', 'I was at school.'),
('brainy6', 'Nie byłeś w szkole.', 'Nie byłeś w szkole.', 'You were not at school.'),
('brainy6', 'Czy był w szkole?', 'Czy był w szkole?', 'Was he at school?'),
('brainy6', 'Ona była smutna.', 'Ona była smutna.', 'She was sad.'),
('brainy6', 'To było słodkie.', 'To było słodkie.', 'It was sweet.'),
('brainy6', 'Nie byliśmy głodni.', 'Nie byliśmy głodni.', 'We were not hungry.'),
('brainy6', 'Czy oni byli w domu?', 'Czy oni byli w domu?', 'Were they at home?'),
('brainy6', 'O której godzinie byłeś w szkole?', 'O której godzinie byłeś w szkole?', 'What time were you at school?'),
('brainy6', 'Było dużo śmieci.', 'Było dużo śmieci.', 'There was a lot of rubbish.'),
('brainy6', 'Tam było dużo ludzi.', 'Tam było dużo ludzi.', 'There were a lot of people.'),
('brainy6', 'Nie było żadnego masła.', 'Nie było żadnego masła.', 'There was not any butter.'),
('brainy6', 'Nie było żadnych bułek.', 'Nie było żadnych bułek.', 'There were not any rolls.'),
('brainy6', 'Czy były jakieś banany?', 'Czy były jakieś banany?', 'Were there any bananas?'),
('brainy6', 'Czy był nóż?', 'Czy był nóż?', 'Was there a knife?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 6 — Health, illness, past simple (44)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'być przeziębionym', 'Jestem przeziębiony.', 'I have a cold.'),
('brainy6', 'mieć kaszel', 'Mam kaszel od tygodnia.', 'I have a cough for a week.'),
('brainy6', 'mieć gorączkę', 'Mam wysoką gorączkę.', 'I have a high fever.'),
('brainy6', 'mieć ból głowy', 'Mam ból głowy.', 'I have a headache.'),
('brainy6', 'mieć ból gardła/mieć chore gardło', 'Mam ból gardła.', 'I have a sore throat.'),
('brainy6', 'mieć ból ucha', 'Mam ból ucha.', 'I have earache.'),
('brainy6', 'mieć grypę', 'Mam grypę i zostaję w łóżku.', 'I have flu and I am staying in bed.'),
('brainy6', 'mieć ból brzucha', 'Mam ból brzucha.', 'I have stomach ache.'),
('brainy6', 'mieć ból zęba', 'Mam ból zęba.', 'I have toothache.'),
('brainy6', 'zadzwonić do lekarza', 'Mama zadzwoniła do lekarza.', 'Mum called a doctor.'),
('brainy6', 'zadzwonić po/wezwać karetkę', 'Tata zadzwonił po karetkę.', 'Dad called an ambulance.'),
('brainy6', 'pojechać na ostry dyżur', 'Pojechaliśmy na ostry dyżur.', 'We went to A&E.'),
('brainy6', 'Idź do przychodni lekarskiej / ośrodka zdrowia', 'Idź do przychodni lekarskiej.', 'Go to the health centre.'),
('brainy6', 'zostać w łóżku', 'Powinieneś zostać w łóżku.', 'You should stay in bed.'),
('brainy6', 'zmierzyć temperaturę', 'Mama zmierzyła mi temperaturę.', 'Mum took my temperature.'),
('brainy6', 'brać leki', 'Biorę leki na ból głowy.', 'I take medicine for a headache.'),
('brainy6', 'złamać nogę', 'Złamałem nogę na nartach.', 'I broke my leg skiing.'),
('brainy6', 'posiniaczyć stopę', 'Posiniaczyłem sobie stopę.', 'I bruised my foot.'),
('brainy6', 'oparzyć rękę', 'Oparzyłem sobie rękę.', 'I burned my hand.'),
('brainy6', 'zaciąć się w palec', 'Zaciąłem się w palec.', 'I cut my finger.'),
('brainy6', 'zranić się w głowę', 'Zraniłem się w głowę.', 'I hurt my head.'),
('brainy6', 'zadrapać kolano', 'Zadrapałem kolano.', 'I scratched my knee.'),
('brainy6', 'Jak to zrobiłeś?', 'Jak to zrobiłeś?', 'How did you do that?'),
('brainy6', 'Jak to się teraz czujesz?', 'Jak to się teraz czujesz?', 'How does it feel now?'),
('brainy6', 'Co Ci się stało?', 'Co Ci się stało?', 'What happened to you?'),
('brainy6', 'Kiedy to się stało?', 'Kiedy to się stało?', 'When did it happen?'),
('brainy6', 'To wcale nie boli.', 'To wcale nie boli.', 'It does not hurt at all.'),
('brainy6', 'Nie boli aż tak bardzo.', 'Nie boli aż tak bardzo.', 'It does not hurt much.'),
('brainy6', 'Bardzo boli.', 'Bardzo boli.', 'It hurts a lot.'),
('brainy6', 'Teraz jest lepiej.', 'Teraz jest lepiej.', 'It is better now.'),
('brainy6', 'Nie jest tak źle.', 'Nie jest tak źle.', 'It is not too bad.'),
('brainy6', 'Pośpiesz się!', 'Pośpiesz się!', 'Hurry up!'),
('brainy6', 'Moja noga boli strasznie.', 'Moja noga boli strasznie.', 'My leg hurts like mad.'),
('brainy6', 'Jesteś w tarapatach.', 'Jesteś w tarapatach.', 'You are in the soup.'),
('brainy6', 'Wczoraj złamałem nogę.', 'Wczoraj złamałem nogę.', 'I broke my leg yesterday.'),
('brainy6', 'Tom nie złamał nogi wczoraj.', 'Tom nie złamał nogi wczoraj.', 'Tom did not break his leg yesterday.'),
('brainy6', 'Czy Tom złamał wczoraj nogę?', 'Czy Tom złamał wczoraj nogę?', 'Did Tom break his leg yesterday?'),
('brainy6', 'Gdzie Tom złamał nogę?', 'Gdzie Tom złamał nogę?', 'Where did Tom break his leg?'),
('brainy6', 'Kiedy Betty zadrapała kolano?', 'Kiedy Betty zadrapała kolano?', 'When did Betty scratch her knee?'),
('brainy6', 'Co oglądałeś wczoraj?', 'Co oglądałeś wczoraj?', 'What did you watch yesterday?'),
('brainy6', 'Dlaczego poszedłeś do szkoły w sobotę?', 'Dlaczego poszedłeś do szkoły w sobotę?', 'Why did you go to school on Saturday?'),
('brainy6', 'Betty miała wczoraj gorączkę.', 'Betty miała wczoraj gorączkę.', 'Betty had a fever yesterday.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 7 — Computers, emotions, present perfect (59)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'komputer stacjonarny', 'Mam komputer stacjonarny w pokoju.', 'I have a desktop computer in my room.'),
('brainy6', 'kontroler gry', 'Mam nowy kontroler gry.', 'I have a new game controller.'),
('brainy6', 'wkład drukujący, toner', 'Drukarka potrzebuje nowego wkładu drukującego.', 'The printer needs a new ink cartridge.'),
('brainy6', 'klawiatura', 'Klawiatura jest na biurku.', 'The keyboard is on the desk.'),
('brainy6', 'laptop', 'Robię lekcje na laptopie.', 'I do homework on my laptop.'),
('brainy6', 'monitor', 'Mam duży monitor.', 'I have a big monitor.'),
('brainy6', 'mysz komputerowa, myszka', 'Myszka nie działa.', 'The mouse is not working.'),
('brainy6', 'drukarka', 'Drukarka drukuje zdjęcia.', 'The printer is printing photos.'),
('brainy6', 'panel dotykowy', 'Mój laptop ma panel dotykowy.', 'My laptop has a touchpad.'),
('brainy6', 'ekran dotykowy', 'Telefon ma ekran dotykowy.', 'The phone has a touch screen.'),
('brainy6', 'kliknąć', 'Kliknij na link.', 'Click on the link.'),
('brainy6', 'przycisnąć klawisz', 'Przyciśnij klawisz Enter.', 'Press the Enter key.'),
('brainy6', 'przeciągnąć ekran', 'Przeciągnij ekran w lewo.', 'Swipe the screen to the left.'),
('brainy6', 'stuknąć (tapnąć)', 'Stuknij ikonę aplikacji.', 'Tap the app icon.'),
('brainy6', 'wpisywać swoje imię', 'Wpisuję swoje imię.', 'I am typing my name.'),
('brainy6', 'sprawdzić', 'Sprawdzam mejle codziennie.', 'I check my emails every day.'),
('brainy6', 'kasować', 'Skasowałem stary plik.', 'I deleted the old file.'),
('brainy6', 'wyszukiwać (np. w internecie)', 'Wyszukuję informacje w internecie.', 'I do searches on the internet.'),
('brainy6', 'pobierać filmy', 'Pobieram filmy z internetu.', 'I download videos from the internet.'),
('brainy6', 'wpisać hasło', 'Wpisz hasło.', 'Enter your password.'),
('brainy6', 'zapomnieć hasło', 'Zapomniałem hasła.', 'I forgot my password.'),
('brainy6', 'przesłać e-mail dalej', 'Przesłałem e-mail dalej.', 'I forwarded the email.'),
('brainy6', 'instalować aplikacje', 'Instaluję nowe aplikacje.', 'I am installing new apps.'),
('brainy6', 'zalogować się', 'Loguję się do systemu.', 'I am logging in to the system.'),
('brainy6', 'wylogować się', 'Wyloguj się przed wyjściem.', 'Log out before you leave.'),
('brainy6', 'zrobić kopię zapasową plików', 'Robię kopię zapasową plików.', 'I am making backups of my files.'),
('brainy6', 'zapisać swoją pracę', 'Zapisz swoją pracę.', 'Save your work.'),
('brainy6', 'wysyłać', 'Wysyłam mejla do mamy.', 'I am sending an email to mum.'),
('brainy6', 'przesyłać filmy', 'Przesyłam filmy na YouTube.', 'I am uploading videos to YouTube.'),
('brainy6', 'zły', 'Mój brat jest zły.', 'My brother is angry.'),
('brainy6', 'radosny', 'Jestem radosny dzisiaj.', 'I am cheerful today.'),
('brainy6', 'speszony, zmieszany', 'Jestem zmieszany pytaniem.', 'I am confused by the question.'),
('brainy6', 'przygnębiony, na dół', 'Jestem przygnębiony.', 'I feel down.'),
('brainy6', 'głodny', 'Jestem głodny.', 'I am hungry.'),
('brainy6', 'zadowolony', 'Jestem zadowolony z oceny.', 'I am pleased with the mark.'),
('brainy6', 'spragniony', 'Jestem spragniony.', 'I am thirsty.'),
('brainy6', 'zmartwiony', 'Mama jest zmartwiona.', 'Mum is worried.'),
('brainy6', 'Gratulacje', 'Gratulacje, wygrałeś!', 'Congratulations, you won!'),
('brainy6', 'Nie martw się. Możemy to rozwiązać.', 'Nie martw się. Możemy to rozwiązać.', 'Do not worry. We can sort it out.'),
('brainy6', 'Czuję się...', 'Czuję się świetnie.', 'I am feeling great.'),
('brainy6', 'O jej', 'O jej, co się stało?', 'Oh dear, what happened?'),
('brainy6', 'Biedny!', 'Biedny!', 'Poor you!'),
('brainy6', 'Szkoda!', 'Szkoda!', 'That is a pity!'),
('brainy6', 'To dobra wiadomość!', 'To dobra wiadomość!', 'That is good news!'),
('brainy6', 'To wspaniale!', 'To wspaniale!', 'That is great!'),
('brainy6', 'Dobra robota!', 'Dobra robota!', 'Well done!'),
('brainy6', 'Co słychać?', 'Co słychać?', 'What is up?'),
('brainy6', 'Tak przypuszczam.', 'Tak przypuszczam.', 'I suppose so.'),
('brainy6', 'Rozpocznijmy nowy rozdział w życiu.', 'Rozpocznijmy nowy rozdział w życiu.', 'Let us turn over a new leaf.'),
('brainy6', 'Wpadliśmy w niezłe tarapaty.', 'Wpadliśmy w niezłe tarapaty.', 'We got into a right mess.'),
('brainy6', 'Grałem dzisiaj w tę grę.', 'Grałem dzisiaj w tę grę.', 'I have played this game today.'),
('brainy6', 'Sprawdziłeś to dzisiaj.', 'Sprawdziłeś to dzisiaj.', 'You have checked it today.'),
('brainy6', 'Tom zalogował się dzisiaj.', 'Tom zalogował się dzisiaj.', 'Tom has logged in today.'),
('brainy6', 'Bob nie wysłał dzisiaj e-maila.', 'Bob nie wysłał dzisiaj e-maila.', 'Bob has not sent an email today.'),
('brainy6', 'Betty i Tom nie przesłali dzisiaj filmów.', 'Betty i Tom nie przesłali dzisiaj filmów.', 'Betty and Tom have not uploaded videos today.'),
('brainy6', 'Czy Betty grała dzisiaj w Minecraft?', 'Czy Betty grała dzisiaj w Minecraft?', 'Has Betty played Minecraft today?'),
('brainy6', 'Czy Tom wpisał swoje imię?', 'Czy Tom wpisał swoje imię?', 'Has Tom typed his name?'),
('brainy6', 'Czy Betty i Tom wylogowali się?', 'Czy Betty i Tom wylogowali się?', 'Have Betty and Tom logged out?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 8 — Activities, ecology, present perfect vs past simple (52)
-- ═══════════════════════════════════════════════════════════
('brainy6', 'wspiąć się na górę', 'Wspięliśmy się na górę.', 'We climbed a mountain.'),
('brainy6', 'skoczyć ze spadochronem', 'Tata skoczył ze spadochronem.', 'Dad did a skydive.'),
('brainy6', 'zwiedzać jaskinię', 'Zwiedzaliśmy jaskinię.', 'We explored a cave.'),
('brainy6', 'iść na ryby', 'Idziemy na ryby w sobotę.', 'We are going fishing on Saturday.'),
('brainy6', 'nurkować z butlą/akwalungiem', 'Lubię nurkować z akwalungiem.', 'I like to go scuba diving.'),
('brainy6', 'obserwować wieloryby', 'Obserwowaliśmy wieloryby na łodzi.', 'We went whale watching on the boat.'),
('brainy6', 'jeździć quadem', 'Jeździłem quadem na wakacjach.', 'I rode a quad bike on holiday.'),
('brainy6', 'spać pod namiotem', 'Spaliśmy pod namiotem.', 'We slept in a tent.'),
('brainy6', 'nurkować z rurką', 'Nurkowałem z rurką w morzu.', 'I went snorkelling in the sea.'),
('brainy6', 'nocować w przyczepie kempingowej', 'Nocowaliśmy w przyczepie kempingowej.', 'We stayed in a caravan.'),
('brainy6', 'pływać z delfinami', 'Pływałem z delfinami.', 'I swam with dolphins.'),
('brainy6', 'posprzątać plażę', 'Posprzątaliśmy plażę.', 'We did a beach clean-up.'),
('brainy6', 'posprzątać park', 'Posprzątaliśmy park.', 'We did a park clean-up.'),
('brainy6', 'posprzątać rzekę', 'Posprzątaliśmy rzekę.', 'We did a river clean-up.'),
('brainy6', 'posprzątać ulicę', 'Posprzątaliśmy ulicę.', 'We did a street clean-up.'),
('brainy6', 'przetwarzać/segregować odpady spożywcze', 'Segreguję odpady spożywcze.', 'I recycle food waste.'),
('brainy6', 'przetwarzać/segregować szkło', 'Segreguję szkło.', 'I recycle glass.'),
('brainy6', 'przetwarzać/segregować papier', 'Segreguję papier.', 'I recycle paper.'),
('brainy6', 'przetwarzać/segregować plastik', 'Segreguję plastik.', 'I recycle plastic.'),
('brainy6', 'przetwarzać/segregować metalowe puszki', 'Segreguję metalowe puszki.', 'I recycle tin cans.'),
('brainy6', 'oszczędzać prąd', 'Oszczędzam prąd, wyłączając światło.', 'I save electricity by turning off the lights.'),
('brainy6', 'oszczędzać gaz', 'Oszczędzamy gaz w kuchni.', 'We save gas in the kitchen.'),
('brainy6', 'oszczędzać benzynę/paliwo', 'Tata oszczędza benzynę.', 'Dad saves petrol.'),
('brainy6', 'oszczędzać wodę', 'Oszczędzam wodę zakręcając kran.', 'I save water by turning off the tap.'),
('brainy6', 'Nie podoba mi się to', 'Nie podoba mi się to.', 'I do not like the sound of that.'),
('brainy6', 'Pasuje mi to', 'Pasuje mi to.', 'I will go with that.'),
('brainy6', 'Nie jestem przekonany', 'Nie jestem przekonany.', 'I am not sure.'),
('brainy6', 'Zróbmy to!', 'Zróbmy to!', 'Let us do it!'),
('brainy6', 'To brzmi dobrze', 'To brzmi dobrze.', 'That sounds good.'),
('brainy6', 'To nie wypali', 'To nie wypali.', 'That will not work.'),
('brainy6', 'Dobry pomysł', 'Dobry pomysł.', 'That is a good idea.'),
('brainy6', 'Może byśmy?', 'Może byśmy poszli do kina?', 'Why do not we go to the cinema?'),
('brainy6', 'Jestem kłębkiem nerwów', 'Jestem kłębkiem nerwów przed testem.', 'I am a bundle of nerves before the test.'),
('brainy6', 'Hura! na cześć', 'Hura na cześć drużyny!', 'Hooray for the team!'),
('brainy6', 'Twoja kolej', 'Twoja kolej.', 'It is your turn.'),
('brainy6', 'Nigdy nie jadłem łososia.', 'Nigdy nie jadłem łososia.', 'I have never eaten salmon.'),
('brainy6', 'Tom nigdy nie oglądał tego filmu.', 'Tom nigdy nie oglądał tego filmu.', 'Tom has never watched this film.'),
('brainy6', 'Czy byłeś kiedyś w Wielkiej Brytanii?', 'Czy byłeś kiedyś w Wielkiej Brytanii?', 'Have you ever been to the UK?'),
('brainy6', 'Czy Michael kiedykolwiek jadł sushi?', 'Czy Michael kiedykolwiek jadł sushi?', 'Has Michael ever eaten sushi?'),
('brainy6', 'Właśnie złamałem nogę.', 'Właśnie złamałem nogę.', 'I have just broken my leg.'),
('brainy6', 'Właśnie odrobił pracę domową.', 'Właśnie odrobił pracę domową.', 'He has just done his homework.'),
('brainy6', 'pięć dni temu', 'Wróciłem z wakacji pięć dni temu.', 'I came back from holiday five days ago.'),
('brainy6', 'wczoraj', 'Wczoraj grałem w piłkę.', 'I played football yesterday.'),
('brainy6', 'zeszły tydzień', 'Zeszły tydzień był ciekawy.', 'Last week was interesting.'),
('brainy6', 'w czerwcu', 'W czerwcu kończy się szkoła.', 'School ends in June.'),
('brainy6', 'w 2010', 'Urodziłem się w 2010.', 'I was born in 2010.'),
('brainy6', 'Poszedłem/Poszłam wczoraj do kina.', 'Poszedłem wczoraj do kina.', 'I went to the cinema yesterday.'),
('brainy6', 'Anna złamała rękę pięć dni temu.', 'Anna złamała rękę pięć dni temu.', 'Anna broke her arm five days ago.'),
('brainy6', 'Allan grał w tenisa w zeszłym tygodniu.', 'Allan grał w tenisa w zeszłym tygodniu.', 'Allan played tennis last week.'),
('brainy6', 'Bob nie zjadł jabłka w grudniu.', 'Bob nie zjadł jabłka w grudniu.', 'Bob did not eat an apple in December.'),
('brainy6', 'Czy oni obejrzeli ten film w 2015 roku?', 'Czy oni obejrzeli ten film w 2015 roku?', 'Did they watch that film in 2015?')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Brainy 6: 502 unikalnych zdan zaktualizowanych/dodanych w word_sentences (502 wpisow w data.js, brak duplikatow).';
END $$;
