-- ═══════════════════════════════════════════════════════════
-- Fix sentences: TOGETHER 4 (klasa 4, szkola podstawowa)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 427 unikalnych slowek z Together 4 (Macmillan).
--
-- Statystyki:
--   - 428 wpisow w data.js (8 unitow)
--   - 1 duplikat synonimu word_pl ('Co sie stalo?' — Unit 4 'What is wrong?'
--     + Unit 6 'What''s the matter?') — pominiete w SQL, UPSERT trzyma
--     jedna wartosc (synonim, brak straty informacji).
--   - 427 unikalnych zdan w word_sentences
--
-- Tematy unitow:
--   Unit 1 (74): liczebniki + dni + narodowosci + kraje + przedstawienie
--   Unit 2 (36): ubrania + przymiotniki + osobowosc + godziny
--   Unit 3 (50): rzeczy + meble + przyimki + zaimki dzierzawcze + zakupy
--   Unit 4 (58): twarz + wlosy + rodzina + have got
--   Unit 5 (55): jedzenie + warzywa + dialog w restauracji + there is/are
--   Unit 6 (55): sport + hobby + can/cannot
--   Unit 7 (50): rutyna + sport + present simple
--   Unit 8 (49): wakacje + miejsca + present continuous + droga
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — Numbers, nationalities, countries (74)
-- ═══════════════════════════════════════════════════════════
('together4', '1', 'Mam jednego brata.', 'I have one brother.'),
('together4', '2', 'Mam dwa koty.', 'I have two cats.'),
('together4', '3', 'Mam trzy książki.', 'I have three books.'),
('together4', '4', 'Stół ma cztery nogi.', 'A table has four legs.'),
('together4', '5', 'Mam pięć palców.', 'I have five fingers.'),
('together4', '6', 'W klasie jest sześć dziewczynek.', 'There are six girls in the class.'),
('together4', '7', 'Tydzień ma siedem dni.', 'A week has seven days.'),
('together4', '8', 'Pająk ma osiem nóg.', 'A spider has eight legs.'),
('together4', '9', 'Mam dziewięć kredek.', 'I have nine crayons.'),
('together4', '10', 'Mam dziesięć palców.', 'I have ten fingers.'),
('together4', '11', 'W klasie jest jedenaście chłopców.', 'There are eleven boys in the class.'),
('together4', '12', 'Rok ma dwanaście miesięcy.', 'A year has twelve months.'),
('together4', '13', 'Trzynaście to liczba pechowa.', 'Thirteen is an unlucky number.'),
('together4', '14', 'Walentynki są czternastego lutego.', 'Valentine''s Day is on the fourteenth of February.'),
('together4', '15', 'Mam piętnaście minut wolnego.', 'I have fifteen minutes free.'),
('together4', '16', 'Lekcja kończy się po szesnastu minutach.', 'The lesson ends after sixteen minutes.'),
('together4', '17', 'Mój brat ma siedemnaście lat.', 'My brother is seventeen years old.'),
('together4', '18', 'Pełnoletność to osiemnaście lat.', 'You become an adult at eighteen.'),
('together4', '19', 'Moja siostra ma dziewiętnaście lat.', 'My sister is nineteen years old.'),
('together4', '20', 'W klasie jest dwadzieścia osób.', 'There are twenty people in the class.'),
('together4', '30', 'Tata ma trzydzieści lat.', 'Dad is thirty years old.'),
('together4', '40', 'Książka ma czterdzieści stron.', 'The book has forty pages.'),
('together4', '50', 'Pięćdziesiąt to połowa stu.', 'Fifty is half of a hundred.'),
('together4', '60', 'Godzina ma sześćdziesiąt minut.', 'An hour has sixty minutes.'),
('together4', '70', 'Babcia ma siedemdziesiąt lat.', 'Grandma is seventy years old.'),
('together4', '80', 'Dziadek ma osiemdziesiąt lat.', 'Grandad is eighty years old.'),
('together4', '90', 'Liczę do dziewięćdziesięciu.', 'I count to ninety.'),
('together4', '100', 'Sto to okrągła liczba.', 'One hundred is a round number.'),
('together4', 'poniedziałek', 'W poniedziałek mam matematykę.', 'I have maths on Monday.'),
('together4', 'wtorek', 'We wtorek gram w piłkę.', 'I play football on Tuesday.'),
('together4', 'środa', 'W środę mam plastykę.', 'I have art on Wednesday.'),
('together4', 'czwartek', 'W czwartek mam wf.', 'I have PE on Thursday.'),
('together4', 'piątek', 'W piątek idę do kina.', 'I go to the cinema on Friday.'),
('together4', 'sobota', 'W sobotę odwiedzam babcię.', 'I visit grandma on Saturday.'),
('together4', 'niedziela', 'W niedzielę odpoczywam.', 'I rest on Sunday.'),
('together4', 'argentyński, Argentyńczyk/Argentynka', 'Lubię argentyńskie tango.', 'I like Argentinian tango.'),
('together4', 'amerykański, Amerykanin/Amerykanka', 'On ma amerykański paszport.', 'He has an American passport.'),
('together4', 'australijski, Australijczyk/Australijka', 'Australijski miś koala jest słodki.', 'The Australian koala bear is cute.'),
('together4', 'brazylijski, Brazylijczyk/Brazylijka', 'Brazylijska piłka nożna jest słynna.', 'Brazilian football is famous.'),
('together4', 'brytyjski, Brytyjczyk/Brytyjka', 'On jest brytyjskim aktorem.', 'He is a British actor.'),
('together4', 'chiński, Chińczyk/Chinka', 'Uczę się chińskiego.', 'I am learning Chinese.'),
('together4', 'francuski, Francuz/Francuzka', 'Mówię trochę po francusku.', 'I speak a little French.'),
('together4', 'polski, Polak/Polka', 'Jestem Polakiem.', 'I am Polish.'),
('together4', 'hiszpański, Hiszpan/Hiszpanka', 'Lubię hiszpańską muzykę.', 'I like Spanish music.'),
('together4', 'turecki, Turek/Turczynka', 'Lubię turecką herbatę.', 'I like Turkish tea.'),
('together4', 'Argentyna', 'Argentyna leży w Ameryce Południowej.', 'Argentina is in South America.'),
('together4', 'Australia', 'W Australii żyją kangury.', 'Kangaroos live in Australia.'),
('together4', 'Brazylia', 'Brazylia jest dużym krajem.', 'Brazil is a big country.'),
('together4', 'Chiny', 'Chiny mają najwięcej mieszkańców.', 'China has the most people.'),
('together4', 'Francja', 'Paryż jest we Francji.', 'Paris is in France.'),
('together4', 'Polska', 'Mieszkam w Polsce.', 'I live in Poland.'),
('together4', 'Hiszpania', 'Hiszpania jest ciepła latem.', 'Spain is warm in summer.'),
('together4', 'Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej', 'Wielka Brytania ma cztery kraje.', 'The UK has four countries.'),
('together4', 'Turcja', 'Turcja leży między Europą a Azją.', 'Turkey is between Europe and Asia.'),
('together4', 'w kawiarni', 'Spotykamy się w kawiarni.', 'We are meeting at a cafe.'),
('together4', 'na imprezie', 'Bawię się na imprezie.', 'I am having fun at a party.'),
('together4', 'na letnim obozie', 'Latem jestem na letnim obozie.', 'In summer I am at a summer camp.'),
('together4', 'w domu', 'Mama jest w domu.', 'Mum is at home.'),
('together4', 'w szkole', 'Jestem w szkole o ósmej.', 'I am at school at eight.'),
('together4', 'w ogrodzie', 'Pies jest w ogrodzie.', 'The dog is in the garden.'),
('together4', 'w parku', 'Bawię się w parku.', 'I play in the park.'),
('together4', 'na wakacjach', 'Latem jesteśmy na wakacjach.', 'In summer we are on holiday.'),
('together4', 'Jaki bałagan!', 'Jaki bałagan w pokoju!', 'What a mess in the room!'),
('together4', 'Nie martw się. Wszystko w porządku.', 'Nie martw się. Wszystko w porządku.', 'Do not worry. It is OK.'),
('together4', 'Jesteś wspaniały!', 'Jesteś wspaniały!', 'You are amazing!'),
('together4', 'Jak się nazywasz?', 'Jak się nazywasz?', 'What is your name?'),
('together4', 'Nazywam się Tom.', 'Nazywam się Tom.', 'My name is Tom.'),
('together4', 'Jak przeliterujesz (Martin)?', 'Jak przeliterujesz Martin?', 'How do you spell Martin?'),
('together4', 'Skąd pochodzisz?', 'Skąd pochodzisz?', 'Where are you from?'),
('together4', 'Jestem z (Polski)', 'Jestem z Polski.', 'I am from Poland.'),
('together4', 'Jaka jest Twoja narodowość?', 'Jaka jest Twoja narodowość?', 'What is your nationality?'),
('together4', 'Jestem (Polakiem).', 'Jestem Polakiem.', 'I am Polish.'),
('together4', 'Ile masz lat?', 'Ile masz lat?', 'How old are you?'),
('together4', 'Mam (10) lat.', 'Mam dziesięć lat.', 'I am ten.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — Clothes, personality, time (36)
-- ═══════════════════════════════════════════════════════════
('together4', 'czapka (z daszkiem)', 'Noszę czerwoną czapkę.', 'I am wearing a red cap.'),
('together4', 'sukienka', 'Moja sukienka jest niebieska.', 'My dress is blue.'),
('together4', 'bluza z kapturem', 'Lubię moją bluzę z kapturem.', 'I like my hoodie.'),
('together4', 'kurtka, marynarka', 'Mam nową kurtkę.', 'I have a new jacket.'),
('together4', 'dżinsy', 'Noszę dżinsy do szkoły.', 'I wear jeans to school.'),
('together4', 'sweter', 'Mój sweter jest ciepły.', 'My jumper is warm.'),
('together4', 'koszula', 'Tata nosi białą koszulę.', 'Dad is wearing a white shirt.'),
('together4', 'buty', 'Moje buty są nowe.', 'My shoes are new.'),
('together4', 'szorty, krótkie spodenki', 'Latem noszę szorty.', 'I wear shorts in summer.'),
('together4', 'spódnica', 'Anna ma czerwoną spódnicę.', 'Anna has a red skirt.'),
('together4', 'skarpetki', 'Mam wełniane skarpetki.', 'I have wool socks.'),
('together4', 'trampki', 'Mam nowe trampki.', 'I have new trainers.'),
('together4', 'spodnie', 'Te spodnie są za małe.', 'These trousers are too small.'),
('together4', 'koszulka', 'Noszę żółtą koszulkę.', 'I am wearing a yellow T-shirt.'),
('together4', 'wygodny', 'Moje buty są wygodne.', 'My shoes are comfortable.'),
('together4', 'elegancki', 'Tata wygląda elegancko.', 'Dad looks smart.'),
('together4', 'sportowy, wysportowany', 'Mój brat jest wysportowany.', 'My brother is sporty.'),
('together4', 'ciepły', 'Mam ciepły płaszcz.', 'I have a warm coat.'),
('together4', 'bystry, inteligentny, mądry', 'Moja siostra jest mądra.', 'My sister is clever.'),
('together4', 'przyjazny, sympatyczny', 'Mój pies jest przyjazny.', 'My dog is friendly.'),
('together4', 'zabawny', 'Mój kuzyn jest zabawny.', 'My cousin is funny.'),
('together4', 'pomocny, uczynny', 'Anna jest pomocna.', 'Anna is helpful.'),
('together4', 'miły, uprzejmy', 'Nasza nauczycielka jest miła.', 'Our teacher is kind.'),
('together4', 'cichy, skromny', 'Klasa jest cicha.', 'The class is quiet.'),
('together4', 'nieśmiały', 'Mój brat jest nieśmiały.', 'My brother is shy.'),
('together4', 'Nie jestem gotowy/gotowa!', 'Nie jestem gotowy! Poczekaj!', 'I am not ready! Wait!'),
('together4', 'Chwileczkę!', 'Chwileczkę! Zaraz wracam.', 'Just a minute! I will be back.'),
('together4', 'Bardzo proszę (gdy coś komuś podajemy)', 'Bardzo proszę, oto twoja książka.', 'Here you are, your book.'),
('together4', 'Kwadrans po (pierwszej)', 'Jest kwadrans po pierwszej.', 'It is quarter past one.'),
('together4', 'W pół do drugiej. (Trzydzieści po pierwszej)', 'Jest wpół do drugiej.', 'It is half past one.'),
('together4', '(Dwadzieścia) po (pierwszej)', 'Jest dwadzieścia po pierwszej.', 'It is twenty past one.'),
('together4', '(Dwadzieścia) do (drugiej)', 'Jest dwadzieścia do drugiej.', 'It is twenty to two.'),
('together4', 'Która jest (teraz) godzina?', 'Która jest teraz godzina?', 'What time is it now?'),
('together4', 'O której godzinie jest (film)?', 'O której godzinie jest film?', 'What time is the film?'),
('together4', 'Jest o (pierwszej).', 'Jest o pierwszej.', 'It is at one o''clock.'),
('together4', 'Jest (pierwsza).', 'Jest pierwsza.', 'It is one o''clock.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 3 — Things, furniture, prepositions, shopping (50)
-- ═══════════════════════════════════════════════════════════
('together4', 'gra planszowa', 'Lubię grę planszową.', 'I like the board game.'),
('together4', 'elektryczna szczoteczka do zębów', 'Mam elektryczną szczoteczkę do zębów.', 'I have an electric toothbrush.'),
('together4', 'konsola do gier', 'Mam nową konsolę do gier.', 'I have a new games console.'),
('together4', 'gitara', 'Gram na gitarze.', 'I play the guitar.'),
('together4', 'laptop', 'Robię lekcje na laptopie.', 'I do homework on my laptop.'),
('together4', 'deskorolka', 'Lubię moją deskorolkę.', 'I like my skateboard.'),
('together4', 'ładowarka', 'Potrzebuję ładowarki.', 'I need a charger.'),
('together4', 'szczotka do włosów', 'Mam różową szczotkę do włosów.', 'I have a pink hairbrush.'),
('together4', 'kask', 'Załóż kask na rower.', 'Put on a helmet for the bike.'),
('together4', 'szkicownik', 'Rysuję w szkicowniku.', 'I draw in my sketchbook.'),
('together4', 'smartwatch', 'Mam nowy smartwatch.', 'I have a new smartwatch.'),
('together4', 'tablet', 'Czytam na tablecie.', 'I read on my tablet.'),
('together4', 'butelka na wodę', 'Wezmę butelkę na wodę.', 'I will take my water bottle.'),
('together4', 'fotel', 'Tata siedzi w fotelu.', 'Dad is sitting in the armchair.'),
('together4', 'łóżko', 'Moje łóżko jest miękkie.', 'My bed is soft.'),
('together4', 'regał na książki', 'Moje książki są na regale.', 'My books are on the bookcase.'),
('together4', 'szafka', 'Talerze są w szafce.', 'The plates are in the cupboard.'),
('together4', 'lampa', 'Lampa jest na biurku.', 'The lamp is on the desk.'),
('together4', 'lustro', 'Lustro jest w łazience.', 'The mirror is in the bathroom.'),
('together4', 'za', 'Kot jest za sofą.', 'The cat is behind the sofa.'),
('together4', 'w', 'Książka jest w plecaku.', 'The book is in the backpack.'),
('together4', 'przed', 'Auto jest przed domem.', 'The car is in front of the house.'),
('together4', 'obok', 'Lampa jest obok łóżka.', 'The lamp is next to the bed.'),
('together4', 'na', 'Kot jest na krześle.', 'The cat is on the chair.'),
('together4', 'pod', 'Pies jest pod stołem.', 'The dog is under the table.'),
('together4', 'Pomóż mi, proszę.', 'Pomóż mi, proszę.', 'Help me, please.'),
('together4', 'Co się dzieje?', 'Co się dzieje?', 'What is happening?'),
('together4', 'To moja wina', 'To moja wina.', 'It is my fault.'),
('together4', 'Cóż za świetny pomysł!', 'Cóż za świetny pomysł!', 'What a great idea!'),
('together4', 'Ile kosztuje (ta deskorolka)?', 'Ile kosztuje ta deskorolka?', 'How much is this skateboard?'),
('together4', 'Ile to kosztuje?', 'Ile to kosztuje?', 'How much is it?'),
('together4', 'Poproszę (deskorolkę i kask).', 'Poproszę deskorolkę i kask.', 'Can I have the skateboard and the helmet, please?'),
('together4', 'To będzie (9 funtów i 50 centów)', 'To będzie 9 funtów i 50 centów.', 'That is 9 pounds 50.'),
('together4', 'Proszę, (10 funtów)', 'Proszę, 10 funtów.', 'Here is 10 pounds.'),
('together4', 'Proszę, (50 pensów) reszty.', 'Proszę, 50 pensów reszty.', 'That is 50p change.'),
('together4', 'Czy coś jeszcze?', 'Czy coś jeszcze?', 'Anything else?'),
('together4', 'Nie, dziękuję!', 'Nie, dziękuję!', 'No, thank you!'),
('together4', 'mój', 'To mój zeszyt.', 'This is my notebook.'),
('together4', 'twój, wasz', 'To twój pies.', 'This is your dog.'),
('together4', 'jego', 'To jego rower.', 'This is his bike.'),
('together4', 'jej', 'To jej książka.', 'This is her book.'),
('together4', 'jego, jej (rzecz, zwierzę, roślina)', 'Pies pije swoje mleko.', 'The dog is drinking its milk.'),
('together4', 'nasz', 'To nasz dom.', 'This is our house.'),
('together4', 'ich', 'To ich kot.', 'This is their cat.'),
('together4', 'Czyja to deskorolka?', 'Czyja to deskorolka?', 'Whose skateboard is it?'),
('together4', 'Czyje to łóżko?', 'Czyje to łóżko?', 'Whose bed is it?'),
('together4', 'to, ta, ten (liczba pojedyncza, blisko)', 'To jabłko jest słodkie.', 'This apple is sweet.'),
('together4', 'to, tamto, tamta, tamten (liczba pojedyncza, daleko)', 'Tamto jabłko jest zielone.', 'That apple is green.'),
('together4', 'to, te, ci (liczba mnoga, blisko)', 'Te książki są moje.', 'These books are mine.'),
('together4', 'to, tamte, tamci (liczba mnoga, daleko)', 'Tamte książki są nowe.', 'Those books are new.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 4 — Face, family, have got (58, 1 dup pominiety)
-- ═══════════════════════════════════════════════════════════
('together4', 'usta', 'Otwórz usta.', 'Open your mouth.'),
('together4', 'nos', 'Mam mały nos.', 'I have a small nose.'),
('together4', 'zęby', 'Myję zęby dwa razy dziennie.', 'I brush my teeth twice a day.'),
('together4', 'blondynka', 'Anna jest blondynką.', 'Anna is blonde.'),
('together4', 'kręcone', 'Mam kręcone włosy.', 'I have curly hair.'),
('together4', 'ciemny', 'Tata ma ciemne włosy.', 'Dad has dark hair.'),
('together4', 'długi', 'Anna ma długie włosy.', 'Anna has long hair.'),
('together4', 'rude włosy', 'Moja siostra ma rude włosy.', 'My sister has red hair.'),
('together4', 'niski/krótki', 'Mam krótkie włosy.', 'I have short hair.'),
('together4', 'sterczące włosy', 'On ma sterczące włosy.', 'He has spiky hair.'),
('together4', 'proste', 'Mam proste włosy.', 'I have straight hair.'),
('together4', 'falowane', 'Mama ma falowane włosy.', 'Mum has wavy hair.'),
('together4', 'ciotka', 'Moja ciotka mieszka w Krakowie.', 'My aunt lives in Krakow.'),
('together4', 'brat', 'Mój brat ma 10 lat.', 'My brother is 10 years old.'),
('together4', 'kuzyn', 'Mój kuzyn mieszka w Gdańsku.', 'My cousin lives in Gdansk.'),
('together4', 'ojciec', 'Mój ojciec jest lekarzem.', 'My father is a doctor.'),
('together4', 'dziadek', 'Mój dziadek lubi szachy.', 'My grandfather likes chess.'),
('together4', 'dziadzio', 'Mój dziadzio ma 75 lat.', 'My granddad is 75 years old.'),
('together4', 'babcia', 'Moja babcia piecze ciasta.', 'My grandmother bakes cakes.'),
('together4', 'babunia', 'Moja babunia opowiada bajki.', 'My granny tells stories.'),
('together4', 'matka', 'Moja matka jest nauczycielką.', 'My mother is a teacher.'),
('together4', 'jedynak', 'Jestem jedynakiem.', 'I am an only child.'),
('together4', 'rodzice', 'Moi rodzice pracują razem.', 'My parents work together.'),
('together4', 'siostra', 'Moja siostra ma 8 lat.', 'My sister is 8 years old.'),
('together4', 'wujek', 'Mój wujek pracuje w fabryce.', 'My uncle works in a factory.'),
('together4', 'szwagierka', 'Moja szwagierka jest miła.', 'My sister-in-law is nice.'),
('together4', 'Co się stało?', 'Co się stało? Wszystko w porządku?', 'What is wrong? Are you OK?'),
('together4', 'Nie ma mowy! / no coś ty', 'Nie ma mowy! Nie zrobię tego!', 'No way! I will not do it!'),
('together4', 'Witaj na mojej imprezie!', 'Witaj na mojej imprezie!', 'Welcome to my party!'),
('together4', 'Dziękuję za zaproszenie', 'Dziękuję za zaproszenie.', 'Thanks for inviting me.'),
('together4', 'To jest mój...', 'To jest mój brat.', 'This is my brother.'),
('together4', 'Miło cię poznać.', 'Miło cię poznać.', 'It is nice to meet you.'),
('together4', 'Również miło mi ciebie poznać', 'Również miło mi ciebie poznać.', 'It is nice to meet you too.'),
('together4', 'Przyjdź i spotkaj się', 'Przyjdź i spotkaj się z moim bratem.', 'Come and meet my brother.'),
('together4', 'Ok, to brzmi dobrze', 'Ok, to brzmi dobrze.', 'OK, that sounds good.'),
('together4', 'ja mam', 'Ja mam kota.', 'I have got a cat.'),
('together4', 'ty masz', 'Ty masz dwa psy.', 'You have got two dogs.'),
('together4', 'on ma', 'On ma rower.', 'He has got a bike.'),
('together4', 'ona ma', 'Ona ma długie włosy.', 'She has got long hair.'),
('together4', 'to ma', 'To ma cztery nogi.', 'It has got four legs.'),
('together4', 'my mamy', 'My mamy duży dom.', 'We have got a big house.'),
('together4', 'wy macie', 'Wy macie nowe książki.', 'You have got new books.'),
('together4', 'oni mają', 'Oni mają psa.', 'They have got a dog.'),
('together4', 'ja nie mam', 'Ja nie mam siostry.', 'I have not got a sister.'),
('together4', 'ty nie masz', 'Ty nie masz roweru.', 'You have not got a bike.'),
('together4', 'on nie ma', 'On nie ma czasu.', 'He has not got time.'),
('together4', 'ona nie ma', 'Ona nie ma kota.', 'She has not got a cat.'),
('together4', 'to nie ma', 'To nie ma ogona.', 'It has not got a tail.'),
('together4', 'my nie mamy', 'My nie mamy lekcji jutro.', 'We have not got lessons tomorrow.'),
('together4', 'wy nie macie', 'Wy nie macie zeszytów.', 'You have not got notebooks.'),
('together4', 'oni nie mają', 'Oni nie mają psa.', 'They have not got a dog.'),
('together4', 'Czy ja mam?', 'Czy ja mam czas?', 'Have I got time?'),
('together4', 'Czy ty masz?', 'Czy ty masz długopis?', 'Have you got a pen?'),
('together4', 'Czy on ma?', 'Czy on ma rower?', 'Has he got a bike?'),
('together4', 'Czy ona ma?', 'Czy ona ma kota?', 'Has she got a cat?'),
('together4', 'Czy to ma?', 'Czy to ma cztery nogi?', 'Has it got four legs?'),
('together4', 'Czy my mamy?', 'Czy my mamy lekcję?', 'Have we got a lesson?'),
('together4', 'Czy wy macie?', 'Czy wy macie zeszyty?', 'Have you got notebooks?'),
('together4', 'Czy oni mają?', 'Czy oni mają psa?', 'Have they got a dog?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 5 — Food, restaurant, there is/are (55)
-- ═══════════════════════════════════════════════════════════
('together4', 'herbatniki', 'Lubię herbatniki z mlekiem.', 'I like biscuits with milk.'),
('together4', 'chleb', 'Mama kupuje świeży chleb.', 'Mum is buying fresh bread.'),
('together4', 'płatki zbożowe', 'Jem płatki zbożowe na śniadanie.', 'I eat cereal for breakfast.'),
('together4', 'ser', 'Lubię żółty ser.', 'I like yellow cheese.'),
('together4', 'frytki', 'Frytki są słone.', 'Chips are salty.'),
('together4', 'jajko', 'Jem jajko na śniadanie.', 'I eat an egg for breakfast.'),
('together4', 'mleko', 'Piję mleko codziennie.', 'I drink milk every day.'),
('together4', 'makaron', 'Lubię makaron z serem.', 'I like pasta with cheese.'),
('together4', 'ryż', 'Ryż jest biały.', 'Rice is white.'),
('together4', 'sałatka', 'Sałatka jest zdrowa.', 'Salad is healthy.'),
('together4', 'koktajl', 'Robię koktajl z owoców.', 'I am making a fruit smoothie.'),
('together4', 'truskawka', 'Truskawka jest słodka.', 'A strawberry is sweet.'),
('together4', 'tost', 'Jem tost z dżemem.', 'I eat toast with jam.'),
('together4', 'fasola', 'Fasola jest zielona.', 'The bean is green.'),
('together4', 'brokuł', 'Brokuły są zielone.', 'Broccoli is green.'),
('together4', 'marchewka', 'Króliki lubią marchewki.', 'Rabbits like carrots.'),
('together4', 'ogórek', 'Ogórek jest zielony.', 'A cucumber is green.'),
('together4', 'winogrono', 'Winogrona są słodkie.', 'Grapes are sweet.'),
('together4', 'kiwi', 'Kiwi jest zielone w środku.', 'Kiwi fruit is green inside.'),
('together4', 'grzyb', 'Grzyb rośnie w lesie.', 'A mushroom grows in the forest.'),
('together4', 'cebula', 'Cebula jest na pizzy.', 'There is onion on the pizza.'),
('together4', 'ananas', 'Ananas jest słodki.', 'A pineapple is sweet.'),
('together4', 'ziemniak', 'Ziemniak jest brązowy.', 'A potato is brown.'),
('together4', 'czerwona papryka', 'Lubię czerwone papryki.', 'I like red peppers.'),
('together4', 'szpinak', 'Szpinak jest bardzo zdrowy.', 'Spinach is very healthy.'),
('together4', 'Jaki piękny dzień! Co za piękny dzień!', 'Jaki piękny dzień!', 'What a lovely day!'),
('together4', 'To jest dziwne!', 'To jest dziwne!', 'That is weird!'),
('together4', 'O jej!', 'O jej! Upadłem!', 'Oh dear! I fell!'),
('together4', 'To wygląda pysznie!', 'To wygląda pysznie!', 'This looks delicious!'),
('together4', 'Co mogę podać? Co dla Ciebie/Pana/Pani?', 'Co mogę podać?', 'What can I get you?'),
('together4', 'Proszę o dużą pizzę z kurczakiem i grzybami.', 'Proszę o dużą pizzę z kurczakiem i grzybami.', 'I would like a large chicken and mushroom pizza, please.'),
('together4', 'Czy chciałbyś/chciałabyś jakieś przystawki?', 'Czy chciałbyś jakieś przystawki?', 'Would you like some sides?'),
('together4', 'Poproszę sałatkę z pomidorów.', 'Poproszę sałatkę z pomidorów.', 'A tomato salad, please.'),
('together4', 'Coś do picia?', 'Coś do picia?', 'Anything to drink?'),
('together4', 'Tak, poproszę wodę gazowaną/niegazowaną.', 'Tak, poproszę wodę gazowaną.', 'Yes, sparkling water, please.'),
('together4', 'Czy to wszystko?', 'Czy to wszystko? Tak.', 'Is that everything? Yes, it is.'),
('together4', 'Na miejscu czy na wynos?', 'Na miejscu czy na wynos?', 'Is that eat in or takeaway?'),
('together4', 'Na wynos, proszę.', 'Na wynos, proszę.', 'Takeaway, please.'),
('together4', 'Jest trochę makaronu.', 'Jest trochę makaronu.', 'There is some pasta.'),
('together4', 'Są cztery banany.', 'Są cztery banany.', 'There are four bananas.'),
('together4', 'Nie ma sałatki.', 'Nie ma sałatki.', 'There is not a salad.'),
('together4', 'Nie ma żadnych ziemniaków.', 'Nie ma żadnych ziemniaków.', 'There are not any potatoes.'),
('together4', 'Jest kiwi.', 'Jest kiwi.', 'There is a kiwi fruit.'),
('together4', 'Jest jajko.', 'Jest jajko.', 'There is an egg.'),
('together4', 'Nie ma owocu kiwi.', 'Nie ma owocu kiwi.', 'There is not a kiwi fruit.'),
('together4', 'Nie ma jajka.', 'Nie ma jajka.', 'There is not an egg.'),
('together4', 'Jest kilka winogron.', 'Jest kilka winogron.', 'There are some grapes.'),
('together4', 'Jest trochę szpinaku.', 'Jest trochę szpinaku.', 'There is some spinach.'),
('together4', 'Jest dużo bananów.', 'Jest dużo bananów.', 'There are a lot of bananas.'),
('together4', 'Jest dużo sera.', 'Jest dużo sera.', 'There is a lot of cheese.'),
('together4', 'Nie ma żadnych bananów.', 'Nie ma żadnych bananów.', 'There are not any bananas.'),
('together4', 'Nie ma (żadnej) wody.', 'Nie ma żadnej wody.', 'There is not any water.'),
('together4', 'dużo', 'Mam dużo zabawek.', 'I have a lot of toys.'),
('together4', 'trochę, kilka', 'Mam trochę pieniędzy.', 'I have some money.'),
('together4', 'żadnych', 'Nie mam żadnych książek.', 'I have not got any books.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 6 — Sport, hobbies, can/cannot (55)
-- ═══════════════════════════════════════════════════════════
-- 'Co się stało?' Unit 6 (What's the matter?) pominiete — duplikat synonimu z Unit 4
('together4', 'koszykówka', 'Koszykówka to mój ulubiony sport.', 'Basketball is my favourite sport.'),
('together4', 'kolarstwo', 'Lubię kolarstwo.', 'I like cycling.'),
('together4', 'hokej', 'Lubię oglądać hokej.', 'I like to watch hockey.'),
('together4', 'dżudo', 'Mój brat trenuje dżudo.', 'My brother does judo.'),
('together4', 'jazda na wrotkach', 'Lubię jazdę na wrotkach.', 'I like roller skating.'),
('together4', 'bieganie', 'Bieganie jest zdrowe.', 'Running is healthy.'),
('together4', 'narciarstwo', 'Zimą lubię narciarstwo.', 'I like skiing in winter.'),
('together4', 'siatkówka', 'Siatkówka jest popularna w Polsce.', 'Volleyball is popular in Poland.'),
('together4', 'szachy', 'Lubię grać w szachy.', 'I like to play chess.'),
('together4', 'rysowanie', 'Rysowanie to moje hobby.', 'Drawing is my hobby.'),
('together4', 'granie w gry przez Internet', 'Lubię granie w gry przez Internet.', 'I like playing online games.'),
('together4', 'granie na fortepianie', 'Granie na fortepianie jest trudne.', 'Playing the piano is difficult.'),
('together4', 'czytanie', 'Czytanie to moje ulubione hobby.', 'Reading is my favourite hobby.'),
('together4', 'śpiewanie', 'Śpiewanie sprawia mi radość.', 'Singing makes me happy.'),
('together4', 'pisanie bloga', 'Lubię pisanie bloga.', 'I like writing my blog.'),
('together4', 'łapać', 'Potrafię łapać piłkę.', 'I can catch a ball.'),
('together4', 'wspinać się', 'Małpy potrafią się wspinać.', 'Monkeys can climb.'),
('together4', 'tańczyć', 'Lubię tańczyć z mamą.', 'I like to dance with mum.'),
('together4', 'nurkować', 'Lubię nurkować w morzu.', 'I like to dive in the sea.'),
('together4', 'latać', 'Ptaki potrafią latać.', 'Birds can fly.'),
('together4', 'skakać', 'Potrafię skakać wysoko.', 'I can jump high.'),
('together4', 'jeździć', 'Lubię jeździć rowerem.', 'I like to ride a bike.'),
('together4', 'pływać', 'Pływam w basenie.', 'I swim in the pool.'),
('together4', 'chodzić', 'Lubię chodzić w górach.', 'I like to walk in the mountains.'),
('together4', 'zrobić ciasto', 'Mama zrobi ciasto.', 'Mum will make a cake.'),
('together4', 'grać w piłkę nożną', 'Lubię grać w piłkę nożną.', 'I like to play football.'),
('together4', 'jeździć konno', 'Mama potrafi jeździć konno.', 'Mum can ride a horse.'),
('together4', 'Wszystko w porządku?', 'Wszystko w porządku?', 'Are you alright?'),
('together4', 'Kiepsko radzę sobie w sportach!', 'Kiepsko radzę sobie w sportach!', 'I am terrible at sports!'),
('together4', 'Co robimy teraz?', 'Co robimy teraz?', 'What shall we do now?'),
('together4', 'Czy mogę Cię o coś spytać?', 'Czy mogę Cię o coś spytać?', 'Can I ask you something?'),
('together4', 'Pewnie, co tam?', 'Pewnie, co tam?', 'Sure, what is up?'),
('together4', 'Czy mogę iść na przyjęcie?', 'Czy mogę iść na przyjęcie?', 'Can I go to a party?'),
('together4', 'Gdzie jest przyjęcie?', 'Gdzie jest przyjęcie?', 'Where is the party?'),
('together4', 'Jest w jej domu.', 'Jest w jej domu.', 'It is at her house.'),
('together4', 'O której godzinie jest przyjęcie?', 'O której godzinie jest przyjęcie?', 'What time is the party?'),
('together4', 'O czwartej.', 'Jest o czwartej.', 'It is at four o''clock.'),
('together4', 'O której godzinie się kończy?', 'O której godzinie się kończy?', 'And what time does it end?'),
('together4', 'Około siódmej.', 'Około siódmej.', 'About seven o''clock.'),
('together4', 'Brzmi w porządku.', 'Brzmi w porządku.', 'That sounds OK.'),
('together4', 'Tak, możesz iść.', 'Tak, możesz iść.', 'Yes, you can go.'),
('together4', 'Potrafię pływać.', 'Potrafię pływać.', 'I can swim.'),
('together4', 'Umiesz pływać.', 'Ty umiesz pływać.', 'You can swim.'),
('together4', 'On umie pływać.', 'On umie pływać.', 'He can swim.'),
('together4', 'Ona potrafi grać w szachy.', 'Ona potrafi grać w szachy.', 'She can play chess.'),
('together4', 'My potrafimy się wspinać.', 'My potrafimy się wspinać.', 'We can climb.'),
('together4', 'Oni potrafią tańczyć bardzo dobrze.', 'Oni potrafią tańczyć bardzo dobrze.', 'They can dance very well.'),
('together4', 'Ja nie potrafię latać.', 'Ja nie potrafię latać.', 'I cannot fly.'),
('together4', 'Ona nie potrafi szybko pływać.', 'Ona nie potrafi szybko pływać.', 'She cannot swim fast.'),
('together4', 'Czy ty umiesz pływać?', 'Czy ty umiesz pływać?', 'Can you swim?'),
('together4', 'Czy on potrafi tańczyć?', 'Czy on potrafi tańczyć?', 'Can he dance?'),
('together4', 'Czy ona potrafi grać w szachy?', 'Czy ona potrafi grać w szachy? Tak. Nie.', 'Can she play chess? Yes, she can. No, she cannot.'),
('together4', 'Co potrafisz robić?', 'Co potrafisz robić?', 'What can you do?'),
('together4', 'Gdzie mogę biegać?', 'Gdzie mogę biegać?', 'Where can I run?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 7 — Daily routine, present simple (50)
-- ═══════════════════════════════════════════════════════════
('together4', 'szczotkować zęby', 'Szczotkuję zęby dwa razy dziennie.', 'I brush my teeth twice a day.'),
('together4', 'ćwiczyć', 'Codziennie ćwiczę.', 'I do exercise every day.'),
('together4', 'odrabiać pracę domową', 'Odrabiam pracę domową wieczorem.', 'I do homework in the evening.'),
('together4', 'ubierać się', 'Ubieram się szybko.', 'I get dressed quickly.'),
('together4', 'wstawać', 'Wstaję o siódmej.', 'I get up at seven.'),
('together4', 'iść do domu', 'Idę do domu o trzeciej.', 'I go home at three.'),
('together4', 'kłaść się do łóżka', 'Kładę się do łóżka o dziewiątej.', 'I go to bed at nine.'),
('together4', 'iść do szkoły', 'Idę do szkoły o ósmej.', 'I go to school at eight.'),
('together4', 'brać prysznic', 'Biorę prysznic wieczorem.', 'I have a shower in the evening.'),
('together4', 'mieć lekcje', 'Mam lekcje od ósmej.', 'I have lessons from eight.'),
('together4', 'pomagać rodzicom', 'Pomagam rodzicom w kuchni.', 'I help my parents in the kitchen.'),
('together4', 'spotkać się z moimi przyjaciółmi', 'Spotkam się z moimi przyjaciółmi.', 'I will meet my friends.'),
('together4', 'posprzątać mój pokój', 'Posprzątam mój pokój w sobotę.', 'I will tidy my room on Saturday.'),
('together4', 'oglądać telewizję', 'Wieczorem oglądam telewizję.', 'I watch TV in the evening.'),
('together4', 'rozmawiać przez telefon', 'Lubię rozmawiać przez telefon.', 'I like to chat on my phone.'),
('together4', 'układać puzzle', 'Lubię układać puzzle.', 'I like to do puzzles.'),
('together4', 'słuchać muzyki', 'Lubię słuchać muzyki.', 'I like to listen to music.'),
('together4', 'tworzyć krótkie filmy', 'Lubię tworzyć krótkie filmy.', 'I like to make videos.'),
('together4', 'malować', 'Lubię malować obrazy.', 'I like to paint.'),
('together4', 'grać w gry planszowe', 'Lubię grać w gry planszowe.', 'I like to play board games.'),
('together4', 'jeździć na hulajnodze', 'Lubię jeździć na hulajnodze.', 'I like to ride a scooter.'),
('together4', 'spędzać czas z przyjaciółmi', 'Lubię spędzać czas z przyjaciółmi.', 'I like to spend time with friends.'),
('together4', 'korzystać z mediów społecznościowych', 'Lubię korzystać z mediów społecznościowych.', 'I like to use social media.'),
('together4', 'oglądać seriale', 'Lubię oglądać seriale.', 'I like to watch series.'),
('together4', 'oglądać sport', 'Lubię oglądać sport.', 'I like to watch sports.'),
('together4', 'oglądać filmiki', 'Lubię oglądać filmiki.', 'I like to watch video clips.'),
('together4', 'Jestem spóźniony!', 'Jestem spóźniony!', 'I am late!'),
('together4', 'Jestem zestresowany!', 'Jestem zestresowany!', 'I am stressed out!'),
('together4', 'Porozmawiajmy o tym.', 'Porozmawiajmy o tym.', 'Let us talk about it.'),
('together4', 'To za dużo!', 'To za dużo!', 'It is too much!'),
('together4', 'Czy lubisz sport?', 'Czy lubisz sport?', 'Do you like sports?'),
('together4', 'Tak, kocham sport!', 'Tak, kocham sport!', 'Yes, I love sports!'),
('together4', 'Jaki jest Twój ulubiony sport?', 'Jaki jest Twój ulubiony sport?', 'What is your favourite sport?'),
('together4', 'Naprawdę lubię piłkę ręczną.', 'Naprawdę lubię piłkę ręczną.', 'I really like handball.'),
('together4', 'Jakie sporty lubisz?', 'Jakie sporty lubisz?', 'What sports do you like?'),
('together4', 'Ja też lubię piłkę nożną.', 'Ja też lubię piłkę nożną.', 'I like football, too.'),
('together4', 'Nie za bardzo lubię tenisa.', 'Nie za bardzo lubię tenisa.', 'I do not like tennis that much.'),
('together4', 'To mój ulubiony sport.', 'To mój ulubiony sport!', 'It is my favourite sport!'),
('together4', 'Ja wstaję o szóstej trzydzieści.', 'Ja wstaję o szóstej trzydzieści.', 'I get up at half past six.'),
('together4', 'Ty ćwiczysz o siódmej.', 'Ty ćwiczysz o siódmej.', 'You do exercise at seven o''clock.'),
('together4', 'Ona wstaje o siódmej.', 'Ona wstaje o siódmej.', 'She gets up at seven o''clock.'),
('together4', 'On kładzie się do łóżka o dziewiątej.', 'On kładzie się do łóżka o dziewiątej.', 'He goes to bed at nine o''clock.'),
('together4', 'W sobotę nie chodzimy do szkoły.', 'W sobotę nie chodzimy do szkoły.', 'We do not go to school on Saturday.'),
('together4', 'Oni nie biorą prysznica o piątej.', 'Oni nie biorą prysznica o piątej.', 'They do not have a shower at five o''clock.'),
('together4', 'Ona nie słucha muzyki w poniedziałek.', 'Ona nie słucha muzyki w poniedziałek.', 'She does not listen to music on Monday.'),
('together4', 'On nie ogląda klipów wideo.', 'On nie ogląda klipów wideo.', 'He does not watch video clips.'),
('together4', 'Kiedy idziesz do szkoły?', 'Kiedy idziesz do szkoły?', 'When do you go to school?'),
('together4', 'Kiedy jeździsz na hulajnodze?', 'Kiedy jeździsz na hulajnodze?', 'When do you ride a scooter?'),
('together4', 'Kiedy on maluje?', 'Kiedy on maluje?', 'When does he paint?'),
('together4', 'Kiedy ona gra w gry planszowe?', 'Kiedy ona gra w gry planszowe?', 'When does she play board games?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 8 — Holidays, places, present continuous (49)
-- ═══════════════════════════════════════════════════════════
('together4', 'biwakowanie', 'Lubię biwakowanie w lesie.', 'I like camping in the forest.'),
('together4', 'kajakarstwo', 'Lubię kajakarstwo na jeziorze.', 'I like canoeing on the lake.'),
('together4', 'wspinaczka', 'Wspinaczka jest trudna.', 'Climbing is difficult.'),
('together4', 'kodowanie', 'Uczę się kodowania.', 'I am learning coding.'),
('together4', 'pójście na festiwal sztuk', 'Lubię pójście na festiwal sztuk.', 'I like going to an arts festival.'),
('together4', 'wyjazd na wycieczkę', 'Lubię wyjazd na wycieczkę.', 'I like going on a trip.'),
('together4', 'wędrowanie', 'Wędrowanie w górach jest piękne.', 'Hiking in the mountains is beautiful.'),
('together4', 'zwiedzanie', 'Lubimy zwiedzanie miast.', 'We like sightseeing in cities.'),
('together4', 'opalanie się', 'Latem lubię opalanie się.', 'I like sunbathing in summer.'),
('together4', 'robienie zdjęć', 'Lubię robienie zdjęć.', 'I like taking photos.'),
('together4', 'skakanie na trampolinie', 'Lubię skakanie na trampolinie.', 'I like trampolining.'),
('together4', 'wizyta w zoo', 'Wizyta w zoo była wspaniała.', 'Visiting the zoo was wonderful.'),
('together4', 'przystanek autobusowy', 'Czekam na przystanku autobusowym.', 'I am waiting at the bus stop.'),
('together4', 'biblioteka', 'Czytam w bibliotece.', 'I read at the library.'),
('together4', 'rynek', 'Na rynku są warzywa.', 'There are vegetables at the market.'),
('together4', 'posterunek policji', 'Posterunek policji jest blisko.', 'The police station is near.'),
('together4', 'poczta', 'Wysyłam list na poczcie.', 'I send a letter at the post office.'),
('together4', 'centrum handlowe', 'Idziemy do centrum handlowego.', 'We are going to the shopping centre.'),
('together4', 'centrum sportowe', 'Trenuję w centrum sportowym.', 'I train at the sports centre.'),
('together4', 'stadion', 'Mecz odbywa się na stadionie.', 'The match is at the stadium.'),
('together4', 'basen', 'Pływam w basenie.', 'I swim in the swimming pool.'),
('together4', 'dworzec kolejowy', 'Pociąg odjeżdża z dworca kolejowego.', 'The train leaves from the train station.'),
('together4', 'Do zobaczenia później!', 'Do zobaczenia później!', 'See you later!'),
('together4', 'Biedna dziewczyna!', 'Biedna dziewczyna!', 'Poor girl!'),
('together4', 'To nie działa!', 'To nie działa!', 'It is not working!'),
('together4', 'Oto jest!', 'Oto jest!', 'There he is!'),
('together4', 'Czy mógłby mi Pan pomóc?', 'Czy mógłby mi Pan pomóc?', 'Can you help me?'),
('together4', 'Szukam kina.', 'Szukam kina.', 'I am looking for the cinema.'),
('together4', 'Idź prosto.', 'Idź prosto.', 'Go straight on.'),
('together4', 'Skręć w lewo.', 'Skręć w lewo.', 'Turn left.'),
('together4', 'Następnie skręć w prawo.', 'Następnie skręć w prawo.', 'Then turn right.'),
('together4', 'Miń park.', 'Miń park.', 'Go past the park.'),
('together4', 'Czy to jest daleko?', 'Czy to jest daleko?', 'Is it far?'),
('together4', 'To jest po lewej stronie.', 'To jest po lewej stronie.', 'It is on the left.'),
('together4', 'To jest po prawej stronie.', 'To jest po prawej stronie.', 'It is on the right.'),
('together4', 'To jest około pięciu minut stąd.', 'To jest około pięciu minut stąd.', 'It is about five minutes from here.'),
('together4', 'Dziękuję bardzo.', 'Dziękuję bardzo.', 'Thanks very much.'),
('together4', 'Nie ma za co.', 'Nie ma za co.', 'You are welcome.'),
('together4', 'Teraz robię zdjęcia.', 'Teraz robię zdjęcia.', 'I am taking photos now.'),
('together4', 'Teraz skaczesz na trampolinie.', 'Teraz skaczesz na trampolinie.', 'You are trampolining now.'),
('together4', 'On odwiedza teraz zoo.', 'On odwiedza teraz zoo.', 'He is visiting the zoo now.'),
('together4', 'Kodujemy teraz.', 'Kodujemy teraz.', 'We are coding now.'),
('together4', 'Teraz nie biwakuję.', 'Teraz nie biwakuję.', 'I am not camping now.'),
('together4', 'Teraz nie wspinasz się.', 'Teraz nie wspinasz się.', 'You are not climbing now.'),
('together4', 'On nie jedzie teraz na wycieczkę.', 'On nie jedzie teraz na wycieczkę.', 'He is not going on a trip now.'),
('together4', 'Ona nie opala się teraz.', 'Ona nie opala się teraz.', 'She is not sunbathing now.'),
('together4', 'Czy teraz zwiedzasz?', 'Czy teraz zwiedzasz?', 'Are you sightseeing now?'),
('together4', 'Czy on idzie na festiwal sztuki?', 'Czy on idzie na festiwal sztuki?', 'Is he going to an arts festival?'),
('together4', 'Czy oni teraz pływają?', 'Czy oni teraz pływają?', 'Are they swimming now?')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Together 4: 427 unikalnych zdan zaktualizowanych/dodanych w word_sentences (428 wpisow w data.js, 1 duplikat synonimu Co sie stalo? zdedupedowany przez UPSERT).';
END $$;
