-- ═══════════════════════════════════════════════════════════
-- Fix sentences: TOGETHER 6 (klasa 6, szkola podstawowa)
-- ═══════════════════════════════════════════════════════════
--
-- Cel: kompletne, starannie napisane przyklady zdan dla wszystkich
-- 370 unikalnych slowek z Together 6 (Macmillan).
--
-- Tematy unitow:
--   Unit 1 (43): szkola + przyjazn + opinie + stroje narodowe
--   Unit 2 (45): technologia + komputery + przyszlosc (will)
--   Unit 3 (60): zycie + cykl zyciowy + uroczystosci + podziekowania
--   Unit 4 (47): hobby + filmy + zainteresowania
--   Unit 5 (50): zdrowie + dolegliwosci + porady (should)
--   Unit 6 (43): sport + sprzet + sukces + porownania
--   Unit 7 (45): sklepy + zakupy + platnosci + recykling
--   Unit 8 (42): wakacje + zwiedzanie + pytania o atrakcje
--
-- UPSERT (INSERT ... ON CONFLICT DO UPDATE) — idempotentna.

INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target) VALUES

-- ═══════════════════════════════════════════════════════════
-- Unit 1 — School, friendship, opinions (43)
-- ═══════════════════════════════════════════════════════════
('together6', 'przygotować prezentację', 'Muszę przygotować prezentację z historii.', 'I have to do a presentation in history.'),
('together6', 'nie zaliczyć testu/klasówki', 'Nie zaliczyłem testu z matematyki.', 'I failed the maths test.'),
('together6', 'dostać dobrą/słabą ocenę', 'Dostałem dobrą ocenę z angielskiego.', 'I got a good mark in English.'),
('together6', 'opuszczać zajęcia w szkole', 'Nie chcę opuszczać zajęć w szkole.', 'I do not want to miss school.'),
('together6', 'zaliczyć test/klasówkę', 'Zaliczyłem test z biologii.', 'I passed the biology test.'),
('together6', 'powtarzać materiał przed testem/klasówką', 'Powtarzam materiał przed testem.', 'I am revising for the test.'),
('together6', 'pisać test/klasówkę', 'Piszę test z matematyki w piątek.', 'I am taking a test in maths on Friday.'),
('together6', 'notować', 'Lubię notować na lekcji.', 'I like to take notes in class.'),
('together6', 'nosić mundurek', 'W naszej szkole nosimy mundurek.', 'We wear a uniform at our school.'),
('together6', 'pisać wypracowanie', 'Muszę napisać wypracowanie po angielsku.', 'I have to write an essay in English.'),
('together6', 'przerwa', 'Po lekcji jest przerwa.', 'There is a breaktime after the lesson.'),
('together6', 'szkoła prywatna', 'Anna chodzi do szkoły prywatnej.', 'Anna goes to a private school.'),
('together6', 'rok szkolny', 'Rok szkolny zaczyna się we wrześniu.', 'The school year starts in September.'),
('together6', 'szkoła publiczna', 'Chodzę do szkoły publicznej.', 'I go to a state school.'),
('together6', 'semestr/semestry', 'Mamy dwa semestry w roku.', 'We have two state terms in a year.'),
('together6', 'pocieszyć kogoś', 'Pociesz brata, gdy jest smutny.', 'Cheer your brother up when he is sad.'),
('together6', 'czuć się samotnym/samotną', 'Czuję się samotna dzisiaj.', 'I feel lonely today.'),
('together6', '(dobrze) się dogadywać', 'Dobrze się dogaduję z bratem.', 'I get on well with my brother.'),
('together6', 'poznać', 'Chcę go lepiej poznać.', 'I want to get to know him better.'),
('together6', 'mieć (dużo) wspólnego', 'Mamy dużo wspólnego z Tomkiem.', 'We have a lot in common with Tomek.'),
('together6', 'pokłócić się', 'Pokłóciłem się z bratem.', 'I had an argument with my brother.'),
('together6', 'dochowywać tajemnicy', 'Potrafię dochowywać tajemnicy.', 'I can keep a secret.'),
('together6', 'zaprzyjaźnić się', 'Zaprzyjaźniłem się z Anną.', 'I made friends with Anna.'),
('together6', 'przeprosić', 'Powinieneś przeprosić siostrę.', 'You should say sorry to your sister.'),
('together6', 'mówić prawdę', 'Zawsze mówię prawdę.', 'I always tell the truth.'),
('together6', 'Sobota rano mi nie pasuje.', 'Sobota rano mi nie pasuje.', 'Saturday morning does not work for me.'),
('together6', 'Świetnie!', 'Świetnie! Dobra robota!', 'That is so cool!'),
('together6', 'Ojej!', 'Ojej! Upuściłem szklankę.', 'Oops! I dropped the glass.'),
('together6', 'Poddaję się!', 'Poddaję się! To za trudne!', 'I give up! It is too difficult!'),
('together6', 'Nie zgadzam się!', 'Nie zgadzam się!', 'I disagree!'),
('together6', 'To prawda.', 'To prawda. Masz rację.', 'That is true. You are right.'),
('together6', 'No właśnie!', 'No właśnie! Też tak myślę.', 'Exactly! I think so too.'),
('together6', 'Nie jestem tego pewny/pewna.', 'Nie jestem tego pewny.', 'I am not sure about that.'),
('together6', 'Słuszna uwaga!', 'Słuszna uwaga!', 'That is a good point!'),
('together6', 'Też tak sądzę.', 'Też tak sądzę.', 'I think so, too.'),
('together6', 'równy', 'Wszyscy ludzie są równi.', 'All people are equal.'),
('together6', 'strój narodowy', 'Każdy kraj ma swój strój narodowy.', 'Every country has its national costume.'),
('together6', 'nadruk, wzór', 'Lubię koszulki w kolorowy nadruk.', 'I like T-shirts with a colourful print.'),
('together6', 'szata', 'Sędzia nosi czarną szatę.', 'The judge wears a black robe.'),
('together6', 'fartuch, kitel', 'Lekarz nosi biały fartuch.', 'A doctor wears a white smock.'),
('together6', 'różnić się', 'Polskie zwyczaje różnią się od chińskich.', 'Polish customs vary from Chinese ones.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 2 — Technology, computers, will (45)
-- ═══════════════════════════════════════════════════════════
('together6', 'sztuczna inteligencja', 'Sztuczna inteligencja jest coraz mądrzejsza.', 'AI is getting smarter and smarter.'),
('together6', 'chatbot', 'Chatbot odpowiada na pytania.', 'A chatbot answers questions.'),
('together6', 'przenośna pamięć', 'Mam pliki na przenośnej pamięci.', 'I have files on a memory stick.'),
('together6', 'mysz (do komputera)', 'Mysz nie działa.', 'The mouse is not working.'),
('together6', 'przenośny głośnik', 'Mam przenośny głośnik bluetooth.', 'I have a portable speaker with bluetooth.'),
('together6', 'ekran', 'Ekran jest jasny.', 'The screen is bright.'),
('together6', 'drukarka 3D', 'Drukarka 3D drukuje plastikowe modele.', 'A 3D printer prints plastic models.'),
('together6', 'panel dotykowy', 'Mój laptop ma panel dotykowy.', 'My laptop has a touchpad.'),
('together6', 'klawiatura wirtualna', 'Pisanie na klawiaturze wirtualnej jest wolne.', 'Typing on a virtual keyboard is slow.'),
('together6', 'słuchawki bezprzewodowe', 'Mam nowe słuchawki bezprzewodowe.', 'I have new wireless headphones.'),
('together6', 'podłączać', 'Podłącz drukarkę do laptopa.', 'Connect the printer to the laptop.'),
('together6', 'drukować', 'Drukuję moje zdjęcia.', 'I am printing my photos.'),
('together6', 'zapisywać', 'Zapisz plik przed wyjściem.', 'Save the file before you leave.'),
('together6', 'wysyłać', 'Wysyłam mejl do mamy.', 'I am sending an email to mum.'),
('together6', 'pisać na klawiaturze', 'Piszę na klawiaturze szybko.', 'I type quickly.'),
('together6', 'klikać', 'Kliknij na link.', 'Click on the link.'),
('together6', 'pobierać', 'Pobieram nowy program.', 'I am downloading a new program.'),
('together6', 'wprowadzać (hasło)', 'Wprowadź hasło.', 'Enter your password.'),
('together6', 'logować się', 'Loguję się do systemu.', 'I am logging in to the system.'),
('together6', 'wylogować się', 'Wyloguj się przed wyjściem.', 'Log out before you leave.'),
('together6', 'zamieszczać', 'Zamieszczam zdjęcia na blogu.', 'I am posting photos on the blog.'),
('together6', 'szukać (czegoś)', 'Szukam informacji w internecie.', 'I am searching for information on the internet.'),
('together6', 'udostępniać', 'Udostępnij ten post.', 'Share this post.'),
('together6', 'dotknąć', 'Dotknij ekran.', 'Tap the screen.'),
('together6', 'ładować', 'Ładuję zdjęcia na chmurę.', 'I am uploading photos to the cloud.'),
('together6', 'Mam już dość tego czekania.', 'Mam już dość tego czekania.', 'I am tired of waiting.'),
('together6', 'Tylko sobie wyobraź!', 'Tylko sobie wyobraź!', 'Just imagine!'),
('together6', 'Szkoda, że teraz tego nie mamy.', 'Szkoda, że teraz tego nie mamy.', 'Pity we cannot have one now!'),
('together6', 'Jestem tak głodny/głodna, że zjadłbym/zjadłabym konia z kopytami!', 'Jestem tak głodny, że zjadłbym konia z kopytami!', 'I am so hungry I could eat a horse!'),
('together6', 'Szkoda, że teraz nie możemy tego zrobić.', 'Szkoda, że teraz nie możemy tego zrobić.', 'Pity we cannot do it now!'),
('together6', 'Może masz rację.', 'Może masz rację.', 'Maybe you are right.'),
('together6', 'Chciałbym/Chciałabym kiedyś (grać na gitarze w zespole).', 'Chciałbym kiedyś grać na gitarze w zespole.', 'I would like to play the guitar in a band one day.'),
('together6', 'Myślisz, że będziesz (grać na koncertach)?', 'Myślisz, że będziesz grać na koncertach?', 'Do you think you will play in concerts?'),
('together6', 'Mam nadzieję, że tak!', 'Mam nadzieję, że tak!', 'I hope so!'),
('together6', 'Mam nadzieję, że nie.', 'Mam nadzieję, że nie.', 'I hope not.'),
('together6', 'Nie sądzę, że (będę bogaty/bogata).', 'Nie sądzę, że będę bogaty.', 'I do not think I will be rich.'),
('together6', 'Myślę, że to właśnie (będę studiować na uniwersytecie).', 'Myślę, że to właśnie będę studiować na uniwersytecie.', 'I think I will study it at university.'),
('together6', 'Mam nadzieję, że zostanę (wynalazcą/wynalazczynią).', 'Mam nadzieję, że zostanę wynalazcą.', 'I hope to be an inventor.'),
('together6', 'niewidomy', 'Niewidomy człowiek używa laski.', 'A blind person uses a stick.'),
('together6', 'ścieżka rowerowa', 'Jadę ścieżką rowerową.', 'I am riding on the cycle lane.'),
('together6', 'mniej', 'Mam mniej pracy dzisiaj.', 'I have fewer tasks today.'),
('together6', 'naprawa', 'Naprawa roweru kosztuje dużo.', 'The bike repair costs a lot.'),
('together6', 'panel słoneczny', 'Mamy panele słoneczne na dachu.', 'We have solar panels on the roof.'),
('together6', 'światła drogowe', 'Stoję na czerwonych światłach drogowych.', 'I am stopping at the red traffic lights.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 3 — Life cycle, celebrations, thanking (60)
-- ═══════════════════════════════════════════════════════════
('together6', 'urodzić się', 'Urodziłem się w Warszawie.', 'I was born in Warsaw.'),
('together6', 'uczyć się chodzić', 'Niemowlę uczy się chodzić.', 'The baby is learning to walk.'),
('together6', 'dzieciństwo', 'Moje dzieciństwo było szczęśliwe.', 'My childhood was happy.'),
('together6', 'dorastanie', 'Dorastanie jest trudne.', 'Growing up is difficult.'),
('together6', 'edukacja', 'Edukacja jest ważna.', 'Education is important.'),
('together6', 'ukończyć studia', 'Mama ukończyła studia.', 'Mum graduated.'),
('together6', 'skończyć uniwersytet/studia', 'Skończył uniwersytet w 2020.', 'He finished university in 2020.'),
('together6', 'dostać pracę', 'Dostał pracę w Warszawie.', 'He got a job in Warsaw.'),
('together6', 'kariera', 'On ma świetną karierę.', 'He has a great career.'),
('together6', 'zakochać się', 'Zakochałem się w Annie.', 'I fell in love with Anna.'),
('together6', 'randkowanie', 'Randkowanie jest ekscytujące.', 'Dating is exciting.'),
('together6', 'zaręczyć się', 'Zaręczyli się rok temu.', 'They got engaged a year ago.'),
('together6', 'wziąć ślub', 'Pobrali się w czerwcu.', 'They got married in June.'),
('together6', 'iść do przedszkola', 'Mój brat idzie do przedszkola.', 'My brother is going to nursery.'),
('together6', 'iść na uniwersytet/studia', 'Po szkole pójdę na studia.', 'After school I will go to university.'),
('together6', 'założyć rodzinę', 'Chcę założyć rodzinę.', 'I want to raise a family.'),
('together6', 'mieć dziecko', 'Mama miała dziecko zeszłego roku.', 'Mum had a baby last year.'),
('together6', 'mieć dzieci', 'Oni mają trójkę dzieci.', 'They have three children.'),
('together6', 'skończyć szkołę', 'Skończę szkołę w czerwcu.', 'I will leave school in June.'),
('together6', 'przejść na emeryturę', 'Dziadek przeszedł na emeryturę.', 'Grandad retired.'),
('together6', 'zacząć szkołę', 'Mój brat zacznie szkołę we wrześniu.', 'My brother will start school in September.'),
('together6', 'dorosły', 'Mój tata jest dorosły.', 'My dad is an adult.'),
('together6', 'niemowlę, dziecko', 'Niemowlę śpi.', 'The baby is sleeping.'),
('together6', 'dziecko (dzieci)', 'Dzieci bawią się w parku.', 'The children are playing in the park.'),
('together6', 'dziecko w wieku 9-12 lat', 'Mój brat to dziecko w wieku 9-12 lat.', 'My brother is a pre-teen.'),
('together6', 'nastolatek/nastolatka', 'Moja siostra to nastolatka.', 'My sister is a teenager.'),
('together6', 'urodziny', 'Moje urodziny są w maju.', 'My birthday is in May.'),
('together6', 'Dzień Ojca', 'Dzień Ojca jest w czerwcu.', 'Father''s Day is in June.'),
('together6', 'Dzień Matki', 'Dzień Matki jest w maju.', 'Mother''s Day is in May.'),
('together6', 'sylwester', 'W Sylwestra są fajerwerki.', 'There are fireworks on New Year''s Eve.'),
('together6', 'ślub', 'Idziemy na ślub.', 'We are going to a wedding.'),
('together6', 'zdmuchnąć świeczki', 'Zdmuchuję świeczki na torcie.', 'I am blowing out candles on the cake.'),
('together6', 'przebrać się, stroić', 'Lubię przebierać się na imprezę.', 'I like to dress up for parties.'),
('together6', 'wręczać kartki/prezenty', 'Wręczam kartki na urodziny.', 'I give cards on birthdays.'),
('together6', 'urządzać przyjęcie z grillem', 'Latem urządzamy przyjęcie z grillem.', 'In summer we have a barbecue.'),
('together6', 'jeść ciasto/tort', 'Jemy tort na urodzinach.', 'We have a cake at the birthday.'),
('together6', 'jeść rodzinny posiłek', 'W niedzielę jemy rodzinny posiłek.', 'We have a family meal on Sunday.'),
('together6', 'urządzać imprezę (bal przebierańców)', 'Urządzamy imprezę bal przebierańców.', 'We are having a fancy dress party.'),
('together6', 'zapraszać gości', 'Zapraszam gości na urodziny.', 'I am inviting guests for my birthday.'),
('together6', 'Wspaniałe przyjęcie!', 'Wspaniałe przyjęcie!', 'Great party!'),
('together6', 'To łatwe!', 'To łatwe!', 'That is easy!'),
('together6', 'Nie mam pojęcia!', 'Nie mam pojęcia!', 'I have no idea!'),
('together6', 'Podpowiedz mi. / Naprowadź mnie.', 'Podpowiedz mi.', 'Give me a clue.'),
('together6', 'To dziwne!', 'To dziwne!', 'That is strange!'),
('together6', 'Dziękuję za wspaniałe przyjęcie/świetną imprezę!', 'Dziękuję za wspaniałe przyjęcie!', 'Thanks for a great party!'),
('together6', 'Proszę.', 'Proszę.', 'You are welcome.'),
('together6', 'Cieszę się, że Ci się podobało.', 'Cieszę się, że Ci się podobało.', 'Glad you enjoyed it.'),
('together6', 'Świetnie się bawiłem/bawiłam.', 'Świetnie się bawiłem.', 'I had a really good time.'),
('together6', 'Dziękuję za prezent.', 'Dziękuję za prezent.', 'Thanks for the present.'),
('together6', 'Bardzo mi się podobało.', 'Bardzo mi się podobało.', 'I really enjoyed the party.'),
('together6', 'Dziękuję za wszystko!', 'Dziękuję za wszystko!', 'Thanks for everything!'),
('together6', 'Nie ma za co.', 'Nie ma za co.', 'That is all right.'),
('together6', 'Dziękuję, że przyeszłeś/przyszłaś.', 'Dziękuję, że przyszedłeś.', 'Thanks for coming.'),
('together6', 'Masz wszystko?', 'Masz wszystko?', 'Have you got everything?'),
('together6', 'guzik', 'Mam guzik na koszuli.', 'I have a button on my shirt.'),
('together6', 'dyplom', 'Dostałem dyplom z konkursu.', 'I got a diploma from the competition.'),
('together6', 'maszerować', 'Żołnierze maszerują w paradzie.', 'Soldiers are marching in the parade.'),
('together6', 'gimnazjum', 'Chodziłem do gimnazjum 3 lata.', 'I went to middle school for 3 years.'),
('together6', 'ciężarówka', 'Ciężarówka jedzie szybko.', 'The truck is going fast.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 4 — Hobbies, films, interests (47)
-- ═══════════════════════════════════════════════════════════
('together6', 'tworzenie filmów animowanych', 'Lubię tworzenie filmów animowanych.', 'I like animation.'),
('together6', 'taniec baletowy', 'Trenuję taniec baletowy.', 'I do ballet dancing.'),
('together6', 'kolekcjonowanie figurek', 'Lubię kolekcjonowanie figurek.', 'I like collecting action figures.'),
('together6', 'taniec hip-hopowy', 'Lubię taniec hip-hopowy.', 'I like hip hop dancing.'),
('together6', 'tworzenie biżuterii', 'Lubię tworzenie biżuterii.', 'I like making jewellery.'),
('together6', 'rysowanie komiksów', 'Lubię rysowanie komiksów.', 'I like making comics.'),
('together6', 'gra na perkusji', 'Mój brat gra na perkusji.', 'My brother plays the drums.'),
('together6', 'gra na keyboardzie', 'Lubię grać na keyboardzie.', 'I like playing keyboards.'),
('together6', 'ceramika', 'Lubię ceramikę.', 'I like pottery.'),
('together6', 'śpiewanie w zespole', 'Lubię śpiewanie w zespole.', 'I like singing in a band.'),
('together6', 'jazda konna', 'Lubię jazdę konną.', 'I like horse-riding.'),
('together6', 'jazda na łyżwach', 'Zimą lubię jazdę na łyżwach.', 'I like ice-skating in winter.'),
('together6', 'karate', 'Trenuję karate.', 'I do karate.'),
('together6', 'jazda na snowboardzie', 'Lubię jazdę na snowboardzie.', 'I like snowboarding.'),
('together6', 'tenis stołowy', 'Gram w tenisa stołowego w szkole.', 'I play table tennis at school.'),
('together6', 'film akcji', 'Lubię filmy akcji.', 'I like action films.'),
('together6', 'film animowany', 'Mój brat lubi filmy animowane.', 'My brother likes animated films.'),
('together6', 'komedia', 'Komedia jest zabawna.', 'A comedy is funny.'),
('together6', 'film fantasy', 'Lubię filmy fantasy.', 'I like fantasy films.'),
('together6', 'horror', 'Horror jest straszny.', 'A horror film is scary.'),
('together6', 'musical', 'Idziemy do teatru na musical.', 'We are going to the theatre to see a musical.'),
('together6', 'romans', 'Mama lubi romanse.', 'Mum likes romantic films.'),
('together6', 'film science fiction', 'Lubię filmy science fiction.', 'I like science-fiction films.'),
('together6', 'reżyser / reżyserka', 'Reżyser zrobił świetny film.', 'The director made a great film.'),
('together6', 'główny bohater / główna bohaterka', 'Główny bohater jest odważny.', 'The main character is brave.'),
('together6', 'akcja, wątek', 'Akcja filmu jest interesująca.', 'The plot of the film is interesting.'),
('together6', 'efekty specjalne', 'Efekty specjalne są niesamowite.', 'The special effects are amazing.'),
('together6', 'lał deszcz', 'Lał deszcz cały dzień.', 'It was pouring with rain all day.'),
('together6', 'cały / cała zmokłem / zmokłam', 'Cały zmokłem na deszczu.', 'I got soaked in the rain.'),
('together6', 'byłem / byłam przerażony / przerażona', 'Byłem przerażony oglądając horror.', 'I was terrified watching the horror film.'),
('together6', 'wierz lub nie', 'Wierz lub nie, ale wygrałem.', 'Believe it or not, I won.'),
('together6', 'nie przepadam za (grami planszowymi)', 'Nie przepadam za grami planszowymi.', 'I am not really into board games.'),
('together6', 'uwielbiasz (czytać komiksy)', 'Uwielbiasz czytać komiksy.', 'You love reading comics.'),
('together6', 'nie jestem zbyt dobry / dobra w (rysowaniu)', 'Nie jestem zbyt dobry w rysowaniu.', 'I am not very good at drawing.'),
('together6', 'lubię (filmy animowane)', 'Lubię filmy animowane.', 'I like animated films.'),
('together6', 'interesuję się (nauką, jak to robić)', 'Interesuję się nauką, jak to robić.', 'I am interested in learning how to do it.'),
('together6', 'nie przepadam za (sportami indywidualnymi)', 'Nie przepadam za sportami indywidualnymi.', 'I am not keen on individual sports.'),
('together6', 'lubię (słuchać muzyki)', 'Lubię słuchać muzyki.', 'I enjoy listening to music.'),
('together6', 'okropnie śpiewam', 'Okropnie śpiewam.', 'I am terrible at singing!'),
('together6', 'jestem fanem / fanką (muzyki hip-hopowej)', 'Jestem fanem muzyki hip-hopowej.', 'I am a fan of hip hop music.'),
('together6', 'lubię (tańczyć)', 'Lubię tańczyć.', 'I like dancing.'),
('together6', 'starodawny', 'To starodawna księga.', 'This is an ancient book.'),
('together6', 'oddychać', 'Trudno mi oddychać.', 'It is hard to breathe.'),
('together6', 'motyl', 'Motyl jest piękny.', 'The butterfly is beautiful.'),
('together6', 'chronić', 'Chronię swoją rodzinę.', 'I protect my family.'),
('together6', 'rzeźba', 'W muzeum jest piękna rzeźba.', 'There is a beautiful sculpture in the museum.'),
('together6', 'dym', 'Z komina idzie dym.', 'There is smoke from the chimney.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 5 — Health, illness, advice (50)
-- ═══════════════════════════════════════════════════════════
('together6', 'przeziębienie', 'Mam przeziębienie.', 'I have got a cold.'),
('together6', 'kaszel', 'Mam kaszel od tygodnia.', 'I have got a cough for a week.'),
('together6', 'gorączka', 'Mam gorączkę.', 'I have got a fever.'),
('together6', 'ból głowy', 'Boli mnie głowa.', 'I have got a headache.'),
('together6', 'katar', 'Mam katar.', 'I have got a runny nose.'),
('together6', 'ból gardła', 'Boli mnie gardło.', 'I have got a sore throat.'),
('together6', 'ból brzucha', 'Boli mnie brzuch.', 'I have got a stomach ache.'),
('together6', 'ból ucha', 'Boli mnie ucho.', 'I have got an earache.'),
('together6', 'grypa', 'Mam grypę i gorączkę.', 'I have got the flu and a fever.'),
('together6', 'ból zęba', 'Boli mnie ząb.', 'I have got a toothache.'),
('together6', 'złamać rękę', 'Złamałem rękę na nartach.', 'I broke an arm skiing.'),
('together6', 'złamać nogę', 'Brat złamał nogę.', 'My brother broke a leg.'),
('together6', 'skaleczyć się w palec', 'Skaleczyłem się w palec.', 'I cut a finger.'),
('together6', 'skaleczyć się w kolano', 'Skaleczyłem się w kolano.', 'I cut a knee.'),
('together6', 'czuć się chorym', 'Czuję się chorym.', 'I feel ill.'),
('together6', 'odczuwać zawroty głowy', 'Odczuwam zawroty głowy.', 'I feel dizzy.'),
('together6', 'mieć alergię/uczulenie', 'Mam alergię na orzechy.', 'I have got an allergy to nuts.'),
('together6', 'zranić się w/uszkodzić ramię', 'Zraniłem się w ramię.', 'I hurt my shoulder.'),
('together6', 'wezwać pogotowie', 'Wezwij pogotowie!', 'Call an ambulance!'),
('together6', 'mieć prześwietlenie', 'Lekarz każe mi mieć prześwietlenie.', 'The doctor wants me to have an X-ray.'),
('together6', 'mieć operację', 'Tata miał operację w zeszłym roku.', 'Dad had surgery last year.'),
('together6', 'założyć bandaż', 'Mama założyła mi bandaż.', 'Mum put on a bandage.'),
('together6', 'przykleić plaster', 'Przykleiłem plaster na palec.', 'I put on a plaster on my finger.'),
('together6', 'pójść do lekarza', 'Powinieneś pójść do lekarza.', 'You should see a doctor.'),
('together6', 'zostać w łóżku', 'Powinieneś zostać w łóżku.', 'You should stay in bed.'),
('together6', 'przyjmować lekarstwo/lekarstwa', 'Muszę przyjmować lekarstwa codziennie.', 'I have to take some medicine every day.'),
('together6', 'brać tabletki', 'Biorę tabletki na ból głowy.', 'I take some tablets for headache.'),
('together6', 'mierzyć temperaturę', 'Mierzę sobie temperaturę.', 'I am taking my temperature.'),
('together6', 'To straszne!', 'To straszne!', 'That is terrible!'),
('together6', 'Nie jest tak źle.', 'Nie jest tak źle.', 'It is not too bad.'),
('together6', 'Czy potrzebujesz przy tym pomocy?', 'Czy potrzebujesz przy tym pomocy?', 'Do you need any help with that?'),
('together6', 'Pozytywem jest to, że...', 'Pozytywem jest to, że jest weekend.', 'The good thing is that it is the weekend.'),
('together6', 'Masz szczęście!', 'Masz szczęście!', 'Lucky you!'),
('together6', 'Uważam, że nie powinieneś/powinnaś iść jutro do szkoły.', 'Uważam, że nie powinieneś iść jutro do szkoły.', 'I do not think you should come to school tomorrow.'),
('together6', 'Masz jakieś pomysły?', 'Masz jakieś pomysły?', 'Have you got any ideas?'),
('together6', 'Powinieneś/Powinnaś powiedzieć nauczycielce, że się nie czujesz dobrze.', 'Powinieneś powiedzieć nauczycielce, że się nie czujesz dobrze.', 'I think you should tell the teacher that you do not feel well.'),
('together6', 'Dobry pomysł.', 'Dobry pomysł.', 'That is a good idea.'),
('together6', 'Co jeszcze powinienem/powinnam zrobić?', 'Co jeszcze powinienem zrobić?', 'What else should I do?'),
('together6', 'Ważne, żeby pić dużo wody.', 'Ważne, żeby pić dużo wody.', 'It is important to drink a lot of water.'),
('together6', 'Nie zapomnij pójść wcześnie spać.', 'Nie zapomnij pójść wcześnie spać.', 'Do not forget to go to bed early.'),
('together6', 'Nie sądzę, że to jest dobry pomysł, aby pracować dziś wieczorem.', 'Nie sądzę, że to dobry pomysł, by pracować dziś wieczorem.', 'I do not think it is a good idea to work this evening.'),
('together6', 'Powinieneś/Powinnaś dobrze się wyspać.', 'Powinieneś dobrze się wyspać.', 'You should try to get a good night sleep.'),
('together6', 'Myślę, że masz rację.', 'Myślę, że masz rację.', 'I think you are right.'),
('together6', 'Tak zrobię.', 'Tak zrobię.', 'I will do that.'),
('together6', 'dostarczać', 'Dostarczam paczki.', 'I deliver parcels.'),
('together6', 'nagły wypadek', 'To nagły wypadek!', 'It is an emergency!'),
('together6', 'lekarstwa', 'Karetka wiezie lekarstwa.', 'The ambulance is delivering medical supplies.'),
('together6', 'pacjent/pacjentka', 'Pacjent jest w szpitalu.', 'The patient is in the hospital.'),
('together6', 'syrena', 'Słyszę syrenę karetki.', 'I can hear the siren of the ambulance.'),
('together6', 'szczepionka', 'Dostałem szczepionkę przeciw grypie.', 'I got the flu vaccine.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 6 — Sport, equipment, success (43)
-- ═══════════════════════════════════════════════════════════
('together6', 'rakieta (do tenisa stołowego)', 'Mam nową rakietę do tenisa stołowego.', 'I have a new bat for table tennis.'),
('together6', 'buty (np. do jazdy na nartach)', 'Mam nowe buty do nart.', 'I have new ski boots.'),
('together6', 'okulary (np. do pływania)', 'Mam okulary do pływania.', 'I have swimming goggles.'),
('together6', 'łyżwy', 'Mam nowe łyżwy.', 'I have new ice skates.'),
('together6', 'rakieta (do tenisa)', 'Mam nową rakietę tenisową.', 'I have a new tennis racket.'),
('together6', 'rolki', 'Lubię jeździć na rolkach.', 'I like to skate on rollerblades.'),
('together6', 'narty', 'Zimą używam nart.', 'In winter I use my skis.'),
('together6', 'kostium/strój pływacki', 'Mam nowy kostium pływacki.', 'I have a new swimming costume.'),
('together6', 'dres', 'Noszę dres na lekcji wf-u.', 'I wear a tracksuit at PE class.'),
('together6', 'kąpielówki', 'Mam niebieskie kąpielówki.', 'I have blue trunks.'),
('together6', 'boisko do piłki nożnej/do hokeja na trawie', 'Gramy na boisku do piłki nożnej.', 'We are playing on the football pitch.'),
('together6', 'lodowisko', 'Idziemy na lodowisko.', 'We are going to the ice rink.'),
('together6', 'bieżnia', 'Trenuję na bieżni.', 'I train on the running track.'),
('together6', 'stok narciarski', 'Jeździmy na stoku narciarskim.', 'We are skiing on the ski slope.'),
('together6', 'kort tenisowy/boisko do koszykówki', 'Gramy na korcie tenisowym.', 'We are playing on the tennis court.'),
('together6', 'trener/trenerka', 'Mój trener jest miły.', 'My coach is nice.'),
('together6', 'zakończyć się remisem', 'Mecz zakończył się remisem.', 'The match ended in a draw.'),
('together6', 'przegrać', 'Nasza drużyna przegrała.', 'Our team lost.'),
('together6', 'medal', 'Wygrał złoty medal.', 'He won a gold medal.'),
('together6', 'sędzia sportowy', 'Sędzia sportowy gwiżdże.', 'The referee blows the whistle.'),
('together6', 'ustanowić rekord', 'On ustanowił rekord świata.', 'He set a world record.'),
('together6', 'wziąć udział w', 'Wziąłem udział w konkursie.', 'I took part in the competition.'),
('together6', 'trenować', 'Trenuję trzy razy w tygodniu.', 'I train three times a week.'),
('together6', 'trofeum, puchar', 'Wygraliśmy trofeum.', 'We won the trophy.'),
('together6', 'wygrać', 'Chcę wygrać turniej.', 'I want to win the tournament.'),
('together6', 'Nie wiem, co robić.', 'Nie wiem, co robić.', 'I do not know what to do.'),
('together6', 'Rzucę okiem.', 'Rzucę okiem.', 'I will have a look.'),
('together6', 'Założę się, że...', 'Założę się, że wygramy.', 'I bet we will win.'),
('together6', 'Wziąłem/wzięłam to przez pomyłkę.', 'Wziąłem to przez pomyłkę.', 'I took it by mistake.'),
('together6', 'Wielkie dzięki!', 'Wielkie dzięki!', 'Thanks a million!'),
('together6', 'A może zrobimy coś wspólnie?', 'A może zrobimy coś wspólnie?', 'Why do not we do something together?'),
('together6', 'W soboty gram w tenisa, może się przyłączysz?', 'W soboty gram w tenisa, może się przyłączysz?', 'I play tennis on Saturdays, maybe you could join me?'),
('together6', 'Nie jestem przekonany/przekonana.', 'Nie jestem przekonany.', 'I am not sure.'),
('together6', 'Czy wolisz sporty halowe czy na świeżym powietrzu?', 'Czy wolisz sporty halowe czy na świeżym powietrzu?', 'Do you prefer indoor or outdoor sports?'),
('together6', 'Zdecydowanie wolę sporty halowe.', 'Zdecydowanie wolę sporty halowe.', 'I definitely prefer indoor sports.'),
('together6', 'A co powiesz na pływanie?', 'A co powiesz na pływanie?', 'What about swimming then?'),
('together6', 'Wolę koszykówkę od siatkówki, ale nie jestem jej wielkim fanem/wielką fanką.', 'Wolę koszykówkę od siatkówki, ale nie jestem jej wielkim fanem.', 'I prefer basketball to volleyball, but I am not really a fan.'),
('together6', 'Już wiem! Zacznijmy grać w ping-ponga!', 'Już wiem! Zacznijmy grać w ping-ponga!', 'I know! Let us play table tennis!'),
('together6', 'kolumna', 'Kolumna jest wysoka.', 'The column is tall.'),
('together6', 'ogrzewany', 'Mamy ogrzewany basen.', 'We have a heated swimming pool.'),
('together6', 'pandemia', 'Pandemia była trudnym czasem.', 'The pandemic was a difficult time.'),
('together6', 'miejsce, lokalizacja', 'Jakie jest miejsce wydarzenia?', 'What is the venue of the event?'),

-- ═══════════════════════════════════════════════════════════
-- Unit 7 — Shops, shopping, payments (45)
-- ═══════════════════════════════════════════════════════════
('together6', 'księgarnia', 'Kupuję książki w księgarni.', 'I buy books at the bookshop.'),
('together6', 'sklep z ubraniami', 'Mama kupuje sukienkę w sklepie z ubraniami.', 'Mum is buying a dress at the clothes shop.'),
('together6', 'dom handlowy', 'Idziemy do domu handlowego.', 'We are going to the department store.'),
('together6', 'sklep z elektroniką', 'Kupuję telefon w sklepie z elektroniką.', 'I am buying a phone at the electronics shop.'),
('together6', 'sklep z prezentami', 'Kupuję prezent w sklepie z prezentami.', 'I am buying a present at the gift shop.'),
('together6', 'sklep obuwniczy', 'Mama kupuje buty w sklepie obuwniczym.', 'Mum is buying shoes at the shoe shop.'),
('together6', 'sklep sportowy', 'Mam piłkę ze sklepu sportowego.', 'I have a ball from the sports shop.'),
('together6', 'sklep papierniczy', 'Kupuję zeszyty w sklepie papierniczym.', 'I am buying notebooks at the stationery shop.'),
('together6', 'sklep z zabawkami', 'W sklepie z zabawkami są lalki.', 'There are dolls in the toy shop.'),
('together6', 'piekarnia', 'Kupuję chleb w piekarni.', 'I buy bread at the baker''s.'),
('together6', 'apteka, drogeria', 'Idę do apteki po lekarstwa.', 'I am going to the chemist''s for medicine.'),
('together6', 'sklep osiedlowy', 'Mleko kupuję w sklepie osiedlowym.', 'I buy milk at the corner shop.'),
('together6', 'kwiaciarnia', 'Mama kupiła kwiaty w kwiaciarni.', 'Mum bought flowers at the florist''s.'),
('together6', 'sklep z owocami i warzywami', 'Idę do sklepu z owocami i warzywami.', 'I am going to the greengrocer''s.'),
('together6', 'kiosk z gazetami', 'Kupuję gazetę w kiosku z gazetami.', 'I am buying a newspaper at the newsagent''s.'),
('together6', 'kupować przez internet', 'Lubię kupować przez internet.', 'I like to buy online.'),
('together6', 'kupować używane produkty', 'Lubię kupować używane produkty.', 'I like to buy second hand.'),
('together6', 'kosztować', 'Książka kosztuje 30 złotych.', 'The book costs 30 zlotys.'),
('together6', 'oglądać wystawy', 'Lubię oglądać wystawy w centrum.', 'I like to go window shopping in the centre.'),
('together6', 'wydawać pieniądze na (coś)', 'Wydaję pieniądze na książki.', 'I spend money on books.'),
('together6', 'zwrócić (coś)', 'Chcę zwrócić tę koszulę.', 'I want to take this shirt back.'),
('together6', 'płacić kartą kredytową', 'Mama płaci kartą kredytową.', 'Mum is paying by credit card.'),
('together6', 'płacić za (coś)', 'Płacę za pizzę.', 'I am paying for the pizza.'),
('together6', 'płacić gotówką', 'Płacę gotówką.', 'I am paying in cash.'),
('together6', 'płacić telefonem', 'Płacę telefonem.', 'I am paying with my phone.'),
('together6', 'To za drogo!', 'To za drogo!', 'That is too expensive!'),
('together6', 'Pasują do ciebie. / Dobrze w nich wyglądasz.', 'Pasują do ciebie.', 'They suit you.'),
('together6', 'Nie mogę się zdecydować.', 'Nie mogę się zdecydować.', 'I cannot make up my mind.'),
('together6', 'Ja stawiam!', 'Ja stawiam! Ja zapłacę!', 'My treat! I will pay!'),
('together6', 'Jesteś super!', 'Jesteś super!', 'You are the best!'),
('together6', 'W czym mogę pomóc?', 'W czym mogę pomóc?', 'Can I help you?'),
('together6', 'Dziękuję, tylko oglądam.', 'Dziękuję, tylko oglądam.', 'I am just looking, thanks.'),
('together6', 'Szukam (fajnej spódnicy).', 'Szukam fajnej spódnicy.', 'I am looking for a cool skirt.'),
('together6', 'Czy mogę to przymierzyć?', 'Czy mogę to przymierzyć?', 'Can I try it on?'),
('together6', 'Przymierzalnie są tam.', 'Przymierzalnie są tam.', 'The changing rooms are over there.'),
('together6', 'Wezmę to/je.', 'Wezmę to.', 'I will take it.'),
('together6', 'Bardzo mi się podoba, ale jest za duży / za duża.', 'Bardzo mi się podoba, ale jest za duży.', 'I really like it, but I think it is too big.'),
('together6', 'Czy jest mniejszy rozmiar?', 'Czy jest mniejszy rozmiar?', 'Have you got a smaller size?'),
('together6', 'Mamy tylko ten.', 'Mamy tylko ten.', 'We have only got that one.'),
('together6', 'Jak chciałby/chciałaby Pani zapłacić?', 'Jak chciałaby Pani zapłacić?', 'How would you like to pay?'),
('together6', 'w dobrym stanie', 'Książka jest w dobrym stanie.', 'The book is in good condition.'),
('together6', 'wysypisko śmieci', 'Plastik trafia na wysypisko śmieci.', 'Plastic goes to the landfill.'),
('together6', 'opakowanie', 'Wyrzucam opakowanie do kosza.', 'I throw the packaging in the bin.'),
('together6', 'sortować', 'Sortuję śmieci do recyklingu.', 'I am sorting the rubbish for recycling.'),
('together6', 'wyrzucać', 'Nie wyrzucaj jedzenia.', 'Do not throw away food.'),

-- ═══════════════════════════════════════════════════════════
-- Unit 8 — Holidays, sightseeing, asking about attractions (42)
-- ═══════════════════════════════════════════════════════════
('together6', 'aktywny wypoczynek', 'Lubię aktywny wypoczynek.', 'I like an adventure holiday.'),
('together6', 'podróżowanie z przyczepą kempingową, karawaning', 'Lubimy karawaning.', 'We like caravan holidays.'),
('together6', 'agroturystyka', 'Spędzamy lato na agroturystyce.', 'We spend summer on a farm holiday.'),
('together6', 'zorganizowany wypoczynek', 'Wybraliśmy zorganizowany wypoczynek.', 'We chose a package holiday.'),
('together6', 'apartament, mieszkanie do wynajęcia', 'Mamy apartament nad morzem.', 'We have an apartment by the sea.'),
('together6', 'pensjonat oferujący nocleg i śniadanie', 'Spędzamy noc w pensjonacie.', 'We are spending a night at a bed and breakfast.'),
('together6', 'kemping', 'Mieszkamy na kempingu.', 'We are staying at the campsite.'),
('together6', 'dom na wsi', 'Babcia ma dom na wsi.', 'Grandma has a cottage in the countryside.'),
('together6', 'hostel', 'Mieszkamy w hostelu.', 'We are staying at the hostel.'),
('together6', 'aktywny', 'Mój brat jest aktywny.', 'My brother is active.'),
('together6', 'okropny', 'Pogoda jest okropna.', 'The weather is awful.'),
('together6', 'nudny', 'Ten film jest nudny.', 'This film is boring.'),
('together6', 'ekscytujący', 'Ten mecz jest ekscytujący.', 'This match is exciting.'),
('together6', 'odprężający', 'Ten weekend był odprężający.', 'This weekend was relaxing.'),
('together6', 'cudowny', 'To cudowny dzień.', 'It is a wonderful day.'),
('together6', 'galeria sztuki', 'Idziemy do galerii sztuki.', 'We are going to the art gallery.'),
('together6', 'most', 'Most jest stary.', 'The bridge is old.'),
('together6', 'mury miejskie', 'Stare mury miejskie są piękne.', 'The old city walls are beautiful.'),
('together6', 'latarnia morska', 'Latarnia morska świeci nocą.', 'The lighthouse shines at night.'),
('together6', 'plac główny', 'Plac główny jest w centrum.', 'The main square is in the centre.'),
('together6', 'pomnik', 'Pomnik jest na placu.', 'The monument is in the square.'),
('together6', 'piramida', 'Piramidy są w Egipcie.', 'The pyramids are in Egypt.'),
('together6', 'ruiny', 'Zwiedzamy stare ruiny.', 'We are visiting the old ruins.'),
('together6', 'posąg', 'Posąg jest wysoki.', 'The statue is tall.'),
('together6', 'wieża', 'Wieża Eiffla jest w Paryżu.', 'The Eiffel Tower is in Paris.'),
('together6', 'Chyba tak.', 'Chyba tak.', 'I guess so.'),
('together6', 'Mam dość tego deszczu.', 'Mam dość tego deszczu.', 'I am fed up with the weather.'),
('together6', 'Marzy mi się piękna plaża w sierpniu.', 'Marzy mi się piękna plaża w sierpniu.', 'I fancy a beautiful beach in August.'),
('together6', 'Brzmi wspaniale./Brzmi idealnie.', 'Brzmi wspaniale.', 'That sounds perfect.'),
('together6', 'Chciałbym/Chciałabym dowiedzieć się, które miejsca warto odwiedzić w (Oxfordzie).', 'Chciałbym dowiedzieć się, które miejsca warto odwiedzić w Oxfordzie.', 'I would like some information about places to visit in Oxford.'),
('together6', 'Czy może mi Pan/Pani powiedzieć, co warto zobaczyć?', 'Czy może mi Pan powiedzieć, co warto zobaczyć?', 'Can you give me some information about places to see?'),
('together6', 'Chciałbym/Chciałabym zobaczyć wszystkie ważne miejsca.', 'Chciałbym zobaczyć wszystkie ważne miejsca.', 'I am interested in seeing all the important sites.'),
('together6', 'Ile to kosztuje?', 'Ile to kosztuje?', 'How much does it cost?'),
('together6', 'O której godzinie odjeżdża (autobus)?', 'O której godzinie odjeżdża autobus?', 'What time does the bus leave?'),
('together6', 'O której godzinie się otwiera?', 'O której godzinie się otwiera?', 'What time does it open?'),
('together6', 'Jak się tam dostać?', 'Jak się tam dostać?', 'How can I get there?'),
('together6', 'jaskinia nietoperzy', 'Zwiedzamy jaskinię nietoperzy.', 'We are visiting the bat cave.'),
('together6', 'pożyczać', 'Pożyczam książkę z biblioteki.', 'I am borrowing a book from the library.'),
('together6', 'stulecie, wiek', 'To było w XIX stuleciu.', 'It was in the nineteenth century.'),
('together6', 'bronić', 'Mury bronią miasta.', 'The walls defend the city.'),
('together6', 'skamielina', 'Znaleźliśmy skamielinę.', 'We found a fossil.'),
('together6', 'przewodnik/przewodniczka', 'Nasz przewodnik jest świetny.', 'Our guide is great.')

ON CONFLICT (book_id, word_pl) DO UPDATE SET
  sentence_pl     = EXCLUDED.sentence_pl,
  sentence_target = EXCLUDED.sentence_target,
  updated_at      = NOW();

DO $$ BEGIN
  RAISE NOTICE 'OK — Together 6: 370 unikalnych zdan zaktualizowanych/dodanych w word_sentences (370 wpisow w data.js, brak duplikatow).';
END $$;
