#!/usr/bin/env python3
"""Generate SQL sentences for vocabulary words from all_words.json."""
import json
import re

def escape_sql(s):
    """Escape single quotes for SQL."""
    return s.replace("'", "''")

def is_phrase_or_sentence(text):
    """Check if the text is already a full phrase/sentence."""
    words = text.split()
    if any(c in text for c in '.?!'):
        return True
    if len(words) >= 5:
        return True
    sentence_starters = [
        'I ', "I'm", "I've", 'Do ', 'Is ', 'Are ', 'Can ', 'What', 'Where',
        "It's", "There's", 'Yes,', 'No,', 'Put ', 'Take ', 'Have ', 'Touch ',
        'Read ', 'Play ', 'Drink ', 'Help', 'Good ', 'Great', 'Happy', 'Here ',
        'Thank', 'Ja ', 'Czy ', 'Jest ', 'Nie ', 'Jestem ', 'Mam ', 'Gdzie ',
        'Boli ', 'Zjedz', 'Odpocznij', 'Przeczytaj', 'Pograj', 'Napij',
        'Nosze', 'Zaloz', 'Zdejmij', 'Lubie', 'Jaka ', 'Prosze', 'Dziekuje',
        'Dotknij', 'Co ', 'Gepardy', 'Krokodyle', 'Rekiny', 'Kangury', 'Goryle',
        'Nosorozce', 'Ktora', 'Jem ', 'O kt', 'Jaki ', 'Jezdze',
        'Laptopy', 'Tablety', 'Mysle', 'Mam nadzieje',
        'We ', 'They ', 'He ', 'She ', 'You ', 'My ', 'Let',
        "Don't", 'Nie,', 'Tak,',
        'Noszę', 'Załóż', 'Lubię', 'Proszę', 'Dziękuję',
        'Która', 'Jeżdżę', 'Myślę',
        'Bolą',
    ]
    for starter in sentence_starters:
        if text.startswith(starter):
            return True
    return False

def generate_sentence(pl_word, en_word, book_id):
    pl = pl_word.strip()
    en = en_word.strip()

    if is_phrase_or_sentence(pl) or is_phrase_or_sentence(en):
        return (pl, en)

    pl_clean = pl.split('/')[0].split(',')[0].strip()
    en_clean = en.split('/')[0].split(',')[0].strip()
    en_lower = en_clean.lower().strip()

    # Giant lookup table
    lookup = {
        'coat': ('Załóż płaszcz, jest zimno.', 'Put on your coat, it is cold.'),
        'jumper': ('Mój sweter jest ciepły.', 'My jumper is warm.'),
        'shoes': ('Moje buty są nowe.', 'My shoes are new.'),
        'shorts': ('Noszę spodenki latem.', 'I wear shorts in summer.'),
        'skirt': ('Moja spódnica jest niebieska.', 'My skirt is blue.'),
        'trousers': ('Te spodnie są brązowe.', 'These trousers are brown.'),
        'T-shirt': ('Moja koszulka jest biała.', 'My T-shirt is white.'),
        't-shirt': ('Moja koszulka jest biała.', 'My T-shirt is white.'),
        'cap': ('Noszę czapkę w słońcu.', 'I wear a cap in the sun.'),
        'spring': ('Wiosną kwitną kwiaty.', 'Flowers bloom in spring.'),
        'summer': ('Latem jest gorąco.', 'It is hot in summer.'),
        'autumn': ('Jesienią liście spadają.', 'Leaves fall in autumn.'),
        'winter': ('Zimą pada śnieg.', 'It snows in winter.'),
        'cloudy': ('Dzisiaj jest pochmurnie.', 'It is cloudy today.'),
        'rainy': ('Dzisiaj jest deszczowo.', 'It is rainy today.'),
        'sunny': ('Dzisiaj jest słonecznie.', 'It is sunny today.'),
        'snowy': ('Dzisiaj jest śnieżnie.', 'It is snowy today.'),
        'bathroom': ('Myję ręce w łazience.', 'I wash my hands in the bathroom.'),
        'bedroom': ('Śpię w sypialni.', 'I sleep in the bedroom.'),
        'dining room': ('Jemy obiad w jadalni.', 'We eat lunch in the dining room.'),
        'hall': ('Buty są w przedpokoju.', 'The shoes are in the hall.'),
        'kitchen': ('Mama gotuje w kuchni.', 'Mum cooks in the kitchen.'),
        'living room': ('Oglądam telewizję w salonie.', 'I watch TV in the living room.'),
        'toilet': ('Toaleta jest na górze.', 'The toilet is upstairs.'),
        'shelf': ('Książki są na półce.', 'The books are on the shelf.'),
        'cupboard': ('Talerze są w szafce.', 'The plates are in the cupboard.'),
        'desk': ('Piszę przy biurku.', 'I write at the desk.'),
        'fridge': ('Mleko jest w lodówce.', 'The milk is in the fridge.'),
        'lamp': ('Lampa jest na stole.', 'The lamp is on the table.'),
        'shower': ('Biorę prysznic rano.', 'I have a shower in the morning.'),
        'garden': ('Bawię się w ogrodzie.', 'I play in the garden.'),
        'box': ('To jest pudełko z zabawkami.', 'This is a box of toys.'),
        'ear': ('Ucho mnie boli.', 'My ear hurts.'),
        'back': ('Moje plecy bolą.', 'My back hurts.'),
        'finger': ('Mam dziesięć palców.', 'I have ten fingers.'),
        'neck': ('Szyja mnie boli.', 'My neck hurts.'),
        'toe': ('Palec u nogi mnie boli.', 'My toe hurts.'),
        'tooth': ('Ząb mnie boli.', 'My tooth hurts.'),
        'tummy': ('Brzuch mnie boli.', 'My tummy hurts.'),
        'body': ('Moje ciało jest silne.', 'My body is strong.'),
        'legs': ('Moje nogi są długie.', 'My legs are long.'),
        'nose': ('Nos jest na twarzy.', 'The nose is on the face.'),
        'mouth': ('Otwieram buzię.', 'I open my mouth.'),
        'eyes': ('Moje oczy są niebieskie.', 'My eyes are blue.'),
        'arms': ('Moje ręce są silne.', 'My arms are strong.'),
        'head': ('Moja głowa jest duża.', 'My head is big.'),
        'backache': ('Mam ból pleców.', 'I have a backache.'),
        'earache': ('Mam ból ucha.', 'I have an earache.'),
        'headache': ('Mam ból głowy.', 'I have a headache.'),
        'neck ache': ('Mam ból szyi.', 'I have a neck ache.'),
        'toothache': ('Mam ból zęba.', 'I have a toothache.'),
        'tummy ache': ('Mam ból brzucha.', 'I have a tummy ache.'),
        'bored': ('Jestem znudzony.', 'I am bored.'),
        'cold': ('Jest mi zimno.', 'I am cold.'),
        'hot': ('Jest mi gorąco.', 'I am hot.'),
        'hungry': ('Jestem głodny.', 'I am hungry.'),
        'thirsty': ('Jestem spragniony.', 'I am thirsty.'),
        'tired': ('Jestem zmęczony.', 'I am tired.'),
        'cabbage': ('Ja lubię kapustę.', 'I like cabbage.'),
        'chips': ('Jem frytki na obiad.', 'I eat chips for lunch.'),
        'meatballs': ('Pulpety są bardzo dobre.', 'Meatballs are very good.'),
        'pasta': ('Lubię jeść makaron.', 'I like eating pasta.'),
        'pizza': ('Jem pizzę w piątek.', 'I eat pizza on Friday.'),
        'salad': ('Sałatka jest zdrowa.', 'Salad is healthy.'),
        'soup': ('Zupa jest gorąca.', 'The soup is hot.'),
        'chicken': ('Kurczak jest na obiad.', 'Chicken is for lunch.'),
        'breakfast': ('Jem śniadanie o siódmej.', 'I eat breakfast at seven.'),
        'lunch': ('Jem obiad w szkole.', 'I eat lunch at school.'),
        'dinner': ('Jemy kolację razem.', 'We eat dinner together.'),
        'tea': ('Piję herbatę po obiedzie.', 'I drink tea after lunch.'),
        'snack': ('Jem przekąskę po szkole.', 'I eat a snack after school.'),
        'apple': ('Jabłko jest czerwone.', 'The apple is red.'),
        'banana': ('Banan jest żółty.', 'The banana is yellow.'),
        'yogurt': ('Jem jogurt na śniadanie.', 'I eat yogurt for breakfast.'),
        'yoghurt': ('Jem jogurt na śniadanie.', 'I eat yoghurt for breakfast.'),
        'apple pie': ('Uwielbiam szarlotkę.', 'I love apple pie.'),
        'biscuits': ('Herbatniki są słodkie.', 'Biscuits are sweet.'),
        'fish and chips': ('Lubię rybę z frytkami.', 'I like fish and chips.'),
        'cheese': ('Lubię żółty ser.', 'I like cheese.'),
        'water': ('Piję dużo wody.', 'I drink a lot of water.'),
        'cinema': ('Idziemy do kina w sobotę.', 'We go to the cinema on Saturday.'),
        'funfair': ('Wesołe miasteczko jest fajne.', 'The funfair is fun.'),
        'museum': ('Idziemy do muzeum.', 'We go to the museum.'),
        'sports centre': ('Gram w centrum sportowym.', 'I play at the sports centre.'),
        'swimming pool': ('Pływam na basenie.', 'I swim at the swimming pool.'),
        'water park': ('Park wodny jest świetny.', 'The water park is great.'),
        'zoo': ('W zoo są lwy i słonie.', 'There are lions at the zoo.'),
        'park': ('Gram w piłkę w parku.', 'I play football in the park.'),
        'play football': ('Gram w piłkę nożną po szkole.', 'I play football after school.'),
        'ride a bike': ('Jeżdżę rowerem w parku.', 'I ride a bike in the park.'),
        'roller-skate': ('Lubię jeździć na wrotkach.', 'I like to roller-skate.'),
        'swim': ('Pływam w basenie.', 'I swim in the pool.'),
        'walk': ('Chodzę na spacer codziennie.', 'I walk every day.'),
        'school': ('Chodzę do szkoły codziennie.', 'I go to school every day.'),
        'mountains': ('Jedziemy w góry zimą.', 'We go to the mountains in winter.'),
        # bugsteam3
        'kangaroo': ('Kangur skacze wysoko.', 'A kangaroo jumps high.'),
        'rhino': ('Nosorożec jest bardzo duży.', 'A rhino is very big.'),
        'cheetah': ('Gepard biega bardzo szybko.', 'A cheetah runs very fast.'),
        'tiger': ('Tygrys żyje w dżungli.', 'A tiger lives in the jungle.'),
        'whale': ('Wieloryb pływa w morzu.', 'A whale swims in the sea.'),
        'gorilla': ('Goryl jest bardzo silny.', 'A gorilla is very strong.'),
        'shark': ('Rekin żyje w morzu.', 'A shark lives in the sea.'),
        'lizard': ('Jaszczurka siedzi na kamieniu.', 'A lizard sits on a rock.'),
        'fruit': ('Owoce są zdrowe.', 'Fruit is healthy.'),
        'vegetables': ('Warzywa są zdrowe.', 'Vegetables are healthy.'),
        'insects': ('Owady są bardzo małe.', 'Insects are very small.'),
        'meat': ('Mięso jest na obiad.', 'Meat is for lunch.'),
        'fish': ('Ryby pływają w rzece.', 'Fish swim in the river.'),
        'jungle': ('W dżungli żyją małpy.', 'Monkeys live in the jungle.'),
        'desert': ('Pustynia jest gorąca.', 'The desert is hot.'),
        'sea': ('Morze jest niebieskie.', 'The sea is blue.'),
        'grasslands': ('Zebry żyją na sawannie.', 'Zebras live in the grasslands.'),
        'river': ('Rzeka jest długa.', 'The river is long.'),
        'whiskers': ('Kot ma długie wąsy.', 'The cat has long whiskers.'),
        'tongue': ('Język jest czerwony.', 'The tongue is red.'),
        'teeth': ('Myję zęby dwa razy dziennie.', 'I brush my teeth twice a day.'),
        'tail': ('Kot ma długi ogon.', 'The cat has a long tail.'),
        'wings': ('Ptak ma skrzydła.', 'A bird has wings.'),
        'claws': ('Kot ma ostre pazury.', 'The cat has sharp claws.'),
        'short': ('Mój brat jest niski.', 'My brother is short.'),
        'long': ('Wąż jest długi.', 'The snake is long.'),
        'sharp': ('Nóż jest ostry.', 'The knife is sharp.'),
        'strong': ('Goryl jest bardzo silny.', 'A gorilla is very strong.'),
        'thin': ('Pies jest chudy.', 'The dog is thin.'),
        'thick': ('Ta książka jest gruba.', 'This book is thick.'),
        'get up': ('Wstaję o siódmej rano.', 'I get up at seven in the morning.'),
        'get dressed': ('Ubieram się szybko.', 'I get dressed quickly.'),
        'have breakfast': ('Jem śniadanie o siódmej.', 'I have breakfast at seven.'),
        'brush my teeth': ('Myję zęby rano i wieczorem.', 'I brush my teeth morning and evening.'),
        'go to school': ('Idę do szkoły o ósmej.', 'I go to school at eight.'),
        'have lunch': ('Jem obiad w szkole.', 'I have lunch at school.'),
        'have a shower': ('Biorę prysznic wieczorem.', 'I have a shower in the evening.'),
        'have dinner': ('Jem kolację z rodziną.', 'I have dinner with my family.'),
        'go to bed': ('Idę spać o dziewiątej.', 'I go to bed at nine.'),
        'one': ('Mam jednego kota.', 'I have one cat.'),
        'two': ('Mam dwa psy.', 'I have two dogs.'),
        'three': ('Mam trzy książki.', 'I have three books.'),
        'four': ('Mam cztery kredki.', 'I have four crayons.'),
        'five': ('Mam pięć palców.', 'I have five fingers.'),
        'six': ('Mam sześć lat.', 'I am six years old.'),
        'seven': ('Wstaję o siódmej.', 'I get up at seven.'),
        'eight': ('Szkoła zaczyna się o ósmej.', 'School starts at eight.'),
        'nine': ('Idę spać o dziewiątej.', 'I go to bed at nine.'),
        'ten': ('Mam dziesięć palców u rąk.', 'I have ten fingers.'),
        'twelve': ('W roku jest dwanaście miesięcy.', 'There are twelve months in a year.'),
        'teacher': ('Nauczyciel uczy nas matematyki.', 'The teacher teaches us maths.'),
        'firefighter': ('Strażak gasi pożary.', 'A firefighter puts out fires.'),
        'doctor': ('Lekarz pomaga chorym.', 'A doctor helps sick people.'),
        'shop assistant': ('Sprzedawca pracuje w sklepie.', 'A shop assistant works in a shop.'),
        'police officer': ('Policjant pomaga ludziom.', 'A police officer helps people.'),
        'vet': ('Weterynarz leczy zwierzęta.', 'A vet helps animals.'),
        # stepsplus4
        'after': ('Po szkole gram w piłkę.', 'After school I play football.'),
        'age': ('Mam osiem lat.', 'I am eight years old.'),
        'all along': ('Przez cały czas to wiedziałem.', 'I knew it all along.'),
        'all the time': ('Cały czas się uśmiecham.', 'I smile all the time.'),
        'always': ('Zawsze jem śniadanie.', 'I always eat breakfast.'),
        'animal lover': ('Miłośnik zwierząt kocha psy.', 'An animal lover loves dogs.'),
        'art': ('Sztuka jest moim ulubionym przedmiotem.', 'Art is my favourite subject.'),
        'aunt': ('Moja ciotka ma psa.', 'My aunt has a dog.'),
        'best friend': ('To jest mój najlepszy przyjaciel.', 'This is my best friend.'),
        'big': ('Mój dom jest duży.', 'My house is big.'),
        'bossy': ('On jest narzucający.', 'He is bossy.'),
        'boy': ('Chłopiec biega szybko.', 'The boy runs fast.'),
        'café': ('Piję kakao w kawiarni.', 'I drink cocoa at the café.'),
        'cameraman': ('Kamerzysta nagrywa filmy.', 'A cameraman films movies.'),
        'cat': ('Mam kota w domu.', 'I have a cat at home.'),
        'child (children)': ('Dzieci bawią się w parku.', 'Children play in the park.'),
        'city': ('Miasto jest duże.', 'The city is big.'),
        'clank': ('Roboty szczękają.', 'The robots clank.'),
        'class': ('W klasie jest dwadzieścia uczniów.', 'There are twenty pupils in class.'),
        'classroom': ('Nasza sala lekcyjna jest duża.', 'Our classroom is big.'),
        'competition': ('Konkurs jest w piątek.', 'The competition is on Friday.'),
        'country': ('Wieś jest spokojna.', 'The country is quiet.'),
        'cousin': ('Mój kuzyn ma osiem lat.', 'My cousin is eight years old.'),
        'daughter': ('Córka je śniadanie.', 'The daughter eats breakfast.'),
        'director': ('Reżyser kręci filmy.', 'A director makes films.'),
        'dog': ('Mój pies jest duży.', 'My dog is big.'),
        'easy': ('To zadanie jest łatwe.', 'This task is easy.'),
        'family': ('Moja rodzina jest duża.', 'My family is big.'),
        'famous': ('Ten aktor jest sławny.', 'This actor is famous.'),
        'favourite': ('To mój ulubiony kolor.', 'This is my favourite colour.'),
        'food': ('Jedzenie jest gotowe.', 'The food is ready.'),
        'geography': ('Lubię geografię.', 'I like geography.'),
        'girl': ('Dziewczyna czyta książkę.', 'The girl reads a book.'),
        'grandad': ('Mój dziadek jest zabawny.', 'My grandad is funny.'),
        'granddaughter': ('Wnuczka rysuje obrazek.', 'The granddaughter draws a picture.'),
        'grandma': ('Moja babcia piecze ciasta.', 'My grandma bakes cakes.'),
        'grandparents': ('Moi dziadkowie mieszkają blisko.', 'My grandparents live nearby.'),
        'grandson': ('Wnuk jest mały.', 'The grandson is small.'),
        'photo': ('Robię zdjęcie.', 'I take a photo.'),
        'pop star': ('Gwiazda muzyki pop śpiewa.', 'A pop star sings songs.'),
        'prince': ('Książę mieszka w zamku.', 'The prince lives in a castle.'),
        'princess': ('Księżniczka nosi koronę.', 'The princess wears a crown.'),
        'prize': ('Nagroda jest piękna.', 'The prize is beautiful.'),
        'queen': ('Królowa mieszka w pałacu.', 'The queen lives in a palace.'),
        'question': ('Mam pytanie do nauczyciela.', 'I have a question for the teacher.'),
        'rabbit': ('Królik je marchewkę.', 'The rabbit eats a carrot.'),
        'RE (religious education)': ('Mamy religię w poniedziałek.', 'We have RE on Monday.'),
        'real': ('To jest prawdziwy diament.', 'This is a real diamond.'),
        'restaurant': ('Jemy obiad w restauracji.', 'We eat lunch at the restaurant.'),
        'robot': ('Robot jest inteligentny.', 'The robot is clever.'),
        'sister': ('Moja siostra ma sześć lat.', 'My sister is six years old.'),
        'son': ('Syn gra w piłkę.', 'The son plays football.'),
        'uncle': ('Mój wujek jest wysoki.', 'My uncle is tall.'),
        'maths': ('Matematyka jest trudna.', 'Maths is difficult.'),
        'science': ('Nauka jest ciekawa.', 'Science is interesting.'),
        'English': ('Uczę się angielskiego.', 'I learn English.'),
        'music': ('Muzyka jest fajna.', 'Music is fun.'),
        'PE': ('WF jest w środę.', 'PE is on Wednesday.'),
        'IT': ('Informatyka jest ciekawa.', 'IT is interesting.'),
        'history': ('Historia jest ciekawa.', 'History is interesting.'),
        'Monday': ('Poniedziałek to pierwszy dzień.', 'Monday is the first day.'),
        'Tuesday': ('Wtorek jest po poniedziałku.', 'Tuesday is after Monday.'),
        'Wednesday': ('W środę mam WF.', 'I have PE on Wednesday.'),
        'Thursday': ('W czwartek mam angielski.', 'I have English on Thursday.'),
        'Friday': ('Piątek jest moim ulubionym dniem.', 'Friday is my favourite day.'),
        'Saturday': ('W sobotę nie chodzę do szkoły.', 'I don''t go to school on Saturday.'),
        'Sunday': ('Niedziela jest dniem wolnym.', 'Sunday is a day off.'),
        'mum': ('Moja mama jest miła.', 'My mum is kind.'),
        'dad': ('Mój tata jest wysoki.', 'My dad is tall.'),
        'brother': ('Mój brat gra w piłkę.', 'My brother plays football.'),
        'parents': ('Moi rodzice pracują.', 'My parents work.'),
        'baby': ('Niemowlę śpi.', 'The baby sleeps.'),
        'friend': ('Mój przyjaciel jest miły.', 'My friend is kind.'),
        'twin': ('Mam brata bliźniaka.', 'I have a twin brother.'),
        'twins': ('Bliźniaki wyglądają tak samo.', 'The twins look the same.'),
        'neighbour': ('Mój sąsiad jest miły.', 'My neighbour is kind.'),
        'table': ('Stół jest w kuchni.', 'The table is in the kitchen.'),
        'chair': ('Usiądź na krześle.', 'Sit on the chair.'),
        'bed': ('Idę do łóżka o ósmej.', 'I go to bed at eight.'),
        'sofa': ('Siadam na kanapie.', 'I sit on the sofa.'),
        'wardrobe': ('Ubrania są w szafie.', 'The clothes are in the wardrobe.'),
        'mirror': ('Patrzę w lustro.', 'I look in the mirror.'),
        'bath': ('Biorę kąpiel wieczorem.', 'I have a bath in the evening.'),
        'armchair': ('Tata siedzi w fotelu.', 'Dad sits in the armchair.'),
        'bookcase': ('Regał jest pełen książek.', 'The bookcase is full of books.'),
        'carpet': ('Dywan jest miękki.', 'The carpet is soft.'),
        'cooker': ('Kuchenka jest w kuchni.', 'The cooker is in the kitchen.'),
        'curtains': ('Zasłony są zielone.', 'The curtains are green.'),
        'dishwasher': ('Zmywarka myje talerze.', 'The dishwasher cleans plates.'),
        'fireplace': ('Kominek jest ciepły.', 'The fireplace is warm.'),
        'rug': ('Dywanik jest na podłodze.', 'The rug is on the floor.'),
        'sink': ('Zlew jest w kuchni.', 'The sink is in the kitchen.'),
        'washing machine': ('Pralka pierze ubrania.', 'The washing machine washes clothes.'),
        'picture': ('Obrazek wisi na ścianie.', 'The picture is on the wall.'),
        'poster': ('Plakat jest na ścianie.', 'The poster is on the wall.'),
        'flat': ('Mieszkam w mieszkaniu.', 'I live in a flat.'),
        'house': ('Mój dom jest duży.', 'My house is big.'),
        'block of flats': ('Mieszkam w bloku.', 'I live in a block of flats.'),
        'detached house': ('To jest dom wolnostojący.', 'This is a detached house.'),
        'cottage': ('Domek jest na wsi.', 'The cottage is in the country.'),
        'palace': ('Pałac jest bardzo duży.', 'The palace is very big.'),
        'castle': ('Zamek jest stary.', 'The castle is old.'),
        'downstairs': ('Kuchnia jest na dole.', 'The kitchen is downstairs.'),
        'upstairs': ('Sypialnia jest na górze.', 'The bedroom is upstairs.'),
        'garage': ('Samochód jest w garażu.', 'The car is in the garage.'),
        'attic': ('Na strychu są stare rzeczy.', 'There are old things in the attic.'),
        'balcony': ('Stoimy na balkonie.', 'We stand on the balcony.'),
        'roof': ('Dach jest czerwony.', 'The roof is red.'),
        'wall': ('Ściana jest biała.', 'The wall is white.'),
        'floor': ('Podłoga jest czysta.', 'The floor is clean.'),
        'door': ('Zamknij drzwi.', 'Close the door.'),
        'window': ('Otwórz okno.', 'Open the window.'),
        'stairs': ('Schody prowadzą na górę.', 'The stairs go upstairs.'),
        'laptop': ('Mam laptopa do nauki.', 'I have a laptop for learning.'),
        'computer': ('Gram na komputerze.', 'I play on the computer.'),
        'mobile phone': ('Mam telefon komórkowy.', 'I have a mobile phone.'),
        'tablet': ('Rysuję na tablecie.', 'I draw on the tablet.'),
        'keyboard': ('Piszę na klawiaturze.', 'I type on the keyboard.'),
        'camera': ('Robię zdjęcia aparatem.', 'I take photos with a camera.'),
        'screen': ('Ekran jest duży.', 'The screen is big.'),
        'mouse': ('Klikam myszką.', 'I click the mouse.'),
        'feathers': ('Ptak ma piękne pióra.', 'The bird has pretty feathers.'),
        'shell': ('Żółw ma skorupę.', 'A turtle has a shell.'),
        'fur': ('Kot ma miękkie futro.', 'The cat has soft fur.'),
        'beak': ('Ptak ma dziób.', 'A bird has a beak.'),
        'scales': ('Ryba ma łuski.', 'A fish has scales.'),
        'mammals': ('Ssaki mają futro.', 'Mammals have fur.'),
        'reptiles': ('Gady mają łuski.', 'Reptiles have scales.'),
        'amphibians': ('Płazy żyją w wodzie i na lądzie.', 'Amphibians live in water and on land.'),
        'birds': ('Ptaki latają po niebie.', 'Birds fly in the sky.'),
        'fruit juice': ('Piję sok owocowy.', 'I drink fruit juice.'),
        'sandwiches': ('Robię kanapki na obiad.', 'I make sandwiches for lunch.'),
        'crisps': ('Chipsy są słone.', 'Crisps are salty.'),
        'chocolate': ('Czekolada jest słodka.', 'Chocolate is sweet.'),
        'strawberries': ('Truskawki są czerwone.', 'Strawberries are red.'),
        'ice cream': ('Uwielbiam lody.', 'I love ice cream.'),
        'sweet': ('Cukierki są słodkie.', 'Sweets are sweet.'),
        'salty': ('Te chipsy są słone.', 'These crisps are salty.'),
        'sour': ('Cytryna jest kwaśna.', 'A lemon is sour.'),
        'bitter': ('Ta herbata jest gorzka.', 'This tea is bitter.'),
        'healthy': ('Owoce są zdrowe.', 'Fruit is healthy.'),
        'dessert': ('Deser jest pyszny.', 'The dessert is delicious.'),
        'happy': ('Jestem szczęśliwy.', 'I am happy.'),
        'sad': ('Jestem smutny.', 'I am sad.'),
        'angry': ('Jestem zły.', 'I am angry.'),
        'scared': ('Jestem przestraszony.', 'I am scared.'),
        'surprised': ('Jestem zaskoczony.', 'I am surprised.'),
        'worried': ('Jestem zmartwiony.', 'I am worried.'),
        'excited': ('Jestem podekscytowany.', 'I am excited.'),
        'nervous': ('Jestem zdenerwowany.', 'I am nervous.'),
        'hat': ('Czapka jest na głowie.', 'The hat is on my head.'),
        'scarf': ('Szalik jest ciepły.', 'The scarf is warm.'),
        'gloves': ('Rękawiczki są ciepłe.', 'The gloves are warm.'),
        'boots': ('Noszę buty zimą.', 'I wear boots in winter.'),
        'dress': ('Moja sukienka jest różowa.', 'My dress is pink.'),
        'jacket': ('Kurtka jest w szafie.', 'The jacket is in the wardrobe.'),
        'jeans': ('Noszę dżinsy do szkoły.', 'I wear jeans to school.'),
        'socks': ('Moje skarpetki są białe.', 'My socks are white.'),
        'trainers': ('Noszę buty sportowe na WF.', 'I wear trainers for PE.'),
        'uniform': ('Noszę mundur do szkoły.', 'I wear a uniform to school.'),
        'pyjamas': ('Wkładam piżamę przed snem.', 'I put on my pyjamas before bed.'),
        'swimsuit': ('Wkładam kostium na basen.', 'I wear a swimsuit to the pool.'),
        'hoodie': ('Moja bluza jest wygodna.', 'My hoodie is comfortable.'),
        'shirt': ('Koszula jest biała.', 'The shirt is white.'),
        'sunglasses': ('Noszę okulary w słońcu.', 'I wear sunglasses in the sun.'),
        'slippers': ('Noszę kapcie w domu.', 'I wear slippers at home.'),
        'tracksuit': ('Noszę dres na WF.', 'I wear a tracksuit for PE.'),
        'tights': ('Rajstopy są ciepłe.', 'Tights are warm.'),
        'wellies': ('Noszę kalosze w deszczu.', 'I wear wellies in the rain.'),
        'raincoat': ('Wkładam płaszcz w deszczu.', 'I put on my raincoat in the rain.'),
        'hair': ('Moje włosy są brązowe.', 'My hair is brown.'),
        'face': ('Myję twarz rano.', 'I wash my face in the morning.'),
        'hand': ('Daj mi rękę.', 'Give me your hand.'),
        'hands': ('Myję ręce przed jedzeniem.', 'I wash my hands before eating.'),
        'feet': ('Moje stopy są małe.', 'My feet are small.'),
        'knee': ('Kolano mnie boli.', 'My knee hurts.'),
        'shoulder': ('Ramię mnie boli.', 'My shoulder hurts.'),
        'stomach': ('Żołądek mnie boli.', 'My stomach hurts.'),
        'car': ('Jedziemy samochodem do szkoły.', 'We go to school by car.'),
        'bus': ('Jadę autobusem do szkoły.', 'I go to school by bus.'),
        'bike': ('Jeżdżę rowerem do parku.', 'I ride my bike to the park.'),
        'train': ('Jedziemy pociągiem do babci.', 'We go to grandma by train.'),
        'plane': ('Lecimy samolotem na wakacje.', 'We fly by plane on holiday.'),
        'boat': ('Łódka pływa po jeziorze.', 'A boat sails on the lake.'),
        'helicopter': ('Helikopter lata wysoko.', 'A helicopter flies high.'),
        'scooter': ('Jeżdżę na hulajnodze.', 'I ride a scooter.'),
        'hospital': ('Szpital jest duży.', 'The hospital is big.'),
        'library': ('Czytam książki w bibliotece.', 'I read books in the library.'),
        'shop': ('Idziemy do sklepu.', 'We go to the shop.'),
        'supermarket': ('Kupujemy jedzenie w sklepie.', 'We buy food at the supermarket.'),
        'town': ('Miasteczko jest małe.', 'The town is small.'),
        'village': ('Wioska jest mała.', 'The village is small.'),
        'beach': ('Plaża jest piaszczysta.', 'The beach is sandy.'),
        'forest': ('Las jest zielony.', 'The forest is green.'),
        'lake': ('Jezioro jest czyste.', 'The lake is clean.'),
        'island': ('Wyspa jest piękna.', 'The island is beautiful.'),
        'farm': ('Farma ma dużo zwierząt.', 'The farm has many animals.'),
        'playground': ('Dzieci bawią się na placu zabaw.', 'Children play on the playground.'),
        'post office': ('Wysyłam list na poczcie.', 'I send a letter at the post office.'),
        'police station': ('Komisariat jest obok szkoły.', 'The police station is near the school.'),
        'fire station': ('Remiza jest blisko parku.', 'The fire station is near the park.'),
        'bus stop': ('Przystanek jest obok szkoły.', 'The bus stop is near the school.'),
        'airport': ('Lotnisko jest daleko.', 'The airport is far away.'),
        'pet shop': ('Sklep zoologiczny ma rybki.', 'The pet shop has fish.'),
        'toyshop': ('Sklep z zabawkami jest fajny.', 'The toyshop is fun.'),
        'bookshop': ('Księgarnia ma dużo książek.', 'The bookshop has many books.'),
        'shopping centre': ('Centrum handlowe jest duże.', 'The shopping centre is big.'),
        'bank': ('Bank jest obok poczty.', 'The bank is next to the post office.'),
        'chemist': ('Apteka jest obok szkoły.', 'The chemist is near the school.'),
        'bakery': ('W piekarni jest świeży chleb.', 'The bakery has fresh bread.'),
        'theatre': ('Teatr jest w centrum.', 'The theatre is in the centre.'),
        'play basketball': ('Gram w koszykówkę.', 'I play basketball.'),
        'play tennis': ('Gram w tenisa.', 'I play tennis.'),
        'play volleyball': ('Gram w siatkówkę.', 'I play volleyball.'),
        'play the piano': ('Gram na pianinie.', 'I play the piano.'),
        'play the guitar': ('Gram na gitarze.', 'I play the guitar.'),
        'do gymnastics': ('Ćwiczę gimnastykę.', 'I do gymnastics.'),
        'do judo': ('Ćwiczę judo.', 'I do judo.'),
        'do karate': ('Ćwiczę karate.', 'I do karate.'),
        'go swimming': ('Chodzę na pływanie.', 'I go swimming.'),
        'go cycling': ('Jeżdżę na rowerze.', 'I go cycling.'),
        'go fishing': ('Chodzę na ryby.', 'I go fishing.'),
        'go horse riding': ('Jeżdżę konno.', 'I go horse riding.'),
        'go shopping': ('Chodzę na zakupy.', 'I go shopping.'),
        'go camping': ('Jedziemy na kemping.', 'We go camping.'),
        'hobby': ('Moje hobby to rysowanie.', 'My hobby is drawing.'),
        'run': ('Biegam w parku.', 'I run in the park.'),
        'jump': ('Skaczę bardzo wysoko.', 'I jump very high.'),
        'dance': ('Tańczę w domu.', 'I dance at home.'),
        'sing': ('Śpiewam piosenki.', 'I sing songs.'),
        'read': ('Czytam książkę wieczorem.', 'I read a book in the evening.'),
        'draw': ('Rysuję obrazek.', 'I draw a picture.'),
        'paint': ('Maluję obrazy farbami.', 'I paint pictures with paints.'),
        'write': ('Piszę w zeszycie.', 'I write in my notebook.'),
        'catch': ('Łapię piłkę.', 'I catch the ball.'),
        'throw': ('Rzucam piłkę.', 'I throw the ball.'),
        'kick': ('Kopię piłkę.', 'I kick the ball.'),
        'score a goal': ('Strzelam gola.', 'I score a goal.'),
        'win': ('Chcę wygrać mecz.', 'I want to win the game.'),
        'lose': ('Nie lubię przegrywać.', 'I don''t like to lose.'),
        'race': ('Biegam w wyścigu.', 'I run in a race.'),
        'match': ('Mecz jest w sobotę.', 'The match is on Saturday.'),
        'team': ('Moja drużyna jest świetna.', 'My team is great.'),
        'trophy': ('Mamy puchar za wygraną.', 'We have a trophy for winning.'),
        'medal': ('Zdobywam medal.', 'I win a medal.'),
        'ill': ('Jestem chory.', 'I am ill.'),
        'well': ('Czuję się dobrze.', 'I feel well.'),
        'bread': ('Chleb jest świeży.', 'The bread is fresh.'),
        'butter': ('Masło jest w lodówce.', 'The butter is in the fridge.'),
        'egg': ('Jem jajko na śniadanie.', 'I eat an egg for breakfast.'),
        'eggs': ('Jajka są na śniadanie.', 'Eggs are for breakfast.'),
        'rice': ('Ryż jest na obiad.', 'Rice is for lunch.'),
        'milk': ('Piję mleko rano.', 'I drink milk in the morning.'),
        'cake': ('Ciasto jest pyszne.', 'The cake is delicious.'),
        'sandwich': ('Robię kanapkę na obiad.', 'I make a sandwich for lunch.'),
        'ham': ('Szynka jest na kanapce.', 'The ham is on the sandwich.'),
        'honey': ('Miód jest słodki.', 'Honey is sweet.'),
        'jam': ('Dżem jest na chlebie.', 'Jam is on the bread.'),
        'cereal': ('Jem płatki na śniadanie.', 'I eat cereal for breakfast.'),
        'tomato': ('Pomidor jest czerwony.', 'The tomato is red.'),
        'potato': ('Ziemniak jest na obiad.', 'The potato is for lunch.'),
        'carrot': ('Marchewka jest pomarańczowa.', 'The carrot is orange.'),
        'onion': ('Cebula jest w zupie.', 'The onion is in the soup.'),
        'mushrooms': ('Grzyby są w lesie.', 'Mushrooms are in the forest.'),
        'pepper': ('Pieprz jest ostry.', 'Pepper is spicy.'),
        'pear': ('Gruszka jest słodka.', 'A pear is sweet.'),
        'grapes': ('Winogrona są pyszne.', 'Grapes are delicious.'),
        'lemon': ('Cytryna jest kwaśna.', 'A lemon is sour.'),
        'orange': ('Pomarańcza jest słodka.', 'An orange is sweet.'),
        'watermelon': ('Arbuz jest duży.', 'A watermelon is big.'),
        'coconut': ('Kokos jest smaczny.', 'Coconut is tasty.'),
        'mango': ('Mango jest słodkie.', 'A mango is sweet.'),
        'beans': ('Fasola jest zdrowa.', 'Beans are healthy.'),
        'corn': ('Kukurydza jest żółta.', 'Corn is yellow.'),
        'cucumber': ('Ogórek jest zielony.', 'A cucumber is green.'),
        'pineapple': ('Ananas jest słodki.', 'A pineapple is sweet.'),
        'sweets': ('Nie jem dużo słodyczy.', 'I don''t eat many sweets.'),
        'popcorn': ('Jem popcorn w kinie.', 'I eat popcorn at the cinema.'),
        'lemonade': ('Lemoniada jest zimna.', 'Lemonade is cold.'),
        'hot chocolate': ('Piję gorącą czekoladę.', 'I drink hot chocolate.'),
        'meal': ('Posiłek jest gotowy.', 'The meal is ready.'),
        'today': ('Dzisiaj jest piękny dzień.', 'Today is a beautiful day.'),
        'tomorrow': ('Jutro idziemy do parku.', 'Tomorrow we go to the park.'),
        'yesterday': ('Wczoraj byłem w szkole.', 'Yesterday I was at school.'),
        'morning': ('Jem śniadanie rano.', 'I eat breakfast in the morning.'),
        'afternoon': ('Po południu odrabiam lekcje.', 'In the afternoon I do homework.'),
        'evening': ('Wieczorem oglądam telewizję.', 'In the evening I watch TV.'),
        'night': ('W nocy śpię.', 'At night I sleep.'),
        'day': ('Dzień jest słoneczny.', 'The day is sunny.'),
        'week': ('Tydzień ma siedem dni.', 'A week has seven days.'),
        'month': ('Miesiąc ma trzydzieści dni.', 'A month has thirty days.'),
        'year': ('Rok ma dwanaście miesięcy.', 'A year has twelve months.'),
        'weekend': ('W weekend odpoczywam.', 'I rest at the weekend.'),
        'holiday': ('Wakacje są latem.', 'The holiday is in summer.'),
        'birthday': ('Moje urodziny są w maju.', 'My birthday is in May.'),
        'never': ('Nigdy nie jestem spóźniony.', 'I am never late.'),
        'sometimes': ('Czasem gram w piłkę.', 'I sometimes play football.'),
        'often': ('Często chodzę do parku.', 'I often go to the park.'),
        'usually': ('Zwykle wstaję o siódmej.', 'I usually get up at seven.'),
        'every day': ('Chodzę do szkoły codziennie.', 'I go to school every day.'),
        'before': ('Przed szkołą jem śniadanie.', 'Before school I eat breakfast.'),
        'January': ('Styczeń jest zimny.', 'January is cold.'),
        'February': ('W lutym jest walentynki.', 'Valentine''s Day is in February.'),
        'March': ('W marcu zaczyna się wiosna.', 'Spring starts in March.'),
        'April': ('W kwietniu pada deszcz.', 'It rains in April.'),
        'May': ('W maju jest ciepło.', 'It is warm in May.'),
        'June': ('W czerwcu zaczynają się wakacje.', 'Holidays start in June.'),
        'July': ('Lipiec jest gorący.', 'July is hot.'),
        'August': ('W sierpniu jedziemy na wakacje.', 'We go on holiday in August.'),
        'September': ('We wrześniu wracam do szkoły.', 'I go back to school in September.'),
        'October': ('W październiku jest Halloween.', 'Halloween is in October.'),
        'November': ('Listopad jest pochmurny.', 'November is cloudy.'),
        'December': ('W grudniu są święta.', 'Christmas is in December.'),
        'windy': ('Dzisiaj jest wietrznie.', 'It is windy today.'),
        'foggy': ('Dzisiaj jest mgliście.', 'It is foggy today.'),
        'stormy': ('Dzisiaj jest burzowo.', 'It is stormy today.'),
        'warm': ('Dzisiaj jest ciepło.', 'It is warm today.'),
        'rain': ('Pada deszcz.', 'It is raining.'),
        'snow': ('Pada śnieg.', 'It is snowing.'),
        'rainbow': ('Widzę tęczę na niebie.', 'I see a rainbow in the sky.'),
        'red': ('Jabłko jest czerwone.', 'The apple is red.'),
        'blue': ('Niebo jest niebieskie.', 'The sky is blue.'),
        'green': ('Trawa jest zielona.', 'The grass is green.'),
        'yellow': ('Banan jest żółty.', 'The banana is yellow.'),
        'pink': ('Kwiat jest różowy.', 'The flower is pink.'),
        'purple': ('Śliwka jest fioletowa.', 'The plum is purple.'),
        'white': ('Śnieg jest biały.', 'Snow is white.'),
        'black': ('Kot jest czarny.', 'The cat is black.'),
        'brown': ('Czekolada jest brązowa.', 'Chocolate is brown.'),
        'grey': ('Niebo jest szare dzisiaj.', 'The sky is grey today.'),
        'horse': ('Koń biega po polu.', 'A horse runs in the field.'),
        'frog': ('Żaba skacze do wody.', 'A frog jumps into the water.'),
        'bird': ('Ptak śpiewa na drzewie.', 'A bird sings in a tree.'),
        'parrot': ('Papuga jest kolorowa.', 'A parrot is colourful.'),
        'hamster': ('Chomik jest mały i miły.', 'A hamster is small and cute.'),
        'snake': ('Wąż jest długi.', 'A snake is long.'),
        'spider': ('Pająk robi sieć.', 'A spider makes a web.'),
        'butterfly': ('Motyl lata nad kwiatami.', 'A butterfly flies over flowers.'),
        'penguin': ('Pingwin lubi zimno.', 'A penguin likes cold weather.'),
        'bear': ('Niedźwiedź mieszka w lesie.', 'A bear lives in the forest.'),
        'cow': ('Krowa daje mleko.', 'A cow gives milk.'),
        'sheep': ('Owca jest na farmie.', 'A sheep is on the farm.'),
        'pig': ('Świnia jest na farmie.', 'A pig is on the farm.'),
        'hen': ('Kura znosi jajka.', 'A hen lays eggs.'),
        'duck': ('Kaczka pływa na jeziorze.', 'A duck swims on the lake.'),
        'elephant': ('Słoń jest bardzo duży.', 'An elephant is very big.'),
        'lion': ('Lew jest królem zwierząt.', 'A lion is the king of animals.'),
        'monkey': ('Małpa wspina się na drzewo.', 'A monkey climbs a tree.'),
        'giraffe': ('Żyrafa ma długą szyję.', 'A giraffe has a long neck.'),
        'crocodile': ('Krokodyl żyje w rzece.', 'A crocodile lives in a river.'),
        'turtle': ('Żółw chodzi powoli.', 'A turtle walks slowly.'),
        'dolphin': ('Delfin pływa szybko.', 'A dolphin swims fast.'),
        'eagle': ('Orzeł lata wysoko.', 'An eagle flies high.'),
        'owl': ('Sowa poluje w nocy.', 'An owl hunts at night.'),
        'pet': ('Mam zwierzątko domowe.', 'I have a pet.'),
        'fast': ('Gepard jest szybki.', 'A cheetah is fast.'),
        'slow': ('Żółw jest powolny.', 'A turtle is slow.'),
        'heavy': ('Ten plecak jest ciężki.', 'This bag is heavy.'),
        'light': ('Piórko jest lekkie.', 'A feather is light.'),
        'clean': ('Pokój jest czysty.', 'The room is clean.'),
        'dirty': ('Buty są brudne.', 'The shoes are dirty.'),
        'beautiful': ('Kwiat jest piękny.', 'The flower is beautiful.'),
        'nice': ('Pogoda jest ładna.', 'The weather is nice.'),
        'good': ('Ten film jest dobry.', 'This film is good.'),
        'bad': ('Pogoda jest zła.', 'The weather is bad.'),
        'new': ('Mam nowy plecak.', 'I have a new bag.'),
        'old': ('Dziadek jest stary.', 'Grandad is old.'),
        'young': ('Dziecko jest młode.', 'The child is young.'),
        'tall': ('Tata jest wysoki.', 'Dad is tall.'),
        'different': ('Jesteśmy inni.', 'We are different.'),
        'same': ('Mamy takie same buty.', 'We have the same shoes.'),
        'important': ('To jest ważne.', 'This is important.'),
        'interesting': ('Ta książka jest ciekawa.', 'This book is interesting.'),
        'boring': ('Ten film jest nudny.', 'This film is boring.'),
        'dangerous': ('Rekin jest niebezpieczny.', 'A shark is dangerous.'),
        'safe': ('Park jest bezpieczny.', 'The park is safe.'),
        'empty': ('Lodówka jest pusta.', 'The fridge is empty.'),
        'full': ('Plecak jest pełny.', 'The bag is full.'),
        'open': ('Okno jest otwarte.', 'The window is open.'),
        'closed': ('Drzwi są zamknięte.', 'The door is closed.'),
        'popular': ('Piłka nożna jest popularna.', 'Football is popular.'),
        'huge': ('Słoń jest ogromny.', 'An elephant is huge.'),
        'tiny': ('Mrówka jest malutka.', 'An ant is tiny.'),
        'dark': ('Piwnica jest ciemna.', 'The basement is dark.'),
        'bright': ('Słońce jest jasne.', 'The sun is bright.'),
        'wooden': ('Stół jest drewniany.', 'The table is wooden.'),
        'modern': ('Dom jest nowoczesny.', 'The house is modern.'),
        'ordinary': ('To jest zwykły dzień.', 'This is an ordinary day.'),
        'amazing': ('Ten film jest niesamowity.', 'This film is amazing.'),
        'strange': ('To jest dziwne.', 'That is strange.'),
        'scary': ('Ten film jest straszny.', 'This film is scary.'),
        'wonderful': ('Pogoda jest wspaniała.', 'The weather is wonderful.'),
        'perfect': ('To jest idealny dzień.', 'This is a perfect day.'),
        'terrible': ('Pogoda jest okropna.', 'The weather is terrible.'),
        'special': ('To jest wyjątkowy dzień.', 'This is a special day.'),
        'quiet': ('Bądź cicho w bibliotece.', 'Be quiet in the library.'),
        'loud': ('Muzyka jest głośna.', 'The music is loud.'),
        'friendly': ('On jest przyjazny.', 'He is friendly.'),
        'kind': ('Ona jest miła.', 'She is kind.'),
        'funny': ('On jest zabawny.', 'He is funny.'),
        'clever': ('Ona jest mądra.', 'She is clever.'),
        'naughty': ('Kot jest niegrzeczny.', 'The cat is naughty.'),
        'shy': ('Jestem nieśmiały.', 'I am shy.'),
        'brave': ('Jestem odważny.', 'I am brave.'),
        'lazy': ('Jestem leniwy dzisiaj.', 'I am lazy today.'),
        'proud': ('Jestem dumny z siebie.', 'I am proud of myself.'),
        'lonely': ('Czuję się samotny.', 'I feel lonely.'),
        'colourful': ('Motyl jest kolorowy.', 'The butterfly is colourful.'),
        'round': ('Piłka jest okrągła.', 'The ball is round.'),
        'blind': ('Pies jest niewidomy.', 'The dog is blind.'),
        'cycle lane': ('Ścieżka rowerowa jest bezpieczna.', 'The cycle lane is safe.'),
        'fewer': ('Mniej dzieci jest na placu.', 'There are fewer children here.'),
        'repair': ('Tata naprawia rower.', 'Dad repairs the bike.'),
        'solar panel': ('Panel słoneczny daje energię.', 'A solar panel gives energy.'),
        'traffic lights': ('Stoimy przy światłach drogowych.', 'We stop at the traffic lights.'),
        'be born': ('Urodziłem się w Polsce.', 'I was born in Poland.'),
        'learn to walk': ('Niemowlę uczy się chodzić.', 'A baby learns to walk.'),
        'childhood': ('Dzieciństwo jest szczęśliwe.', 'Childhood is happy.'),
        'growing up': ('Dorastanie jest ciekawe.', 'Growing up is interesting.'),
        'education': ('Edukacja jest ważna.', 'Education is important.'),
        'graduate': ('Kończę studia.', 'I graduate from university.'),
        'finish university': ('Kończę uniwersytet.', 'I finish university.'),
        'get a job': ('Dostaję pracę.', 'I get a job.'),
        'career': ('Kariera jest ważna.', 'A career is important.'),
        'fall in love': ('Zakochuję się.', 'I fall in love.'),
        'dating': ('Randkowanie jest fajne.', 'Dating is fun.'),
        'get engaged': ('Zaręczam się.', 'I get engaged.'),
        'get married': ('Biorę ślub.', 'I get married.'),
        'go to nursery': ('Idę do przedszkola.', 'I go to nursery.'),
        'go to university': ('Idę na uniwersytet.', 'I go to university.'),
        'raise a family': ('Zakładam rodzinę.', 'I raise a family.'),
        'have a baby': ('Mamy dziecko.', 'We have a baby.'),
        'have children': ('Mamy dzieci.', 'We have children.'),
        'leave school': ('Kończę szkołę.', 'I leave school.'),
        'retire': ('Przechodzę na emeryturę.', 'I retire.'),
        'start school': ('Zaczynam szkołę.', 'I start school.'),
        'adult': ('Dorosły pracuje.', 'An adult works.'),
        'pre-teen': ('Dziecko ma dziesięć lat.', 'The pre-teen is ten years old.'),
        'teenager': ('Nastolatek lubi muzykę.', 'A teenager likes music.'),
        "Father's Day": ('Dzień Ojca jest w czerwcu.', "Father''s Day is in June."),
        "Mother's Day": ('Dzień Matki jest w maju.', "Mother''s Day is in May."),
        "New Year's Eve": ('Sylwester jest ostatniego dnia roku.', "New Year''s Eve is the last day."),
        'wedding': ('Ślub jest w kościele.', 'The wedding is in church.'),
        'blow out candles': ('Zdmuchuję świeczki.', 'I blow out candles.'),
        'dress up': ('Przebieramy się na przyjęcie.', 'We dress up for the party.'),
        'give cards/presents': ('Wręczam kartki i prezenty.', 'I give cards and presents.'),
        'have a barbecue': ('Robimy grilla w ogrodzie.', 'We have a barbecue in the garden.'),
        'set off fireworks': ('Puszczamy fajerwerki.', 'We set off fireworks.'),
        'hang up decorations': ('Wieszamy dekoracje.', 'We hang up decorations.'),
        'watch a parade': ('Oglądamy paradę.', 'We watch a parade.'),
        'people': ('Ludzie są mili.', 'People are kind.'),
        'man': ('Mężczyzna jest wysoki.', 'The man is tall.'),
        'woman': ('Kobieta czyta książkę.', 'The woman reads a book.'),
        'game': ('Ta gra jest fajna.', 'This game is fun.'),
        'song': ('Ta piosenka jest piękna.', 'This song is beautiful.'),
        'story': ('Ta historia jest ciekawa.', 'This story is interesting.'),
        'tree': ('Drzewo jest wysokie.', 'The tree is tall.'),
        'flower': ('Kwiat jest piękny.', 'The flower is beautiful.'),
        'grass': ('Trawa jest zielona.', 'The grass is green.'),
        'star': ('Gwiazda świeci na niebie.', 'A star shines in the sky.'),
        'moon': ('Księżyc świeci w nocy.', 'The moon shines at night.'),
        'present': ('Dostaję prezent na urodziny.', 'I get a present for my birthday.'),
        'toy': ('Mam ulubioną zabawkę.', 'I have a favourite toy.'),
        'ball': ('Piłka jest okrągła.', 'The ball is round.'),
        'card': ('Piszę kartkę do babci.', 'I write a card to grandma.'),
        'letter': ('Piszę list do przyjaciela.', 'I write a letter to my friend.'),
        'money': ('Mam pieniądze w skarbonce.', 'I have money in my piggy bank.'),
        'key': ('Mam klucz do domu.', 'I have a key to the house.'),
        'map': ('Patrzę na mapę.', 'I look at the map.'),
        'party': ('Przyjęcie jest w sobotę.', 'The party is on Saturday.'),
        'street': ('Ulica jest długa.', 'The street is long.'),
        'road': ('Droga jest prosta.', 'The road is straight.'),
        'bridge': ('Most jest nad rzeką.', 'The bridge is over the river.'),
        'path': ('Ścieżka prowadzi do lasu.', 'The path leads to the forest.'),
        'corner': ('Sklep jest na rogu.', 'The shop is on the corner.'),
        'crossing': ('Przejście jest bezpieczne.', 'The crossing is safe.'),
        'pavement': ('Chodnik jest szeroki.', 'The pavement is wide.'),
        'tower': ('Wieża jest bardzo wysoka.', 'The tower is very tall.'),
        'painting': ('Obraz wisi na ścianie.', 'The painting is on the wall.'),
        'costume': ('Kostium jest kolorowy.', 'The costume is colourful.'),
        'glasses': ('Noszę okulary.', 'I wear glasses.'),
        'recycling': ('Recykling jest ważny.', 'Recycling is important.'),
        'ticket': ('Mam bilet do kina.', 'I have a ticket to the cinema.'),
        'adventure': ('To jest wielka przygoda.', 'This is a great adventure.'),
        'everybody': ('Wszyscy są szczęśliwi.', 'Everybody is happy.'),
        'something': ('Coś jest pod łóżkiem.', 'Something is under the bed.'),
        'nothing': ('Nic tu nie ma.', 'There is nothing here.'),
        'everything': ('Wszystko jest gotowe.', 'Everything is ready.'),
        'near': ('Szkoła jest blisko domu.', 'The school is near the house.'),
        'between': ('Park jest między szkołą a domem.', 'The park is between the school and home.'),
        'next to': ('Siedzę obok przyjaciela.', 'I sit next to my friend.'),
        'behind': ('Kot jest za kanapą.', 'The cat is behind the sofa.'),
        'in front of': ('Stoimy przed szkołą.', 'We stand in front of the school.'),
        'opposite': ('Sklep jest naprzeciwko parku.', 'The shop is opposite the park.'),
        'left': ('Skręć w lewo.', 'Turn left.'),
        'right': ('Skręć w prawo.', 'Turn right.'),
        'straight on': ('Idź prosto.', 'Go straight on.'),
        'north': ('Północ jest na górze mapy.', 'North is at the top of the map.'),
        'south': ('Południe jest na dole mapy.', 'South is at the bottom of the map.'),
        'east': ('Słońce wschodzi na wschodzie.', 'The sun rises in the east.'),
        'west': ('Słońce zachodzi na zachodzie.', 'The sun sets in the west.'),
        'name': ('Mam na imię Zosia.', 'My name is Zosia.'),
        'book': ('Czytam książkę.', 'I read a book.'),
        'pen': ('Piszę długopisem.', 'I write with a pen.'),
        'pencil': ('Rysuję ołówkiem.', 'I draw with a pencil.'),
        'rubber': ('Ścierka jest na biurku.', 'The rubber is on the desk.'),
        'ruler': ('Linijka jest długa.', 'The ruler is long.'),
        'bag': ('Plecak jest ciężki.', 'The bag is heavy.'),
        'notebook': ('Piszę w zeszycie.', 'I write in the notebook.'),
        'scissors': ('Nożyczki są ostre.', 'The scissors are sharp.'),
        'crayon': ('Kredka jest kolorowa.', 'The crayon is colourful.'),
        'board': ('Nauczyciel pisze na tablicy.', 'The teacher writes on the board.'),
        'homework': ('Odrabiam zadanie domowe.', 'I do my homework.'),
        'project': ('Robimy projekt w szkole.', 'We do a project at school.'),
        'answer': ('Odpowiedź jest poprawna.', 'The answer is correct.'),
        'idea': ('Mam dobry pomysł.', 'I have a good idea.'),
        'problem': ('Mam problem z zadaniem.', 'I have a problem with the task.'),
        'rule': ('Przestrzegaj zasad.', 'Follow the rules.'),
        'surprise': ('To jest niespodzianka.', 'This is a surprise.'),
        'half': ('Połowa tortu jest czekoladowa.', 'Half the cake is chocolate.'),
        'century': ('Wiek trwa sto lat.', 'A century is a hundred years.'),
        'first': ('Jestem pierwszy w kolejce.', 'I am first in the line.'),
        'second': ('Jestem drugi w wyścigu.', 'I am second in the race.'),
        'third': ('Jestem trzeci w klasie.', 'I am third in class.'),
        'number': ('Mój ulubiony numer to siedem.', 'My favourite number is seven.'),
        'hundred': ('W szkole jest sto uczniów.', 'There are a hundred pupils at school.'),
        'world': ('Świat jest duży.', 'The world is big.'),
        'place': ('To jest piękne miejsce.', 'This is a beautiful place.'),
        'thing': ('Co to za rzecz?', 'What is this thing?'),
        'dream': ('Mam piękny sen.', 'I have a beautiful dream.'),
        'secret': ('To jest sekret.', 'This is a secret.'),
        'noise': ('Hałas jest głośny.', 'The noise is loud.'),
        'mountain': ('Góra jest wysoka.', 'The mountain is tall.'),
        'nature': ('Natura jest piękna.', 'Nature is beautiful.'),
        'planet': ('Nasza planeta to Ziemia.', 'Our planet is Earth.'),
        'energy': ('Energia słoneczna jest czysta.', 'Solar energy is clean.'),
        'scientist': ('Naukowiec robi eksperymenty.', 'A scientist does experiments.'),
        'inventor': ('Wynalazca wymyśla nowe rzeczy.', 'An inventor creates new things.'),
        'cook': ('Gotuję z mamą.', 'I cook with mum.'),
        'nurse': ('Pielęgniarka pracuje w szpitalu.', 'A nurse works in a hospital.'),
        'farmer': ('Rolnik pracuje na farmie.', 'A farmer works on a farm.'),
        'pilot': ('Pilot lata samolotem.', 'A pilot flies a plane.'),
        'singer': ('Piosenkarz śpiewa piosenki.', 'A singer sings songs.'),
        'astronaut': ('Astronauta lata w kosmos.', 'An astronaut flies to space.'),
        'waiter': ('Kelner przynosi jedzenie.', 'A waiter brings food.'),
        'dentist': ('Dentysta sprawdza zęby.', 'The dentist checks teeth.'),
        'builder': ('Budowniczy buduje domy.', 'A builder builds houses.'),
        # beHappy2 extras
        'doll': ('Lalka ma sukienkę.', 'The doll has a dress.'),
        'kite': ('Latawiec lata wysoko.', 'The kite flies high.'),
        'teddy bear': ('Miś pluszowy jest miękki.', 'The teddy bear is soft.'),
        'plane (toy)': ('Samolot jest na stole.', 'The toy plane is on the table.'),
        'train (toy)': ('Pociąg jest zabawką.', 'The toy train is fun.'),
        'car (toy)': ('Samochodzik jest czerwony.', 'The toy car is red.'),
        'puzzle': ('Układanka jest fajna.', 'The puzzle is fun.'),
        'skipping rope': ('Skaczę na skakance.', 'I jump with a skipping rope.'),
        'lollipop': ('Lizak jest słodki.', 'The lollipop is sweet.'),
        'balloon': ('Balon jest czerwony.', 'The balloon is red.'),
        'candle': ('Świeczka się świeci.', 'The candle is burning.'),
        'drum': ('Bęben jest głośny.', 'The drum is loud.'),
        'trumpet': ('Trąbka jest głośna.', 'The trumpet is loud.'),
        'guitar': ('Gitara jest piękna.', 'The guitar is beautiful.'),
        'piano': ('Gram na pianinie.', 'I play the piano.'),
        'flute': ('Flet jest mały.', 'The flute is small.'),
        'violin': ('Gram na skrzypcach.', 'I play the violin.'),
        'eye': ('Moje oko jest niebieskie.', 'My eye is blue.'),
        'arm': ('Moje ramię jest silne.', 'My arm is strong.'),
        'leg': ('Moja noga jest długa.', 'My leg is long.'),
        'foot': ('Moja stopa jest mała.', 'My foot is small.'),
    }

    # Search in lookup
    for key in [en_lower, en_clean, en, en_clean.lower()]:
        if key in lookup:
            return lookup[key]

    # Try without parentheses
    en_no_paren = re.sub(r'\s*\([^)]*\)\s*', '', en).strip()
    for key in [en_no_paren.lower(), en_no_paren]:
        if key in lookup:
            return lookup[key]

    # FALLBACK: generate a generic sentence
    verb_endings = ('ać', 'ić', 'ować', 'ywać', 'ąć', 'eć')
    pl_lower = pl_clean.lower()

    if pl_lower.endswith(verb_endings):
        return (f'Lubię {pl_lower}.', f'I like to {en_lower}.')
    else:
        article = 'an' if en_lower and en_lower[0] in 'aeiou' else 'a'
        if en_lower.endswith('s') and not en_lower.endswith('ss'):
            return (f'Widzę {pl_lower}.', f'I see {en_lower}.')
        else:
            return (f'Widzę {pl_lower}.', f'I see {article} {en_lower}.')


def main():
    with open('C:/Users/Asus/Desktop/Sowie fiszki 2 — kopia/all_words.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    lines = []
    lines.append("-- Auto-generated example sentences for vocabulary words")
    lines.append("-- Books: bugsteam2, bugsteam3, stepsplus4, beHappy2")
    lines.append("")

    target_books = ['bugsteam2', 'bugsteam3', 'stepsplus4', 'beHappy2']
    total = 0
    seen = {}

    for book_id in target_books:
        if book_id not in data:
            lines.append(f"-- WARNING: {book_id} not found in data!")
            continue

        book_data = data[book_id]
        words = book_data['words']
        lines.append(f"-- {book_id}: {book_data['name']} ({len(words)} words)")
        lines.append("")

        count = 0
        for word in words:
            pl = word.get('pl', '')
            en = word.get('en', '')
            if not pl or not en:
                continue

            key = (book_id, pl)
            if key in seen:
                continue
            seen[key] = True

            result = generate_sentence(pl, en, book_id)
            if result:
                sentence_pl, sentence_en = result
                pl_esc = escape_sql(pl)
                spl_esc = escape_sql(sentence_pl)
                sen_esc = escape_sql(sentence_en)

                lines.append(
                    f"INSERT INTO word_sentences (book_id, word_pl, sentence_pl, sentence_target)\n"
                    f"VALUES ('{book_id}', '{pl_esc}', '{spl_esc}', '{sen_esc}')\n"
                    f"ON CONFLICT (book_id, word_pl) DO NOTHING;"
                )
                lines.append("")
                count += 1

        total += count
        lines.append(f"-- End of {book_id}: {count} entries")
        lines.append("")

    lines.append(f"-- Total entries: {total}")

    output_path = 'C:/Users/Asus/Desktop/Sowie fiszki 2 — kopia/sentences-bugsteam-steps-behappy.sql'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated {total} SQL entries to {output_path}")


if __name__ == '__main__':
    main()
