-- ═══════════════════════════════════════════════════════════
-- SEED fiszek kontekstowych — bugsteam2 (słowa i krótkie wyrażenia)
-- Bez dłuższych zwrotów/wypowiedzi (pełne zdania, dialogi), tabel gramatycznych i jednorazowych dat.
-- Wymaga migracji #59 (word-contexts-schema.sql). Idempotentny (DELETE+INSERT per słowo).
-- ═══════════════════════════════════════════════════════════

DELETE FROM public.word_contexts WHERE book_id='bugsteam2' AND word_pl IN (
  'płaszcz, kurtka',
  'sweter',
  'buty',
  'spodenki',
  'spódnica',
  'spodnie',
  'koszulka',
  'czapka z daszkiem',
  'wiosna',
  'lato',
  'jesień',
  'zima',
  'pochmurnie',
  'deszczowo',
  'słonecznie',
  'śnieżnie',
  'kot',
  'krowa',
  'kaczka',
  'koza',
  'kura',
  'koń',
  'owca',
  'cielątko, cielę',
  'kurczątko, pisklę',
  'kaczątko',
  'źrebiątko, źrebię, źrebak',
  'kociątko, kociak, kocię',
  'jagniątko, jagnię, owieczka',
  'szczeniątko, szczenię, szczeniak',
  'mleko',
  'jajka',
  'wełna',
  'gospodarstwo, farma',
  'rzeka',
  'łazienka',
  'sypialnia',
  'jadalnia',
  'przedpokój',
  'kuchnia',
  'salon',
  'toaleta',
  'półka',
  'szafka',
  'biurko',
  'lodówka',
  'lampa',
  'prysznic',
  'ogród',
  'pudełko',
  'ucho',
  'plecy',
  'palec u ręki',
  'szyja',
  'palec u nogi',
  'ząb',
  'brzuch',
  'ciało',
  'nogi',
  'nos',
  'buzia',
  'oczy',
  'ręce, ramiona',
  'głowa',
  'ból pleców',
  'ból ucha',
  'ból głowy',
  'ból szyi',
  'ból zęba',
  'ból brzucha',
  'znudzony',
  'przeziębiony',
  'gorący',
  'głodny',
  'spragniony',
  'zmęczony',
  'kapusta',
  'frytki',
  'pulpety',
  'makaron',
  'pizza',
  'sałatka',
  'zupa',
  'kurczak',
  'śniadanie',
  'obiad',
  'kolacja',
  'podwieczorek',
  'przekąska',
  'jabłko',
  'banan',
  'jogurt',
  'szarlotka',
  'herbatniki',
  'ryba z frytkami',
  'ser',
  'woda',
  'kino',
  'wesołe miasteczko',
  'muzeum',
  'centrum sportowe',
  'basen',
  'park wodny',
  'zoo',
  'park',
  'grać w piłkę nożną',
  'jeździć rowerem',
  'jeździć na rolkach/wrotkach',
  'pływać',
  'chodzić',
  'szkoła',
  'góry'
);

INSERT INTO public.word_contexts (book_id, word_pl, ord, sentence_gap, answer, full_sentence, translation_pl) VALUES
('bugsteam2','płaszcz, kurtka',0,'Put on your ______. It''s cold.','coat','Put on your coat. It''s cold.','Załóż płaszcz. Jest zimno.'),
('bugsteam2','płaszcz, kurtka',1,'My ______ is red.','coat','My coat is red.','Mój płaszcz jest czerwony.'),
('bugsteam2','płaszcz, kurtka',2,'I''ve got a new ______.','coat','I''ve got a new coat.','Mam nową kurtkę.'),
('bugsteam2','sweter',0,'I''m wearing a green ______.','jumper','I''m wearing a green jumper.','Mam na sobie zielony sweter.'),
('bugsteam2','sweter',1,'This ______ is warm.','jumper','This jumper is warm.','Ten sweter jest ciepły.'),
('bugsteam2','sweter',2,'Grandma''s got a blue ______.','jumper','Grandma''s got a blue jumper.','Babcia ma niebieski sweter.'),
('bugsteam2','buty',0,'Take off your ______.','shoes','Take off your shoes.','Zdejmij buty.'),
('bugsteam2','buty',1,'My ______ are black.','shoes','My shoes are black.','Moje buty są czarne.'),
('bugsteam2','buty',2,'I''ve got new ______.','shoes','I''ve got new shoes.','Mam nowe buty.'),
('bugsteam2','spodenki',0,'It''s hot. I''m wearing ______.','shorts','It''s hot. I''m wearing shorts.','Jest gorąco. Mam na sobie spodenki.'),
('bugsteam2','spodenki',1,'My ______ are yellow.','shorts','My shorts are yellow.','Moje spodenki są żółte.'),
('bugsteam2','spodenki',2,'Tom''s got blue ______.','shorts','Tom''s got blue shorts.','Tom ma niebieskie spodenki.'),
('bugsteam2','spódnica',0,'I''m wearing a pink ______.','skirt','I''m wearing a pink skirt.','Mam na sobie różową spódnicę.'),
('bugsteam2','spódnica',1,'Her ______ is long.','skirt','Her skirt is long.','Jej spódnica jest długa.'),
('bugsteam2','spódnica',2,'I like your ______.','skirt','I like your skirt.','Podoba mi się twoja spódnica.'),
('bugsteam2','spodnie',0,'My ______ are brown.','trousers','My trousers are brown.','Moje spodnie są brązowe.'),
('bugsteam2','spodnie',1,'Dad is wearing grey ______.','trousers','Dad is wearing grey trousers.','Tata ma na sobie szare spodnie.'),
('bugsteam2','spodnie',2,'Put on your ______.','trousers','Put on your trousers.','Załóż spodnie.'),
('bugsteam2','koszulka',0,'I''m wearing a white ______.','T-shirt','I''m wearing a white T-shirt.','Mam na sobie białą koszulkę.'),
('bugsteam2','koszulka',1,'My ______ is orange.','T-shirt','My T-shirt is orange.','Moja koszulka jest pomarańczowa.'),
('bugsteam2','koszulka',2,'There''s a cat on my ______.','T-shirt','There''s a cat on my T-shirt.','Na mojej koszulce jest kot.'),
('bugsteam2','czapka z daszkiem',0,'It''s sunny. Put on your ______.','cap','It''s sunny. Put on your cap.','Jest słonecznie. Załóż czapkę z daszkiem.'),
('bugsteam2','czapka z daszkiem',1,'My ______ is red.','cap','My cap is red.','Moja czapka z daszkiem jest czerwona.'),
('bugsteam2','czapka z daszkiem',2,'He''s wearing a blue ______.','cap','He''s wearing a blue cap.','On ma na sobie niebieską czapkę z daszkiem.'),
('bugsteam2','wiosna',0,'It''s ______. I can see flowers.','spring','It''s spring. I can see flowers.','Jest wiosna. Widzę kwiaty.'),
('bugsteam2','wiosna',1,'I like ______.','spring','I like spring.','Lubię wiosnę.'),
('bugsteam2','wiosna',2,'In ______ the trees are green.','spring','In spring the trees are green.','Wiosną drzewa są zielone.'),
('bugsteam2','lato',0,'It''s ______. It''s hot.','summer','It''s summer. It''s hot.','Jest lato. Jest gorąco.'),
('bugsteam2','lato',1,'I swim in the sea in ______.','summer','I swim in the sea in summer.','Latem pływam w morzu.'),
('bugsteam2','lato',2,'My favourite season is ______.','summer','My favourite season is summer.','Moja ulubiona pora roku to lato.'),
('bugsteam2','jesień',0,'It''s ______. The leaves are brown.','autumn','It''s autumn. The leaves are brown.','Jest jesień. Liście są brązowe.'),
('bugsteam2','jesień',1,'I don''t like ______.','autumn','I don''t like autumn.','Nie lubię jesieni.'),
('bugsteam2','jesień',2,'In ______ it''s rainy.','autumn','In autumn it''s rainy.','Jesienią jest deszczowo.'),
('bugsteam2','zima',0,'It''s ______. It''s cold.','winter','It''s winter. It''s cold.','Jest zima. Jest zimno.'),
('bugsteam2','zima',1,'I like ______. I can see snow.','winter','I like winter. I can see snow.','Lubię zimę. Widzę śnieg.'),
('bugsteam2','zima',2,'In ______ I wear a coat.','winter','In winter I wear a coat.','Zimą noszę płaszcz.'),
('bugsteam2','pochmurnie',0,'It''s ______ today.','cloudy','It''s cloudy today.','Dzisiaj jest pochmurnie.'),
('bugsteam2','pochmurnie',1,'It''s ______. I can''t see the sun.','cloudy','It''s cloudy. I can''t see the sun.','Jest pochmurnie. Nie widzę słońca.'),
('bugsteam2','pochmurnie',2,'Is it ______? Yes, it is.','cloudy','Is it cloudy? Yes, it is.','Czy jest pochmurnie? Tak.'),
('bugsteam2','deszczowo',0,'It''s ______. Take an umbrella.','rainy','It''s rainy. Take an umbrella.','Jest deszczowo. Weź parasol.'),
('bugsteam2','deszczowo',1,'It''s ______ in autumn.','rainy','It''s rainy in autumn.','Jesienią jest deszczowo.'),
('bugsteam2','deszczowo',2,'It''s ______ today. I''m at home.','rainy','It''s rainy today. I''m at home.','Dzisiaj jest deszczowo. Jestem w domu.'),
('bugsteam2','słonecznie',0,'It''s ______. Put on your cap.','sunny','It''s sunny. Put on your cap.','Jest słonecznie. Załóż czapkę z daszkiem.'),
('bugsteam2','słonecznie',1,'It''s ______ in summer.','sunny','It''s sunny in summer.','Latem jest słonecznie.'),
('bugsteam2','słonecznie',2,'It''s ______ today. Let''s go to the park.','sunny','It''s sunny today. Let''s go to the park.','Dzisiaj jest słonecznie. Chodźmy do parku.'),
('bugsteam2','śnieżnie',0,'It''s ______. I can make a snowman.','snowy','It''s snowy. I can make a snowman.','Pada śnieg. Mogę ulepić bałwana.'),
('bugsteam2','śnieżnie',1,'It''s ______ in winter.','snowy','It''s snowy in winter.','Zimą pada śnieg.'),
('bugsteam2','śnieżnie',2,'It''s cold and ______ today.','snowy','It''s cold and snowy today.','Dzisiaj jest zimno i śnieżnie.'),
('bugsteam2','kot',0,'I''ve got a ______.','cat','I''ve got a cat.','Mam kota.'),
('bugsteam2','kot',1,'The ______ is black.','cat','The cat is black.','Kot jest czarny.'),
('bugsteam2','kot',2,'My ______ likes milk.','cat','My cat likes milk.','Mój kot lubi mleko.'),
('bugsteam2','krowa',0,'The ______ is black and white.','cow','The cow is black and white.','Krowa jest czarno-biała.'),
('bugsteam2','krowa',1,'We get milk from a ______.','cow','We get milk from a cow.','Mleko mamy od krowy.'),
('bugsteam2','krowa',2,'I can see a ______ on the farm.','cow','I can see a cow on the farm.','Widzę krowę na farmie.'),
('bugsteam2','kaczka',0,'The ______ is on the river.','duck','The duck is on the river.','Kaczka jest na rzece.'),
('bugsteam2','kaczka',1,'The ______ can swim.','duck','The duck can swim.','Kaczka umie pływać.'),
('bugsteam2','kaczka',2,'This ______ is white.','duck','This duck is white.','Ta kaczka jest biała.'),
('bugsteam2','koza',0,'The ______ has got a beard.','goat','The goat has got a beard.','Koza ma brodę.'),
('bugsteam2','koza',1,'I can see a ______ on the farm.','goat','I can see a goat on the farm.','Widzę kozę na farmie.'),
('bugsteam2','koza',2,'The ______ is eating grass.','goat','The goat is eating grass.','Koza je trawę.'),
('bugsteam2','kura',0,'The ______ is brown.','hen','The hen is brown.','Kura jest brązowa.'),
('bugsteam2','kura',1,'We get eggs from a ______.','hen','We get eggs from a hen.','Jajka mamy od kury.'),
('bugsteam2','kura',2,'The ______ has got a chick.','hen','The hen has got a chick.','Kura ma kurczątko.'),
('bugsteam2','koń',0,'I can ride a ______.','horse','I can ride a horse.','Umiem jeździć na koniu.'),
('bugsteam2','koń',1,'The ______ is big and brown.','horse','The horse is big and brown.','Koń jest duży i brązowy.'),
('bugsteam2','koń',2,'The ______ can run fast.','horse','The horse can run fast.','Koń umie szybko biegać.'),
('bugsteam2','owca',0,'The ______ is white.','sheep','The sheep is white.','Owca jest biała.'),
('bugsteam2','owca',1,'We get wool from a ______.','sheep','We get wool from a sheep.','Wełnę mamy od owcy.'),
('bugsteam2','owca',2,'A ______ has got a lamb.','sheep','A sheep has got a lamb.','Owca ma jagnię.'),
('bugsteam2','cielątko, cielę',0,'A cow has got a ______.','calf','A cow has got a calf.','Krowa ma cielę.'),
('bugsteam2','cielątko, cielę',1,'The ______ is small.','calf','The calf is small.','Cielątko jest małe.'),
('bugsteam2','cielątko, cielę',2,'The ______ is drinking milk.','calf','The calf is drinking milk.','Cielę pije mleko.'),
('bugsteam2','kurczątko, pisklę',0,'The ______ is yellow.','chick','The chick is yellow.','Kurczątko jest żółte.'),
('bugsteam2','kurczątko, pisklę',1,'A hen has got a ______.','chick','A hen has got a chick.','Kura ma kurczątko.'),
('bugsteam2','kurczątko, pisklę',2,'The ______ is very small.','chick','The chick is very small.','Pisklę jest bardzo małe.'),
('bugsteam2','kaczątko',0,'A duck has got a ______.','duckling','A duck has got a duckling.','Kaczka ma kaczątko.'),
('bugsteam2','kaczątko',1,'The ______ is on the river.','duckling','The duckling is on the river.','Kaczątko jest na rzece.'),
('bugsteam2','kaczątko',2,'The ______ is small and yellow.','duckling','The duckling is small and yellow.','Kaczątko jest małe i żółte.'),
('bugsteam2','źrebiątko, źrebię, źrebak',0,'A horse has got a ______.','foal','A horse has got a foal.','Koń ma źrebię.'),
('bugsteam2','źrebiątko, źrebię, źrebak',1,'The ______ is brown.','foal','The foal is brown.','Źrebak jest brązowy.'),
('bugsteam2','źrebiątko, źrebię, źrebak',2,'The ______ can run.','foal','The foal can run.','Źrebiątko umie biegać.'),
('bugsteam2','kociątko, kociak, kocię',0,'My cat has got a ______.','kitten','My cat has got a kitten.','Moja kotka ma kociątko.'),
('bugsteam2','kociątko, kociak, kocię',1,'The ______ is playing.','kitten','The kitten is playing.','Kociak się bawi.'),
('bugsteam2','kociątko, kociak, kocię',2,'The ______ likes milk.','kitten','The kitten likes milk.','Kocię lubi mleko.'),
('bugsteam2','jagniątko, jagnię, owieczka',0,'A sheep has got a ______.','lamb','A sheep has got a lamb.','Owca ma jagnię.'),
('bugsteam2','jagniątko, jagnię, owieczka',1,'The ______ is white.','lamb','The lamb is white.','Owieczka jest biała.'),
('bugsteam2','jagniątko, jagnię, owieczka',2,'The ______ is small.','lamb','The lamb is small.','Jagniątko jest małe.'),
('bugsteam2','szczeniątko, szczenię, szczeniak',0,'I''ve got a ______.','puppy','I''ve got a puppy.','Mam szczeniaka.'),
('bugsteam2','szczeniątko, szczenię, szczeniak',1,'The ______ is playing with a ball.','puppy','The puppy is playing with a ball.','Szczeniak bawi się piłką.'),
('bugsteam2','szczeniątko, szczenię, szczeniak',2,'The dog has got a ______.','puppy','The dog has got a puppy.','Pies ma szczenię.'),
('bugsteam2','mleko',0,'I like ______.','milk','I like milk.','Lubię mleko.'),
('bugsteam2','mleko',1,'We get ______ from cows.','milk','We get milk from cows.','Mleko mamy od krów.'),
('bugsteam2','mleko',2,'The cat is drinking ______.','milk','The cat is drinking milk.','Kot pije mleko.'),
('bugsteam2','jajka',0,'We get ______ from hens.','eggs','We get eggs from hens.','Jajka mamy od kur.'),
('bugsteam2','jajka',1,'I eat ______ for breakfast.','eggs','I eat eggs for breakfast.','Jem jajka na śniadanie.'),
('bugsteam2','jajka',2,'I can see three ______.','eggs','I can see three eggs.','Widzę trzy jajka.'),
('bugsteam2','wełna',0,'We get ______ from sheep.','wool','We get wool from sheep.','Wełnę mamy od owiec.'),
('bugsteam2','wełna',1,'My jumper is made of ______.','wool','My jumper is made of wool.','Mój sweter jest z wełny.'),
('bugsteam2','wełna',2,'The ______ is white and soft.','wool','The wool is white and soft.','Wełna jest biała i miękka.'),
('bugsteam2','gospodarstwo, farma',0,'I can see a cow on the ______.','farm','I can see a cow on the farm.','Widzę krowę na farmie.'),
('bugsteam2','gospodarstwo, farma',1,'Grandpa has got a ______.','farm','Grandpa has got a farm.','Dziadek ma gospodarstwo.'),
('bugsteam2','gospodarstwo, farma',2,'There are hens on the ______.','farm','There are hens on the farm.','Na farmie są kury.'),
('bugsteam2','rzeka',0,'The ducks are on the ______.','river','The ducks are on the river.','Kaczki są na rzece.'),
('bugsteam2','rzeka',1,'I''ve got a boat on the ______.','river','I''ve got a boat on the river.','Mam łódkę na rzece.'),
('bugsteam2','rzeka',2,'The ______ is blue.','river','The river is blue.','Rzeka jest niebieska.'),
('bugsteam2','łazienka',0,'The shower is in the ______.','bathroom','The shower is in the bathroom.','Prysznic jest w łazience.'),
('bugsteam2','łazienka',1,'I''m in the ______.','bathroom','I''m in the bathroom.','Jestem w łazience.'),
('bugsteam2','łazienka',2,'Our ______ is white.','bathroom','Our bathroom is white.','Nasza łazienka jest biała.'),
('bugsteam2','sypialnia',0,'My bed is in the ______.','bedroom','My bed is in the bedroom.','Moje łóżko jest w sypialni.'),
('bugsteam2','sypialnia',1,'This is my ______.','bedroom','This is my bedroom.','To jest moja sypialnia.'),
('bugsteam2','sypialnia',2,'The ______ is small.','bedroom','The bedroom is small.','Sypialnia jest mała.'),
('bugsteam2','jadalnia',0,'We eat lunch in the ______.','dining room','We eat lunch in the dining room.','Jemy obiad w jadalni.'),
('bugsteam2','jadalnia',1,'The table is in the ______.','dining room','The table is in the dining room.','Stół jest w jadalni.'),
('bugsteam2','jadalnia',2,'Mum is in the ______.','dining room','Mum is in the dining room.','Mama jest w jadalni.'),
('bugsteam2','przedpokój',0,'My shoes are in the ______.','hall','My shoes are in the hall.','Moje buty są w przedpokoju.'),
('bugsteam2','przedpokój',1,'The coats are in the ______.','hall','The coats are in the hall.','Płaszcze są w przedpokoju.'),
('bugsteam2','przedpokój',2,'Dad is in the ______.','hall','Dad is in the hall.','Tata jest w przedpokoju.'),
('bugsteam2','kuchnia',0,'The fridge is in the ______.','kitchen','The fridge is in the kitchen.','Lodówka jest w kuchni.'),
('bugsteam2','kuchnia',1,'Mum is cooking in the ______.','kitchen','Mum is cooking in the kitchen.','Mama gotuje w kuchni.'),
('bugsteam2','kuchnia',2,'The mouse is in the ______.','kitchen','The mouse is in the kitchen.','Mysz jest w kuchni.'),
('bugsteam2','salon',0,'The TV is in the ______.','living room','The TV is in the living room.','Telewizor jest w salonie.'),
('bugsteam2','salon',1,'We play games in the ______.','living room','We play games in the living room.','Gramy w gry w salonie.'),
('bugsteam2','salon',2,'There''s a cupboard in the ______.','living room','There''s a cupboard in the living room.','W salonie jest szafka.'),
('bugsteam2','toaleta',0,'Where''s the ______?','toilet','Where''s the toilet?','Gdzie jest toaleta?'),
('bugsteam2','toaleta',1,'The ______ is in the bathroom.','toilet','The toilet is in the bathroom.','Toaleta jest w łazience.'),
('bugsteam2','toaleta',2,'Can I go to the ______, please?','toilet','Can I go to the toilet, please?','Czy mogę wyjść do toalety?'),
('bugsteam2','półka',0,'My books are on the ______.','shelf','My books are on the shelf.','Moje książki są na półce.'),
('bugsteam2','półka',1,'The cat is on the ______.','shelf','The cat is on the shelf.','Kot jest na półce.'),
('bugsteam2','półka',2,'The ______ is in my bedroom.','shelf','The shelf is in my bedroom.','Półka jest w mojej sypialni.'),
('bugsteam2','szafka',0,'There''s a ______ in the kitchen.','cupboard','There''s a cupboard in the kitchen.','W kuchni jest szafka.'),
('bugsteam2','szafka',1,'The cups are in the ______.','cupboard','The cups are in the cupboard.','Kubki są w szafce.'),
('bugsteam2','szafka',2,'The ______ is brown.','cupboard','The cupboard is brown.','Szafka jest brązowa.'),
('bugsteam2','biurko',0,'My ______ is in my bedroom.','desk','My desk is in my bedroom.','Moje biurko jest w mojej sypialni.'),
('bugsteam2','biurko',1,'The pencil is on the ______.','desk','The pencil is on the desk.','Ołówek jest na biurku.'),
('bugsteam2','biurko',2,'I''ve got a new ______.','desk','I''ve got a new desk.','Mam nowe biurko.'),
('bugsteam2','lodówka',0,'The milk is in the ______.','fridge','The milk is in the fridge.','Mleko jest w lodówce.'),
('bugsteam2','lodówka',1,'The ______ is in the kitchen.','fridge','The fridge is in the kitchen.','Lodówka jest w kuchni.'),
('bugsteam2','lodówka',2,'Our ______ is white.','fridge','Our fridge is white.','Nasza lodówka jest biała.'),
('bugsteam2','lampa',0,'The ______ is on my desk.','lamp','The lamp is on my desk.','Lampa jest na moim biurku.'),
('bugsteam2','lampa',1,'I''ve got a green ______.','lamp','I''ve got a green lamp.','Mam zieloną lampę.'),
('bugsteam2','lampa',2,'The ______ is in the living room.','lamp','The lamp is in the living room.','Lampa jest w salonie.'),
('bugsteam2','prysznic',0,'The ______ is in the bathroom.','shower','The shower is in the bathroom.','Prysznic jest w łazience.'),
('bugsteam2','prysznic',1,'Dad is in the ______.','shower','Dad is in the shower.','Tata jest pod prysznicem.'),
('bugsteam2','prysznic',2,'I have a ______ every day.','shower','I have a shower every day.','Biorę prysznic codziennie.'),
('bugsteam2','ogród',0,'I''m playing in the ______.','garden','I''m playing in the garden.','Bawię się w ogrodzie.'),
('bugsteam2','ogród',1,'There are flowers in the ______.','garden','There are flowers in the garden.','W ogrodzie są kwiaty.'),
('bugsteam2','ogród',2,'Grandma''s got a big ______.','garden','Grandma''s got a big garden.','Babcia ma duży ogród.'),
('bugsteam2','pudełko',0,'The mouse is in the ______.','box','The mouse is in the box.','Mysz jest w pudełku.'),
('bugsteam2','pudełko',1,'The cat is on the ______.','box','The cat is on the box.','Kot jest na pudełku.'),
('bugsteam2','pudełko',2,'The ball is under the ______.','box','The ball is under the box.','Piłka jest pod pudełkiem.'),
('bugsteam2','ucho',0,'My ______ hurts.','ear','My ear hurts.','Boli mnie ucho.'),
('bugsteam2','ucho',1,'The rabbit has got a long ______.','ear','The rabbit has got a long ear.','Królik ma długie ucho.'),
('bugsteam2','ucho',2,'Touch your ______.','ear','Touch your ear.','Dotknij ucha.'),
('bugsteam2','plecy',0,'My ______ hurts.','back','My back hurts.','Bolą mnie plecy.'),
('bugsteam2','plecy',1,'Touch your ______.','back','Touch your back.','Dotknij pleców.'),
('bugsteam2','plecy',2,'The monkey is on my ______.','back','The monkey is on my back.','Małpka jest na moich plecach.'),
('bugsteam2','palec u ręki',0,'I''ve got ten ______.','fingers','I''ve got ten fingers.','Mam dziesięć palców u rąk.'),
('bugsteam2','palec u ręki',1,'My ______ hurts.','finger','My finger hurts.','Boli mnie palec.'),
('bugsteam2','palec u ręki',2,'Touch your nose with your ______.','finger','Touch your nose with your finger.','Dotknij nosa palcem.'),
('bugsteam2','szyja',0,'The giraffe has got a long ______.','neck','The giraffe has got a long neck.','Żyrafa ma długą szyję.'),
('bugsteam2','szyja',1,'My ______ hurts.','neck','My neck hurts.','Boli mnie szyja.'),
('bugsteam2','szyja',2,'Touch your ______.','neck','Touch your neck.','Dotknij szyi.'),
('bugsteam2','palec u nogi',0,'I''ve got ten ______.','toes','I''ve got ten toes.','Mam dziesięć palców u nóg.'),
('bugsteam2','palec u nogi',1,'My ______ hurts.','toe','My toe hurts.','Boli mnie palec u nogi.'),
('bugsteam2','palec u nogi',2,'Touch your ______.','toes','Touch your toes.','Dotknij palców u nóg.'),
('bugsteam2','ząb',0,'My ______ hurts.','tooth','My tooth hurts.','Boli mnie ząb.'),
('bugsteam2','ząb',1,'I brush my ______ every day.','teeth','I brush my teeth every day.','Codziennie myję zęby.'),
('bugsteam2','ząb',2,'The shark has got a big ______.','tooth','The shark has got a big tooth.','Rekin ma duży ząb.'),
('bugsteam2','brzuch',0,'My ______ hurts.','tummy','My tummy hurts.','Boli mnie brzuch.'),
('bugsteam2','brzuch',1,'Touch your ______.','tummy','Touch your tummy.','Dotknij brzucha.'),
('bugsteam2','brzuch',2,'My ______ is full.','tummy','My tummy is full.','Mój brzuch jest pełny.'),
('bugsteam2','ciało',0,'This is my ______.','body','This is my body.','To jest moje ciało.'),
('bugsteam2','ciało',1,'The robot has got a square ______.','body','The robot has got a square body.','Robot ma kwadratowe ciało.'),
('bugsteam2','ciało',2,'The monster has got a green ______.','body','The monster has got a green body.','Potwór ma zielone ciało.'),
('bugsteam2','nogi',0,'I''ve got two ______.','legs','I''ve got two legs.','Mam dwie nogi.'),
('bugsteam2','nogi',1,'A spider has got eight ______.','legs','A spider has got eight legs.','Pająk ma osiem nóg.'),
('bugsteam2','nogi',2,'My ______ are long.','legs','My legs are long.','Moje nogi są długie.'),
('bugsteam2','nos',0,'Touch your ______.','nose','Touch your nose.','Dotknij nosa.'),
('bugsteam2','nos',1,'The clown has got a red ______.','nose','The clown has got a red nose.','Klaun ma czerwony nos.'),
('bugsteam2','nos',2,'My ______ is small.','nose','My nose is small.','Mój nos jest mały.'),
('bugsteam2','buzia',0,'Open your ______.','mouth','Open your mouth.','Otwórz buzię.'),
('bugsteam2','buzia',1,'The crocodile has got a big ______.','mouth','The crocodile has got a big mouth.','Krokodyl ma dużą paszczę.'),
('bugsteam2','buzia',2,'Touch your ______.','mouth','Touch your mouth.','Dotknij buzi.'),
('bugsteam2','oczy',0,'I''ve got blue ______.','eyes','I''ve got blue eyes.','Mam niebieskie oczy.'),
('bugsteam2','oczy',1,'Close your ______.','eyes','Close your eyes.','Zamknij oczy.'),
('bugsteam2','oczy',2,'The cat has got green ______.','eyes','The cat has got green eyes.','Kot ma zielone oczy.'),
('bugsteam2','ręce, ramiona',0,'I''ve got two ______.','arms','I''ve got two arms.','Mam dwie ręce.'),
('bugsteam2','ręce, ramiona',1,'Wave your ______.','arms','Wave your arms.','Pomachaj rękami.'),
('bugsteam2','ręce, ramiona',2,'The monkey has got long ______.','arms','The monkey has got long arms.','Małpa ma długie ręce.'),
('bugsteam2','głowa',0,'Touch your ______.','head','Touch your head.','Dotknij głowy.'),
('bugsteam2','głowa',1,'My ______ hurts.','head','My head hurts.','Boli mnie głowa.'),
('bugsteam2','głowa',2,'The cap is on my ______.','head','The cap is on my head.','Czapka z daszkiem jest na mojej głowie.'),
('bugsteam2','ból pleców',0,'I''ve got a ______.','backache','I''ve got a backache.','Bolą mnie plecy.'),
('bugsteam2','ból pleców',1,'Grandpa has got a ______.','backache','Grandpa has got a backache.','Dziadka bolą plecy.'),
('bugsteam2','ból pleców',2,'I''ve got a ______. I can''t play.','backache','I''ve got a backache. I can''t play.','Bolą mnie plecy. Nie mogę się bawić.'),
('bugsteam2','ból ucha',0,'I''ve got an ______.','earache','I''ve got an earache.','Boli mnie ucho.'),
('bugsteam2','ból ucha',1,'She''s got an ______.','earache','She''s got an earache.','Ją boli ucho.'),
('bugsteam2','ból ucha',2,'I''ve got an ______. I''m at home.','earache','I''ve got an earache. I''m at home.','Boli mnie ucho. Jestem w domu.'),
('bugsteam2','ból głowy',0,'I''ve got a ______.','headache','I''ve got a headache.','Boli mnie głowa.'),
('bugsteam2','ból głowy',1,'Mum has got a ______.','headache','Mum has got a headache.','Mamę boli głowa.'),
('bugsteam2','ból głowy',2,'I''ve got a ______. I''m tired.','headache','I''ve got a headache. I''m tired.','Boli mnie głowa. Jestem zmęczony.'),
('bugsteam2','ból szyi',0,'I''ve got a ______.','neck ache','I''ve got a neck ache.','Boli mnie szyja.'),
('bugsteam2','ból szyi',1,'Dad has got a ______.','neck ache','Dad has got a neck ache.','Tatę boli szyja.'),
('bugsteam2','ból szyi',2,'The giraffe has got a ______.','neck ache','The giraffe has got a neck ache.','Żyrafę boli szyja.'),
('bugsteam2','ból zęba',0,'I''ve got a ______.','toothache','I''ve got a toothache.','Boli mnie ząb.'),
('bugsteam2','ból zęba',1,'He''s got a ______.','toothache','He''s got a toothache.','Jego boli ząb.'),
('bugsteam2','ból zęba',2,'I''ve got a ______. I can''t eat.','toothache','I''ve got a toothache. I can''t eat.','Boli mnie ząb. Nie mogę jeść.'),
('bugsteam2','ból brzucha',0,'I''ve got a ______.','tummy ache','I''ve got a tummy ache.','Boli mnie brzuch.'),
('bugsteam2','ból brzucha',1,'Tom has got a ______.','tummy ache','Tom has got a tummy ache.','Toma boli brzuch.'),
('bugsteam2','ból brzucha',2,'I''ve got a ______. No pizza, please.','tummy ache','I''ve got a tummy ache. No pizza, please.','Boli mnie brzuch. Bez pizzy, proszę.'),
('bugsteam2','znudzony',0,'I''m ______. Let''s play a game.','bored','I''m bored. Let''s play a game.','Nudzi mi się. Zagrajmy w grę.'),
('bugsteam2','znudzony',1,'The cat is ______.','bored','The cat is bored.','Kot jest znudzony.'),
('bugsteam2','znudzony',2,'I''m ______. Read a book.','bored','I''m bored. Read a book.','Nudzi mi się. Przeczytaj książkę.'),
('bugsteam2','przeziębiony',0,'I''ve got a ______.','cold','I''ve got a cold.','Jestem przeziębiony.'),
('bugsteam2','przeziębiony',1,'She''s got a ______. She''s at home.','cold','She''s got a cold. She''s at home.','Ona jest przeziębiona. Jest w domu.'),
('bugsteam2','przeziębiony',2,'I''ve got a ______. Have a rest.','cold','I''ve got a cold. Have a rest.','Jestem przeziębiony. Odpocznij.'),
('bugsteam2','gorący',0,'I''m ______. Drink some water.','hot','I''m hot. Drink some water.','Jest mi gorąco. Napij się trochę wody.'),
('bugsteam2','gorący',1,'The soup is ______.','hot','The soup is hot.','Zupa jest gorąca.'),
('bugsteam2','gorący',2,'It''s ______ in summer.','hot','It''s hot in summer.','Latem jest gorąco.'),
('bugsteam2','głodny',0,'I''m ______. Have a banana.','hungry','I''m hungry. Have a banana.','Jestem głodny. Zjedz banana.'),
('bugsteam2','głodny',1,'The dog is ______.','hungry','The dog is hungry.','Pies jest głodny.'),
('bugsteam2','głodny',2,'Are you ______?','hungry','Are you hungry?','Czy jesteś głodny?'),
('bugsteam2','spragniony',0,'I''m ______. Drink some water.','thirsty','I''m thirsty. Drink some water.','Chce mi się pić. Napij się trochę wody.'),
('bugsteam2','spragniony',1,'The horse is ______.','thirsty','The horse is thirsty.','Koń jest spragniony.'),
('bugsteam2','spragniony',2,'Are you ______?','thirsty','Are you thirsty?','Czy chce ci się pić?'),
('bugsteam2','zmęczony',0,'I''m ______. Have a rest.','tired','I''m tired. Have a rest.','Jestem zmęczony. Odpocznij.'),
('bugsteam2','zmęczony',1,'Grandpa is ______.','tired','Grandpa is tired.','Dziadek jest zmęczony.'),
('bugsteam2','zmęczony',2,'I''m ______. I want to sleep.','tired','I''m tired. I want to sleep.','Jestem zmęczony. Chcę spać.'),
('bugsteam2','kapusta',0,'I don''t like ______.','cabbage','I don''t like cabbage.','Nie lubię kapusty.'),
('bugsteam2','kapusta',1,'The ______ is green.','cabbage','The cabbage is green.','Kapusta jest zielona.'),
('bugsteam2','kapusta',2,'The rabbit is eating ______.','cabbage','The rabbit is eating cabbage.','Królik je kapustę.'),
('bugsteam2','frytki',0,'I like ______.','chips','I like chips.','Lubię frytki.'),
('bugsteam2','frytki',1,'Can I have some ______, please?','chips','Can I have some chips, please?','Czy mogę prosić o frytki?'),
('bugsteam2','frytki',2,'The ______ are hot.','chips','The chips are hot.','Frytki są gorące.'),
('bugsteam2','pulpety',0,'I don''t like ______.','meatballs','I don''t like meatballs.','Nie lubię pulpetów.'),
('bugsteam2','pulpety',1,'There are ______ on the menu.','meatballs','There are meatballs on the menu.','W menu są pulpety.'),
('bugsteam2','pulpety',2,'I eat ______ for lunch.','meatballs','I eat meatballs for lunch.','Jem pulpety na obiad.'),
('bugsteam2','makaron',0,'I like ______.','pasta','I like pasta.','Lubię makaron.'),
('bugsteam2','makaron',1,'Can I have some ______, please?','pasta','Can I have some pasta, please?','Czy mogę prosić o makaron?'),
('bugsteam2','makaron',2,'We eat ______ for lunch.','pasta','We eat pasta for lunch.','Jemy makaron na obiad.'),
('bugsteam2','pizza',0,'I like ______ with cheese.','pizza','I like pizza with cheese.','Lubię pizzę z serem.'),
('bugsteam2','pizza',1,'This ______ is big.','pizza','This pizza is big.','Ta pizza jest duża.'),
('bugsteam2','pizza',2,'Can I have some ______, please?','pizza','Can I have some pizza, please?','Czy mogę prosić o pizzę?'),
('bugsteam2','sałatka',0,'I like ______.','salad','I like salad.','Lubię sałatkę.'),
('bugsteam2','sałatka',1,'There''s soup and ______.','salad','There''s soup and salad.','Jest zupa i sałatka.'),
('bugsteam2','sałatka',2,'The ______ is green.','salad','The salad is green.','Sałatka jest zielona.'),
('bugsteam2','zupa',0,'Mum is cooking ______.','soup','Mum is cooking soup.','Mama gotuje zupę.'),
('bugsteam2','zupa',1,'The ______ is hot.','soup','The soup is hot.','Zupa jest gorąca.'),
('bugsteam2','zupa',2,'Can I have some ______, please?','soup','Can I have some soup, please?','Czy mogę prosić o zupę?'),
('bugsteam2','kurczak',0,'Can I have some ______, please?','chicken','Can I have some chicken, please?','Czy mogę prosić o kurczaka?'),
('bugsteam2','kurczak',1,'I like ______ and chips.','chicken','I like chicken and chips.','Lubię kurczaka z frytkami.'),
('bugsteam2','kurczak',2,'We eat ______ for lunch.','chicken','We eat chicken for lunch.','Jemy kurczaka na obiad.'),
('bugsteam2','śniadanie',0,'I eat eggs for ______.','breakfast','I eat eggs for breakfast.','Jem jajka na śniadanie.'),
('bugsteam2','śniadanie',1,'I have ______ at home.','breakfast','I have breakfast at home.','Jem śniadanie w domu.'),
('bugsteam2','śniadanie',2,'It''s time for ______.','breakfast','It''s time for breakfast.','Czas na śniadanie.'),
('bugsteam2','obiad',0,'I eat soup for ______.','lunch','I eat soup for lunch.','Jem zupę na obiad.'),
('bugsteam2','obiad',1,'I have ______ at school.','lunch','I have lunch at school.','Jem obiad w szkole.'),
('bugsteam2','obiad',2,'It''s time for ______.','lunch','It''s time for lunch.','Czas na obiad.'),
('bugsteam2','kolacja',0,'I eat salad for ______.','dinner','I eat salad for dinner.','Jem sałatkę na kolację.'),
('bugsteam2','kolacja',1,'We have ______ at home.','dinner','We have dinner at home.','Jemy kolację w domu.'),
('bugsteam2','kolacja',2,'It''s time for ______.','dinner','It''s time for dinner.','Czas na kolację.'),
('bugsteam2','podwieczorek',0,'I eat biscuits for ______.','tea','I eat biscuits for tea.','Jem herbatniki na podwieczorek.'),
('bugsteam2','podwieczorek',1,'It''s time for ______.','tea','It''s time for tea.','Czas na podwieczorek.'),
('bugsteam2','podwieczorek',2,'We have apple pie for ______.','tea','We have apple pie for tea.','Na podwieczorek mamy szarlotkę.'),
('bugsteam2','przekąska',0,'An apple is a good ______.','snack','An apple is a good snack.','Jabłko to dobra przekąska.'),
('bugsteam2','przekąska',1,'I''ve got a ______ in my bag.','snack','I''ve got a snack in my bag.','Mam przekąskę w plecaku.'),
('bugsteam2','przekąska',2,'Can I have a ______, please?','snack','Can I have a snack, please?','Czy mogę prosić o przekąskę?'),
('bugsteam2','jabłko',0,'The ______ is red.','apple','The apple is red.','Jabłko jest czerwone.'),
('bugsteam2','jabłko',1,'I eat an ______ every day.','apple','I eat an apple every day.','Codziennie jem jabłko.'),
('bugsteam2','jabłko',2,'Can I have an ______, please?','apple','Can I have an apple, please?','Czy mogę prosić o jabłko?'),
('bugsteam2','banan',0,'The ______ is yellow.','banana','The banana is yellow.','Banan jest żółty.'),
('bugsteam2','banan',1,'I''m hungry. Have a ______.','banana','I''m hungry. Have a banana.','Jestem głodny. Zjedz banana.'),
('bugsteam2','banan',2,'The monkey likes ______.','bananas','The monkey likes bananas.','Małpa lubi banany.'),
('bugsteam2','jogurt',0,'I eat ______ for breakfast.','yogurt','I eat yogurt for breakfast.','Jem jogurt na śniadanie.'),
('bugsteam2','jogurt',1,'This ______ is pink.','yogurt','This yogurt is pink.','Ten jogurt jest różowy.'),
('bugsteam2','jogurt',2,'I like ______ with fruit.','yogurt','I like yogurt with fruit.','Lubię jogurt z owocami.'),
('bugsteam2','szarlotka',0,'Grandma makes ______.','apple pie','Grandma makes apple pie.','Babcia robi szarlotkę.'),
('bugsteam2','szarlotka',1,'I like ______.','apple pie','I like apple pie.','Lubię szarlotkę.'),
('bugsteam2','szarlotka',2,'Can I have some ______, please?','apple pie','Can I have some apple pie, please?','Czy mogę prosić o szarlotkę?'),
('bugsteam2','herbatniki',0,'I like ______.','biscuits','I like biscuits.','Lubię herbatniki.'),
('bugsteam2','herbatniki',1,'The ______ are in the box.','biscuits','The biscuits are in the box.','Herbatniki są w pudełku.'),
('bugsteam2','herbatniki',2,'Can I have some ______, please?','biscuits','Can I have some biscuits, please?','Czy mogę prosić o herbatniki?'),
('bugsteam2','ryba z frytkami',0,'I like ______.','fish and chips','I like fish and chips.','Lubię rybę z frytkami.'),
('bugsteam2','ryba z frytkami',1,'We eat ______ on Friday.','fish and chips','We eat fish and chips on Friday.','W piątek jemy rybę z frytkami.'),
('bugsteam2','ryba z frytkami',2,'Can I have ______, please?','fish and chips','Can I have fish and chips, please?','Czy mogę prosić o rybę z frytkami?'),
('bugsteam2','ser',0,'The mouse likes ______.','cheese','The mouse likes cheese.','Mysz lubi ser.'),
('bugsteam2','ser',1,'I like pizza with ______.','cheese','I like pizza with cheese.','Lubię pizzę z serem.'),
('bugsteam2','ser',2,'The ______ is yellow.','cheese','The cheese is yellow.','Ser jest żółty.'),
('bugsteam2','woda',0,'I''m thirsty. Drink some ______.','water','I''m thirsty. Drink some water.','Chce mi się pić. Napij się trochę wody.'),
('bugsteam2','woda',1,'Can I have some ______, please?','water','Can I have some water, please?','Czy mogę prosić o wodę?'),
('bugsteam2','woda',2,'The ______ is cold.','water','The water is cold.','Woda jest zimna.'),
('bugsteam2','kino',0,'Let''s go to the ______.','cinema','Let''s go to the cinema.','Chodźmy do kina.'),
('bugsteam2','kino',1,'I''m at the ______ with Dad.','cinema','I''m at the cinema with Dad.','Jestem w kinie z tatą.'),
('bugsteam2','kino',2,'Is there a ______ in town?','cinema','Is there a cinema in town?','Czy w mieście jest kino?'),
('bugsteam2','wesołe miasteczko',0,'Do you want to go to the ______?','funfair','Do you want to go to the funfair?','Czy chcesz pójść do wesołego miasteczka?'),
('bugsteam2','wesołe miasteczko',1,'Is there a ______ in town?','funfair','Is there a funfair in town?','Czy w mieście jest wesołe miasteczko?'),
('bugsteam2','wesołe miasteczko',2,'I like the ______.','funfair','I like the funfair.','Lubię wesołe miasteczko.'),
('bugsteam2','muzeum',0,'I can see dinosaurs in the ______.','museum','I can see dinosaurs in the museum.','W muzeum widzę dinozaury.'),
('bugsteam2','muzeum',1,'Let''s go to the ______.','museum','Let''s go to the museum.','Chodźmy do muzeum.'),
('bugsteam2','muzeum',2,'The ______ is big.','museum','The museum is big.','Muzeum jest duże.'),
('bugsteam2','centrum sportowe',0,'I play football at the ______.','sports centre','I play football at the sports centre.','Gram w piłkę nożną w centrum sportowym.'),
('bugsteam2','centrum sportowe',1,'Is there a ______ in town?','sports centre','Is there a sports centre in town?','Czy w mieście jest centrum sportowe?'),
('bugsteam2','centrum sportowe',2,'The ______ is new.','sports centre','The sports centre is new.','Centrum sportowe jest nowe.'),
('bugsteam2','basen',0,'I swim in the ______.','swimming pool','I swim in the swimming pool.','Pływam w basenie.'),
('bugsteam2','basen',1,'Let''s go to the ______.','swimming pool','Let''s go to the swimming pool.','Chodźmy na basen.'),
('bugsteam2','basen',2,'The ______ is big and blue.','swimming pool','The swimming pool is big and blue.','Basen jest duży i niebieski.'),
('bugsteam2','park wodny',0,'I want to go to the ______.','water park','I want to go to the water park.','Chcę pójść do parku wodnego.'),
('bugsteam2','park wodny',1,'The ______ is fun.','water park','The water park is fun.','Park wodny jest fajny.'),
('bugsteam2','park wodny',2,'I can swim at the ______.','water park','I can swim at the water park.','W parku wodnym mogę pływać.'),
('bugsteam2','zoo',0,'I want to go to the ______.','zoo','I want to go to the zoo.','Chcę pójść do zoo.'),
('bugsteam2','zoo',1,'I can see a lion at the ______.','zoo','I can see a lion at the zoo.','W zoo widzę lwa.'),
('bugsteam2','zoo',2,'Is there a ______ in town?','zoo','Is there a zoo in town?','Czy w mieście jest zoo?'),
('bugsteam2','park',0,'I ride a bike in the ______.','park','I ride a bike in the park.','Jeżdżę rowerem w parku.'),
('bugsteam2','park',1,'Let''s go to the ______.','park','Let''s go to the park.','Chodźmy do parku.'),
('bugsteam2','park',2,'The ______ is green.','park','The park is green.','Park jest zielony.'),
('bugsteam2','grać w piłkę nożną',0,'I ______ in the park.','play football','I play football in the park.','Gram w piłkę nożną w parku.'),
('bugsteam2','grać w piłkę nożną',1,'Let''s ______.','play football','Let''s play football.','Zagrajmy w piłkę nożną.'),
('bugsteam2','grać w piłkę nożną',2,'I can ______.','play football','I can play football.','Umiem grać w piłkę nożną.'),
('bugsteam2','jeździć rowerem',0,'I ______ in the park.','ride a bike','I ride a bike in the park.','Jeżdżę rowerem w parku.'),
('bugsteam2','jeździć rowerem',1,'I can''t ______.','ride a bike','I can''t ride a bike.','Nie umiem jeździć rowerem.'),
('bugsteam2','jeździć rowerem',2,'Can you ______?','ride a bike','Can you ride a bike?','Czy umiesz jeździć rowerem?'),
('bugsteam2','jeździć na rolkach/wrotkach',0,'I can ______.','roller-skate','I can roller-skate.','Umiem jeździć na rolkach.'),
('bugsteam2','jeździć na rolkach/wrotkach',1,'I ______ in the park.','roller-skate','I roller-skate in the park.','Jeżdżę na rolkach w parku.'),
('bugsteam2','jeździć na rolkach/wrotkach',2,'Can you ______?','roller-skate','Can you roller-skate?','Czy umiesz jeździć na wrotkach?'),
('bugsteam2','pływać',0,'I can ______ well.','swim','I can swim well.','Umiem dobrze pływać.'),
('bugsteam2','pływać',1,'Ducks can ______.','swim','Ducks can swim.','Kaczki umieją pływać.'),
('bugsteam2','pływać',2,'I ______ in the swimming pool.','swim','I swim in the swimming pool.','Pływam w basenie.'),
('bugsteam2','chodzić',0,'I ______ to school.','walk','I walk to school.','Chodzę do szkoły pieszo.'),
('bugsteam2','chodzić',1,'The baby can ______.','walk','The baby can walk.','Dziecko umie chodzić.'),
('bugsteam2','chodzić',2,'We ______ in the park.','walk','We walk in the park.','Spacerujemy w parku.'),
('bugsteam2','szkoła',0,'I go to ______.','school','I go to school.','Chodzę do szkoły.'),
('bugsteam2','szkoła',1,'My ______ is big.','school','My school is big.','Moja szkoła jest duża.'),
('bugsteam2','szkoła',2,'I have lunch at ______.','school','I have lunch at school.','Jem obiad w szkole.'),
('bugsteam2','góry',0,'I like the ______.','mountains','I like the mountains.','Lubię góry.'),
('bugsteam2','góry',1,'The ______ are high.','mountains','The mountains are high.','Góry są wysokie.'),
('bugsteam2','góry',2,'It''s snowy in the ______.','mountains','It''s snowy in the mountains.','W górach jest śnieżnie.');

SELECT 'OK — bugsteam2: 112 słów, 336 zdań kontekstowych' AS status;
