-- ═══════════════════════════════════════════════════════════
-- SEED fiszek kontekstowych — stayBrainy4 (słowa i krótkie wyrażenia)
-- Bez dłuższych zwrotów/wypowiedzi (pełne zdania, dialogi), tabel gramatycznych i jednorazowych dat.
-- Wymaga migracji #59 (word-contexts-schema.sql). Idempotentny (DELETE+INSERT per słowo).
-- ═══════════════════════════════════════════════════════════

DELETE FROM public.word_contexts WHERE book_id='stayBrainy4' AND word_pl IN (
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '30',
  '40',
  '50',
  '60',
  '70',
  '80',
  '90',
  '100',
  'tablica',
  'książka',
  'krzesło',
  'komputer',
  'biurko',
  'zeszyt',
  'długopis',
  'ołówek',
  'piórnik',
  'gumka',
  'plecak',
  'mądry',
  'przyjacielski',
  'zabawny',
  'pomocny',
  'uprzejmy',
  'cichy',
  'nieśmiały',
  'wysportowany',
  'kredka',
  'flamaster',
  'długopis żelowy',
  'klej w sztyfcie',
  'tablica ogłoszeń',
  'linijka',
  'temperówka',
  'taśma klejąca',
  'Argentyna',
  'Anglia',
  'Niemcy',
  'Francja',
  'Włochy',
  'Hiszpania',
  'Stany Zjednoczone Ameryki (USA)',
  'Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej (UK)',
  'Polska',
  'niebezpieczny',
  'bezpieczny',
  'trudny',
  'flaga',
  'popularny',
  'co, jaki',
  'kto',
  'jakiego koloru',
  'gdzie',
  'ile lat',
  'ładowarka',
  'grzebień',
  'szczotka do włosów',
  'słuchawki',
  'klucz',
  'pamięć przenośna',
  'portmonetka',
  'pilot (np. do telewizora)',
  'smartfon',
  'chusteczka papierowa',
  'parasol',
  'portfel',
  'czapka',
  'sukienka',
  'kurtka',
  'sandały',
  'koszula',
  'buty',
  'szorty',
  'spódnica',
  'skarpetki',
  'sweter',
  'buty sportowe',
  'spodnie',
  'koszulka',
  'to, ta, ten (l. poj., blisko)',
  'to, tamto, tamta, tamten (l. poj., daleko)',
  'to, te, ci (l. mn., blisko)',
  'to, tamte, tamci (l. mn., daleko)',
  'ciocia',
  'brat',
  'kuzyn',
  'ojciec',
  'dziadek',
  'babcia',
  'pradziadek',
  'prababcia',
  'matka',
  'siostra',
  'wujek',
  'czarne',
  'kręcone',
  'jasne',
  'siwe',
  'długie',
  'rude',
  'krótkie',
  'proste',
  'falowane',
  'wspinać się na drzewa',
  'robić sztuczki na deskorolce',
  'prowadzić samochód',
  'latać',
  'jeździć na rowerze',
  'jeździć na nartach',
  'mówić po chińsku',
  'mówić po angielsku',
  'pływać',
  'opowiadać kawały',
  'gotować',
  'jeździć na łyżwach',
  'malować',
  'grać w szachy',
  'grać na pianinie',
  'czytać nuty',
  'jeździć na rolkach',
  'śpiewać',
  'jeździć na snowboardzie',
  'gwizdać',
  'ciastko',
  'chleb',
  'ciasto',
  'ser',
  'lody',
  'dżem',
  'makaron',
  'pizza',
  'kiełbaska',
  'truskawka',
  'fasola',
  'burak czerwony',
  'kapusta',
  'marchewka',
  'ogórek',
  'cebula',
  'czerwona papryka',
  'pomidor',
  'bekon',
  'jagody',
  'kurczak',
  'winogrona',
  'szynka',
  'cytryna',
  'sałata',
  'mięso',
  'grzyb',
  'ananas',
  'ziemniak',
  'ryż',
  'trochę, kilka',
  'dużo',
  'żadnych (-), jakieś (?)',
  'rozmawiać przez komunikator w telefonie',
  'ćwiczyć',
  'pobierać muzykę z internetu',
  'wychodzić',
  'chodzić na lekcje tańca',
  'spędzać wolny czas ze znajomymi',
  'grać w siatkówkę',
  'zamieszczać komentarze w internecie',
  'robić zdjęcia',
  'oglądać telewizję',
  'myć zęby',
  'ubierać się',
  'wstawać',
  'iść do domu',
  'iść spać',
  'iść do szkoły',
  'brać prysznic',
  'jeść śniadanie',
  'jeść lunch',
  'jeść obiad',
  'rano',
  'po południu',
  'wieczorem',
  'w nocy',
  'kupić bilety',
  'wskoczyć do jeziora z krokodylami',
  'walczyć z dinozaurem',
  'znaleźć skarb',
  'uczyć się sztuczek magicznych',
  'szukać Brainyballs',
  'odwiedzić zamek strachów',
  'wygrać nagrody',
  'przystanek autobusowy',
  'kawiarnia',
  'parking',
  'kino',
  'rynek',
  'muzeum',
  'szkoła',
  'centrum handlowe',
  'supermarket',
  'stacja kolejowa'
);

INSERT INTO public.word_contexts (book_id, word_pl, ord, sentence_gap, answer, full_sentence, translation_pl) VALUES
('stayBrainy4','1',0,'I''ve got ______ brother.','one','I''ve got one brother.','Mam jednego brata.'),
('stayBrainy4','1',1,'There is only ______ apple on the table.','one','There is only one apple on the table.','Na stole jest tylko jedno jabłko.'),
('stayBrainy4','1',2,'My baby sister is ______ year old.','one','My baby sister is one year old.','Moja młodsza siostra ma jeden rok.'),
('stayBrainy4','2',0,'I''ve got ______ cats.','two','I''ve got two cats.','Mam dwa koty.'),
('stayBrainy4','2',1,'A bicycle has got ______ wheels.','two','A bicycle has got two wheels.','Rower ma dwa koła.'),
('stayBrainy4','2',2,'We have ______ English lessons on Monday.','two','We have two English lessons on Monday.','W poniedziałek mamy dwie lekcje angielskiego.'),
('stayBrainy4','3',0,'There are ______ pencils in my pencil case.','three','There are three pencils in my pencil case.','W moim piórniku są trzy ołówki.'),
('stayBrainy4','3',1,'My cousin is ______ years old.','three','My cousin is three years old.','Mój kuzyn ma trzy lata.'),
('stayBrainy4','3',2,'I''ve got ______ sisters.','three','I''ve got three sisters.','Mam trzy siostry.'),
('stayBrainy4','4',0,'A dog has got ______ legs.','four','A dog has got four legs.','Pies ma cztery nogi.'),
('stayBrainy4','4',1,'There are ______ people in my family.','four','There are four people in my family.','W mojej rodzinie są cztery osoby.'),
('stayBrainy4','4',2,'I can see ______ birds in the tree.','four','I can see four birds in the tree.','Widzę cztery ptaki na drzewie.'),
('stayBrainy4','5',0,'I''ve got ______ fingers on my hand.','five','I''ve got five fingers on my hand.','Mam pięć palców u ręki.'),
('stayBrainy4','5',1,'My brother is ______ years old.','five','My brother is five years old.','Mój brat ma pięć lat.'),
('stayBrainy4','5',2,'There are ______ apples in the bag.','five','There are five apples in the bag.','W torbie jest pięć jabłek.'),
('stayBrainy4','6',0,'I get up at ______ o''clock.','six','I get up at six o''clock.','Wstaję o szóstej.'),
('stayBrainy4','6',1,'There are ______ chairs in the kitchen.','six','There are six chairs in the kitchen.','W kuchni jest sześć krzeseł.'),
('stayBrainy4','6',2,'An insect has got ______ legs.','six','An insect has got six legs.','Owad ma sześć nóg.'),
('stayBrainy4','7',0,'There are ______ days in a week.','seven','There are seven days in a week.','Tydzień ma siedem dni.'),
('stayBrainy4','7',1,'My sister is ______ years old.','seven','My sister is seven years old.','Moja siostra ma siedem lat.'),
('stayBrainy4','7',2,'I''ve got ______ crayons.','seven','I''ve got seven crayons.','Mam siedem kredek.'),
('stayBrainy4','8',0,'A spider has got ______ legs.','eight','A spider has got eight legs.','Pająk ma osiem nóg.'),
('stayBrainy4','8',1,'School starts at ______ o''clock.','eight','School starts at eight o''clock.','Szkoła zaczyna się o ósmej.'),
('stayBrainy4','8',2,'There are ______ books on my desk.','eight','There are eight books on my desk.','Na moim biurku jest osiem książek.'),
('stayBrainy4','9',0,'I''m ______ years old.','nine','I''m nine years old.','Mam dziewięć lat.'),
('stayBrainy4','9',1,'There are ______ players in a baseball team.','nine','There are nine players in a baseball team.','W drużynie baseballowej jest dziewięciu zawodników.'),
('stayBrainy4','9',2,'I go to bed at ______ o''clock.','nine','I go to bed at nine o''clock.','Chodzę spać o dziewiątej.'),
('stayBrainy4','10',0,'There are ______ pens in the box.','ten','There are ten pens in the box.','W pudełku jest dziesięć długopisów.'),
('stayBrainy4','10',1,'The pizza costs ______ pounds.','ten','The pizza costs ten pounds.','Pizza kosztuje dziesięć funtów.'),
('stayBrainy4','10',2,'Count from one to ______.','ten','Count from one to ten.','Policz od jednego do dziesięciu.'),
('stayBrainy4','11',0,'There are ______ players in a football team.','eleven','There are eleven players in a football team.','W drużynie piłkarskiej jest jedenastu zawodników.'),
('stayBrainy4','11',1,'My sister is ______ years old.','eleven','My sister is eleven years old.','Moja siostra ma jedenaście lat.'),
('stayBrainy4','11',2,'The film starts at ______ o''clock.','eleven','The film starts at eleven o''clock.','Film zaczyna się o jedenastej.'),
('stayBrainy4','12',0,'There are ______ months in a year.','twelve','There are twelve months in a year.','Rok ma dwanaście miesięcy.'),
('stayBrainy4','12',1,'We have lunch at ______ o''clock.','twelve','We have lunch at twelve o''clock.','Jemy lunch o dwunastej.'),
('stayBrainy4','12',2,'There are ______ eggs in the box.','twelve','There are twelve eggs in the box.','W pudełku jest dwanaście jajek.'),
('stayBrainy4','13',0,'My cousin is ______ years old.','thirteen','My cousin is thirteen years old.','Mój kuzyn ma trzynaście lat.'),
('stayBrainy4','13',1,'There are ______ girls in my class.','thirteen','There are thirteen girls in my class.','W mojej klasie jest trzynaście dziewczynek.'),
('stayBrainy4','13',2,'Bob lives at number ______.','thirteen','Bob lives at number thirteen.','Bob mieszka pod numerem trzynaście.'),
('stayBrainy4','14',0,'There are ______ days in two weeks.','fourteen','There are fourteen days in two weeks.','Dwa tygodnie mają czternaście dni.'),
('stayBrainy4','14',1,'My brother is ______ years old.','fourteen','My brother is fourteen years old.','Mój brat ma czternaście lat.'),
('stayBrainy4','14',2,'There are ______ boys in my class.','fourteen','There are fourteen boys in my class.','W mojej klasie jest czternastu chłopców.'),
('stayBrainy4','15',0,'The bus comes in ______ minutes.','fifteen','The bus comes in fifteen minutes.','Autobus przyjedzie za piętnaście minut.'),
('stayBrainy4','15',1,'My sister is ______ years old.','fifteen','My sister is fifteen years old.','Moja siostra ma piętnaście lat.'),
('stayBrainy4','15',2,'Ten and five is ______.','fifteen','Ten and five is fifteen.','Dziesięć i pięć to piętnaście.'),
('stayBrainy4','16',0,'There are ______ students in our class.','sixteen','There are sixteen students in our class.','W naszej klasie jest szesnastu uczniów.'),
('stayBrainy4','16',1,'My cousin is ______ years old.','sixteen','My cousin is sixteen years old.','Moja kuzynka ma szesnaście lat.'),
('stayBrainy4','16',2,'Eight and eight is ______.','sixteen','Eight and eight is sixteen.','Osiem i osiem to szesnaście.'),
('stayBrainy4','17',0,'My brother is ______ years old.','seventeen','My brother is seventeen years old.','Mój brat ma siedemnaście lat.'),
('stayBrainy4','17',1,'Ten and seven is ______.','seventeen','Ten and seven is seventeen.','Dziesięć i siedem to siedemnaście.'),
('stayBrainy4','17',2,'There are ______ crayons in the box.','seventeen','There are seventeen crayons in the box.','W pudełku jest siedemnaście kredek.'),
('stayBrainy4','18',0,'My aunt''s house is number ______.','eighteen','My aunt''s house is number eighteen.','Dom mojej cioci ma numer osiemnaście.'),
('stayBrainy4','18',1,'Nine and nine is ______.','eighteen','Nine and nine is eighteen.','Dziewięć i dziewięć to osiemnaście.'),
('stayBrainy4','18',2,'My sister is ______ years old.','eighteen','My sister is eighteen years old.','Moja siostra ma osiemnaście lat.'),
('stayBrainy4','19',0,'There are ______ chairs in the classroom.','nineteen','There are nineteen chairs in the classroom.','W klasie jest dziewiętnaście krzeseł.'),
('stayBrainy4','19',1,'Ten and nine is ______.','nineteen','Ten and nine is nineteen.','Dziesięć i dziewięć to dziewiętnaście.'),
('stayBrainy4','19',2,'My cousin is ______ years old.','nineteen','My cousin is nineteen years old.','Mój kuzyn ma dziewiętnaście lat.'),
('stayBrainy4','20',0,'There are ______ students in my class.','twenty','There are twenty students in my class.','W mojej klasie jest dwudziestu uczniów.'),
('stayBrainy4','20',1,'I''ve got ______ fingers and toes.','twenty','I''ve got twenty fingers and toes.','Mam dwadzieścia palców u rąk i nóg.'),
('stayBrainy4','20',2,'Ten and ten is ______.','twenty','Ten and ten is twenty.','Dziesięć i dziesięć to dwadzieścia.'),
('stayBrainy4','30',0,'There are ______ days in June.','thirty','There are thirty days in June.','Czerwiec ma trzydzieści dni.'),
('stayBrainy4','30',1,'My mum is ______ years old.','thirty','My mum is thirty years old.','Moja mama ma trzydzieści lat.'),
('stayBrainy4','30',2,'There are ______ pages in my notebook.','thirty','There are thirty pages in my notebook.','Mój zeszyt ma trzydzieści stron.'),
('stayBrainy4','40',0,'My dad is ______ years old.','forty','My dad is forty years old.','Mój tata ma czterdzieści lat.'),
('stayBrainy4','40',1,'Twenty and twenty is ______.','forty','Twenty and twenty is forty.','Dwadzieścia i dwadzieścia to czterdzieści.'),
('stayBrainy4','40',2,'There are ______ books on the shelf.','forty','There are forty books on the shelf.','Na półce jest czterdzieści książek.'),
('stayBrainy4','50',0,'My aunt is ______ years old.','fifty','My aunt is fifty years old.','Moja ciocia ma pięćdziesiąt lat.'),
('stayBrainy4','50',1,'There are ______ chairs in the school hall.','fifty','There are fifty chairs in the school hall.','W auli szkolnej jest pięćdziesiąt krzeseł.'),
('stayBrainy4','50',2,'This pen costs ______ pence.','fifty','This pen costs fifty pence.','Ten długopis kosztuje pięćdziesiąt pensów.'),
('stayBrainy4','60',0,'There are ______ minutes in an hour.','sixty','There are sixty minutes in an hour.','Godzina ma sześćdziesiąt minut.'),
('stayBrainy4','60',1,'My grandmother is ______ years old.','sixty','My grandmother is sixty years old.','Moja babcia ma sześćdziesiąt lat.'),
('stayBrainy4','60',2,'There are ______ seconds in a minute.','sixty','There are sixty seconds in a minute.','Minuta ma sześćdziesiąt sekund.'),
('stayBrainy4','70',0,'My grandfather is ______ years old.','seventy','My grandfather is seventy years old.','Mój dziadek ma siedemdziesiąt lat.'),
('stayBrainy4','70',1,'Thirty and forty is ______.','seventy','Thirty and forty is seventy.','Trzydzieści i czterdzieści to siedemdziesiąt.'),
('stayBrainy4','70',2,'The sandwich costs ______ pence.','seventy','The sandwich costs seventy pence.','Kanapka kosztuje siedemdziesiąt pensów.'),
('stayBrainy4','80',0,'My great-grandmother is ______ years old.','eighty','My great-grandmother is eighty years old.','Moja prababcia ma osiemdziesiąt lat.'),
('stayBrainy4','80',1,'There are ______ pages in this book.','eighty','There are eighty pages in this book.','Ta książka ma osiemdziesiąt stron.'),
('stayBrainy4','80',2,'Forty and forty is ______.','eighty','Forty and forty is eighty.','Czterdzieści i czterdzieści to osiemdziesiąt.'),
('stayBrainy4','90',0,'My great-grandfather is ______ years old.','ninety','My great-grandfather is ninety years old.','Mój pradziadek ma dziewięćdziesiąt lat.'),
('stayBrainy4','90',1,'A football match is ______ minutes long.','ninety','A football match is ninety minutes long.','Mecz piłki nożnej trwa dziewięćdziesiąt minut.'),
('stayBrainy4','90',2,'Fifty and forty is ______.','ninety','Fifty and forty is ninety.','Pięćdziesiąt i czterdzieści to dziewięćdziesiąt.'),
('stayBrainy4','100',0,'There are ______ pence in a pound.','a hundred','There are a hundred pence in a pound.','Funt ma sto pensów.'),
('stayBrainy4','100',1,'I can count to ______.','a hundred','I can count to a hundred.','Umiem liczyć do stu.'),
('stayBrainy4','100',2,'There are ______ books in our classroom.','a hundred','There are a hundred books in our classroom.','W naszej klasie jest sto książek.'),
('stayBrainy4','tablica',0,'The teacher is writing on the ______.','board','The teacher is writing on the board.','Nauczyciel pisze na tablicy.'),
('stayBrainy4','tablica',1,'Look at the ______, please.','board','Look at the board, please.','Spójrzcie na tablicę, proszę.'),
('stayBrainy4','tablica',2,'There is a big white ______ in our classroom.','board','There is a big white board in our classroom.','W naszej klasie jest duża biała tablica.'),
('stayBrainy4','książka',0,'Open your ______ at page ten.','book','Open your book at page ten.','Otwórz książkę na stronie dziesiątej.'),
('stayBrainy4','książka',1,'This ______ is about dinosaurs.','book','This book is about dinosaurs.','Ta książka jest o dinozaurach.'),
('stayBrainy4','książka',2,'My English ______ is in my schoolbag.','book','My English book is in my schoolbag.','Moja książka do angielskiego jest w plecaku.'),
('stayBrainy4','krzesło',0,'Sit on the ______, please.','chair','Sit on the chair, please.','Usiądź na krześle, proszę.'),
('stayBrainy4','krzesło',1,'There is a cat under the ______.','chair','There is a cat under the chair.','Pod krzesłem jest kot.'),
('stayBrainy4','krzesło',2,'My ______ is next to the window.','chair','My chair is next to the window.','Moje krzesło jest obok okna.'),
('stayBrainy4','komputer',0,'I play games on my ______.','computer','I play games on my computer.','Gram w gry na komputerze.'),
('stayBrainy4','komputer',1,'There is a ______ on the teacher''s desk.','computer','There is a computer on the teacher''s desk.','Na biurku nauczyciela jest komputer.'),
('stayBrainy4','komputer',2,'My dad works on his ______.','computer','My dad works on his computer.','Mój tata pracuje na komputerze.'),
('stayBrainy4','biurko',0,'My books are on the ______.','desk','My books are on the desk.','Moje książki są na biurku.'),
('stayBrainy4','biurko',1,'I do my homework at my ______.','desk','I do my homework at my desk.','Odrabiam pracę domową przy biurku.'),
('stayBrainy4','biurko',2,'There is a lamp on my ______.','desk','There is a lamp on my desk.','Na moim biurku jest lampka.'),
('stayBrainy4','zeszyt',0,'Write the words in your ______.','notebook','Write the words in your notebook.','Zapisz słowa w zeszycie.'),
('stayBrainy4','zeszyt',1,'My ______ is blue.','notebook','My notebook is blue.','Mój zeszyt jest niebieski.'),
('stayBrainy4','zeszyt',2,'I''ve got a new ______ for English.','notebook','I''ve got a new notebook for English.','Mam nowy zeszyt do angielskiego.'),
('stayBrainy4','długopis',0,'Can I borrow your ______?','pen','Can I borrow your pen?','Czy mogę pożyczyć twój długopis?'),
('stayBrainy4','długopis',1,'I write with a blue ______.','pen','I write with a blue pen.','Piszę niebieskim długopisem.'),
('stayBrainy4','długopis',2,'My ______ is in my pencil case.','pen','My pen is in my pencil case.','Mój długopis jest w piórniku.'),
('stayBrainy4','ołówek',0,'I draw with a ______.','pencil','I draw with a pencil.','Rysuję ołówkiem.'),
('stayBrainy4','ołówek',1,'My ______ is very short.','pencil','My pencil is very short.','Mój ołówek jest bardzo krótki.'),
('stayBrainy4','ołówek',2,'There''s a green ______ on the desk.','pencil','There''s a green pencil on the desk.','Na biurku jest zielony ołówek.'),
('stayBrainy4','piórnik',0,'My pens are in my ______.','pencil case','My pens are in my pencil case.','Moje długopisy są w piórniku.'),
('stayBrainy4','piórnik',1,'I''ve got a red ______.','pencil case','I''ve got a red pencil case.','Mam czerwony piórnik.'),
('stayBrainy4','piórnik',2,'Put your rubber in your ______.','pencil case','Put your rubber in your pencil case.','Włóż gumkę do piórnika.'),
('stayBrainy4','gumka',0,'Can I borrow your ______, please?','rubber','Can I borrow your rubber, please?','Czy mogę pożyczyć twoją gumkę?'),
('stayBrainy4','gumka',1,'I need a ______ to fix my mistake.','rubber','I need a rubber to fix my mistake.','Potrzebuję gumki, żeby poprawić błąd.'),
('stayBrainy4','gumka',2,'This ______ is small and pink.','rubber','This rubber is small and pink.','Ta gumka jest mała i różowa.'),
('stayBrainy4','plecak',0,'My books are in my ______.','schoolbag','My books are in my schoolbag.','Moje książki są w plecaku.'),
('stayBrainy4','plecak',1,'My ______ is very heavy today.','schoolbag','My schoolbag is very heavy today.','Mój plecak jest dziś bardzo ciężki.'),
('stayBrainy4','plecak',2,'I''ve got a new blue ______.','schoolbag','I''ve got a new blue schoolbag.','Mam nowy niebieski plecak.'),
('stayBrainy4','mądry',0,'My sister is very ______. She knows everything.','clever','My sister is very clever. She knows everything.','Moja siostra jest bardzo mądra. Wie wszystko.'),
('stayBrainy4','mądry',1,'Owls are ______ birds.','clever','Owls are clever birds.','Sowy to mądre ptaki.'),
('stayBrainy4','mądry',2,'He''s a ______ boy. He''s good at maths.','clever','He''s a clever boy. He''s good at maths.','To mądry chłopiec. Jest dobry z matematyki.'),
('stayBrainy4','przyjacielski',0,'My new teacher is very ______.','friendly','My new teacher is very friendly.','Moja nowa nauczycielka jest bardzo przyjacielska.'),
('stayBrainy4','przyjacielski',1,'Our dog is ______. It likes people.','friendly','Our dog is friendly. It likes people.','Nasz pies jest przyjazny. Lubi ludzi.'),
('stayBrainy4','przyjacielski',2,'Tom is ______. He''s got a lot of friends.','friendly','Tom is friendly. He''s got a lot of friends.','Tom jest przyjacielski. Ma wielu przyjaciół.'),
('stayBrainy4','zabawny',0,'My uncle is very ______. He tells jokes.','funny','My uncle is very funny. He tells jokes.','Mój wujek jest bardzo zabawny. Opowiada kawały.'),
('stayBrainy4','zabawny',1,'This film is really ______.','funny','This film is really funny.','Ten film jest naprawdę zabawny.'),
('stayBrainy4','zabawny',2,'Clowns are ______.','funny','Clowns are funny.','Klauni są zabawni.'),
('stayBrainy4','pomocny',0,'My brother is ______. He helps me with my homework.','helpful','My brother is helpful. He helps me with my homework.','Mój brat jest pomocny. Pomaga mi w pracy domowej.'),
('stayBrainy4','pomocny',1,'Thank you! You''re very ______.','helpful','Thank you! You''re very helpful.','Dziękuję! Jesteś bardzo pomocny.'),
('stayBrainy4','pomocny',2,'The shop assistant is very ______.','helpful','The shop assistant is very helpful.','Sprzedawca jest bardzo pomocny.'),
('stayBrainy4','uprzejmy',0,'My grandmother is very ______.','kind','My grandmother is very kind.','Moja babcia jest bardzo uprzejma.'),
('stayBrainy4','uprzejmy',1,'It''s ______ of you to help me.','kind','It''s kind of you to help me.','To uprzejme z twojej strony, że mi pomagasz.'),
('stayBrainy4','uprzejmy',2,'Be ______ to your friends.','kind','Be kind to your friends.','Bądź uprzejmy dla swoich przyjaciół.'),
('stayBrainy4','cichy',0,'Be ______, please. The baby is sleeping.','quiet','Be quiet, please. The baby is sleeping.','Bądź cicho, proszę. Dziecko śpi.'),
('stayBrainy4','cichy',1,'Anna is a ______ girl. She doesn''t talk a lot.','quiet','Anna is a quiet girl. She doesn''t talk a lot.','Anna jest cichą dziewczynką. Nie mówi dużo.'),
('stayBrainy4','cichy',2,'The library is a ______ place.','quiet','The library is a quiet place.','Biblioteka to ciche miejsce.'),
('stayBrainy4','nieśmiały',0,'The new boy in our class is ______.','shy','The new boy in our class is shy.','Nowy chłopiec w naszej klasie jest nieśmiały.'),
('stayBrainy4','nieśmiały',1,'My sister is ______. She doesn''t like big parties.','shy','My sister is shy. She doesn''t like big parties.','Moja siostra jest nieśmiała. Nie lubi dużych imprez.'),
('stayBrainy4','nieśmiały',2,'Don''t be ______! Say hello.','shy','Don''t be shy! Say hello.','Nie bądź nieśmiały! Przywitaj się.'),
('stayBrainy4','wysportowany',0,'My brother is ______. He plays football and tennis.','sporty','My brother is sporty. He plays football and tennis.','Mój brat jest wysportowany. Gra w piłkę nożną i w tenisa.'),
('stayBrainy4','wysportowany',1,'Are you ______?','sporty','Are you sporty?','Czy jesteś wysportowany?'),
('stayBrainy4','wysportowany',2,'Kate is a ______ girl. She can swim and ski.','sporty','Kate is a sporty girl. She can swim and ski.','Kate to wysportowana dziewczynka. Umie pływać i jeździć na nartach.'),
('stayBrainy4','kredka',0,'Can I borrow your red ______?','crayon','Can I borrow your red crayon?','Czy mogę pożyczyć twoją czerwoną kredkę?'),
('stayBrainy4','kredka',1,'I draw the sun with a yellow ______.','crayon','I draw the sun with a yellow crayon.','Rysuję słońce żółtą kredką.'),
('stayBrainy4','kredka',2,'There are ten ______ in the box.','crayons','There are ten crayons in the box.','W pudełku jest dziesięć kredek.'),
('stayBrainy4','flamaster',0,'I colour the picture with a ______.','felt-tip pen','I colour the picture with a felt-tip pen.','Koloruję obrazek flamastrem.'),
('stayBrainy4','flamaster',1,'My green ______ doesn''t work.','felt-tip pen','My green felt-tip pen doesn''t work.','Mój zielony flamaster nie pisze.'),
('stayBrainy4','flamaster',2,'I''ve got twelve ______ in my pencil case.','felt-tip pens','I''ve got twelve felt-tip pens in my pencil case.','Mam dwanaście flamastrów w piórniku.'),
('stayBrainy4','długopis żelowy',0,'I write with a pink ______.','gel pen','I write with a pink gel pen.','Piszę różowym długopisem żelowym.'),
('stayBrainy4','długopis żelowy',1,'This ______ is purple and smells nice.','gel pen','This gel pen is purple and smells nice.','Ten długopis żelowy jest fioletowy i ładnie pachnie.'),
('stayBrainy4','długopis żelowy',2,'Have you got a ______?','gel pen','Have you got a gel pen?','Czy masz długopis żelowy?'),
('stayBrainy4','klej w sztyfcie',0,'I need a ______ for my project.','glue stick','I need a glue stick for my project.','Potrzebuję kleju w sztyfcie do mojego projektu.'),
('stayBrainy4','klej w sztyfcie',1,'Put the ______ back in your pencil case.','glue stick','Put the glue stick back in your pencil case.','Włóż klej w sztyfcie z powrotem do piórnika.'),
('stayBrainy4','klej w sztyfcie',2,'Stick the picture in your notebook with a ______.','glue stick','Stick the picture in your notebook with a glue stick.','Wklej obrazek do zeszytu klejem w sztyfcie.'),
('stayBrainy4','tablica ogłoszeń',0,'There is a poster on the ______.','noticeboard','There is a poster on the noticeboard.','Na tablicy ogłoszeń jest plakat.'),
('stayBrainy4','tablica ogłoszeń',1,'Look at the ______ in the hall.','noticeboard','Look at the noticeboard in the hall.','Spójrz na tablicę ogłoszeń na korytarzu.'),
('stayBrainy4','tablica ogłoszeń',2,'Our photos are on the ______.','noticeboard','Our photos are on the noticeboard.','Nasze zdjęcia są na tablicy ogłoszeń.'),
('stayBrainy4','linijka',0,'Draw a line with a ______.','ruler','Draw a line with a ruler.','Narysuj linię linijką.'),
('stayBrainy4','linijka',1,'My ______ is thirty centimetres long.','ruler','My ruler is thirty centimetres long.','Moja linijka ma trzydzieści centymetrów długości.'),
('stayBrainy4','linijka',2,'There is a ______ on my desk.','ruler','There is a ruler on my desk.','Na moim biurku jest linijka.'),
('stayBrainy4','temperówka',0,'My pencil is broken. I need a ______.','sharpener','My pencil is broken. I need a sharpener.','Mój ołówek jest złamany. Potrzebuję temperówki.'),
('stayBrainy4','temperówka',1,'The ______ is in my pencil case.','sharpener','The sharpener is in my pencil case.','Temperówka jest w moim piórniku.'),
('stayBrainy4','temperówka',2,'I''ve got a blue ______.','sharpener','I''ve got a blue sharpener.','Mam niebieską temperówkę.'),
('stayBrainy4','taśma klejąca',0,'Put the poster on the wall with ______.','sticky tape','Put the poster on the wall with sticky tape.','Przyklej plakat do ściany taśmą klejącą.'),
('stayBrainy4','taśma klejąca',1,'Have you got any ______?','sticky tape','Have you got any sticky tape?','Czy masz taśmę klejącą?'),
('stayBrainy4','taśma klejąca',2,'I need ______ to fix my book.','sticky tape','I need sticky tape to fix my book.','Potrzebuję taśmy klejącej, żeby naprawić książkę.'),
('stayBrainy4','Argentyna',0,'Lionel Messi is from ______.','Argentina','Lionel Messi is from Argentina.','Lionel Messi jest z Argentyny.'),
('stayBrainy4','Argentyna',1,'______ is in South America.','Argentina','Argentina is in South America.','Argentyna leży w Ameryce Południowej.'),
('stayBrainy4','Argentyna',2,'My uncle lives in ______.','Argentina','My uncle lives in Argentina.','Mój wujek mieszka w Argentynie.'),
('stayBrainy4','Anglia',0,'London is in ______.','England','London is in England.','Londyn jest w Anglii.'),
('stayBrainy4','Anglia',1,'My cousin is from ______.','England','My cousin is from England.','Mój kuzyn jest z Anglii.'),
('stayBrainy4','Anglia',2,'People speak English in ______.','England','People speak English in England.','W Anglii ludzie mówią po angielsku.'),
('stayBrainy4','Niemcy',0,'Berlin is in ______.','Germany','Berlin is in Germany.','Berlin jest w Niemczech.'),
('stayBrainy4','Niemcy',1,'My aunt lives in ______.','Germany','My aunt lives in Germany.','Moja ciocia mieszka w Niemczech.'),
('stayBrainy4','Niemcy',2,'______ is next to Poland.','Germany','Germany is next to Poland.','Niemcy graniczą z Polską.'),
('stayBrainy4','Francja',0,'Paris is in ______.','France','Paris is in France.','Paryż jest we Francji.'),
('stayBrainy4','Francja',1,'People speak French in ______.','France','People speak French in France.','We Francji ludzie mówią po francusku.'),
('stayBrainy4','Francja',2,'Pierre is from ______.','France','Pierre is from France.','Pierre jest z Francji.'),
('stayBrainy4','Włochy',0,'Rome is in ______.','Italy','Rome is in Italy.','Rzym jest we Włoszech.'),
('stayBrainy4','Włochy',1,'Pizza and pasta are from ______.','Italy','Pizza and pasta are from Italy.','Pizza i makaron pochodzą z Włoch.'),
('stayBrainy4','Włochy',2,'Marco is from ______.','Italy','Marco is from Italy.','Marco jest z Włoch.'),
('stayBrainy4','Hiszpania',0,'Madrid is in ______.','Spain','Madrid is in Spain.','Madryt jest w Hiszpanii.'),
('stayBrainy4','Hiszpania',1,'People speak Spanish in ______.','Spain','People speak Spanish in Spain.','W Hiszpanii ludzie mówią po hiszpańsku.'),
('stayBrainy4','Hiszpania',2,'It''s hot in ______ in summer.','Spain','It''s hot in Spain in summer.','Latem w Hiszpanii jest gorąco.'),
('stayBrainy4','Stany Zjednoczone Ameryki (USA)',0,'New York is in ______.','the USA','New York is in the USA.','Nowy Jork jest w USA.'),
('stayBrainy4','Stany Zjednoczone Ameryki (USA)',1,'My cousin lives in ______.','the USA','My cousin lives in the USA.','Mój kuzyn mieszka w USA.'),
('stayBrainy4','Stany Zjednoczone Ameryki (USA)',2,'The flag of ______ is red, white and blue.','the USA','The flag of the USA is red, white and blue.','Flaga USA jest czerwono-biało-niebieska.'),
('stayBrainy4','Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej (UK)',0,'London is the capital of ______.','the UK','London is the capital of the UK.','Londyn jest stolicą Wielkiej Brytanii.'),
('stayBrainy4','Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej (UK)',1,'My English teacher is from ______.','the UK','My English teacher is from the UK.','Mój nauczyciel angielskiego jest z Wielkiej Brytanii.'),
('stayBrainy4','Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej (UK)',2,'People drive on the left in ______.','the UK','People drive on the left in the UK.','W Wielkiej Brytanii ludzie jeżdżą lewą stroną drogi.'),
('stayBrainy4','Polska',0,'Warsaw is in ______.','Poland','Warsaw is in Poland.','Warszawa jest w Polsce.'),
('stayBrainy4','Polska',1,'I live in ______.','Poland','I live in Poland.','Mieszkam w Polsce.'),
('stayBrainy4','Polska',2,'The flag of ______ is white and red.','Poland','The flag of Poland is white and red.','Flaga Polski jest biało-czerwona.'),
('stayBrainy4','niebezpieczny',0,'Crocodiles are ______ animals.','dangerous','Crocodiles are dangerous animals.','Krokodyle to niebezpieczne zwierzęta.'),
('stayBrainy4','niebezpieczny',1,'It''s ______ to play near the road.','dangerous','It''s dangerous to play near the road.','Zabawa przy drodze jest niebezpieczna.'),
('stayBrainy4','niebezpieczny',2,'This river is ______.','dangerous','This river is dangerous.','Ta rzeka jest niebezpieczna.'),
('stayBrainy4','bezpieczny',0,'Our school is a ______ place.','safe','Our school is a safe place.','Nasza szkoła to bezpieczne miejsce.'),
('stayBrainy4','bezpieczny',1,'Is this dog ______?','safe','Is this dog safe?','Czy ten pies jest bezpieczny?'),
('stayBrainy4','bezpieczny',2,'Wear a helmet and be ______ on your bike.','safe','Wear a helmet and be safe on your bike.','Noś kask i bądź bezpieczny na rowerze.'),
('stayBrainy4','trudny',0,'This test is very ______.','difficult','This test is very difficult.','Ten test jest bardzo trudny.'),
('stayBrainy4','trudny',1,'Maths is ______ for me.','difficult','Maths is difficult for me.','Matematyka jest dla mnie trudna.'),
('stayBrainy4','trudny',2,'Chinese is a ______ language.','difficult','Chinese is a difficult language.','Chiński to trudny język.'),
('stayBrainy4','flaga',0,'The Polish ______ is white and red.','flag','The Polish flag is white and red.','Polska flaga jest biało-czerwona.'),
('stayBrainy4','flaga',1,'I can draw the ______ of Italy.','flag','I can draw the flag of Italy.','Umiem narysować flagę Włoch.'),
('stayBrainy4','flaga',2,'There is a ______ on the school building.','flag','There is a flag on the school building.','Na budynku szkoły jest flaga.'),
('stayBrainy4','popularny',0,'Football is very ______ in Poland.','popular','Football is very popular in Poland.','Piłka nożna jest bardzo popularna w Polsce.'),
('stayBrainy4','popularny',1,'Pizza is a ______ food.','popular','Pizza is a popular food.','Pizza to popularne jedzenie.'),
('stayBrainy4','popularny',2,'Tom is ______ at school. Everybody likes him.','popular','Tom is popular at school. Everybody likes him.','Tom jest popularny w szkole. Wszyscy go lubią.'),
('stayBrainy4','co, jaki',0,'______ is your favourite colour?','What','What is your favourite colour?','Jaki jest twój ulubiony kolor?'),
('stayBrainy4','co, jaki',1,'______ is this?','What','What is this?','Co to jest?'),
('stayBrainy4','co, jaki',2,'______ have you got in your bag?','What','What have you got in your bag?','Co masz w torbie?'),
('stayBrainy4','kto',0,'______ is your teacher?','Who','Who is your teacher?','Kto jest twoim nauczycielem?'),
('stayBrainy4','kto',1,'______ is that boy?','Who','Who is that boy?','Kim jest tamten chłopiec?'),
('stayBrainy4','kto',2,'______ is your best friend?','Who','Who is your best friend?','Kto jest twoim najlepszym przyjacielem?'),
('stayBrainy4','jakiego koloru',0,'______ is your schoolbag?','What colour','What colour is your schoolbag?','Jakiego koloru jest twój plecak?'),
('stayBrainy4','jakiego koloru',1,'______ are your shoes?','What colour','What colour are your shoes?','Jakiego koloru są twoje buty?'),
('stayBrainy4','jakiego koloru',2,'______ is your cat?','What colour','What colour is your cat?','Jakiego koloru jest twój kot?'),
('stayBrainy4','gdzie',0,'______ is my pen?','Where','Where is my pen?','Gdzie jest mój długopis?'),
('stayBrainy4','gdzie',1,'______ do you live?','Where','Where do you live?','Gdzie mieszkasz?'),
('stayBrainy4','gdzie',2,'______ are my keys?','Where','Where are my keys?','Gdzie są moje klucze?'),
('stayBrainy4','ile lat',0,'______ is your brother?','How old','How old is your brother?','Ile lat ma twój brat?'),
('stayBrainy4','ile lat',1,'______ is your grandmother?','How old','How old is your grandmother?','Ile lat ma twoja babcia?'),
('stayBrainy4','ile lat',2,'______ is your dog?','How old','How old is your dog?','Ile lat ma twój pies?'),
('stayBrainy4','ładowarka',0,'My phone is dead. Where''s my ______?','charger','My phone is dead. Where''s my charger?','Mój telefon się rozładował. Gdzie jest moja ładowarka?'),
('stayBrainy4','ładowarka',1,'Can I borrow your phone ______?','charger','Can I borrow your phone charger?','Czy mogę pożyczyć twoją ładowarkę do telefonu?'),
('stayBrainy4','ładowarka',2,'The ______ is next to my bed.','charger','The charger is next to my bed.','Ładowarka jest obok mojego łóżka.'),
('stayBrainy4','grzebień',0,'I''ve got a small ______ in my bag.','comb','I''ve got a small comb in my bag.','Mam mały grzebień w torbie.'),
('stayBrainy4','grzebień',1,'Use a ______ for your hair.','comb','Use a comb for your hair.','Użyj grzebienia do włosów.'),
('stayBrainy4','grzebień',2,'My ______ is pink.','comb','My comb is pink.','Mój grzebień jest różowy.'),
('stayBrainy4','szczotka do włosów',0,'Where is my ______? My hair is a mess!','hairbrush','Where is my hairbrush? My hair is a mess!','Gdzie jest moja szczotka do włosów? Moje włosy są potargane!'),
('stayBrainy4','szczotka do włosów',1,'My sister has got a purple ______.','hairbrush','My sister has got a purple hairbrush.','Moja siostra ma fioletową szczotkę do włosów.'),
('stayBrainy4','szczotka do włosów',2,'I brush my hair with a ______.','hairbrush','I brush my hair with a hairbrush.','Czeszę włosy szczotką.'),
('stayBrainy4','słuchawki',0,'I listen to music with my ______.','headphones','I listen to music with my headphones.','Słucham muzyki przez słuchawki.'),
('stayBrainy4','słuchawki',1,'My new ______ are black.','headphones','My new headphones are black.','Moje nowe słuchawki są czarne.'),
('stayBrainy4','słuchawki',2,'Put on your ______, please.','headphones','Put on your headphones, please.','Załóż słuchawki, proszę.'),
('stayBrainy4','klucz',0,'I can''t open the door. Where''s my ______?','key','I can''t open the door. Where''s my key?','Nie mogę otworzyć drzwi. Gdzie jest mój klucz?'),
('stayBrainy4','klucz',1,'The ______ is in my pocket.','key','The key is in my pocket.','Klucz jest w mojej kieszeni.'),
('stayBrainy4','klucz',2,'This is the ______ to my house.','key','This is the key to my house.','To jest klucz do mojego domu.'),
('stayBrainy4','pamięć przenośna',0,'My photos are on a ______.','memory stick','My photos are on a memory stick.','Moje zdjęcia są na pamięci przenośnej.'),
('stayBrainy4','pamięć przenośna',1,'Put the ______ into the computer.','memory stick','Put the memory stick into the computer.','Włóż pamięć przenośną do komputera.'),
('stayBrainy4','pamięć przenośna',2,'I''ve got a blue ______.','memory stick','I''ve got a blue memory stick.','Mam niebieską pamięć przenośną.'),
('stayBrainy4','portmonetka',0,'Mum''s money is in her ______.','purse','Mum''s money is in her purse.','Pieniądze mamy są w jej portmonetce.'),
('stayBrainy4','portmonetka',1,'I''ve got a red ______.','purse','I''ve got a red purse.','Mam czerwoną portmonetkę.'),
('stayBrainy4','portmonetka',2,'There are ten pounds in my ______.','purse','There are ten pounds in my purse.','W mojej portmonetce jest dziesięć funtów.'),
('stayBrainy4','pilot (np. do telewizora)',0,'Where''s the TV ______?','remote','Where''s the TV remote?','Gdzie jest pilot do telewizora?'),
('stayBrainy4','pilot (np. do telewizora)',1,'The ______ is on the sofa.','remote','The remote is on the sofa.','Pilot jest na kanapie.'),
('stayBrainy4','pilot (np. do telewizora)',2,'Can you give me the ______, please?','remote','Can you give me the remote, please?','Możesz mi podać pilota, proszę?'),
('stayBrainy4','smartfon',0,'My brother has got a new ______.','smartphone','My brother has got a new smartphone.','Mój brat ma nowy smartfon.'),
('stayBrainy4','smartfon',1,'I take photos with my ______.','smartphone','I take photos with my smartphone.','Robię zdjęcia smartfonem.'),
('stayBrainy4','smartfon',2,'Your ______ is on the table.','smartphone','Your smartphone is on the table.','Twój smartfon jest na stole.'),
('stayBrainy4','chusteczka papierowa',0,'I''ve got a cold. Can I have a ______?','tissue','I''ve got a cold. Can I have a tissue?','Jestem przeziębiony. Czy mogę dostać chusteczkę?'),
('stayBrainy4','chusteczka papierowa',1,'There''s a ______ in my pocket.','tissue','There''s a tissue in my pocket.','W mojej kieszeni jest chusteczka.'),
('stayBrainy4','chusteczka papierowa',2,'Take a ______ from the box.','tissue','Take a tissue from the box.','Weź chusteczkę z pudełka.'),
('stayBrainy4','parasol',0,'It''s raining. Take an ______.','umbrella','It''s raining. Take an umbrella.','Pada deszcz. Weź parasol.'),
('stayBrainy4','parasol',1,'My ______ is yellow.','umbrella','My umbrella is yellow.','Mój parasol jest żółty.'),
('stayBrainy4','parasol',2,'Where''s my ______?','umbrella','Where''s my umbrella?','Gdzie jest mój parasol?'),
('stayBrainy4','portfel',0,'Dad''s money is in his ______.','wallet','Dad''s money is in his wallet.','Pieniądze taty są w jego portfelu.'),
('stayBrainy4','portfel',1,'I''ve got a brown ______.','wallet','I''ve got a brown wallet.','Mam brązowy portfel.'),
('stayBrainy4','portfel',2,'Oh no! My ______ is at home.','wallet','Oh no! My wallet is at home.','O nie! Mój portfel jest w domu.'),
('stayBrainy4','czapka',0,'It''s sunny. Put on your ______.','cap','It''s sunny. Put on your cap.','Jest słonecznie. Załóż czapkę.'),
('stayBrainy4','czapka',1,'My ______ is red and white.','cap','My cap is red and white.','Moja czapka jest czerwono-biała.'),
('stayBrainy4','czapka',2,'Tom is wearing a blue ______.','cap','Tom is wearing a blue cap.','Tom ma na sobie niebieską czapkę.'),
('stayBrainy4','sukienka',0,'My sister is wearing a pink ______.','dress','My sister is wearing a pink dress.','Moja siostra ma na sobie różową sukienkę.'),
('stayBrainy4','sukienka',1,'This ______ is very pretty.','dress','This dress is very pretty.','Ta sukienka jest bardzo ładna.'),
('stayBrainy4','sukienka',2,'Mum has got a new ______ for the party.','dress','Mum has got a new dress for the party.','Mama ma nową sukienkę na przyjęcie.'),
('stayBrainy4','kurtka',0,'It''s cold. Put on your ______.','jacket','It''s cold. Put on your jacket.','Jest zimno. Załóż kurtkę.'),
('stayBrainy4','kurtka',1,'My ______ is black.','jacket','My jacket is black.','Moja kurtka jest czarna.'),
('stayBrainy4','kurtka',2,'Your ______ is on the chair.','jacket','Your jacket is on the chair.','Twoja kurtka jest na krześle.'),
('stayBrainy4','sandały',0,'I wear ______ in summer.','sandals','I wear sandals in summer.','Latem noszę sandały.'),
('stayBrainy4','sandały',1,'My new ______ are brown.','sandals','My new sandals are brown.','Moje nowe sandały są brązowe.'),
('stayBrainy4','sandały',2,'Put on your ______. We''re going to the beach.','sandals','Put on your sandals. We''re going to the beach.','Załóż sandały. Idziemy na plażę.'),
('stayBrainy4','koszula',0,'Dad is wearing a white ______.','shirt','Dad is wearing a white shirt.','Tata ma na sobie białą koszulę.'),
('stayBrainy4','koszula',1,'This ______ is too big for me.','shirt','This shirt is too big for me.','Ta koszula jest dla mnie za duża.'),
('stayBrainy4','koszula',2,'I wear a ______ to school.','shirt','I wear a shirt to school.','Noszę koszulę do szkoły.'),
('stayBrainy4','buty',0,'My ______ are under the bed.','shoes','My shoes are under the bed.','Moje buty są pod łóżkiem.'),
('stayBrainy4','buty',1,'Put on your ______.','shoes','Put on your shoes.','Załóż buty.'),
('stayBrainy4','buty',2,'These ______ are new.','shoes','These shoes are new.','Te buty są nowe.'),
('stayBrainy4','szorty',0,'It''s hot. I''m wearing ______.','shorts','It''s hot. I''m wearing shorts.','Jest gorąco. Mam na sobie szorty.'),
('stayBrainy4','szorty',1,'My ______ are blue.','shorts','My shorts are blue.','Moje szorty są niebieskie.'),
('stayBrainy4','szorty',2,'I wear ______ when I play football.','shorts','I wear shorts when I play football.','Noszę szorty, kiedy gram w piłkę nożną.'),
('stayBrainy4','spódnica',0,'Anna is wearing a red ______.','skirt','Anna is wearing a red skirt.','Anna ma na sobie czerwoną spódnicę.'),
('stayBrainy4','spódnica',1,'This ______ is long.','skirt','This skirt is long.','Ta spódnica jest długa.'),
('stayBrainy4','spódnica',2,'My sister has got a new ______.','skirt','My sister has got a new skirt.','Moja siostra ma nową spódnicę.'),
('stayBrainy4','skarpetki',0,'I''ve got green ______.','socks','I''ve got green socks.','Mam zielone skarpetki.'),
('stayBrainy4','skarpetki',1,'Put on your ______ and shoes.','socks','Put on your socks and shoes.','Załóż skarpetki i buty.'),
('stayBrainy4','skarpetki',2,'Where are my ______?','socks','Where are my socks?','Gdzie są moje skarpetki?'),
('stayBrainy4','sweter',0,'It''s cold. Put on a ______.','sweater','It''s cold. Put on a sweater.','Jest zimno. Załóż sweter.'),
('stayBrainy4','sweter',1,'My ______ is very warm.','sweater','My sweater is very warm.','Mój sweter jest bardzo ciepły.'),
('stayBrainy4','sweter',2,'Grandma has got a green ______.','sweater','Grandma has got a green sweater.','Babcia ma zielony sweter.'),
('stayBrainy4','buty sportowe',0,'I wear ______ for PE.','trainers','I wear trainers for PE.','Na WF noszę buty sportowe.'),
('stayBrainy4','buty sportowe',1,'My new ______ are white.','trainers','My new trainers are white.','Moje nowe buty sportowe są białe.'),
('stayBrainy4','buty sportowe',2,'Put on your ______. We''re going running.','trainers','Put on your trainers. We''re going running.','Załóż buty sportowe. Idziemy biegać.'),
('stayBrainy4','spodnie',0,'Dad is wearing black ______.','trousers','Dad is wearing black trousers.','Tata ma na sobie czarne spodnie.'),
('stayBrainy4','spodnie',1,'These ______ are too long.','trousers','These trousers are too long.','Te spodnie są za długie.'),
('stayBrainy4','spodnie',2,'My ______ are on the chair.','trousers','My trousers are on the chair.','Moje spodnie są na krześle.'),
('stayBrainy4','koszulka',0,'I''m wearing a green ______.','T-shirt','I''m wearing a green T-shirt.','Mam na sobie zieloną koszulkę.'),
('stayBrainy4','koszulka',1,'My favourite ______ is white.','T-shirt','My favourite T-shirt is white.','Moja ulubiona koszulka jest biała.'),
('stayBrainy4','koszulka',2,'This ______ is from London.','T-shirt','This T-shirt is from London.','Ta koszulka jest z Londynu.'),
('stayBrainy4','to, ta, ten (l. poj., blisko)',0,'______ is my brother.','This','This is my brother.','To jest mój brat.'),
('stayBrainy4','to, ta, ten (l. poj., blisko)',1,'I like ______ book.','this','I like this book.','Lubię tę książkę.'),
('stayBrainy4','to, ta, ten (l. poj., blisko)',2,'Is ______ your pen?','this','Is this your pen?','Czy to jest twój długopis?'),
('stayBrainy4','to, tamto, tamta, tamten (l. poj., daleko)',0,'Look at ______ dog over there!','that','Look at that dog over there!','Spójrz na tamtego psa!'),
('stayBrainy4','to, tamto, tamta, tamten (l. poj., daleko)',1,'______ girl over there is my sister.','That','That girl over there is my sister.','Tamta dziewczynka to moja siostra.'),
('stayBrainy4','to, tamto, tamta, tamten (l. poj., daleko)',2,'Who is ______ man?','that','Who is that man?','Kim jest tamten mężczyzna?'),
('stayBrainy4','to, te, ci (l. mn., blisko)',0,'______ are my shoes.','These','These are my shoes.','To są moje buty.'),
('stayBrainy4','to, te, ci (l. mn., blisko)',1,'I like ______ socks.','these','I like these socks.','Lubię te skarpetki.'),
('stayBrainy4','to, te, ci (l. mn., blisko)',2,'Are ______ your crayons?','these','Are these your crayons?','Czy to są twoje kredki?'),
('stayBrainy4','to, tamte, tamci (l. mn., daleko)',0,'______ boys over there are my brothers.','Those','Those boys over there are my brothers.','Tamci chłopcy to moi bracia.'),
('stayBrainy4','to, tamte, tamci (l. mn., daleko)',1,'Look at ______ birds!','those','Look at those birds!','Spójrz na tamte ptaki!'),
('stayBrainy4','to, tamte, tamci (l. mn., daleko)',2,'Are ______ trainers over there yours?','those','Are those trainers over there yours?','Czy tamte buty sportowe są twoje?'),
('stayBrainy4','ciocia',0,'My ______ is my mum''s sister.','aunt','My aunt is my mum''s sister.','Moja ciocia jest siostrą mojej mamy.'),
('stayBrainy4','ciocia',1,'My ______ lives in London.','aunt','My aunt lives in London.','Moja ciocia mieszka w Londynie.'),
('stayBrainy4','ciocia',2,'I visit my ______ on Sunday.','aunt','I visit my aunt on Sunday.','W niedzielę odwiedzam ciocię.'),
('stayBrainy4','brat',0,'My ______ is ten years old.','brother','My brother is ten years old.','Mój brat ma dziesięć lat.'),
('stayBrainy4','brat',1,'I''ve got one sister and one ______.','brother','I''ve got one sister and one brother.','Mam jedną siostrę i jednego brata.'),
('stayBrainy4','brat',2,'My little ______ likes cars.','brother','My little brother likes cars.','Mój młodszy brat lubi samochody.'),
('stayBrainy4','kuzyn',0,'My ______ is my uncle''s son.','cousin','My cousin is my uncle''s son.','Mój kuzyn jest synem mojego wujka.'),
('stayBrainy4','kuzyn',1,'I play with my ______ at the weekend.','cousin','I play with my cousin at the weekend.','W weekend bawię się z kuzynem.'),
('stayBrainy4','kuzyn',2,'My ______ lives in Germany.','cousin','My cousin lives in Germany.','Mój kuzyn mieszka w Niemczech.'),
('stayBrainy4','ojciec',0,'My ______ is a teacher.','father','My father is a teacher.','Mój ojciec jest nauczycielem.'),
('stayBrainy4','ojciec',1,'My ______ has got short hair.','father','My father has got short hair.','Mój ojciec ma krótkie włosy.'),
('stayBrainy4','ojciec',2,'This is my ______. His name is Adam.','father','This is my father. His name is Adam.','To mój ojciec. Ma na imię Adam.'),
('stayBrainy4','dziadek',0,'My ______ is seventy years old.','grandfather','My grandfather is seventy years old.','Mój dziadek ma siedemdziesiąt lat.'),
('stayBrainy4','dziadek',1,'My ______ has got a garden.','grandfather','My grandfather has got a garden.','Mój dziadek ma ogród.'),
('stayBrainy4','dziadek',2,'My ______ is my dad''s father.','grandfather','My grandfather is my dad''s father.','Mój dziadek jest tatą mojego taty.'),
('stayBrainy4','babcia',0,'My ______ makes great cakes.','grandmother','My grandmother makes great cakes.','Moja babcia piecze świetne ciasta.'),
('stayBrainy4','babcia',1,'My ______ is my mum''s mother.','grandmother','My grandmother is my mum''s mother.','Moja babcia jest mamą mojej mamy.'),
('stayBrainy4','babcia',2,'I visit my ______ every Sunday.','grandmother','I visit my grandmother every Sunday.','Odwiedzam babcię w każdą niedzielę.'),
('stayBrainy4','pradziadek',0,'My ______ is ninety years old.','great-grandfather','My great-grandfather is ninety years old.','Mój pradziadek ma dziewięćdziesiąt lat.'),
('stayBrainy4','pradziadek',1,'My ______ is my grandmother''s father.','great-grandfather','My great-grandfather is my grandmother''s father.','Mój pradziadek jest tatą mojej babci.'),
('stayBrainy4','pradziadek',2,'My ______ tells funny stories.','great-grandfather','My great-grandfather tells funny stories.','Mój pradziadek opowiada zabawne historie.'),
('stayBrainy4','prababcia',0,'My ______ is eighty-five years old.','great-grandmother','My great-grandmother is eighty-five years old.','Moja prababcia ma osiemdziesiąt pięć lat.'),
('stayBrainy4','prababcia',1,'My ______ is my grandfather''s mother.','great-grandmother','My great-grandmother is my grandfather''s mother.','Moja prababcia jest mamą mojego dziadka.'),
('stayBrainy4','prababcia',2,'My ______ has got white hair.','great-grandmother','My great-grandmother has got white hair.','Moja prababcia ma białe włosy.'),
('stayBrainy4','matka',0,'My ______ is a doctor.','mother','My mother is a doctor.','Moja matka jest lekarką.'),
('stayBrainy4','matka',1,'My ______ has got long brown hair.','mother','My mother has got long brown hair.','Moja matka ma długie brązowe włosy.'),
('stayBrainy4','matka',2,'This is my ______. Her name is Ewa.','mother','This is my mother. Her name is Ewa.','To moja matka. Ma na imię Ewa.'),
('stayBrainy4','siostra',0,'My ______ is five years old.','sister','My sister is five years old.','Moja siostra ma pięć lat.'),
('stayBrainy4','siostra',1,'I''ve got a little ______.','sister','I''ve got a little sister.','Mam młodszą siostrę.'),
('stayBrainy4','siostra',2,'My ______ likes dancing.','sister','My sister likes dancing.','Moja siostra lubi tańczyć.'),
('stayBrainy4','wujek',0,'My ______ is my dad''s brother.','uncle','My uncle is my dad''s brother.','Mój wujek jest bratem mojego taty.'),
('stayBrainy4','wujek',1,'My ______ has got a big dog.','uncle','My uncle has got a big dog.','Mój wujek ma dużego psa.'),
('stayBrainy4','wujek',2,'My ______ can play the guitar.','uncle','My uncle can play the guitar.','Mój wujek umie grać na gitarze.'),
('stayBrainy4','czarne',0,'She''s got long ______ hair.','black','She''s got long black hair.','Ona ma długie czarne włosy.'),
('stayBrainy4','czarne',1,'My dad has got short ______ hair.','black','My dad has got short black hair.','Mój tata ma krótkie czarne włosy.'),
('stayBrainy4','czarne',2,'Has your sister got ______ hair?','black','Has your sister got black hair?','Czy twoja siostra ma czarne włosy?'),
('stayBrainy4','kręcone',0,'My cousin has got ______ hair.','curly','My cousin has got curly hair.','Mój kuzyn ma kręcone włosy.'),
('stayBrainy4','kręcone',1,'She''s got short ______ hair.','curly','She''s got short curly hair.','Ona ma krótkie kręcone włosy.'),
('stayBrainy4','kręcone',2,'I''ve got long ______ red hair.','curly','I''ve got long curly red hair.','Mam długie kręcone rude włosy.'),
('stayBrainy4','jasne',0,'My sister has got long ______ hair.','fair','My sister has got long fair hair.','Moja siostra ma długie jasne włosy.'),
('stayBrainy4','jasne',1,'He''s got short ______ hair and blue eyes.','fair','He''s got short fair hair and blue eyes.','On ma krótkie jasne włosy i niebieskie oczy.'),
('stayBrainy4','jasne',2,'Has your brother got ______ hair?','fair','Has your brother got fair hair?','Czy twój brat ma jasne włosy?'),
('stayBrainy4','siwe',0,'My grandma has got short ______ hair.','grey','My grandma has got short grey hair.','Moja babcia ma krótkie siwe włosy.'),
('stayBrainy4','siwe',1,'Our teacher has got ______ hair.','grey','Our teacher has got grey hair.','Nasz nauczyciel ma siwe włosy.'),
('stayBrainy4','siwe',2,'Has your grandfather got ______ hair?','grey','Has your grandfather got grey hair?','Czy twój dziadek ma siwe włosy?'),
('stayBrainy4','długie',0,'Rapunzel has got very ______ hair.','long','Rapunzel has got very long hair.','Roszpunka ma bardzo długie włosy.'),
('stayBrainy4','długie',1,'My mum has got ______ straight hair.','long','My mum has got long straight hair.','Moja mama ma długie proste włosy.'),
('stayBrainy4','długie',2,'Have you got ______ hair?','long','Have you got long hair?','Czy masz długie włosy?'),
('stayBrainy4','rude',0,'He''s got short ______ hair.','red','He''s got short red hair.','On ma krótkie rude włosy.'),
('stayBrainy4','rude',1,'My friend has got curly ______ hair.','red','My friend has got curly red hair.','Mój przyjaciel ma kręcone rude włosy.'),
('stayBrainy4','rude',2,'Has your cousin got ______ hair?','red','Has your cousin got red hair?','Czy twoja kuzynka ma rude włosy?'),
('stayBrainy4','krótkie',0,'My brother has got ______ hair.','short','My brother has got short hair.','Mój brat ma krótkie włosy.'),
('stayBrainy4','krótkie',1,'She''s got ______ curly hair.','short','She''s got short curly hair.','Ona ma krótkie kręcone włosy.'),
('stayBrainy4','krótkie',2,'Have you got long or ______ hair?','short','Have you got long or short hair?','Masz długie czy krótkie włosy?'),
('stayBrainy4','proste',0,'My sister has got long ______ hair.','straight','My sister has got long straight hair.','Moja siostra ma długie proste włosy.'),
('stayBrainy4','proste',1,'Is her hair curly or ______?','straight','Is her hair curly or straight?','Czy ona ma kręcone, czy proste włosy?'),
('stayBrainy4','proste',2,'He''s got short ______ black hair.','straight','He''s got short straight black hair.','On ma krótkie proste czarne włosy.'),
('stayBrainy4','falowane',0,'My aunt has got ______ hair.','wavy','My aunt has got wavy hair.','Moja ciocia ma falowane włosy.'),
('stayBrainy4','falowane',1,'She''s got long ______ brown hair.','wavy','She''s got long wavy brown hair.','Ona ma długie falowane brązowe włosy.'),
('stayBrainy4','falowane',2,'Has your mum got ______ hair?','wavy','Has your mum got wavy hair?','Czy twoja mama ma falowane włosy?'),
('stayBrainy4','wspinać się na drzewa',0,'I can ______.','climb trees','I can climb trees.','Umiem wspinać się na drzewa.'),
('stayBrainy4','wspinać się na drzewa',1,'Monkeys can ______ very fast.','climb trees','Monkeys can climb trees very fast.','Małpy potrafią bardzo szybko wspinać się na drzewa.'),
('stayBrainy4','wspinać się na drzewa',2,'My brother likes to ______ in the park.','climb trees','My brother likes to climb trees in the park.','Mój brat lubi wspinać się na drzewa w parku.'),
('stayBrainy4','robić sztuczki na deskorolce',0,'My cousin can ______.','do skateboard tricks','My cousin can do skateboard tricks.','Mój kuzyn umie robić sztuczki na deskorolce.'),
('stayBrainy4','robić sztuczki na deskorolce',1,'Can you ______?','do skateboard tricks','Can you do skateboard tricks?','Czy umiesz robić sztuczki na deskorolce?'),
('stayBrainy4','robić sztuczki na deskorolce',2,'Tom likes to ______ in the park.','do skateboard tricks','Tom likes to do skateboard tricks in the park.','Tom lubi robić sztuczki na deskorolce w parku.'),
('stayBrainy4','prowadzić samochód',0,'My mum can ______.','drive a car','My mum can drive a car.','Moja mama umie prowadzić samochód.'),
('stayBrainy4','prowadzić samochód',1,'Children can''t ______.','drive a car','Children can''t drive a car.','Dzieci nie mogą prowadzić samochodu.'),
('stayBrainy4','prowadzić samochód',2,'Can your grandfather ______?','drive a car','Can your grandfather drive a car?','Czy twój dziadek umie prowadzić samochód?'),
('stayBrainy4','latać',0,'Birds can ______.','fly','Birds can fly.','Ptaki umieją latać.'),
('stayBrainy4','latać',1,'Penguins can''t ______.','fly','Penguins can''t fly.','Pingwiny nie umieją latać.'),
('stayBrainy4','latać',2,'I want to ______ like a bird.','fly','I want to fly like a bird.','Chcę latać jak ptak.'),
('stayBrainy4','jeździć na rowerze',0,'I can ______.','ride a bicycle','I can ride a bicycle.','Umiem jeździć na rowerze.'),
('stayBrainy4','jeździć na rowerze',1,'My little sister can''t ______.','ride a bicycle','My little sister can''t ride a bicycle.','Moja młodsza siostra nie umie jeździć na rowerze.'),
('stayBrainy4','jeździć na rowerze',2,'It''s fun to ______ in the park.','ride a bicycle','It''s fun to ride a bicycle in the park.','Fajnie jest jeździć na rowerze w parku.'),
('stayBrainy4','jeździć na nartach',0,'We can ______ in the mountains.','ski','We can ski in the mountains.','Umiemy jeździć na nartach w górach.'),
('stayBrainy4','jeździć na nartach',1,'Can you ______?','ski','Can you ski?','Czy umiesz jeździć na nartach?'),
('stayBrainy4','jeździć na nartach',2,'My dad likes to ______ in winter.','ski','My dad likes to ski in winter.','Mój tata lubi jeździć na nartach zimą.'),
('stayBrainy4','mówić po chińsku',0,'My teacher can ______.','speak Chinese','My teacher can speak Chinese.','Moja nauczycielka umie mówić po chińsku.'),
('stayBrainy4','mówić po chińsku',1,'People in China ______.','speak Chinese','People in China speak Chinese.','Ludzie w Chinach mówią po chińsku.'),
('stayBrainy4','mówić po chińsku',2,'I can''t ______. It''s difficult!','speak Chinese','I can''t speak Chinese. It''s difficult!','Nie umiem mówić po chińsku. To trudne!'),
('stayBrainy4','mówić po angielsku',0,'I can ______.','speak English','I can speak English.','Umiem mówić po angielsku.'),
('stayBrainy4','mówić po angielsku',1,'People in England ______.','speak English','People in England speak English.','Ludzie w Anglii mówią po angielsku.'),
('stayBrainy4','mówić po angielsku',2,'Can your mum ______?','speak English','Can your mum speak English?','Czy twoja mama umie mówić po angielsku?'),
('stayBrainy4','pływać',0,'Fish can ______.','swim','Fish can swim.','Ryby umieją pływać.'),
('stayBrainy4','pływać',1,'I ______ in the pool on Saturday.','swim','I swim in the pool on Saturday.','W sobotę pływam na basenie.'),
('stayBrainy4','pływać',2,'Can you ______ fast?','swim','Can you swim fast?','Czy umiesz szybko pływać?'),
('stayBrainy4','opowiadać kawały',0,'My uncle likes to ______.','tell jokes','My uncle likes to tell jokes.','Mój wujek lubi opowiadać kawały.'),
('stayBrainy4','opowiadać kawały',1,'Can you ______?','tell jokes','Can you tell jokes?','Czy umiesz opowiadać kawały?'),
('stayBrainy4','opowiadać kawały',2,'Tom is funny. He can ______ very well.','tell jokes','Tom is funny. He can tell jokes very well.','Tom jest zabawny. Umie bardzo dobrze opowiadać kawały.'),
('stayBrainy4','gotować',0,'My dad can ______ very well.','cook','My dad can cook very well.','Mój tata umie bardzo dobrze gotować.'),
('stayBrainy4','gotować',1,'I can''t ______.','cook','I can''t cook.','Nie umiem gotować.'),
('stayBrainy4','gotować',2,'Grandma likes to ______ for the family.','cook','Grandma likes to cook for the family.','Babcia lubi gotować dla rodziny.'),
('stayBrainy4','jeździć na łyżwach',0,'Can you ______?','ice-skate','Can you ice-skate?','Czy umiesz jeździć na łyżwach?'),
('stayBrainy4','jeździć na łyżwach',1,'We ______ in winter.','ice-skate','We ice-skate in winter.','Zimą jeździmy na łyżwach.'),
('stayBrainy4','jeździć na łyżwach',2,'My sister can ______ very well.','ice-skate','My sister can ice-skate very well.','Moja siostra umie bardzo dobrze jeździć na łyżwach.'),
('stayBrainy4','malować',0,'I like to ______ pictures.','paint','I like to paint pictures.','Lubię malować obrazki.'),
('stayBrainy4','malować',1,'My friend can ______ animals.','paint','My friend can paint animals.','Moja koleżanka umie malować zwierzęta.'),
('stayBrainy4','malować',2,'Can you ______ a flower?','paint','Can you paint a flower?','Czy umiesz namalować kwiatek?'),
('stayBrainy4','grać w szachy',0,'My grandfather can ______.','play chess','My grandfather can play chess.','Mój dziadek umie grać w szachy.'),
('stayBrainy4','grać w szachy',1,'Do you ______?','play chess','Do you play chess?','Czy grasz w szachy?'),
('stayBrainy4','grać w szachy',2,'We ______ after school.','play chess','We play chess after school.','Po szkole gramy w szachy.'),
('stayBrainy4','grać na pianinie',0,'My sister can ______.','play the piano','My sister can play the piano.','Moja siostra umie grać na pianinie.'),
('stayBrainy4','grać na pianinie',1,'I ______ every day.','play the piano','I play the piano every day.','Gram na pianinie codziennie.'),
('stayBrainy4','grać na pianinie',2,'Can you ______?','play the piano','Can you play the piano?','Czy umiesz grać na pianinie?'),
('stayBrainy4','czytać nuty',0,'I can ______.','read music','I can read music.','Umiem czytać nuty.'),
('stayBrainy4','czytać nuty',1,'Can you ______?','read music','Can you read music?','Czy umiesz czytać nuty?'),
('stayBrainy4','czytać nuty',2,'Musicians can ______.','read music','Musicians can read music.','Muzycy umieją czytać nuty.'),
('stayBrainy4','jeździć na rolkach',0,'I ______ in the park.','rollerblade','I rollerblade in the park.','Jeżdżę na rolkach w parku.'),
('stayBrainy4','jeździć na rolkach',1,'Can you ______?','rollerblade','Can you rollerblade?','Czy umiesz jeździć na rolkach?'),
('stayBrainy4','jeździć na rolkach',2,'My brother can ______ fast.','rollerblade','My brother can rollerblade fast.','Mój brat umie szybko jeździć na rolkach.'),
('stayBrainy4','śpiewać',0,'I can ______ well.','sing','I can sing well.','Umiem dobrze śpiewać.'),
('stayBrainy4','śpiewać',1,'Birds ______ in the morning.','sing','Birds sing in the morning.','Ptaki śpiewają rano.'),
('stayBrainy4','śpiewać',2,'Let''s ______ a song!','sing','Let''s sing a song!','Zaśpiewajmy piosenkę!'),
('stayBrainy4','jeździć na snowboardzie',0,'My cousin can ______.','snowboard','My cousin can snowboard.','Mój kuzyn umie jeździć na snowboardzie.'),
('stayBrainy4','jeździć na snowboardzie',1,'We ______ in the mountains in winter.','snowboard','We snowboard in the mountains in winter.','Zimą jeździmy na snowboardzie w górach.'),
('stayBrainy4','jeździć na snowboardzie',2,'Can you ______?','snowboard','Can you snowboard?','Czy umiesz jeździć na snowboardzie?'),
('stayBrainy4','gwizdać',0,'I can ______.','whistle','I can whistle.','Umiem gwizdać.'),
('stayBrainy4','gwizdać',1,'My dad can ______ a song.','whistle','My dad can whistle a song.','Mój tata umie wygwizdać piosenkę.'),
('stayBrainy4','gwizdać',2,'Please don''t ______ in the classroom.','whistle','Please don''t whistle in the classroom.','Proszę, nie gwiżdż w klasie.'),
('stayBrainy4','ciastko',0,'Can I have a ______, please?','biscuit','Can I have a biscuit, please?','Czy mogę prosić o ciastko?'),
('stayBrainy4','ciastko',1,'I eat a ______ with my tea.','biscuit','I eat a biscuit with my tea.','Jem ciastko do herbaty.'),
('stayBrainy4','ciastko',2,'There are some chocolate ______ in the box.','biscuits','There are some chocolate biscuits in the box.','W pudełku są czekoladowe ciastka.'),
('stayBrainy4','chleb',0,'I eat ______ with butter for breakfast.','bread','I eat bread with butter for breakfast.','Na śniadanie jem chleb z masłem.'),
('stayBrainy4','chleb',1,'There is some ______ on the table.','bread','There is some bread on the table.','Na stole jest trochę chleba.'),
('stayBrainy4','chleb',2,'Mum buys ______ at the shop.','bread','Mum buys bread at the shop.','Mama kupuje chleb w sklepie.'),
('stayBrainy4','ciasto',0,'Grandma makes a chocolate ______.','cake','Grandma makes a chocolate cake.','Babcia piecze ciasto czekoladowe.'),
('stayBrainy4','ciasto',1,'There''s a big ______ for my birthday.','cake','There''s a big cake for my birthday.','Na moje urodziny jest duże ciasto.'),
('stayBrainy4','ciasto',2,'Can I have some ______, please?','cake','Can I have some cake, please?','Czy mogę prosić o kawałek ciasta?'),
('stayBrainy4','ser',0,'I like ______ sandwiches.','cheese','I like cheese sandwiches.','Lubię kanapki z serem.'),
('stayBrainy4','ser',1,'Mice like ______.','cheese','Mice like cheese.','Myszy lubią ser.'),
('stayBrainy4','ser',2,'There is some ______ on my pizza.','cheese','There is some cheese on my pizza.','Na mojej pizzy jest trochę sera.'),
('stayBrainy4','lody',0,'I like strawberry ______.','ice cream','I like strawberry ice cream.','Lubię lody truskawkowe.'),
('stayBrainy4','lody',1,'We eat ______ in summer.','ice cream','We eat ice cream in summer.','Latem jemy lody.'),
('stayBrainy4','lody',2,'Can I have some ______, please?','ice cream','Can I have some ice cream, please?','Czy mogę prosić o lody?'),
('stayBrainy4','dżem',0,'I eat bread with ______.','jam','I eat bread with jam.','Jem chleb z dżemem.'),
('stayBrainy4','dżem',1,'Grandma makes strawberry ______.','jam','Grandma makes strawberry jam.','Babcia robi dżem truskawkowy.'),
('stayBrainy4','dżem',2,'There''s some ______ in the fridge.','jam','There''s some jam in the fridge.','W lodówce jest trochę dżemu.'),
('stayBrainy4','makaron',0,'I like ______ with tomato sauce.','pasta','I like pasta with tomato sauce.','Lubię makaron z sosem pomidorowym.'),
('stayBrainy4','makaron',1,'We have ______ for dinner.','pasta','We have pasta for dinner.','Na obiad jemy makaron.'),
('stayBrainy4','makaron',2,'Italian ______ is delicious.','pasta','Italian pasta is delicious.','Włoski makaron jest pyszny.'),
('stayBrainy4','pizza',0,'I like ______ with cheese and ham.','pizza','I like pizza with cheese and ham.','Lubię pizzę z serem i szynką.'),
('stayBrainy4','pizza',1,'Let''s order a ______!','pizza','Let''s order a pizza!','Zamówmy pizzę!'),
('stayBrainy4','pizza',2,'This ______ is very big.','pizza','This pizza is very big.','Ta pizza jest bardzo duża.'),
('stayBrainy4','kiełbaska',0,'I have a ______ for breakfast.','sausage','I have a sausage for breakfast.','Na śniadanie jem kiełbaskę.'),
('stayBrainy4','kiełbaska',1,'Dogs like ______.','sausages','Dogs like sausages.','Psy lubią kiełbaski.'),
('stayBrainy4','kiełbaska',2,'There are two ______ on my plate.','sausages','There are two sausages on my plate.','Na moim talerzu są dwie kiełbaski.'),
('stayBrainy4','truskawka',0,'______ are red and sweet.','Strawberries','Strawberries are red and sweet.','Truskawki są czerwone i słodkie.'),
('stayBrainy4','truskawka',1,'There''s a ______ on my cake.','strawberry','There''s a strawberry on my cake.','Na moim cieście jest truskawka.'),
('stayBrainy4','truskawka',2,'Grandma grows ______ in her garden.','strawberries','Grandma grows strawberries in her garden.','Babcia uprawia truskawki w ogrodzie.'),
('stayBrainy4','fasola',0,'I don''t like green ______.','beans','I don''t like green beans.','Nie lubię zielonej fasolki.'),
('stayBrainy4','fasola',1,'There are some ______ in the soup.','beans','There are some beans in the soup.','W zupie jest trochę fasoli.'),
('stayBrainy4','fasola',2,'I eat ______ on toast for breakfast.','beans','I eat beans on toast for breakfast.','Na śniadanie jem fasolkę na grzance.'),
('stayBrainy4','burak czerwony',0,'______ is red.','Beetroot','Beetroot is red.','Burak jest czerwony.'),
('stayBrainy4','burak czerwony',1,'Grandma makes soup with ______.','beetroot','Grandma makes soup with beetroot.','Babcia robi zupę z buraków.'),
('stayBrainy4','burak czerwony',2,'There''s some ______ in the salad.','beetroot','There''s some beetroot in the salad.','W sałatce jest trochę buraka.'),
('stayBrainy4','kapusta',0,'There is a big ______ in the garden.','cabbage','There is a big cabbage in the garden.','W ogrodzie jest duża kapusta.'),
('stayBrainy4','kapusta',1,'Rabbits like ______.','cabbage','Rabbits like cabbage.','Króliki lubią kapustę.'),
('stayBrainy4','kapusta',2,'Mum makes soup with ______.','cabbage','Mum makes soup with cabbage.','Mama robi zupę z kapusty.'),
('stayBrainy4','marchewka',0,'Rabbits love ______.','carrots','Rabbits love carrots.','Króliki uwielbiają marchewki.'),
('stayBrainy4','marchewka',1,'______ are orange.','Carrots','Carrots are orange.','Marchewki są pomarańczowe.'),
('stayBrainy4','marchewka',2,'I eat a ______ every day.','carrot','I eat a carrot every day.','Codziennie jem marchewkę.'),
('stayBrainy4','ogórek',0,'There''s a ______ in my sandwich.','cucumber','There''s a cucumber in my sandwich.','W mojej kanapce jest ogórek.'),
('stayBrainy4','ogórek',1,'A ______ is long and green.','cucumber','A cucumber is long and green.','Ogórek jest długi i zielony.'),
('stayBrainy4','ogórek',2,'I want a tomato and ______ salad.','cucumber','I want a tomato and cucumber salad.','Chcę sałatkę z pomidorów i ogórków.'),
('stayBrainy4','cebula',0,'______ make me cry.','Onions','Onions make me cry.','Cebula sprawia, że płaczę.'),
('stayBrainy4','cebula',1,'There''s an ______ in the soup.','onion','There''s an onion in the soup.','W zupie jest cebula.'),
('stayBrainy4','cebula',2,'I don''t like ______ on my pizza.','onion','I don''t like onion on my pizza.','Nie lubię cebuli na pizzy.'),
('stayBrainy4','czerwona papryka',0,'I like ______ in my salad.','red pepper','I like red pepper in my salad.','Lubię czerwoną paprykę w sałatce.'),
('stayBrainy4','czerwona papryka',1,'A ______ is sweet and crunchy.','red pepper','A red pepper is sweet and crunchy.','Czerwona papryka jest słodka i chrupiąca.'),
('stayBrainy4','czerwona papryka',2,'There''s some ______ on the pizza.','red pepper','There''s some red pepper on the pizza.','Na pizzy jest trochę czerwonej papryki.'),
('stayBrainy4','pomidor',0,'A ______ is red.','tomato','A tomato is red.','Pomidor jest czerwony.'),
('stayBrainy4','pomidor',1,'I like ______ soup.','tomato','I like tomato soup.','Lubię zupę pomidorową.'),
('stayBrainy4','pomidor',2,'There are three ______ in the fridge.','tomatoes','There are three tomatoes in the fridge.','W lodówce są trzy pomidory.'),
('stayBrainy4','bekon',0,'Dad eats eggs and ______ for breakfast.','bacon','Dad eats eggs and bacon for breakfast.','Tata je jajka z bekonem na śniadanie.'),
('stayBrainy4','bekon',1,'I like ______ sandwiches.','bacon','I like bacon sandwiches.','Lubię kanapki z bekonem.'),
('stayBrainy4','bekon',2,'There is some ______ on my plate.','bacon','There is some bacon on my plate.','Na moim talerzu jest trochę bekonu.'),
('stayBrainy4','jagody',0,'I like ______ with yoghurt.','blueberries','I like blueberries with yoghurt.','Lubię jagody z jogurtem.'),
('stayBrainy4','jagody',1,'______ are small and blue.','Blueberries','Blueberries are small and blue.','Jagody są małe i niebieskie.'),
('stayBrainy4','jagody',2,'There are some ______ on my cake.','blueberries','There are some blueberries on my cake.','Na moim cieście są jagody.'),
('stayBrainy4','kurczak',0,'We have ______ and rice for dinner.','chicken','We have chicken and rice for dinner.','Na obiad jemy kurczaka z ryżem.'),
('stayBrainy4','kurczak',1,'I like ______ soup.','chicken','I like chicken soup.','Lubię rosół z kurczaka.'),
('stayBrainy4','kurczak',2,'Is there any ______ in the fridge?','chicken','Is there any chicken in the fridge?','Czy w lodówce jest kurczak?'),
('stayBrainy4','winogrona',0,'I like green ______.','grapes','I like green grapes.','Lubię zielone winogrona.'),
('stayBrainy4','winogrona',1,'There are some ______ in the bowl.','grapes','There are some grapes in the bowl.','W misce są winogrona.'),
('stayBrainy4','winogrona',2,'______ are sweet.','Grapes','Grapes are sweet.','Winogrona są słodkie.'),
('stayBrainy4','szynka',0,'I want a ______ sandwich.','ham','I want a ham sandwich.','Chcę kanapkę z szynką.'),
('stayBrainy4','szynka',1,'There''s some ______ in the fridge.','ham','There''s some ham in the fridge.','W lodówce jest trochę szynki.'),
('stayBrainy4','szynka',2,'I eat bread with ______ and cheese.','ham','I eat bread with ham and cheese.','Jem chleb z szynką i serem.'),
('stayBrainy4','cytryna',0,'A ______ is yellow.','lemon','A lemon is yellow.','Cytryna jest żółta.'),
('stayBrainy4','cytryna',1,'I like tea with ______.','lemon','I like tea with lemon.','Lubię herbatę z cytryną.'),
('stayBrainy4','cytryna',2,'This ______ is very sour.','lemon','This lemon is very sour.','Ta cytryna jest bardzo kwaśna.'),
('stayBrainy4','sałata',0,'There''s some ______ in my sandwich.','lettuce','There''s some lettuce in my sandwich.','W mojej kanapce jest trochę sałaty.'),
('stayBrainy4','sałata',1,'Rabbits eat ______.','lettuce','Rabbits eat lettuce.','Króliki jedzą sałatę.'),
('stayBrainy4','sałata',2,'______ is green.','Lettuce','Lettuce is green.','Sałata jest zielona.'),
('stayBrainy4','mięso',0,'Lions eat ______.','meat','Lions eat meat.','Lwy jedzą mięso.'),
('stayBrainy4','mięso',1,'I don''t eat ______.','meat','I don''t eat meat.','Nie jem mięsa.'),
('stayBrainy4','mięso',2,'There''s some ______ in the soup.','meat','There''s some meat in the soup.','W zupie jest trochę mięsa.'),
('stayBrainy4','grzyb',0,'There are some ______ on my pizza.','mushrooms','There are some mushrooms on my pizza.','Na mojej pizzy są grzyby.'),
('stayBrainy4','grzyb',1,'We look for ______ in the forest.','mushrooms','We look for mushrooms in the forest.','Szukamy grzybów w lesie.'),
('stayBrainy4','grzyb',2,'This ______ is big and brown.','mushroom','This mushroom is big and brown.','Ten grzyb jest duży i brązowy.'),
('stayBrainy4','ananas',0,'A ______ is sweet and yellow inside.','pineapple','A pineapple is sweet and yellow inside.','Ananas jest słodki i żółty w środku.'),
('stayBrainy4','ananas',1,'I like pizza with ham and ______.','pineapple','I like pizza with ham and pineapple.','Lubię pizzę z szynką i ananasem.'),
('stayBrainy4','ananas',2,'There''s a big ______ in the bowl.','pineapple','There''s a big pineapple in the bowl.','W misce jest duży ananas.'),
('stayBrainy4','ziemniak',0,'We have ______ for dinner.','potatoes','We have potatoes for dinner.','Na obiad mamy ziemniaki.'),
('stayBrainy4','ziemniak',1,'There''s a big ______ on my plate.','potato','There''s a big potato on my plate.','Na moim talerzu jest duży ziemniak.'),
('stayBrainy4','ziemniak',2,'Grandpa grows ______ in his garden.','potatoes','Grandpa grows potatoes in his garden.','Dziadek uprawia ziemniaki w ogrodzie.'),
('stayBrainy4','ryż',0,'I like chicken with ______.','rice','I like chicken with rice.','Lubię kurczaka z ryżem.'),
('stayBrainy4','ryż',1,'People in China eat a lot of ______.','rice','People in China eat a lot of rice.','Ludzie w Chinach jedzą dużo ryżu.'),
('stayBrainy4','ryż',2,'There''s some ______ in the bowl.','rice','There''s some rice in the bowl.','W misce jest trochę ryżu.'),
('stayBrainy4','trochę, kilka',0,'There is ______ cheese in the fridge.','some','There is some cheese in the fridge.','W lodówce jest trochę sera.'),
('stayBrainy4','trochę, kilka',1,'I''ve got ______ sweets.','some','I''ve got some sweets.','Mam kilka cukierków.'),
('stayBrainy4','trochę, kilka',2,'Can I have ______ water, please?','some','Can I have some water, please?','Czy mogę prosić o trochę wody?'),
('stayBrainy4','dużo',0,'There are ______ apples in the basket.','a lot of','There are a lot of apples in the basket.','W koszyku jest dużo jabłek.'),
('stayBrainy4','dużo',1,'I''ve got ______ books.','a lot of','I''ve got a lot of books.','Mam dużo książek.'),
('stayBrainy4','dużo',2,'Don''t eat ______ sweets.','a lot of','Don''t eat a lot of sweets.','Nie jedz dużo słodyczy.'),
('stayBrainy4','żadnych (-), jakieś (?)',0,'There aren''t ______ bananas in the trolley.','any','There aren''t any bananas in the trolley.','W wózku nie ma żadnych bananów.'),
('stayBrainy4','żadnych (-), jakieś (?)',1,'Are there ______ eggs in the fridge?','any','Are there any eggs in the fridge?','Czy w lodówce są jakieś jajka?'),
('stayBrainy4','żadnych (-), jakieś (?)',2,'I haven''t got ______ money.','any','I haven''t got any money.','Nie mam żadnych pieniędzy.'),
('stayBrainy4','rozmawiać przez komunikator w telefonie',0,'I ______ with my friends.','chat on my mobile','I chat on my mobile with my friends.','Rozmawiam z przyjaciółmi przez komunikator w telefonie.'),
('stayBrainy4','rozmawiać przez komunikator w telefonie',1,'She ______ every evening.','chats on her mobile','She chats on her mobile every evening.','Ona co wieczór rozmawia przez komunikator w telefonie.'),
('stayBrainy4','rozmawiać przez komunikator w telefonie',2,'Do you ______ after school?','chat on your mobile','Do you chat on your mobile after school?','Czy po szkole rozmawiasz przez komunikator w telefonie?'),
('stayBrainy4','ćwiczyć',0,'I ______ every morning.','do exercise','I do exercise every morning.','Ćwiczę każdego ranka.'),
('stayBrainy4','ćwiczyć',1,'My mum ______ in the park.','does exercise','My mum does exercise in the park.','Moja mama ćwiczy w parku.'),
('stayBrainy4','ćwiczyć',2,'It''s good to ______.','do exercise','It''s good to do exercise.','Dobrze jest ćwiczyć.'),
('stayBrainy4','pobierać muzykę z internetu',0,'I ______ on my smartphone.','download music','I download music on my smartphone.','Pobieram muzykę na smartfon.'),
('stayBrainy4','pobierać muzykę z internetu',1,'My brother ______ every day.','downloads music','My brother downloads music every day.','Mój brat codziennie pobiera muzykę.'),
('stayBrainy4','pobierać muzykę z internetu',2,'Do you ______ from the internet?','download music','Do you download music from the internet?','Czy pobierasz muzykę z internetu?'),
('stayBrainy4','wychodzić',0,'I ______ with my friends on Saturday.','go out','I go out with my friends on Saturday.','W sobotę wychodzę z przyjaciółmi.'),
('stayBrainy4','wychodzić',1,'My parents ______ in the evening.','go out','My parents go out in the evening.','Moi rodzice wychodzą wieczorem.'),
('stayBrainy4','wychodzić',2,'It''s raining. Don''t ______!','go out','It''s raining. Don''t go out!','Pada deszcz. Nie wychodź!'),
('stayBrainy4','chodzić na lekcje tańca',0,'I ______ on Tuesday.','go to my dance class','I go to my dance class on Tuesday.','We wtorek chodzę na lekcje tańca.'),
('stayBrainy4','chodzić na lekcje tańca',1,'She ______ after school.','goes to her dance class','She goes to her dance class after school.','Ona chodzi na lekcje tańca po szkole.'),
('stayBrainy4','chodzić na lekcje tańca',2,'I ______ with my best friend.','go to my dance class','I go to my dance class with my best friend.','Chodzę na lekcje tańca z moją najlepszą przyjaciółką.'),
('stayBrainy4','spędzać wolny czas ze znajomymi',0,'I ______ at the weekend.','hang out with my friends','I hang out with my friends at the weekend.','W weekend spędzam czas ze znajomymi.'),
('stayBrainy4','spędzać wolny czas ze znajomymi',1,'He ______ in the park.','hangs out with his friends','He hangs out with his friends in the park.','On spędza czas ze znajomymi w parku.'),
('stayBrainy4','spędzać wolny czas ze znajomymi',2,'I like to ______ after school.','hang out with my friends','I like to hang out with my friends after school.','Lubię spędzać czas ze znajomymi po szkole.'),
('stayBrainy4','grać w siatkówkę',0,'We ______ at school.','play volleyball','We play volleyball at school.','W szkole gramy w siatkówkę.'),
('stayBrainy4','grać w siatkówkę',1,'My sister ______ on Monday.','plays volleyball','My sister plays volleyball on Monday.','Moja siostra gra w siatkówkę w poniedziałki.'),
('stayBrainy4','grać w siatkówkę',2,'Can you ______?','play volleyball','Can you play volleyball?','Czy umiesz grać w siatkówkę?'),
('stayBrainy4','zamieszczać komentarze w internecie',0,'My brother ______ on the internet.','posts comments','My brother posts comments on the internet.','Mój brat zamieszcza komentarze w internecie.'),
('stayBrainy4','zamieszczać komentarze w internecie',1,'I don''t ______ online.','post comments','I don''t post comments online.','Nie zamieszczam komentarzy w internecie.'),
('stayBrainy4','zamieszczać komentarze w internecie',2,'People ______ under the video.','post comments','People post comments under the video.','Ludzie zamieszczają komentarze pod filmikiem.'),
('stayBrainy4','robić zdjęcia',0,'I ______ of animals.','take photos','I take photos of animals.','Robię zdjęcia zwierząt.'),
('stayBrainy4','robić zdjęcia',1,'My dad ______ on holiday.','takes photos','My dad takes photos on holiday.','Mój tata robi zdjęcia na wakacjach.'),
('stayBrainy4','robić zdjęcia',2,'Can I ______ here?','take photos','Can I take photos here?','Czy mogę tu robić zdjęcia?'),
('stayBrainy4','oglądać telewizję',0,'I ______ in the evening.','watch TV','I watch TV in the evening.','Oglądam telewizję wieczorem.'),
('stayBrainy4','oglądać telewizję',1,'My grandfather ______ every day.','watches TV','My grandfather watches TV every day.','Mój dziadek codziennie ogląda telewizję.'),
('stayBrainy4','oglądać telewizję',2,'Don''t ______ at night!','watch TV','Don''t watch TV at night!','Nie oglądaj telewizji w nocy!'),
('stayBrainy4','myć zęby',0,'I ______ every morning.','brush my teeth','I brush my teeth every morning.','Myję zęby każdego ranka.'),
('stayBrainy4','myć zęby',1,'Don''t forget to ______!','brush your teeth','Don''t forget to brush your teeth!','Nie zapomnij umyć zębów!'),
('stayBrainy4','myć zęby',2,'She ______ after breakfast.','brushes her teeth','She brushes her teeth after breakfast.','Ona myje zęby po śniadaniu.'),
('stayBrainy4','ubierać się',0,'I ______ after breakfast.','get dressed','I get dressed after breakfast.','Ubieram się po śniadaniu.'),
('stayBrainy4','ubierać się',1,'My little brother ______ very slowly.','gets dressed','My little brother gets dressed very slowly.','Mój młodszy brat ubiera się bardzo powoli.'),
('stayBrainy4','ubierać się',2,'______ quickly! We''re late.','Get dressed','Get dressed quickly! We''re late.','Ubierz się szybko! Jesteśmy spóźnieni.'),
('stayBrainy4','wstawać',0,'I ______ at seven o''clock.','get up','I get up at seven o''clock.','Wstaję o siódmej.'),
('stayBrainy4','wstawać',1,'My dad ______ very early.','gets up','My dad gets up very early.','Mój tata wstaje bardzo wcześnie.'),
('stayBrainy4','wstawać',2,'I don''t ______ early on Sunday.','get up','I don''t get up early on Sunday.','W niedzielę nie wstaję wcześnie.'),
('stayBrainy4','iść do domu',0,'I ______ at three o''clock.','go home','I go home at three o''clock.','Idę do domu o trzeciej.'),
('stayBrainy4','iść do domu',1,'It''s late. Let''s ______.','go home','It''s late. Let''s go home.','Jest późno. Chodźmy do domu.'),
('stayBrainy4','iść do domu',2,'After school, Tom ______ by bus.','goes home','After school, Tom goes home by bus.','Po szkole Tom jedzie do domu autobusem.'),
('stayBrainy4','iść spać',0,'I ______ at half past eight.','go to bed','I go to bed at half past eight.','Chodzę spać o wpół do dziewiątej.'),
('stayBrainy4','iść spać',1,'My little sister ______ early.','goes to bed','My little sister goes to bed early.','Moja młodsza siostra wcześnie chodzi spać.'),
('stayBrainy4','iść spać',2,'It''s late. ______ now!','Go to bed','It''s late. Go to bed now!','Jest późno. Idź teraz spać!'),
('stayBrainy4','iść do szkoły',0,'I ______ from Monday to Friday.','go to school','I go to school from Monday to Friday.','Chodzę do szkoły od poniedziałku do piątku.'),
('stayBrainy4','iść do szkoły',1,'My brother ______ by bike.','goes to school','My brother goes to school by bike.','Mój brat jeździ do szkoły rowerem.'),
('stayBrainy4','iść do szkoły',2,'We don''t ______ on Saturday.','go to school','We don''t go to school on Saturday.','W sobotę nie chodzimy do szkoły.'),
('stayBrainy4','brać prysznic',0,'I ______ every evening.','have a shower','I have a shower every evening.','Biorę prysznic każdego wieczoru.'),
('stayBrainy4','brać prysznic',1,'Dad ______ after football.','has a shower','Dad has a shower after football.','Tata bierze prysznic po piłce nożnej.'),
('stayBrainy4','brać prysznic',2,'I want to ______ now.','have a shower','I want to have a shower now.','Chcę teraz wziąć prysznic.'),
('stayBrainy4','jeść śniadanie',0,'I ______ at seven o''clock.','have breakfast','I have breakfast at seven o''clock.','Jem śniadanie o siódmej.'),
('stayBrainy4','jeść śniadanie',1,'We ______ in the kitchen.','have breakfast','We have breakfast in the kitchen.','Jemy śniadanie w kuchni.'),
('stayBrainy4','jeść śniadanie',2,'She ______ before school.','has breakfast','She has breakfast before school.','Ona je śniadanie przed szkołą.'),
('stayBrainy4','jeść lunch',0,'We ______ at school.','have lunch','We have lunch at school.','Jemy lunch w szkole.'),
('stayBrainy4','jeść lunch',1,'My dad ______ at work.','has lunch','My dad has lunch at work.','Mój tata je lunch w pracy.'),
('stayBrainy4','jeść lunch',2,'Let''s ______ in the park.','have lunch','Let''s have lunch in the park.','Zjedzmy lunch w parku.'),
('stayBrainy4','jeść obiad',0,'We ______ at six o''clock.','have dinner','We have dinner at six o''clock.','Jemy obiad o szóstej.'),
('stayBrainy4','jeść obiad',1,'My family ______ together.','has dinner','My family has dinner together.','Moja rodzina je obiad razem.'),
('stayBrainy4','jeść obiad',2,'I ______ with my grandma on Sunday.','have dinner','I have dinner with my grandma on Sunday.','W niedzielę jem obiad z babcią.'),
('stayBrainy4','rano',0,'I get up at seven ______.','in the morning','I get up at seven in the morning.','Wstaję o siódmej rano.'),
('stayBrainy4','rano',1,'I go to school ______.','in the morning','I go to school in the morning.','Rano chodzę do szkoły.'),
('stayBrainy4','rano',2,'I drink milk ______.','in the morning','I drink milk in the morning.','Rano piję mleko.'),
('stayBrainy4','po południu',0,'I do my homework ______.','in the afternoon','I do my homework in the afternoon.','Po południu odrabiam pracę domową.'),
('stayBrainy4','po południu',1,'We play football ______.','in the afternoon','We play football in the afternoon.','Po południu gramy w piłkę nożną.'),
('stayBrainy4','po południu',2,'My mum comes home ______.','in the afternoon','My mum comes home in the afternoon.','Moja mama wraca do domu po południu.'),
('stayBrainy4','wieczorem',0,'I watch TV ______.','in the evening','I watch TV in the evening.','Wieczorem oglądam telewizję.'),
('stayBrainy4','wieczorem',1,'I read books ______.','in the evening','I read books in the evening.','Wieczorem czytam książki.'),
('stayBrainy4','wieczorem',2,'Dad cooks ______.','in the evening','Dad cooks in the evening.','Tata gotuje wieczorem.'),
('stayBrainy4','w nocy',0,'Owls fly ______.','at night','Owls fly at night.','Sowy latają w nocy.'),
('stayBrainy4','w nocy',1,'I sleep ______.','at night','I sleep at night.','W nocy śpię.'),
('stayBrainy4','w nocy',2,'It''s dark ______.','at night','It''s dark at night.','W nocy jest ciemno.'),
('stayBrainy4','kupić bilety',0,'We ______ at the cinema.','buy tickets','We buy tickets at the cinema.','Kupujemy bilety w kinie.'),
('stayBrainy4','kupić bilety',1,'Dad ______ for the train.','buys tickets','Dad buys tickets for the train.','Tata kupuje bilety na pociąg.'),
('stayBrainy4','kupić bilety',2,'Where can I ______?','buy tickets','Where can I buy tickets?','Gdzie mogę kupić bilety?'),
('stayBrainy4','wskoczyć do jeziora z krokodylami',0,'Do you want to ______? No way!','dive into a crocodile lake','Do you want to dive into a crocodile lake? No way!','Chcesz wskoczyć do jeziora z krokodylami? Nie ma mowy!'),
('stayBrainy4','wskoczyć do jeziora z krokodylami',1,'In this game, you can ______.','dive into a crocodile lake','In this game, you can dive into a crocodile lake.','W tej grze możesz wskoczyć do jeziora z krokodylami.'),
('stayBrainy4','wskoczyć do jeziora z krokodylami',2,'I don''t want to ______!','dive into a crocodile lake','I don''t want to dive into a crocodile lake!','Nie chcę wskakiwać do jeziora z krokodylami!'),
('stayBrainy4','walczyć z dinozaurem',0,'In the theme park, you can ______.','fight a dinosaur','In the theme park, you can fight a dinosaur.','W parku rozrywki możesz walczyć z dinozaurem.'),
('stayBrainy4','walczyć z dinozaurem',1,'Bob wants to ______.','fight a dinosaur','Bob wants to fight a dinosaur.','Bob chce walczyć z dinozaurem.'),
('stayBrainy4','walczyć z dinozaurem',2,'Are you brave? Can you ______?','fight a dinosaur','Are you brave? Can you fight a dinosaur?','Jesteś odważny? Potrafisz walczyć z dinozaurem?'),
('stayBrainy4','znaleźć skarb',0,'Use the map to ______.','find the treasure','Use the map to find the treasure.','Użyj mapy, żeby znaleźć skarb.'),
('stayBrainy4','znaleźć skarb',1,'The pirates want to ______ on the island.','find the treasure','The pirates want to find the treasure on the island.','Piraci chcą znaleźć skarb na wyspie.'),
('stayBrainy4','znaleźć skarb',2,'Can you help me ______?','find the treasure','Can you help me find the treasure?','Możesz mi pomóc znaleźć skarb?'),
('stayBrainy4','uczyć się sztuczek magicznych',0,'I want to ______.','learn magic tricks','I want to learn magic tricks.','Chcę nauczyć się sztuczek magicznych.'),
('stayBrainy4','uczyć się sztuczek magicznych',1,'My brother ______ from videos.','learns magic tricks','My brother learns magic tricks from videos.','Mój brat uczy się sztuczek magicznych z filmików.'),
('stayBrainy4','uczyć się sztuczek magicznych',2,'At the summer camp, you can ______.','learn magic tricks','At the summer camp, you can learn magic tricks.','Na obozie letnim możesz uczyć się sztuczek magicznych.'),
('stayBrainy4','szukać Brainyballs',0,'Let''s ______ in the park!','look for Brainyballs','Let''s look for Brainyballs in the park!','Poszukajmy Brainyballs w parku!'),
('stayBrainy4','szukać Brainyballs',1,'The children ______ in the castle.','look for Brainyballs','The children look for Brainyballs in the castle.','Dzieci szukają Brainyballs w zamku.'),
('stayBrainy4','szukać Brainyballs',2,'We ______ every day.','look for Brainyballs','We look for Brainyballs every day.','Codziennie szukamy Brainyballs.'),
('stayBrainy4','odwiedzić zamek strachów',0,'Let''s ______ on Saturday!','visit the spooky castle','Let''s visit the spooky castle on Saturday!','Odwiedźmy zamek strachów w sobotę!'),
('stayBrainy4','odwiedzić zamek strachów',1,'Do you want to ______?','visit the spooky castle','Do you want to visit the spooky castle?','Chcesz odwiedzić zamek strachów?'),
('stayBrainy4','odwiedzić zamek strachów',2,'We ______ with our class.','visit the spooky castle','We visit the spooky castle with our class.','Odwiedzamy zamek strachów z naszą klasą.'),
('stayBrainy4','wygrać nagrody',0,'You can ______ in this game.','win prizes','You can win prizes in this game.','W tej grze możesz wygrać nagrody.'),
('stayBrainy4','wygrać nagrody',1,'Tom always ______ at the funfair.','wins prizes','Tom always wins prizes at the funfair.','Tom zawsze wygrywa nagrody w wesołym miasteczku.'),
('stayBrainy4','wygrać nagrody',2,'Answer the questions and ______!','win prizes','Answer the questions and win prizes!','Odpowiedz na pytania i wygraj nagrody!'),
('stayBrainy4','przystanek autobusowy',0,'I wait for the bus at the ______.','bus stop','I wait for the bus at the bus stop.','Czekam na autobus na przystanku autobusowym.'),
('stayBrainy4','przystanek autobusowy',1,'The ______ is next to the school.','bus stop','The bus stop is next to the school.','Przystanek autobusowy jest obok szkoły.'),
('stayBrainy4','przystanek autobusowy',2,'Where''s the ______?','bus stop','Where''s the bus stop?','Gdzie jest przystanek autobusowy?'),
('stayBrainy4','kawiarnia',0,'Let''s have ice cream at the ______.','cafe','Let''s have ice cream at the cafe.','Zjedzmy lody w kawiarni.'),
('stayBrainy4','kawiarnia',1,'My mum meets her friends in a ______.','cafe','My mum meets her friends in a cafe.','Moja mama spotyka się z koleżankami w kawiarni.'),
('stayBrainy4','kawiarnia',2,'The ______ is in the main square.','cafe','The cafe is in the main square.','Kawiarnia jest na rynku.'),
('stayBrainy4','parking',0,'Dad leaves the car in the ______.','car park','Dad leaves the car in the car park.','Tata zostawia samochód na parkingu.'),
('stayBrainy4','parking',1,'The ______ is next to the supermarket.','car park','The car park is next to the supermarket.','Parking jest obok supermarketu.'),
('stayBrainy4','parking',2,'There are a lot of cars in the ______.','car park','There are a lot of cars in the car park.','Na parkingu jest dużo samochodów.'),
('stayBrainy4','kino',0,'Let''s go to the ______ on Friday.','cinema','Let''s go to the cinema on Friday.','Chodźmy do kina w piątek.'),
('stayBrainy4','kino',1,'We watch films at the ______.','cinema','We watch films at the cinema.','Oglądamy filmy w kinie.'),
('stayBrainy4','kino',2,'The ______ is near the shopping centre.','cinema','The cinema is near the shopping centre.','Kino jest blisko centrum handlowego.'),
('stayBrainy4','rynek',0,'There''s a big fountain in the ______.','main square','There''s a big fountain in the main square.','Na rynku jest duża fontanna.'),
('stayBrainy4','rynek',1,'Let''s meet in the ______.','main square','Let''s meet in the main square.','Spotkajmy się na rynku.'),
('stayBrainy4','rynek',2,'The museum is in the ______.','main square','The museum is in the main square.','Muzeum jest przy rynku.'),
('stayBrainy4','muzeum',0,'There are dinosaurs in the ______.','museum','There are dinosaurs in the museum.','W muzeum są dinozaury.'),
('stayBrainy4','muzeum',1,'We visit the ______ with our class.','museum','We visit the museum with our class.','Zwiedzamy muzeum z naszą klasą.'),
('stayBrainy4','muzeum',2,'The ______ is open on Sunday.','museum','The museum is open on Sunday.','Muzeum jest otwarte w niedzielę.'),
('stayBrainy4','szkoła',0,'My ______ is big and new.','school','My school is big and new.','Moja szkoła jest duża i nowa.'),
('stayBrainy4','szkoła',1,'The ______ is next to the park.','school','The school is next to the park.','Szkoła jest obok parku.'),
('stayBrainy4','szkoła',2,'There are twenty classrooms in our ______.','school','There are twenty classrooms in our school.','W naszej szkole jest dwadzieścia sal lekcyjnych.'),
('stayBrainy4','centrum handlowe',0,'We buy clothes at the ______.','shopping centre','We buy clothes at the shopping centre.','Kupujemy ubrania w centrum handlowym.'),
('stayBrainy4','centrum handlowe',1,'There''s a cinema in the ______.','shopping centre','There''s a cinema in the shopping centre.','W centrum handlowym jest kino.'),
('stayBrainy4','centrum handlowe',2,'Excuse me, where''s the ______?','shopping centre','Excuse me, where''s the shopping centre?','Przepraszam, gdzie jest centrum handlowe?'),
('stayBrainy4','supermarket',0,'Mum buys food at the ______.','supermarket','Mum buys food at the supermarket.','Mama kupuje jedzenie w supermarkecie.'),
('stayBrainy4','supermarket',1,'The ______ is open every day.','supermarket','The supermarket is open every day.','Supermarket jest otwarty codziennie.'),
('stayBrainy4','supermarket',2,'There are a lot of trolleys at the ______.','supermarket','There are a lot of trolleys at the supermarket.','Przy supermarkecie jest dużo wózków.'),
('stayBrainy4','stacja kolejowa',0,'We wait for the train at the ______.','train station','We wait for the train at the train station.','Czekamy na pociąg na stacji kolejowej.'),
('stayBrainy4','stacja kolejowa',1,'The ______ is in the town centre.','train station','The train station is in the town centre.','Stacja kolejowa jest w centrum miasta.'),
('stayBrainy4','stacja kolejowa',2,'Turn left to get to the ______.','train station','Turn left to get to the train station.','Skręć w lewo, żeby dojść do stacji kolejowej.');

SELECT 'OK — stayBrainy4: 218 słów, 654 zdań kontekstowych' AS status;
