-- ═══════════════════════════════════════════════════════════
-- SEED fiszek kontekstowych — bugsteam3 (słowa i krótkie wyrażenia)
-- Bez dłuższych zwrotów/wypowiedzi (pełne zdania, dialogi), tabel gramatycznych i jednorazowych dat.
-- Wymaga migracji #59 (word-contexts-schema.sql). Idempotentny (DELETE+INSERT per słowo).
-- ═══════════════════════════════════════════════════════════

DELETE FROM public.word_contexts WHERE book_id='bugsteam3' AND word_pl IN (
  'kangur',
  'nosorożec',
  'gepard',
  'tygrys',
  'wieloryb',
  'goryl',
  'rekin',
  'jaszczurka',
  'owoce',
  'warzywa',
  'owady',
  'mięso',
  'ryby',
  'dżungla',
  'pustynia',
  'morze',
  'sawanna, obszary trawiaste',
  'rzeka',
  'wąsy, wibrysy',
  'język',
  'buzia, pysk',
  'zęby',
  'ciało',
  'skrzydła',
  'ogon',
  'pazury',
  'krótki, niski',
  'długi',
  'ostry',
  'silny',
  'cienki',
  'gruby',
  'wstawać',
  'ubierać się',
  'jeść śniadanie',
  'myć zęby',
  'iść do szkoły',
  'jeść obiad',
  'brać prysznic',
  'jeść kolację',
  'iść spać',
  'jeden',
  'dwa',
  'trzy',
  'cztery',
  'pięć',
  'sześć',
  'siedem',
  'osiem',
  'dziewięć',
  'dziesięć',
  'dwanaście',
  'nauczyciel',
  'strażak',
  'lekarz',
  'sprzedawca',
  'policjant',
  'weterynarz',
  'sklep z zabawkami',
  'piekarnia',
  'sklep zoologiczny',
  'księgarnia',
  'sklep ze słodyczami',
  'sklep obuwniczy',
  'sklep odzieżowy',
  'targ, rynek',
  'szkoła',
  'hotel',
  'szpital',
  'poczta',
  'restauracja',
  'dworzec kolejowy',
  'robić zdjęcia',
  'puszczać latawiec',
  'urządzać piknik',
  'łowić ryby',
  'zbierać muszle',
  'budować zamek z piasku',
  'nurkować z rurką',
  'rozpalać ognisko',
  'chodzić po górach, wędrować',
  'plaża',
  'góry',
  'las',
  'jezioro',
  'miasto',
  'wieś'
);

INSERT INTO public.word_contexts (book_id, word_pl, ord, sentence_gap, answer, full_sentence, translation_pl) VALUES
('bugsteam3','kangur',0,'The ______ can jump very high.','kangaroo','The kangaroo can jump very high.','Kangur potrafi skakać bardzo wysoko.'),
('bugsteam3','kangur',1,'A ______ lives in Australia.','kangaroo','A kangaroo lives in Australia.','Kangur żyje w Australii.'),
('bugsteam3','kangur',2,'The baby ______ is in its mum''s pocket.','kangaroo','The baby kangaroo is in its mum''s pocket.','Mały kangur jest w kieszeni swojej mamy.'),
('bugsteam3','nosorożec',0,'The ______ has got a big horn.','rhino','The rhino has got a big horn.','Nosorożec ma duży róg.'),
('bugsteam3','nosorożec',1,'A ______ is very big and grey.','rhino','A rhino is very big and grey.','Nosorożec jest bardzo duży i szary.'),
('bugsteam3','nosorożec',2,'The ______ is eating grass.','rhino','The rhino is eating grass.','Nosorożec je trawę.'),
('bugsteam3','gepard',0,'The ______ can run very fast.','cheetah','The cheetah can run very fast.','Gepard potrafi bardzo szybko biegać.'),
('bugsteam3','gepard',1,'A ______ has got black spots.','cheetah','A cheetah has got black spots.','Gepard ma czarne cętki.'),
('bugsteam3','gepard',2,'The ______ is sleeping under a tree.','cheetah','The cheetah is sleeping under a tree.','Gepard śpi pod drzewem.'),
('bugsteam3','tygrys',0,'The ______ is orange and black.','tiger','The tiger is orange and black.','Tygrys jest pomarańczowo-czarny.'),
('bugsteam3','tygrys',1,'There''s a ______ in the jungle.','tiger','There''s a tiger in the jungle.','W dżungli jest tygrys.'),
('bugsteam3','tygrys',2,'The ______ has got big teeth.','tiger','The tiger has got big teeth.','Tygrys ma duże zęby.'),
('bugsteam3','wieloryb',0,'The ______ lives in the sea.','whale','The whale lives in the sea.','Wieloryb żyje w morzu.'),
('bugsteam3','wieloryb',1,'A ______ is a very big animal.','whale','A whale is a very big animal.','Wieloryb to bardzo duże zwierzę.'),
('bugsteam3','wieloryb',2,'I can see a ______ in the water!','whale','I can see a whale in the water!','Widzę wieloryba w wodzie!'),
('bugsteam3','goryl',0,'The ______ is eating a banana.','gorilla','The gorilla is eating a banana.','Goryl je banana.'),
('bugsteam3','goryl',1,'A ______ is big and strong.','gorilla','A gorilla is big and strong.','Goryl jest duży i silny.'),
('bugsteam3','goryl',2,'The ______ lives in the jungle.','gorilla','The gorilla lives in the jungle.','Goryl żyje w dżungli.'),
('bugsteam3','rekin',0,'The ______ has got sharp teeth.','shark','The shark has got sharp teeth.','Rekin ma ostre zęby.'),
('bugsteam3','rekin',1,'A ______ is swimming in the sea.','shark','A shark is swimming in the sea.','Rekin pływa w morzu.'),
('bugsteam3','rekin',2,'My brother is scared of ______.','sharks','My brother is scared of sharks.','Mój brat boi się rekinów.'),
('bugsteam3','jaszczurka',0,'The ______ is sitting on a rock.','lizard','The lizard is sitting on a rock.','Jaszczurka siedzi na kamieniu.'),
('bugsteam3','jaszczurka',1,'A ______ has got a long tail.','lizard','A lizard has got a long tail.','Jaszczurka ma długi ogon.'),
('bugsteam3','jaszczurka',2,'This green ______ lives in the desert.','lizard','This green lizard lives in the desert.','Ta zielona jaszczurka żyje na pustyni.'),
('bugsteam3','owoce',0,'I eat ______ every day.','fruit','I eat fruit every day.','Codziennie jem owoce.'),
('bugsteam3','owoce',1,'Monkeys like ______.','fruit','Monkeys like fruit.','Małpy lubią owoce.'),
('bugsteam3','owoce',2,'Apples and bananas are ______.','fruit','Apples and bananas are fruit.','Jabłka i banany to owoce.'),
('bugsteam3','warzywa',0,'Carrots are ______.','vegetables','Carrots are vegetables.','Marchewki to warzywa.'),
('bugsteam3','warzywa',1,'My mum buys ______ at the market.','vegetables','My mum buys vegetables at the market.','Moja mama kupuje warzywa na targu.'),
('bugsteam3','warzywa',2,'Rabbits eat ______.','vegetables','Rabbits eat vegetables.','Króliki jedzą warzywa.'),
('bugsteam3','owady',0,'Lizards eat ______.','insects','Lizards eat insects.','Jaszczurki jedzą owady.'),
('bugsteam3','owady',1,'Bees and ants are ______.','insects','Bees and ants are insects.','Pszczoły i mrówki to owady.'),
('bugsteam3','owady',2,'There are a lot of ______ in the garden.','insects','There are a lot of insects in the garden.','W ogrodzie jest dużo owadów.'),
('bugsteam3','mięso',0,'Tigers eat ______.','meat','Tigers eat meat.','Tygrysy jedzą mięso.'),
('bugsteam3','mięso',1,'I don''t eat ______.','meat','I don''t eat meat.','Nie jem mięsa.'),
('bugsteam3','mięso',2,'Dad is cooking ______ for dinner.','meat','Dad is cooking meat for dinner.','Tata gotuje mięso na kolację.'),
('bugsteam3','ryby',0,'Cats like ______.','fish','Cats like fish.','Koty lubią ryby.'),
('bugsteam3','ryby',1,'There are a lot of ______ in the river.','fish','There are a lot of fish in the river.','W rzece jest dużo ryb.'),
('bugsteam3','ryby',2,'Penguins eat ______.','fish','Penguins eat fish.','Pingwiny jedzą ryby.'),
('bugsteam3','dżungla',0,'Gorillas live in the ______.','jungle','Gorillas live in the jungle.','Goryle żyją w dżungli.'),
('bugsteam3','dżungla',1,'The ______ is green and hot.','jungle','The jungle is green and hot.','Dżungla jest zielona i gorąca.'),
('bugsteam3','dżungla',2,'There are a lot of trees in the ______.','jungle','There are a lot of trees in the jungle.','W dżungli jest dużo drzew.'),
('bugsteam3','pustynia',0,'Camels live in the ______.','desert','Camels live in the desert.','Wielbłądy żyją na pustyni.'),
('bugsteam3','pustynia',1,'The ______ is very hot and dry.','desert','The desert is very hot and dry.','Pustynia jest bardzo gorąca i sucha.'),
('bugsteam3','pustynia',2,'There isn''t much water in the ______.','desert','There isn''t much water in the desert.','Na pustyni nie ma dużo wody.'),
('bugsteam3','morze',0,'Whales live in the ______.','sea','Whales live in the sea.','Wieloryby żyją w morzu.'),
('bugsteam3','morze',1,'We swim in the ______ in summer.','sea','We swim in the sea in summer.','Latem pływamy w morzu.'),
('bugsteam3','morze',2,'The ______ is blue today.','sea','The sea is blue today.','Morze jest dziś niebieskie.'),
('bugsteam3','sawanna, obszary trawiaste',0,'Rhinos live in the ______.','grasslands','Rhinos live in the grasslands.','Nosorożce żyją na sawannie.'),
('bugsteam3','sawanna, obszary trawiaste',1,'Zebras eat grass in the ______.','grasslands','Zebras eat grass in the grasslands.','Zebry jedzą trawę na sawannie.'),
('bugsteam3','sawanna, obszary trawiaste',2,'Cheetahs run fast in the ______.','grasslands','Cheetahs run fast in the grasslands.','Gepardy szybko biegają po sawannie.'),
('bugsteam3','rzeka',0,'Crocodiles live in the ______.','river','Crocodiles live in the river.','Krokodyle żyją w rzece.'),
('bugsteam3','rzeka',1,'There are fish in the ______.','river','There are fish in the river.','W rzece są ryby.'),
('bugsteam3','rzeka',2,'The ______ is long and wide.','river','The river is long and wide.','Rzeka jest długa i szeroka.'),
('bugsteam3','wąsy, wibrysy',0,'My cat has got long white ______.','whiskers','My cat has got long white whiskers.','Mój kot ma długie białe wąsy.'),
('bugsteam3','wąsy, wibrysy',1,'A mouse has got short ______.','whiskers','A mouse has got short whiskers.','Mysz ma krótkie wąsy.'),
('bugsteam3','wąsy, wibrysy',2,'The rabbit has got grey ______.','whiskers','The rabbit has got grey whiskers.','Królik ma szare wąsy.'),
('bugsteam3','język',0,'The dog has got a pink ______.','tongue','The dog has got a pink tongue.','Pies ma różowy język.'),
('bugsteam3','język',1,'A lizard catches insects with its ______.','tongue','A lizard catches insects with its tongue.','Jaszczurka łapie owady językiem.'),
('bugsteam3','język',2,'Show me your ______, please.','tongue','Show me your tongue, please.','Pokaż mi, proszę, język.'),
('bugsteam3','buzia, pysk',0,'Open your ______, please.','mouth','Open your mouth, please.','Otwórz, proszę, buzię.'),
('bugsteam3','buzia, pysk',1,'The crocodile has got a big ______.','mouth','The crocodile has got a big mouth.','Krokodyl ma duży pysk.'),
('bugsteam3','buzia, pysk',2,'Don''t talk with food in your ______.','mouth','Don''t talk with food in your mouth.','Nie mów, kiedy masz jedzenie w buzi.'),
('bugsteam3','zęby',0,'Sharks have got sharp ______.','teeth','Sharks have got sharp teeth.','Rekiny mają ostre zęby.'),
('bugsteam3','zęby',1,'I clean my ______ every morning.','teeth','I clean my teeth every morning.','Codziennie rano czyszczę zęby.'),
('bugsteam3','zęby',2,'The baby hasn''t got any ______.','teeth','The baby hasn''t got any teeth.','Niemowlę nie ma zębów.'),
('bugsteam3','ciało',0,'A snake has got a long ______.','body','A snake has got a long body.','Wąż ma długie ciało.'),
('bugsteam3','ciało',1,'The bee''s ______ is yellow and black.','body','The bee''s body is yellow and black.','Ciało pszczoły jest żółto-czarne.'),
('bugsteam3','ciało',2,'Sport is good for your ______.','body','Sport is good for your body.','Sport jest dobry dla ciała.'),
('bugsteam3','skrzydła',0,'Birds have got ______.','wings','Birds have got wings.','Ptaki mają skrzydła.'),
('bugsteam3','skrzydła',1,'The butterfly has got beautiful ______.','wings','The butterfly has got beautiful wings.','Motyl ma piękne skrzydła.'),
('bugsteam3','skrzydła',2,'The bird is opening its ______.','wings','The bird is opening its wings.','Ptak rozkłada skrzydła.'),
('bugsteam3','ogon',0,'My dog has got a long ______.','tail','My dog has got a long tail.','Mój pies ma długi ogon.'),
('bugsteam3','ogon',1,'The monkey is hanging by its ______.','tail','The monkey is hanging by its tail.','Małpa wisi na ogonie.'),
('bugsteam3','ogon',2,'A rabbit has got a short ______.','tail','A rabbit has got a short tail.','Królik ma krótki ogon.'),
('bugsteam3','pazury',0,'Cats have got sharp ______.','claws','Cats have got sharp claws.','Koty mają ostre pazury.'),
('bugsteam3','pazury',1,'The bear has got long ______.','claws','The bear has got long claws.','Niedźwiedź ma długie pazury.'),
('bugsteam3','pazury',2,'The bird is holding a fish in its ______.','claws','The bird is holding a fish in its claws.','Ptak trzyma rybę w pazurach.'),
('bugsteam3','krótki, niski',0,'My hair is ______.','short','My hair is short.','Moje włosy są krótkie.'),
('bugsteam3','krótki, niski',1,'My little brother is ______.','short','My little brother is short.','Mój młodszy brat jest niski.'),
('bugsteam3','krótki, niski',2,'This dog has got ______ legs.','short','This dog has got short legs.','Ten pies ma krótkie nogi.'),
('bugsteam3','długi',0,'A giraffe has got a ______ neck.','long','A giraffe has got a long neck.','Żyrafa ma długą szyję.'),
('bugsteam3','długi',1,'My sister has got ______ hair.','long','My sister has got long hair.','Moja siostra ma długie włosy.'),
('bugsteam3','długi',2,'This snake is very ______.','long','This snake is very long.','Ten wąż jest bardzo długi.'),
('bugsteam3','ostry',0,'Be careful! The knife is ______.','sharp','Be careful! The knife is sharp.','Uważaj! Nóż jest ostry.'),
('bugsteam3','ostry',1,'Tigers have got ______ claws.','sharp','Tigers have got sharp claws.','Tygrysy mają ostre pazury.'),
('bugsteam3','ostry',2,'My pencil is ______ now.','sharp','My pencil is sharp now.','Mój ołówek jest teraz ostry.'),
('bugsteam3','silny',0,'Gorillas are very ______.','strong','Gorillas are very strong.','Goryle są bardzo silne.'),
('bugsteam3','silny',1,'My dad is big and ______.','strong','My dad is big and strong.','Mój tata jest duży i silny.'),
('bugsteam3','silny',2,'An elephant is a ______ animal.','strong','An elephant is a strong animal.','Słoń to silne zwierzę.'),
('bugsteam3','cienki',0,'This book is ______.','thin','This book is thin.','Ta książka jest cienka.'),
('bugsteam3','cienki',1,'A snake has got a long, ______ body.','thin','A snake has got a long, thin body.','Wąż ma długie, cienkie ciało.'),
('bugsteam3','cienki',2,'The spider has got ______ legs.','thin','The spider has got thin legs.','Pająk ma cienkie nogi.'),
('bugsteam3','gruby',0,'This dictionary is very ______.','thick','This dictionary is very thick.','Ten słownik jest bardzo gruby.'),
('bugsteam3','gruby',1,'The elephant has got ______ legs.','thick','The elephant has got thick legs.','Słoń ma grube nogi.'),
('bugsteam3','gruby',2,'I''m wearing a ______ jumper.','thick','I''m wearing a thick jumper.','Mam na sobie gruby sweter.'),
('bugsteam3','wstawać',0,'I ______ at seven o''clock.','get up','I get up at seven o''clock.','Wstaję o siódmej.'),
('bugsteam3','wstawać',1,'My dad ______ early every day.','gets up','My dad gets up early every day.','Mój tata codziennie wcześnie wstaje.'),
('bugsteam3','wstawać',2,'Time to ______! It''s eight o''clock.','get up','Time to get up! It''s eight o''clock.','Czas wstawać! Jest ósma.'),
('bugsteam3','ubierać się',0,'I ______ after breakfast.','get dressed','I get dressed after breakfast.','Ubieram się po śniadaniu.'),
('bugsteam3','ubierać się',1,'She ______ in her bedroom.','gets dressed','She gets dressed in her bedroom.','Ona ubiera się w swojej sypialni.'),
('bugsteam3','ubierać się',2,'Please ______ quickly. We''re late!','get dressed','Please get dressed quickly. We''re late!','Ubierz się szybko, proszę. Jesteśmy spóźnieni!'),
('bugsteam3','jeść śniadanie',0,'I ______ at half past seven.','have breakfast','I have breakfast at half past seven.','Jem śniadanie o wpół do ósmej.'),
('bugsteam3','jeść śniadanie',1,'We ______ in the kitchen.','have breakfast','We have breakfast in the kitchen.','Jemy śniadanie w kuchni.'),
('bugsteam3','jeść śniadanie',2,'Tom ______ with his mum.','has breakfast','Tom has breakfast with his mum.','Tom je śniadanie z mamą.'),
('bugsteam3','myć zęby',0,'I ______ every morning.','brush my teeth','I brush my teeth every morning.','Codziennie rano myję zęby.'),
('bugsteam3','myć zęby',1,'I ______ before bed.','brush my teeth','I brush my teeth before bed.','Myję zęby przed snem.'),
('bugsteam3','myć zęby',2,'I ______ in the bathroom.','brush my teeth','I brush my teeth in the bathroom.','Myję zęby w łazience.'),
('bugsteam3','iść do szkoły',0,'I ______ at eight o''clock.','go to school','I go to school at eight o''clock.','Idę do szkoły o ósmej.'),
('bugsteam3','iść do szkoły',1,'We ______ by bus.','go to school','We go to school by bus.','Jeździmy do szkoły autobusem.'),
('bugsteam3','iść do szkoły',2,'I don''t ______ on Sunday.','go to school','I don''t go to school on Sunday.','W niedzielę nie chodzę do szkoły.'),
('bugsteam3','jeść obiad',0,'I ______ at school.','have lunch','I have lunch at school.','Jem obiad w szkole.'),
('bugsteam3','jeść obiad',1,'We ______ at one o''clock.','have lunch','We have lunch at one o''clock.','Jemy obiad o pierwszej.'),
('bugsteam3','jeść obiad',2,'Let''s ______ in the garden.','have lunch','Let''s have lunch in the garden.','Zjedzmy obiad w ogrodzie.'),
('bugsteam3','brać prysznic',0,'I ______ in the evening.','have a shower','I have a shower in the evening.','Wieczorem biorę prysznic.'),
('bugsteam3','brać prysznic',1,'Dad ______ every morning.','has a shower','Dad has a shower every morning.','Tata codziennie rano bierze prysznic.'),
('bugsteam3','brać prysznic',2,'I ______ after football.','have a shower','I have a shower after football.','Po piłce nożnej biorę prysznic.'),
('bugsteam3','jeść kolację',0,'We ______ at six o''clock.','have dinner','We have dinner at six o''clock.','Jemy kolację o szóstej.'),
('bugsteam3','jeść kolację',1,'I ______ with my family.','have dinner','I have dinner with my family.','Jem kolację z rodziną.'),
('bugsteam3','jeść kolację',2,'Grandma ______ in the kitchen.','has dinner','Grandma has dinner in the kitchen.','Babcia je kolację w kuchni.'),
('bugsteam3','iść spać',0,'I ______ at nine o''clock.','go to bed','I go to bed at nine o''clock.','Chodzę spać o dziewiątej.'),
('bugsteam3','iść spać',1,'My little sister ______ at eight.','goes to bed','My little sister goes to bed at eight.','Moja młodsza siostra chodzi spać o ósmej.'),
('bugsteam3','iść spać',2,'It''s late. ______ now, please!','Go to bed','It''s late. Go to bed now, please!','Jest późno. Idź teraz spać, proszę!'),
('bugsteam3','jeden',0,'I''ve got ______ brother.','one','I''ve got one brother.','Mam jednego brata.'),
('bugsteam3','jeden',1,'There''s ______ apple on the table.','one','There''s one apple on the table.','Na stole jest jedno jabłko.'),
('bugsteam3','jeden',2,'______ plus one is two.','One','One plus one is two.','Jeden plus jeden to dwa.'),
('bugsteam3','dwa',0,'I''ve got ______ hands.','two','I''ve got two hands.','Mam dwie ręce.'),
('bugsteam3','dwa',1,'A bird has got ______ wings.','two','A bird has got two wings.','Ptak ma dwa skrzydła.'),
('bugsteam3','dwa',2,'There are ______ cats in the garden.','two','There are two cats in the garden.','W ogrodzie są dwa koty.'),
('bugsteam3','trzy',0,'I''ve got ______ pencils.','three','I''ve got three pencils.','Mam trzy ołówki.'),
('bugsteam3','trzy',1,'My brother is ______ years old.','three','My brother is three years old.','Mój brat ma trzy lata.'),
('bugsteam3','trzy',2,'There are ______ apples in the bag.','three','There are three apples in the bag.','W torbie są trzy jabłka.'),
('bugsteam3','cztery',0,'A dog has got ______ legs.','four','A dog has got four legs.','Pies ma cztery nogi.'),
('bugsteam3','cztery',1,'There are ______ people in my family.','four','There are four people in my family.','W mojej rodzinie są cztery osoby.'),
('bugsteam3','cztery',2,'I''ve got ______ books in my bag.','four','I''ve got four books in my bag.','Mam w plecaku cztery książki.'),
('bugsteam3','pięć',0,'I''ve got ______ fingers on one hand.','five','I''ve got five fingers on one hand.','Mam pięć palców u jednej ręki.'),
('bugsteam3','pięć',1,'There are ______ ducks on the lake.','five','There are five ducks on the lake.','Na jeziorze jest pięć kaczek.'),
('bugsteam3','pięć',2,'My little brother is ______.','five','My little brother is five.','Mój młodszy brat ma pięć lat.'),
('bugsteam3','sześć',0,'I get up at ______ o''clock.','six','I get up at six o''clock.','Wstaję o szóstej.'),
('bugsteam3','sześć',1,'An insect has got ______ legs.','six','An insect has got six legs.','Owad ma sześć nóg.'),
('bugsteam3','sześć',2,'There are ______ eggs in the box.','six','There are six eggs in the box.','W pudełku jest sześć jajek.'),
('bugsteam3','siedem',0,'There are ______ days in a week.','seven','There are seven days in a week.','Tydzień ma siedem dni.'),
('bugsteam3','siedem',1,'My sister is ______ years old.','seven','My sister is seven years old.','Moja siostra ma siedem lat.'),
('bugsteam3','siedem',2,'I can see ______ birds in the tree.','seven','I can see seven birds in the tree.','Widzę siedem ptaków na drzewie.'),
('bugsteam3','osiem',0,'A spider has got ______ legs.','eight','A spider has got eight legs.','Pająk ma osiem nóg.'),
('bugsteam3','osiem',1,'I''m ______ years old.','eight','I''m eight years old.','Mam osiem lat.'),
('bugsteam3','osiem',2,'School starts at ______ o''clock.','eight','School starts at eight o''clock.','Lekcje zaczynają się o ósmej.'),
('bugsteam3','dziewięć',0,'I''m ______ years old.','nine','I''m nine years old.','Mam dziewięć lat.'),
('bugsteam3','dziewięć',1,'There are ______ children in the park.','nine','There are nine children in the park.','W parku jest dziewięcioro dzieci.'),
('bugsteam3','dziewięć',2,'My cat has got ______ kittens.','nine','My cat has got nine kittens.','Moja kotka ma dziewięć kociąt.'),
('bugsteam3','dziesięć',0,'I''ve got ______ fingers.','ten','I''ve got ten fingers.','Mam dziesięć palców.'),
('bugsteam3','dziesięć',1,'There are ______ books on my desk.','ten','There are ten books on my desk.','Na moim biurku jest dziesięć książek.'),
('bugsteam3','dziesięć',2,'Five and five is ______.','ten','Five and five is ten.','Pięć i pięć to dziesięć.'),
('bugsteam3','dwanaście',0,'There are ______ months in a year.','twelve','There are twelve months in a year.','Rok ma dwanaście miesięcy.'),
('bugsteam3','dwanaście',1,'We have lunch at ______ o''clock.','twelve','We have lunch at twelve o''clock.','Jemy obiad o dwunastej.'),
('bugsteam3','dwanaście',2,'My cousin is ______ years old.','twelve','My cousin is twelve years old.','Mój kuzyn ma dwanaście lat.'),
('bugsteam3','nauczyciel',0,'My ______ is very nice.','teacher','My teacher is very nice.','Mój nauczyciel jest bardzo miły.'),
('bugsteam3','nauczyciel',1,'A ______ works at a school.','teacher','A teacher works at a school.','Nauczyciel pracuje w szkole.'),
('bugsteam3','nauczyciel',2,'Our English ______ is from London.','teacher','Our English teacher is from London.','Nasza nauczycielka angielskiego jest z Londynu.'),
('bugsteam3','strażak',0,'A ______ puts out fires.','firefighter','A firefighter puts out fires.','Strażak gasi pożary.'),
('bugsteam3','strażak',1,'My uncle is a ______.','firefighter','My uncle is a firefighter.','Mój wujek jest strażakiem.'),
('bugsteam3','strażak',2,'The ______ has got a red truck.','firefighter','The firefighter has got a red truck.','Strażak ma czerwony wóz.'),
('bugsteam3','lekarz',0,'I''m ill. I need a ______.','doctor','I''m ill. I need a doctor.','Jestem chory. Potrzebuję lekarza.'),
('bugsteam3','lekarz',1,'The ______ works in a hospital.','doctor','The doctor works in a hospital.','Lekarz pracuje w szpitalu.'),
('bugsteam3','lekarz',2,'My mum is a ______.','doctor','My mum is a doctor.','Moja mama jest lekarką.'),
('bugsteam3','sprzedawca',0,'A ______ works in a shop.','shop assistant','A shop assistant works in a shop.','Sprzedawca pracuje w sklepie.'),
('bugsteam3','sprzedawca',1,'My aunt is a ______ in a shoe shop.','shop assistant','My aunt is a shop assistant in a shoe shop.','Moja ciocia jest sprzedawczynią w sklepie obuwniczym.'),
('bugsteam3','sprzedawca',2,'The ______ is very friendly.','shop assistant','The shop assistant is very friendly.','Sprzedawca jest bardzo miły.'),
('bugsteam3','policjant',0,'A ______ helps people in the street.','police officer','A police officer helps people in the street.','Policjant pomaga ludziom na ulicy.'),
('bugsteam3','policjant',1,'My dad is a ______.','police officer','My dad is a police officer.','Mój tata jest policjantem.'),
('bugsteam3','policjant',2,'The ______ has got a blue car.','police officer','The police officer has got a blue car.','Policjant ma niebieski samochód.'),
('bugsteam3','weterynarz',0,'My dog is ill. Let''s go to the ______.','vet','My dog is ill. Let''s go to the vet.','Mój pies jest chory. Chodźmy do weterynarza.'),
('bugsteam3','weterynarz',1,'A ______ helps animals.','vet','A vet helps animals.','Weterynarz pomaga zwierzętom.'),
('bugsteam3','weterynarz',2,'My sister wants to be a ______.','vet','My sister wants to be a vet.','Moja siostra chce zostać weterynarzem.'),
('bugsteam3','sklep z zabawkami',0,'I can buy a ball in the ______.','toy shop','I can buy a ball in the toy shop.','W sklepie z zabawkami mogę kupić piłkę.'),
('bugsteam3','sklep z zabawkami',1,'There''s a new ______ on my street.','toy shop','There''s a new toy shop on my street.','Na mojej ulicy jest nowy sklep z zabawkami.'),
('bugsteam3','sklep z zabawkami',2,'Let''s go to the ______!','toy shop','Let''s go to the toy shop!','Chodźmy do sklepu z zabawkami!'),
('bugsteam3','piekarnia',0,'I buy bread at the ______.','bakery','I buy bread at the bakery.','Kupuję chleb w piekarni.'),
('bugsteam3','piekarnia',1,'There''s a ______ next to my school.','bakery','There''s a bakery next to my school.','Obok mojej szkoły jest piekarnia.'),
('bugsteam3','piekarnia',2,'The ______ smells nice.','bakery','The bakery smells nice.','W piekarni ładnie pachnie.'),
('bugsteam3','sklep zoologiczny',0,'You can buy a hamster in the ______.','pet shop','You can buy a hamster in the pet shop.','W sklepie zoologicznym możesz kupić chomika.'),
('bugsteam3','sklep zoologiczny',1,'There are fish in the ______.','pet shop','There are fish in the pet shop.','W sklepie zoologicznym są ryby.'),
('bugsteam3','sklep zoologiczny',2,'I buy food for my cat at the ______.','pet shop','I buy food for my cat at the pet shop.','Kupuję jedzenie dla kota w sklepie zoologicznym.'),
('bugsteam3','księgarnia',0,'I''m buying a comic in the ______.','bookshop','I''m buying a comic in the bookshop.','Kupuję komiks w księgarni.'),
('bugsteam3','księgarnia',1,'The ______ is next to the bakery.','bookshop','The bookshop is next to the bakery.','Księgarnia jest obok piekarni.'),
('bugsteam3','księgarnia',2,'There are a lot of books in the ______.','bookshop','There are a lot of books in the bookshop.','W księgarni jest dużo książek.'),
('bugsteam3','sklep ze słodyczami',0,'I buy chocolate at the ______.','sweet shop','I buy chocolate at the sweet shop.','Kupuję czekoladę w sklepie ze słodyczami.'),
('bugsteam3','sklep ze słodyczami',1,'Children love the ______.','sweet shop','Children love the sweet shop.','Dzieci uwielbiają sklep ze słodyczami.'),
('bugsteam3','sklep ze słodyczami',2,'The ______ has got big lollipops.','sweet shop','The sweet shop has got big lollipops.','W sklepie ze słodyczami są duże lizaki.'),
('bugsteam3','sklep obuwniczy',0,'I need new trainers. Let''s go to the ______.','shoe shop','I need new trainers. Let''s go to the shoe shop.','Potrzebuję nowych butów sportowych. Chodźmy do sklepu obuwniczego.'),
('bugsteam3','sklep obuwniczy',1,'Mum is buying boots in the ______.','shoe shop','Mum is buying boots in the shoe shop.','Mama kupuje kozaki w sklepie obuwniczym.'),
('bugsteam3','sklep obuwniczy',2,'The ______ is closed on Sunday.','shoe shop','The shoe shop is closed on Sunday.','Sklep obuwniczy jest zamknięty w niedzielę.'),
('bugsteam3','sklep odzieżowy',0,'I''m buying a T-shirt in the ______.','clothes shop','I''m buying a T-shirt in the clothes shop.','Kupuję koszulkę w sklepie odzieżowym.'),
('bugsteam3','sklep odzieżowy',1,'There''s a big ______ in the city.','clothes shop','There''s a big clothes shop in the city.','W mieście jest duży sklep odzieżowy.'),
('bugsteam3','sklep odzieżowy',2,'My sister works in a ______.','clothes shop','My sister works in a clothes shop.','Moja siostra pracuje w sklepie odzieżowym.'),
('bugsteam3','targ, rynek',0,'We buy fruit at the ______.','market','We buy fruit at the market.','Kupujemy owoce na targu.'),
('bugsteam3','targ, rynek',1,'The ______ is open on Saturday.','market','The market is open on Saturday.','Targ jest otwarty w sobotę.'),
('bugsteam3','targ, rynek',2,'Grandma sells flowers at the ______.','market','Grandma sells flowers at the market.','Babcia sprzedaje kwiaty na targu.'),
('bugsteam3','szkoła',0,'I go to ______ by bike.','school','I go to school by bike.','Jeżdżę do szkoły rowerem.'),
('bugsteam3','szkoła',1,'My ______ is big and old.','school','My school is big and old.','Moja szkoła jest duża i stara.'),
('bugsteam3','szkoła',2,'We play football at ______.','school','We play football at school.','W szkole gramy w piłkę nożną.'),
('bugsteam3','hotel',0,'We''re staying in a ______ by the sea.','hotel','We''re staying in a hotel by the sea.','Nocujemy w hotelu nad morzem.'),
('bugsteam3','hotel',1,'The ______ has got a big swimming pool.','hotel','The hotel has got a big swimming pool.','Hotel ma duży basen.'),
('bugsteam3','hotel',2,'There''s a ______ next to the train station.','hotel','There''s a hotel next to the train station.','Obok dworca kolejowego jest hotel.'),
('bugsteam3','szpital',0,'Doctors work in a ______.','hospital','Doctors work in a hospital.','Lekarze pracują w szpitalu.'),
('bugsteam3','szpital',1,'My grandpa is in ______.','hospital','My grandpa is in hospital.','Mój dziadek jest w szpitalu.'),
('bugsteam3','szpital',2,'The ______ is very big.','hospital','The hospital is very big.','Szpital jest bardzo duży.'),
('bugsteam3','poczta',0,'I''m sending a letter at the ______.','post office','I''m sending a letter at the post office.','Wysyłam list na poczcie.'),
('bugsteam3','poczta',1,'The ______ is next to the bank.','post office','The post office is next to the bank.','Poczta jest obok banku.'),
('bugsteam3','poczta',2,'Mum buys stamps at the ______.','post office','Mum buys stamps at the post office.','Mama kupuje znaczki na poczcie.'),
('bugsteam3','restauracja',0,'We''re having dinner in a ______.','restaurant','We''re having dinner in a restaurant.','Jemy kolację w restauracji.'),
('bugsteam3','restauracja',1,'This ______ has got good pizza.','restaurant','This restaurant has got good pizza.','W tej restauracji jest dobra pizza.'),
('bugsteam3','restauracja',2,'My uncle is a cook in a ______.','restaurant','My uncle is a cook in a restaurant.','Mój wujek jest kucharzem w restauracji.'),
('bugsteam3','dworzec kolejowy',0,'We''re waiting at the ______.','train station','We''re waiting at the train station.','Czekamy na dworcu kolejowym.'),
('bugsteam3','dworzec kolejowy',1,'The ______ is in the city centre.','train station','The train station is in the city centre.','Dworzec kolejowy jest w centrum miasta.'),
('bugsteam3','dworzec kolejowy',2,'Let''s meet at the ______.','train station','Let''s meet at the train station.','Spotkajmy się na dworcu kolejowym.'),
('bugsteam3','robić zdjęcia',0,'She''s ______ of the sea.','taking photos','She''s taking photos of the sea.','Ona robi zdjęcia morza.'),
('bugsteam3','robić zdjęcia',1,'I like ______ with my camera.','taking photos','I like taking photos with my camera.','Lubię robić zdjęcia aparatem.'),
('bugsteam3','robić zdjęcia',2,'Dad is ______ in the mountains.','taking photos','Dad is taking photos in the mountains.','Tata robi zdjęcia w górach.'),
('bugsteam3','puszczać latawiec',0,'Tom is ______ on the beach.','flying a kite','Tom is flying a kite on the beach.','Tom puszcza latawiec na plaży.'),
('bugsteam3','puszczać latawiec',1,'I love ______ on windy days.','flying a kite','I love flying a kite on windy days.','Uwielbiam puszczać latawiec w wietrzne dni.'),
('bugsteam3','puszczać latawiec',2,'We''re ______ in the park.','flying a kite','We''re flying a kite in the park.','Puszczamy latawiec w parku.'),
('bugsteam3','urządzać piknik',0,'We''re ______ in the forest.','having a picnic','We''re having a picnic in the forest.','Urządzamy piknik w lesie.'),
('bugsteam3','urządzać piknik',1,'My family is ______ by the lake.','having a picnic','My family is having a picnic by the lake.','Moja rodzina urządza piknik nad jeziorem.'),
('bugsteam3','urządzać piknik',2,'They''re ______ in the garden.','having a picnic','They''re having a picnic in the garden.','Oni urządzają piknik w ogrodzie.'),
('bugsteam3','łowić ryby',0,'Grandpa is ______ in the river.','fishing','Grandpa is fishing in the river.','Dziadek łowi ryby w rzece.'),
('bugsteam3','łowić ryby',1,'I go ______ with my dad.','fishing','I go fishing with my dad.','Chodzę na ryby z tatą.'),
('bugsteam3','łowić ryby',2,'We''re ______ on the lake.','fishing','We''re fishing on the lake.','Łowimy ryby na jeziorze.'),
('bugsteam3','zbierać muszle',0,'I''m ______ on the beach.','collecting shells','I''m collecting shells on the beach.','Zbieram muszle na plaży.'),
('bugsteam3','zbierać muszle',1,'My sister likes ______.','collecting shells','My sister likes collecting shells.','Moja siostra lubi zbierać muszle.'),
('bugsteam3','zbierać muszle',2,'The children are ______ by the sea.','collecting shells','The children are collecting shells by the sea.','Dzieci zbierają muszle nad morzem.'),
('bugsteam3','budować zamek z piasku',0,'We''re ______ on the beach.','building a sandcastle','We''re building a sandcastle on the beach.','Budujemy zamek z piasku na plaży.'),
('bugsteam3','budować zamek z piasku',1,'Look! Tom is ______.','building a sandcastle','Look! Tom is building a sandcastle.','Spójrz! Tom buduje zamek z piasku.'),
('bugsteam3','budować zamek z piasku',2,'I like ______ with my brother.','building a sandcastle','I like building a sandcastle with my brother.','Lubię budować z bratem zamek z piasku.'),
('bugsteam3','nurkować z rurką',0,'I''m ______ in the sea.','snorkelling','I''m snorkelling in the sea.','Nurkuję z rurką w morzu.'),
('bugsteam3','nurkować z rurką',1,'She loves ______.','snorkelling','She loves snorkelling.','Ona uwielbia nurkować z rurką.'),
('bugsteam3','nurkować z rurką',2,'We go ______ in summer.','snorkelling','We go snorkelling in summer.','Latem nurkujemy z rurką.'),
('bugsteam3','rozpalać ognisko',0,'Dad is ______ in the forest.','making a fire','Dad is making a fire in the forest.','Tata rozpala ognisko w lesie.'),
('bugsteam3','rozpalać ognisko',1,'They''re ______ by the lake.','making a fire','They''re making a fire by the lake.','Oni rozpalają ognisko nad jeziorem.'),
('bugsteam3','rozpalać ognisko',2,'We''re ______ in the evening.','making a fire','We''re making a fire in the evening.','Wieczorem rozpalamy ognisko.'),
('bugsteam3','chodzić po górach, wędrować',0,'We''re ______ in the mountains.','hiking','We''re hiking in the mountains.','Wędrujemy po górach.'),
('bugsteam3','chodzić po górach, wędrować',1,'My parents love ______.','hiking','My parents love hiking.','Moi rodzice uwielbiają chodzić po górach.'),
('bugsteam3','chodzić po górach, wędrować',2,'I go ______ with my uncle.','hiking','I go hiking with my uncle.','Chodzę na wędrówki z wujkiem.'),
('bugsteam3','plaża',0,'We''re playing on the ______.','beach','We''re playing on the beach.','Bawimy się na plaży.'),
('bugsteam3','plaża',1,'The ______ is sunny today.','beach','The beach is sunny today.','Na plaży jest dziś słonecznie.'),
('bugsteam3','plaża',2,'I go to the ______ in summer.','beach','I go to the beach in summer.','Latem jeżdżę na plażę.'),
('bugsteam3','góry',0,'We go skiing in the ______.','mountains','We go skiing in the mountains.','Jeździmy na nartach w górach.'),
('bugsteam3','góry',1,'The ______ are very high.','mountains','The mountains are very high.','Góry są bardzo wysokie.'),
('bugsteam3','góry',2,'There''s snow in the ______.','mountains','There''s snow in the mountains.','W górach jest śnieg.'),
('bugsteam3','las',0,'We''re walking in the ______.','forest','We''re walking in the forest.','Spacerujemy po lesie.'),
('bugsteam3','las',1,'Bears live in the ______.','forest','Bears live in the forest.','Niedźwiedzie żyją w lesie.'),
('bugsteam3','las',2,'I can see mushrooms in the ______.','forest','I can see mushrooms in the forest.','Widzę grzyby w lesie.'),
('bugsteam3','jezioro',0,'The ______ is cold today.','lake','The lake is cold today.','Jezioro jest dziś zimne.'),
('bugsteam3','jezioro',1,'There are ducks on the ______.','lake','There are ducks on the lake.','Na jeziorze są kaczki.'),
('bugsteam3','jezioro',2,'Our house is near a ______.','lake','Our house is near a lake.','Nasz dom jest blisko jeziora.'),
('bugsteam3','miasto',0,'London is a big ______.','city','London is a big city.','Londyn to duże miasto.'),
('bugsteam3','miasto',1,'My cousin lives in the ______.','city','My cousin lives in the city.','Mój kuzyn mieszka w mieście.'),
('bugsteam3','miasto',2,'There are a lot of cars in the ______.','city','There are a lot of cars in the city.','W mieście jest dużo samochodów.'),
('bugsteam3','wieś',0,'My grandma lives in a small ______.','village','My grandma lives in a small village.','Moja babcia mieszka w małej wsi.'),
('bugsteam3','wieś',1,'There are cows and horses in the ______.','village','There are cows and horses in the village.','We wsi są krowy i konie.'),
('bugsteam3','wieś',2,'Our ______ has got a school and a shop.','village','Our village has got a school and a shop.','W naszej wsi jest szkoła i sklep.');

SELECT 'OK — bugsteam3: 87 słów, 261 zdań kontekstowych' AS status;
