// Grammar City — mission & question data
// Question types:
//   c = choice   { q, o:[options], a:indexOfCorrect, e:explanation }
//   t = type     { q (use ___ for the gap), a:[accepted answers], e }
//   o = order    { q (instruction), w:'correct sentence', e }
window.MISSIONS = [
/* ============================ A1 ============================ */
{
  id: 'school', place: 'Westside School', short: 'SCH', topic: 'Czasownik "to be"', level: 'A1', tier: 0,
  block: [2, 3], lot: [0, 0],
  npc: 'Mrs. Parker, nauczycielka',
  story: "Welcome to Grammar City! I'm Mrs. Parker. Before you explore the streets, show me you know the most important verb in English: to be. Answer my questions and you'll get your first pay.",
  storyPL: 'Witaj w Grammar City! Zanim ruszysz na miasto, pokaż, że znasz najważniejszy czasownik w angielskim: "to be".',
  tip: '<b>I am</b> · <b>you/we/they are</b> · <b>he/she/it is</b><br>Przeczenie: <i>I am not, she isn\'t, they aren\'t</i><br>Pytanie: szyk przestawny — <i>Is he at home? Are you ready?</i><br>Krótkie odpowiedzi twierdzące <b>nie</b> mają skrótu: <i>Yes, I am</i> (nie: <s>Yes, I\'m</s>).',
  questions: [
    { t: 'c', q: 'I ___ a new student here.', o: ['am', 'is', 'are', 'be'], a: 0, e: 'Z "I" zawsze używamy "am".' },
    { t: 'c', q: 'My teachers ___ very friendly.', o: ['is', 'are', 'am', 'be'], a: 1, e: '"My teachers" to liczba mnoga (they) → "are".' },
    { t: 'c', q: '___ your brother at school today?', o: ['Are', 'Am', 'Is', 'Be'], a: 2, e: '"Your brother" = he → pytanie zaczynamy od "Is".' },
    { t: 'c', q: 'They ___ not in the classroom.', o: ['is', 'am', 'be', 'are'], a: 3, e: '"They" → "are". Przeczenie: are not / aren\'t.' },
    { t: 't', q: 'She ___ (be) twelve years old.', a: ['is', "'s"], e: 'He/she/it → "is". Po angielsku wiek podajemy z "to be": She is twelve.' },
    { t: 't', q: 'We ___ (not be) late. Użyj formy skróconej.', a: ["aren't"], e: 'We are not → we aren\'t.' },
    { t: 'c', q: 'Where ___ the library?', o: ['are', 'is', 'am', 'be'], a: 1, e: '"The library" to liczba pojedyncza → "is".' },
    { t: 'c', q: '— Are you from Poland? — Yes, I ___.', o: ["'m", 'is', 'am', 'are'], a: 2, e: 'W krótkiej odpowiedzi twierdzącej nie skracamy: Yes, I am.' },
    { t: 'o', q: 'Ułóż pytanie z rozsypanki:', w: 'Is this your pencil', e: 'Pytanie z "to be": czasownik przed podmiotem — Is this…?' },
    { t: 'c', q: 'It ___ cold today, so wear a jacket.', o: ['are', 'am', 'is', 'be'], a: 2, e: 'Pogoda: "It is cold".' },
  ]
},
{
  id: 'pizzeria', place: "Luigi's Pizzeria", short: 'PIZ', topic: 'Przedimki a / an / the', level: 'A1', tier: 0,
  block: [3, 2], lot: [1, 0],
  npc: 'Luigi, właściciel pizzerii',
  story: "Mamma mia! My new waiter keeps mixing up 'a', 'an' and 'the' on the menu. The customers are confused! Help me fix the orders before dinner time.",
  storyPL: 'Nowy kelner myli "a", "an" i "the" w menu. Pomóż poprawić zamówienia przed kolacją.',
  tip: '<b>a</b> — przed spółgłoską w wymowie: <i>a pizza, a university</i> (/ju/)<br><b>an</b> — przed samogłoską w wymowie: <i>an egg, an hour</i> (nieme h)<br><b>the</b> — konkretna, znana rzecz lub jedyna w swoim rodzaju: <i>the sun, the best</i><br><b>brak przedimka</b> — ogólnie o rzeczach niepoliczalnych / liczbie mnogiej: <i>I love cheese.</i>',
  questions: [
    { t: 'c', q: "I'd like ___ pizza, please.", o: ['a', 'an', 'the', '– (nic)'], a: 0, e: 'Jedna, dowolna pizza, słowo zaczyna się spółgłoską → "a".' },
    { t: 'c', q: 'Can I have ___ orange juice?', o: ['a', 'an', 'the', '– (nic)'], a: 1, e: '"Orange" zaczyna się samogłoską → "an".' },
    { t: 'c', q: '___ pizza you ordered is ready.', o: ['A', 'An', 'The', '– (nic)'], a: 2, e: 'Konkretna pizza (ta, którą zamówiłeś) → "the".' },
    { t: 'c', q: 'He is ___ honest waiter.', o: ['a', 'an', 'the', '– (nic)'], a: 1, e: 'W "honest" h jest nieme — wymawiamy /ɒ/ → "an".' },
    { t: 'c', q: 'She works as ___ university professor.', o: ['an', 'the', 'a', '– (nic)'], a: 2, e: '"University" wymawiamy /ju:/ — dźwięk spółgłoskowy → "a".' },
    { t: 'c', q: 'I love ___ cheese.', o: ['a', 'the', 'an', '– (nic)'], a: 3, e: 'Mówimy ogólnie o serze (niepoliczalny) → bez przedimka.' },
    { t: 'c', q: 'We ate at ___ best pizzeria in town.', o: ['a', 'the', 'an', '– (nic)'], a: 1, e: 'Przed stopniem najwyższym zawsze "the".' },
    { t: 't', q: 'It takes ___ hour to bake the dough.', a: ['an'], e: '"Hour" — nieme h, wymowa zaczyna się samogłoską → "an".' },
    { t: 'c', q: '___ sun is shining over the city.', o: ['A', 'The', 'An', '– (nic)'], a: 1, e: 'Rzeczy jedyne w swoim rodzaju (the sun, the moon) → "the".' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'I want a pizza with an egg', e: 'a pizza (spółgłoska), an egg (samogłoska).' },
  ]
},
{
  id: 'park', place: 'Central Park', short: 'PRK', topic: 'There is / there are, liczba mnoga', level: 'A1', tier: 0,
  park: [2, 2],
  npc: 'Tom, strażnik parku',
  story: "Hey there! I'm writing a report about everything in the park, but my English is a bit rusty. What is there? What are there? Help me count everything correctly.",
  storyPL: 'Strażnik parku pisze raport o tym, co jest w parku. Pomóż mu poprawnie opisać i policzyć rzeczy.',
  tip: '<b>There is</b> + l. pojedyncza / niepoliczalne: <i>There is a bench. There is some water.</i><br><b>There are</b> + l. mnoga: <i>There are two dogs.</i><br>Pytanie: <i>Is there…? Are there any…?</i><br>Liczba mnoga nieregularna: <i>child → children, man → men, mouse → mice, foot → feet</i><br>-y po spółgłosce → -ies: <i>city → cities</i>',
  questions: [
    { t: 'c', q: 'There ___ a fountain in the park.', o: ['is', 'are', 'be', 'am'], a: 0, e: 'Jedna fontanna → "There is".' },
    { t: 'c', q: 'There ___ many children on the playground.', o: ['is', 'are', 'am', 'be'], a: 1, e: '"Children" to liczba mnoga → "There are".' },
    { t: 'c', q: 'Liczba mnoga od "child" to:', o: ['childs', 'childes', 'children', 'childrens'], a: 2, e: 'Nieregularna: child → children.' },
    { t: 't', q: 'One mouse, two ___.', a: ['mice'], e: 'Nieregularna: mouse → mice.' },
    { t: 'c', q: '___ there any benches near the lake?', o: ['Is', 'Are', 'Do', 'Have'], a: 1, e: '"Benches" — liczba mnoga → "Are there…?"' },
    { t: 'c', q: 'There ___ some water in the bottle.', o: ['are', 'is', 'be', 'have'], a: 1, e: '"Water" jest niepoliczalne → "There is".' },
    { t: 't', q: 'Two ___ (man) are sitting on the grass.', a: ['men'], e: 'Nieregularna: man → men.' },
    { t: 'c', q: 'Liczba mnoga od "city" to:', o: ['citys', 'cityes', 'cities', 'citis'], a: 2, e: 'Spółgłoska + y → -ies: city → cities.' },
    { t: 'c', q: "There isn't ___ ice cream van today.", o: ['a', 'an', 'some', 'many'], a: 1, e: 'Jedna furgonetka; "ice" zaczyna się samogłoską → "an".' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'There are three dogs in the park', e: 'Liczba mnoga (three dogs) → There are.' },
  ]
},
{
  id: 'cafe', place: 'Sunrise Café', short: 'CAF', topic: 'Present Simple', level: 'A1', tier: 0,
  block: [4, 3], lot: [0, 1],
  npc: 'Maya, baristka',
  story: "Good morning! I know all my regulars and their habits — who drinks what, who comes when. But I need someone to write it all down in proper English. Can you do it?",
  storyPL: 'Baristka zna nawyki stałych klientów. Pomóż opisać je poprawnie w Present Simple.',
  tip: 'Nawyki, rutyna, fakty: <i>She drinks coffee every day.</i><br>He/she/it → końcówka <b>-s / -es</b>: <i>works, watches, goes</i><br>Przeczenie: <b>don\'t / doesn\'t</b> + bezokolicznik: <i>He doesn\'t like tea.</i><br>Pytanie: <b>Do / Does</b> + podmiot + bezokolicznik: <i>Does he work here?</i><br>Po doesn\'t/does czasownik <b>bez -s</b>.',
  questions: [
    { t: 'c', q: 'She ___ coffee every morning.', o: ['drink', 'drinks', 'drinking', 'is drink'], a: 1, e: 'He/she/it w Present Simple → końcówka -s: drinks.' },
    { t: 'c', q: 'They ___ tea.', o: ["doesn't like", "don't likes", "don't like", 'not like'], a: 2, e: 'They → don\'t + bezokolicznik (bez -s).' },
    { t: 'c', q: '___ he work here?', o: ['Do', 'Is', 'Does', 'Has'], a: 2, e: 'Pytanie z he/she/it → "Does".' },
    { t: 't', q: 'My brother ___ (watch) TV every evening.', a: ['watches'], e: 'Czasowniki kończące się na -ch, -sh, -s, -x, -o dostają -es: watches.' },
    { t: 'c', q: 'The café ___ at 7 a.m.', o: ['open', 'opens', 'opening', 'is open at'], a: 1, e: 'Stały rozkład, "the café" = it → opens.' },
    { t: 'c', q: 'I never ___ sugar in my coffee.', o: ['puts', 'putting', 'put', 'am put'], a: 2, e: 'Z "I" czasownik bez końcówki: I never put…' },
    { t: 't', q: 'What time ___ you usually have breakfast?', a: ['do'], e: 'Pytanie z "you" → "do".' },
    { t: 'c', q: 'Water ___ at 100 degrees Celsius.', o: ['boil', 'is boiling', 'boils', 'boiled'], a: 2, e: 'Fakt naukowy → Present Simple: boils.' },
    { t: 'c', q: 'He ___ speak French.', o: ["don't", "doesn't", "isn't", 'not'], a: 1, e: 'He → doesn\'t + bezokolicznik.' },
    { t: 'o', q: 'Ułóż pytanie z rozsypanki:', w: 'Does your sister work in this cafe', e: 'Does + podmiot + czasownik bez -s.' },
  ]
},
{
  id: 'post', place: 'Post Office', short: 'PST', topic: 'Zaimki i dzierżawczość', level: 'A1', tier: 0,
  block: [3, 4], lot: [1, 1],
  npc: 'Mr. Green, listonosz',
  story: "Oh no, the parcels are all mixed up! Whose is this? Is it hers or his? I need a sharp mind to sort out who owns what. Let's deliver them to the right people!",
  storyPL: 'Paczki się pomieszały! Pomóż ustalić, czyje są — użyj właściwych zaimków.',
  tip: 'Podmiot: <i>I, you, he, she, it, we, they</i><br>Dopełnienie: <i>me, you, him, her, it, us, them</i><br>Przymiotniki dzierżawcze (+ rzeczownik): <i>my, your, his, her, its, our, their</i><br>Zaimki dzierżawcze (samodzielnie): <i>mine, yours, his, hers, ours, theirs</i><br><b>its</b> = jego (o rzeczy/zwierzęciu), <b>it\'s</b> = it is<br>Dopełniacz: <i>Tom\'s car, my parents\' house</i>',
  questions: [
    { t: 'c', q: 'This is Anna. ___ is my cousin.', o: ['Her', 'She', 'Hers', 'It'], a: 1, e: 'Podmiot zdania → "She".' },
    { t: 'c', q: 'Give the letter to ___.', o: ['he', 'his', 'him', 'himself'], a: 2, e: 'Po przyimku (to) → forma dopełnienia: him.' },
    { t: 'c', q: "Is this parcel ___? — Yes, it's mine.", o: ['your', 'yours', 'you', "you're"], a: 1, e: 'Samodzielny zaimek dzierżawczy (bez rzeczownika) → yours.' },
    { t: 'c', q: 'The dog is wagging ___ tail.', o: ["it's", 'its', 'his', "its'"], a: 1, e: '"Its" = jego (zwierzęcia). "It\'s" to skrót od "it is".' },
    { t: 'c', q: 'This is ___ car. (samochód Toma)', o: ['Toms', "Toms'", "Tom's", 'of Tom'], a: 2, e: 'Dopełniacz saksoński w l. pojedynczej: Tom\'s.' },
    { t: 't', q: 'We love our house. The house is ___.', a: ['ours'], e: 'Samodzielny zaimek dzierżawczy od "we" → ours.' },
    { t: 'c', q: 'My ___ house is big. (dom moich rodziców)', o: ["parent's", "parents'", 'parents', "parents's"], a: 1, e: 'Liczba mnoga zakończona na -s → sam apostrof: parents\'.' },
    { t: 'c', q: 'They sent ___ a postcard. (do nas)', o: ['we', 'our', 'us', 'ours'], a: 2, e: 'Dopełnienie od "we" → us.' },
    { t: 'c', q: "Whose bag is this? — It's ___.", o: ['her', 'hers', "her's", 'she'], a: 1, e: 'Samodzielnie → hers (nigdy "her\'s").' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'Can you send this letter to her', e: 'Po przyimku "to" → her (dopełnienie).' },
  ]
},
/* ============================ A2 ============================ */
{
  id: 'hospital', place: 'St. Mary Hospital', short: 'HSP', topic: 'Present Continuous', level: 'A2', tier: 1,
  block: [5, 1], lot: [0, 0],
  npc: 'Dr. Evans, lekarka',
  story: "Busy day in the ER! Everything is happening right now and I need live updates for the chief. Tell me what everybody is doing at this moment — quickly!",
  storyPL: 'Na izbie przyjęć wszystko dzieje się teraz. Opisz, co kto robi w tej chwili.',
  tip: '<b>am/is/are + czasownik-ing</b> — czynność trwająca teraz lub tymczasowa: <i>She is working now. I\'m staying with friends this week.</i><br>Pisownia: <i>lie → lying, run → running, make → making</i><br>Czasowniki stanu (<i>know, like, want, understand, believe</i>) zwykle <b>nie</b> występują w formie -ing.<br>Present Simple = zwyczaj; Present Continuous = teraz.',
  questions: [
    { t: 'c', q: 'The doctor ___ a patient right now.', o: ['examines', 'is examining', 'examining', 'are examining'], a: 1, e: '"Right now" → Present Continuous; the doctor = he/she → is examining.' },
    { t: 'c', q: 'Look! The ambulance ___.', o: ['comes', 'is coming', 'come', 'coming'], a: 1, e: '"Look!" wskazuje na coś dziejącego się teraz → is coming.' },
    { t: 'c', q: 'What ___ you doing?', o: ['do', 'is', 'are', 'does'], a: 2, e: 'You → are: What are you doing?' },
    { t: 't', q: 'They ___ (wait) in the waiting room at the moment.', a: ['are waiting', "'re waiting"], e: 'At the moment → are + waiting.' },
    { t: 'c', q: 'I ___ at my aunt\'s house this week.', o: ['stay', 'am staying', 'stays', 'staying'], a: 1, e: 'Sytuacja tymczasowa → Present Continuous.' },
    { t: 'c', q: 'I ___ you now. Thanks for explaining!', o: ['am understanding', 'understand', 'understanding', 'are understand'], a: 1, e: '"Understand" to czasownik stanu — nie używamy go w formie -ing.' },
    { t: 't', q: 'Forma -ing czasownika "lie" (leżeć) to:', a: ['lying'], e: '-ie → -ying: lie → lying, die → dying.' },
    { t: 'c', q: 'The baby ___ sleeping, so be loud if you want.', o: ["isn't", "doesn't", "aren't", "don't"], a: 0, e: 'Przeczenie w Present Continuous: is not / isn\'t + -ing.' },
    { t: 'c', q: 'Nurses usually ___ uniforms, but today they ___ T-shirts.', o: ['wear / wear', 'are wearing / wear', 'wear / are wearing', 'wearing / wear'], a: 2, e: 'Zwyczaj (usually) → Present Simple; dziś, wyjątkowo → Present Continuous.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'The nurse is taking my temperature', e: 'Podmiot + is + czasownik-ing.' },
  ]
},
{
  id: 'police', place: 'Police Station', short: 'POL', topic: 'Past Simple', level: 'A2', tier: 1,
  block: [1, 5], lot: [1, 0],
  npc: 'Detective Stone',
  story: "Someone robbed the jewellery store last night. I've got three witnesses and none of them can tell their story in the past tense! Help me take their statements properly.",
  storyPL: 'Wczoraj w nocy obrabowano jubilera. Pomóż spisać zeznania świadków w czasie przeszłym.',
  tip: 'Zakończone czynności w przeszłości: <i>yesterday, last night, two hours ago, in 2010</i><br>Regularne: <b>-ed</b> — <i>called, stopped</i> (podwojenie spółgłoski!), <i>studied</i><br>Nieregularne: <i>see → saw, buy → bought, run → ran, go → went</i><br>Przeczenie i pytanie: <b>didn\'t / Did</b> + bezokolicznik — <i>Did you see him? I didn\'t see him.</i><br><b>was/were</b> dla "to be".',
  questions: [
    { t: 'c', q: 'Where ___ you last night?', o: ['was', 'were', 'did', 'are'], a: 1, e: '"To be" w przeszłości; you → were.' },
    { t: 'c', q: 'I ___ the thief yesterday.', o: ['see', 'seen', 'saw', 'seed'], a: 2, e: 'See → saw (nieregularny).' },
    { t: 'c', q: '___ you lock the door?', o: ['Were', 'Do', 'Did', 'Was'], a: 2, e: 'Pytanie w Past Simple: Did + podmiot + bezokolicznik.' },
    { t: 't', q: 'Past Simple od "buy" to:', a: ['bought'], e: 'Buy → bought (nieregularny).' },
    { t: 'c', q: "He didn't ___ anything.", o: ['saw', 'see', 'seen', 'sees'], a: 1, e: 'Po "didn\'t" zawsze bezokolicznik: didn\'t see.' },
    { t: 't', q: 'The robbers ___ (run) away at midnight.', a: ['ran'], e: 'Run → ran (nieregularny).' },
    { t: 'c', q: 'We ___ at home at 9 p.m.', o: ['was', 'were', 'did', 'are'], a: 1, e: 'We → were.' },
    { t: 'c', q: 'She ___ the police two hours ago.', o: ['calls', 'called', 'has called', 'call'], a: 1, e: '"Two hours ago" → Past Simple: called.' },
    { t: 't', q: 'Past Simple od "stop" to:', a: ['stopped'], e: 'Krótka sylaba zakończona spółgłoską → podwajamy: stopped.' },
    { t: 'o', q: 'Ułóż pytanie z rozsypanki:', w: 'Did you see the red car', e: 'Did + podmiot + bezokolicznik.' },
  ]
},
{
  id: 'mall', place: 'Mega Mall', short: 'MAL', topic: 'Stopniowanie przymiotników', level: 'A2', tier: 1,
  block: [5, 5], lot: [1, 1],
  npc: 'Kim, stylistka',
  story: "Welcome to the Mega Mall! I'm shooting a fashion video and I need someone who can compare things like a pro. Cheaper, better, the most beautiful — let's go shopping!",
  storyPL: 'Stylistka nagrywa film modowy. Pomóż jej porównywać rzeczy: tańszy, lepszy, najpiękniejszy.',
  tip: 'Krótkie: <i>cheap → cheaper → the cheapest</i>; <i>big → bigger → the biggest</i><br>-y → -ier/-iest: <i>happy → happier → the happiest</i><br>Długie: <i>more / the most expensive</i><br>Nieregularne: <i>good → better → best</i>, <i>bad → worse → worst</i>, <i>far → further</i><br>Porównanie: <b>than</b>; równość: <b>as … as</b>.',
  questions: [
    { t: 'c', q: 'This jacket is ___ than that one.', o: ['cheap', 'cheaper', 'cheapest', 'more cheap'], a: 1, e: 'Krótki przymiotnik + -er + than.' },
    { t: 'c', q: 'This is the ___ shop in the mall.', o: ['bigger', 'most big', 'biggest', 'bigest'], a: 2, e: 'Stopień najwyższy; big → biggest (podwojenie g).' },
    { t: 'c', q: 'This phone is ___ than my old one.', o: ['gooder', 'better', 'best', 'more good'], a: 1, e: 'Good → better → best (nieregularny).' },
    { t: 't', q: 'Stopień wyższy od "expensive" to:', a: ['more expensive'], e: 'Długi przymiotnik → more expensive.' },
    { t: 'c', q: "It's the ___ day of my life!", o: ['baddest', 'worse', 'worst', 'most bad'], a: 2, e: 'Bad → worse → worst.' },
    { t: 'c', q: 'My bag is as big ___ yours.', o: ['than', 'as', 'like', 'that'], a: 1, e: 'Równość: as + przymiotnik + as.' },
    { t: 't', q: 'Stopień najwyższy od "happy" (z the):', a: ['the happiest'], e: 'Spółgłoska + y → -iest: the happiest.' },
    { t: 'c', q: 'Prices here are much ___ than online.', o: ['high', 'highest', 'higher', 'more high'], a: 2, e: '"Much" wzmacnia stopień wyższy: much higher.' },
    { t: 'c', q: 'This mall is ___ than the old one.', o: ['moderner', 'more modern', 'most modern', 'modernest'], a: 1, e: '"Modern" stopniujemy opisowo: more modern.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'This is the most beautiful dress in the shop', e: 'the most + długi przymiotnik + in.' },
  ]
},
{
  id: 'market', place: 'FreshMart Supermarket', short: 'MKT', topic: 'Policzalne i niepoliczalne', level: 'A2', tier: 1,
  block: [1, 1], lot: [0, 1],
  npc: 'Grandma Rose',
  story: "Dear, my eyes aren't what they used to be. Could you help me with my shopping list? How much flour? How many eggs? Some or any? I always get confused!",
  storyPL: 'Babcia potrzebuje pomocy z listą zakupów: how much czy how many? some czy any?',
  tip: 'Policzalne: <i>apple, egg</i> → <b>many, a few</b>; <i>How many apples?</i><br>Niepoliczalne: <i>milk, bread, money, information</i> → <b>much, a little</b>; <i>How much milk?</i><br><b>some</b> — zdania twierdzące i prośby; <b>any</b> — pytania i przeczenia<br>Miary: <i>a loaf of bread, a bottle of water, a piece of information</i>',
  questions: [
    { t: 'c', q: 'How ___ apples do we need?', o: ['much', 'many', 'little', 'any'], a: 1, e: 'Apples są policzalne → many.' },
    { t: 'c', q: 'How ___ milk is left?', o: ['many', 'much', 'few', 'a'], a: 1, e: 'Milk jest niepoliczalne → much.' },
    { t: 'c', q: 'We need ___ bread.', o: ['a', 'many', 'some', 'any'], a: 2, e: 'Zdanie twierdzące + niepoliczalne → some.' },
    { t: 'c', q: 'Is there ___ sugar?', o: ['any', 'many', 'a', 'few'], a: 0, e: 'Pytanie → any.' },
    { t: 'c', q: 'There are only ___ eggs — just two.', o: ['a little', 'a few', 'much', 'a lot'], a: 1, e: 'Kilka (policzalne) → a few.' },
    { t: 'c', q: 'I have ___ money, but not much.', o: ['a few', 'many', 'a little', 'few'], a: 2, e: 'Trochę (niepoliczalne) → a little.' },
    { t: 'c', q: 'Can you buy a ___ of bread?', o: ['bottle', 'loaf', 'glass', 'bar'], a: 1, e: 'A loaf of bread — bochenek chleba.' },
    { t: 't', q: "There isn't ___ rice left.", a: ['any'], e: 'Przeczenie → any.' },
    { t: 'c', q: 'Can you give me ___?', o: ['an information', 'informations', 'some information', 'many informations'], a: 2, e: '"Information" jest niepoliczalne — bez "an" i bez -s.' },
    { t: 'o', q: 'Ułóż pytanie z rozsypanki:', w: 'How much water do you drink', e: 'Water jest niepoliczalne → How much.' },
  ]
},
{
  id: 'airport', place: 'Skyport Terminal', short: 'AIR', topic: 'Przyszłość: will / going to', level: 'A2', tier: 1,
  block: [7, 4], lot: [1, 0],
  npc: 'Captain Lee, pilotka',
  story: "Attention, passengers! I'm Captain Lee. Plans, predictions, promises — the future is full of them. Pass my briefing and you're cleared for take-off.",
  storyPL: 'Pilotka sprawdza, czy znasz sposoby mówienia o przyszłości.',
  tip: '<b>will</b> — decyzja w chwili mówienia, obietnica, przewidywanie z opinii: <i>I\'ll help you. I think it will rain.</i><br><b>be going to</b> — plan/zamiar lub przewidywanie na podstawie dowodów: <i>Look at those clouds! It\'s going to rain.</i><br><b>Present Continuous</b> — ustalone spotkania: <i>I\'m meeting Tom tonight.</i><br><b>Present Simple</b> — rozkłady jazdy: <i>The plane leaves at 6.</i>',
  questions: [
    { t: 'c', q: "Look at those black clouds! It ___ rain.", o: ['will', 'is going to', 'rains', 'is raining to'], a: 1, e: 'Przewidywanie na podstawie widocznych dowodów → going to.' },
    { t: 'c', q: "— These bags are so heavy! — Don't worry, I ___ them for you.", o: ["'ll carry", 'am going to carry', 'carry', 'carried'], a: 0, e: 'Spontaniczna decyzja / oferta pomocy → will.' },
    { t: 'c', q: 'Our flight ___ at 6:15 tomorrow morning (wg rozkładu).', o: ['leave', 'leaves', 'is leave', 'will leaving'], a: 1, e: 'Rozkład jazdy / lotów → Present Simple.' },
    { t: 'c', q: 'I think she ___ like the present.', o: ['will', 'is going', 'going to', 'shall to'], a: 0, e: 'Opinia, przypuszczenie (I think) → will.' },
    { t: 'c', q: "We ___ visit Grandma next week — we've already bought the tickets.", o: ['will', 'are going to', 'go to', 'shall'], a: 1, e: 'Wcześniej zaplanowany zamiar → going to.' },
    { t: 't', q: 'I promise I ___ call you when I land.', a: ['will', "'ll"], e: 'Obietnica → will.' },
    { t: 'c', q: "What ___ you doing this weekend? — I'm meeting friends.", o: ['will', 'do', 'are', 'going'], a: 2, e: 'Ustalone plany → Present Continuous: What are you doing…?' },
    { t: 't', q: 'Forma skrócona od "will not" to:', a: ["won't"], e: 'Will not → won\'t.' },
    { t: 'c', q: 'By 2050 people ___ probably live on Mars.', o: ['are', 'will', 'going to', 'do'], a: 1, e: 'Przewidywanie odległej przyszłości → will (probably).' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'We are going to fly to London', e: 'Plan: am/is/are + going to + bezokolicznik.' },
  ]
},
/* ============================ B1 ============================ */
{
  id: 'hotel', place: 'Grand Royal Hotel', short: 'HTL', topic: 'Present Perfect', level: 'B1', tier: 2,
  block: [6, 6], lot: [0, 0],
  npc: 'Mr. Blake, recepcjonista',
  story: "Welcome to the Grand Royal. Our guests have travelled everywhere — or have they? I need someone who knows the difference between 'I've been' and 'I went'. Interested?",
  storyPL: 'Recepcjonista hotelu potrzebuje kogoś, kto rozróżnia Present Perfect i Past Simple.',
  tip: '<b>have/has + III forma</b> — doświadczenia, skutki teraz, stan trwający do dziś<br><b>ever, never, just, already, yet</b>: <i>Have you ever been…? I\'ve just arrived. He hasn\'t called yet.</i><br><b>for</b> + okres (<i>for ten years</i>), <b>since</b> + punkt w czasie (<i>since Monday</i>)<br>Konkretny czas w przeszłości (<i>yesterday, in 2019</i>) → <b>Past Simple</b>.',
  questions: [
    { t: 'c', q: 'I ___ never ___ to New York.', o: ['have / been', 'has / been', 'did / be', 'have / went'], a: 0, e: 'Doświadczenie życiowe → I have never been.' },
    { t: 'c', q: 'She ___ just checked in.', o: ['have', 'has', 'is', 'did'], a: 1, e: 'She → has + III forma.' },
    { t: 'c', q: '___ you ever stayed in this hotel?', o: ['Did', 'Were', 'Have', 'Has'], a: 2, e: 'Pytanie o doświadczenie → Have you ever…?' },
    { t: 'c', q: 'I ___ here since Monday.', o: ['am', 'was', 'have been', 'be'], a: 2, e: 'Stan trwający do teraz + since → Present Perfect.' },
    { t: 'c', q: 'He has lived here ___ ten years.', o: ['since', 'for', 'from', 'ago'], a: 1, e: 'Okres czasu → for.' },
    { t: 'c', q: 'I ___ my keys yesterday.', o: ['have lost', 'lost', 'has lost', 'lose'], a: 1, e: '"Yesterday" (konkretny czas) → Past Simple.' },
    { t: 't', q: 'III forma (past participle) od "write":', a: ['written'], e: 'Write – wrote – written.' },
    { t: 't', q: "They haven't arrived ___.", a: ['yet'], e: '"Yet" w przeczeniach i pytaniach, na końcu zdania.' },
    { t: 'c', q: 'She has ___ gone to the pool — you just missed her!', o: ['yet', 'ever', 'just', 'since'], a: 2, e: '"Just" = przed chwilą.' },
    { t: 'o', q: 'Ułóż pytanie z rozsypanki:', w: 'Have you ever lost your passport', e: 'Have + podmiot + ever + III forma.' },
  ]
},
{
  id: 'gym', place: 'Iron Gym', short: 'GYM', topic: 'Czasowniki modalne', level: 'B1', tier: 2,
  block: [0, 3], lot: [1, 1],
  npc: 'Coach Rocky',
  story: "Listen up, rookie! In my gym there are rules. Things you must do, things you mustn't do, and things you don't have to do. Get them right or give me twenty push-ups!",
  storyPL: 'Trener pilnuje zasad siłowni: co musisz, czego nie wolno, a czego nie musisz.',
  tip: '<b>must</b> — obowiązek / pewne przypuszczenie: <i>He must be tired.</i><br><b>mustn\'t</b> — zakaz!<br><b>don\'t have to</b> — nie musisz (brak obowiązku)<br><b>should</b> — rada; <b>can/could</b> — umiejętność, prośba<br><b>might/may</b> — możliwość<br>Przeszłość obowiązku: <b>had to</b>',
  questions: [
    { t: 'c', q: "You ___ wear sports shoes here. It's a rule.", o: ['must', 'might', "don't have to", 'could'], a: 0, e: 'Obowiązek, zasada → must.' },
    { t: 'c', q: "You ___ eat before training if you don't want to.", o: ["mustn't", "don't have to", 'must', "shouldn't to"], a: 1, e: 'Brak obowiązku → don\'t have to.' },
    { t: 'c', q: 'You ___ smoke in the gym! It\'s forbidden.', o: ["don't have to", "mustn't", 'might not', "needn't"], a: 1, e: 'Zakaz → mustn\'t.' },
    { t: 'c', q: '___ I use this machine, please?', o: ['Must', 'Should', 'Could', 'Have'], a: 2, e: 'Uprzejma prośba → Could I…?' },
    { t: 'c', q: 'You look exhausted. You ___ rest.', o: ['should', 'mustn\'t', 'could not', 'had'], a: 0, e: 'Rada → should.' },
    { t: 'c', q: 'She ___ lift 100 kg when she was 20.', o: ['can', 'could', 'must', 'should'], a: 1, e: 'Umiejętność w przeszłości → could.' },
    { t: 't', q: 'It ___ rain later — take an umbrella. (możliwość, 5 liter)', a: ['might'], e: 'Możliwość → might (lub may).' },
    { t: 'c', q: 'His car is outside, so he ___ be at home.', o: ['must', "can't", 'should', 'has to'], a: 0, e: 'Logiczny wniosek, pewność → must be.' },
    { t: 'c', q: 'We ___ wear helmets yesterday.', o: ['must', 'had to', 'have to', 'musted'], a: 1, e: '"Must" nie ma przeszłej formy → had to.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'You should drink more water', e: 'Should + bezokolicznik bez "to".' },
  ]
},
{
  id: 'station', place: 'Union Train Station', short: 'TRN', topic: 'Przyimki czasu i miejsca', level: 'B1', tier: 2,
  block: [4, 0], lot: [0, 0],
  npc: 'Conductor Ben',
  story: "All aboard! Well, almost. Our timetable announcements are full of mistakes: in, on, at — all wrong! Fix them before the 5 o'clock express leaves.",
  storyPL: 'Konduktor ma zapowiedzi pełne błędów w przyimkach. Popraw je przed odjazdem ekspresu.',
  tip: 'Czas: <b>at</b> + godzina, noc, święta (<i>at 5, at night, at Christmas</i>); <b>on</b> + dni i daty (<i>on Monday, on 5th June</i>); <b>in</b> + miesiące, lata, pory dnia (<i>in May, in the evening</i>)<br><b>since</b> — od (punkt w czasie), <b>for</b> — przez (okres)<br>Miejsce: <b>at</b> punkt (<i>at the station</i>), <b>in</b> wewnątrz / miasto (<i>in London</i>), <b>on</b> powierzchnia, peron (<i>on platform 3</i>), <b>between</b> — pomiędzy.',
  questions: [
    { t: 'c', q: "The train leaves ___ 5 o'clock.", o: ['in', 'on', 'at', 'by'], a: 2, e: 'Godzina → at.' },
    { t: 'c', q: 'I was born ___ May.', o: ['on', 'at', 'in', 'by'], a: 2, e: 'Miesiąc → in.' },
    { t: 'c', q: 'See you ___ Monday!', o: ['in', 'on', 'at', 'to'], a: 1, e: 'Dzień tygodnia → on.' },
    { t: 'c', q: 'The ticket office is ___ the café and the shop.', o: ['among', 'between', 'next', 'in'], a: 1, e: 'Pomiędzy dwoma rzeczami → between.' },
    { t: 'c', q: "She's waiting ___ platform 3.", o: ['in', 'at', 'on', 'by'], a: 2, e: 'Peron → on platform.' },
    { t: 'c', q: "I'll arrive ___ London ___ the evening.", o: ['at / in', 'in / in', 'in / at', 'to / on'], a: 1, e: 'Miasto → in; pora dnia → in the evening.' },
    { t: 'c', q: 'I have lived here ___ 2015.', o: ['for', 'from', 'since', 'in'], a: 2, e: 'Punkt początkowy + Present Perfect → since.' },
    { t: 't', q: 'My birthday is ___ 5th June.', a: ['on'], e: 'Konkretna data → on.' },
    { t: 't', q: '___ Christmas we always visit our family. (wielką literą lub małą)', a: ['at'], e: 'Święta jako okres → at Christmas.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'The train arrives at noon on Friday', e: 'at + noon, on + dzień tygodnia.' },
  ]
},
{
  id: 'cinema', place: 'Starlight Cinema', short: 'CIN', topic: 'Gerund czy bezokolicznik', level: 'B1', tier: 2,
  block: [2, 6], lot: [1, 1],
  npc: 'Vince, reżyser',
  story: "Cut! Cut! Cut! My actors keep saying 'I enjoy to watch' and 'I decided going'. It's a disaster! You're the new script doctor — fix the dialogue.",
  storyPL: 'Aktorzy mylą formę -ing z "to". Popraw dialogi w scenariuszu.',
  tip: '<b>-ing</b> po: <i>enjoy, mind, avoid, finish, stop, can\'t stand</i> i po przyimkach (<i>looking forward to seeing</i>)<br><b>to + bezokolicznik</b> po: <i>want, decide, agree, hope, plan, would like</i><br><b>stop doing</b> = przestać; <b>stop to do</b> = zatrzymać się, żeby coś zrobić<br><b>remember to do</b> = pamiętać, żeby zrobić; <b>remember doing</b> = pamiętać, że się zrobiło',
  questions: [
    { t: 'c', q: 'I enjoy ___ horror films.', o: ['to watch', 'watching', 'watch', 'watched'], a: 1, e: 'Enjoy + -ing.' },
    { t: 'c', q: 'She decided ___ a ticket.', o: ['buying', 'to buy', 'buy', 'for buying'], a: 1, e: 'Decide + to + bezokolicznik.' },
    { t: 'c', q: 'Do you mind ___ the window?', o: ['to open', 'open', 'opening', 'opened'], a: 2, e: 'Mind + -ing.' },
    { t: 'c', q: "We're looking forward to ___ the new film.", o: ['see', 'seeing', 'saw', 'be seen'], a: 1, e: '"To" jest tu przyimkiem → -ing: looking forward to seeing.' },
    { t: 'c', q: 'I would like ___ some popcorn.', o: ['eating', 'eat', 'to eat', 'ate'], a: 2, e: 'Would like + to + bezokolicznik.' },
    { t: 'c', q: 'He stopped ___ two years ago. (rzucił palenie)', o: ['to smoke', 'smoking', 'smoke', 'smoked'], a: 1, e: 'Stop doing = przestać coś robić.' },
    { t: 'c', q: 'Remember ___ your phone off during the film!', o: ['turning', 'to turn', 'turn', 'turned'], a: 1, e: 'Remember to do = pamiętaj, żeby coś zrobić.' },
    { t: 't', q: "I can't stand ___ (wait) in queues.", a: ['waiting'], e: 'Can\'t stand + -ing.' },
    { t: 't', q: 'They agreed ___ (meet) at 8. (dwa słowa)', a: ['to meet'], e: 'Agree + to + bezokolicznik.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'I would like to see a comedy', e: 'Would like + to + bezokolicznik.' },
  ]
},
/* ============================ B2 ============================ */
{
  id: 'casino', place: 'Lucky Seven Casino', short: 'CAS', topic: 'Tryby warunkowe 0, 1, 2', level: 'B2', tier: 3,
  block: [7, 7], lot: [1, 1],
  npc: 'Mr. Diamond, właściciel kasyna',
  story: "If you play by my rules, you'll win. If you knew my secrets, you would be rich. Conditionals are my game, kid. Let's see if you can beat the house.",
  storyPL: 'Właściciel kasyna gra w tryby warunkowe. Pokonaj go!',
  tip: '<b>Zero</b>: If + Present, Present — prawdy ogólne: <i>If you heat ice, it melts.</i><br><b>First</b>: If + Present, <b>will</b> — realna przyszłość: <i>If it rains, we\'ll stay home.</i><br><b>Second</b>: If + <b>Past</b>, <b>would</b> — nierealne/hipotetyczne: <i>If I had money, I would travel.</i><br><i>If I <b>were</b> you…</i> — rada<br><b>unless</b> = if not (bez przeczenia po nim)',
  questions: [
    { t: 'c', q: 'If you heat ice, it ___.', o: ['melts', 'will melting', 'would melt', 'melted'], a: 0, e: 'Prawda ogólna → Zero Conditional: Present + Present.' },
    { t: 'c', q: 'If it rains tomorrow, we ___ at home.', o: ['stay', 'would stay', 'will stay', 'stayed'], a: 2, e: 'Realna przyszłość → First Conditional: will.' },
    { t: 'c', q: 'If I ___ a million dollars, I would buy a yacht.', o: ['have', 'had', 'will have', 'would have'], a: 1, e: 'Second Conditional: If + Past Simple.' },
    { t: 'c', q: 'If I were you, I ___ bet all your money.', o: ["won't", "don't", "wouldn't", "didn't"], a: 2, e: 'Rada "If I were you" → would / wouldn\'t.' },
    { t: 'c', q: "Unless you ___ now, you'll lose everything.", o: ['stop', "don't stop", "won't stop", 'stopped'], a: 0, e: '"Unless" = if not; po nim zdanie twierdzące w Present Simple.' },
    { t: 't', q: 'If she ___ (win), she will buy a new car.', a: ['wins'], e: 'First Conditional: If + Present Simple (she wins).' },
    { t: 't', q: 'If I ___ (be) rich, I would travel the world.', a: ['were', 'was'], e: 'Second Conditional; forma "were" jest poprawna dla wszystkich osób.' },
    { t: 'c', q: 'What would you do if you ___ the lottery?', o: ['win', 'won', 'will win', 'would win'], a: 1, e: 'Second Conditional: if + Past Simple (won).' },
    { t: 'c', q: 'If you press this button, the machine ___.', o: ['start', 'starts', 'would start', 'started'], a: 1, e: 'Zawsze tak działa → Zero Conditional.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'If I won I would buy a house', e: 'If + Past Simple, would + bezokolicznik.' },
  ]
},
{
  id: 'museum', place: 'City Museum of Art', short: 'MUS', topic: 'Strona bierna', level: 'B2', tier: 3,
  block: [0, 0], lot: [0, 0],
  npc: 'Dr. Whitmore, kuratorka',
  story: "The museum's audio guide was recorded by someone who never uses the passive voice. 'Leonardo painted it, someone built it, somebody stole it'... Help me rewrite it professionally.",
  storyPL: 'Audioprzewodnik muzeum wymaga poprawienia — użyj strony biernej.',
  tip: '<b>be + III forma</b>; czas pokazuje "be":<br><i>is spoken</i> (Present), <i>was built</i> (Past), <i>has been visited</i> (Present Perfect), <i>will be opened</i> (Future), <i>is being painted</i> (Continuous)<br>Wykonawca po <b>by</b>: <i>painted by Leonardo</i><br>Używamy, gdy ważniejsze jest, <b>co</b> się stało, niż <b>kto</b> to zrobił.',
  questions: [
    { t: 'c', q: 'The Mona Lisa ___ by Leonardo da Vinci.', o: ['painted', 'was painted', 'is painting', 'has painted'], a: 1, e: 'Strona bierna, przeszłość → was + painted.' },
    { t: 'c', q: 'This museum ___ in 1900.', o: ['built', 'was built', 'is built', 'has built'], a: 1, e: 'Konkretny rok → Past Simple Passive: was built.' },
    { t: 'c', q: 'English ___ all over the world.', o: ['speaks', 'is speaking', 'is spoken', 'spoken'], a: 2, e: 'Fakt ogólny → Present Simple Passive: is spoken.' },
    { t: 'c', q: 'The paintings ___ every day.', o: ['are cleaned', 'is cleaned', 'clean', 'are cleaning'], a: 0, e: 'Liczba mnoga, rutyna → are cleaned.' },
    { t: 'c', q: 'The statue ___ stolen last night!', o: ['is', 'was', 'has', 'were'], a: 1, e: 'Last night → was stolen.' },
    { t: 't', q: 'The new gallery ___ (open) next year. (trzy słowa)', a: ['will be opened'], e: 'Future Passive: will be + III forma.' },
    { t: 'c', q: 'The exhibition ___ visited by 5,000 people so far.', o: ['was', 'has been', 'is being', 'have been'], a: 1, e: '"So far" → Present Perfect Passive: has been visited.' },
    { t: 'c', q: 'Sorry, the room ___ being painted right now.', o: ['has', 'was', 'is', 'be'], a: 2, e: 'Present Continuous Passive: is being + III forma.' },
    { t: 't', q: 'III forma od "steal":', a: ['stolen'], e: 'Steal – stole – stolen.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'The museum was opened by the mayor', e: 'was + III forma + by + wykonawca.' },
  ]
},
{
  id: 'news', place: 'Daily Herald', short: 'NEWS', topic: 'Mowa zależna', level: 'B2', tier: 3,
  block: [7, 0], lot: [1, 0],
  npc: 'Chief Editor Harris',
  story: "Stop the press! Our reporter wrote down every quote word for word, but the paper needs reported speech. 'She said she was…', not 'She said I am…'. Deadline is in ten minutes!",
  storyPL: 'Redaktor potrzebuje cytatów przepisanych na mowę zależną. Termin za 10 minut!',
  tip: 'Cofamy czas o jeden: <i>am → was, will → would, can → could, have done → had done, did → had done</i><br>Pytania: szyk zdania twierdzącego, <b>if/whether</b> dla pytań tak/nie: <i>He asked if I was ready.</i><br>Polecenia: <b>told me (not) to do</b><br><b>say</b> something / <b>tell</b> somebody<br>Czas i miejsce: <i>yesterday → the day before, here → there</i>',
  questions: [
    { t: 'c', q: '"I am tired." → She said she ___ tired.', o: ['is', 'was', 'had', 'were been'], a: 1, e: 'Am → was.' },
    { t: 'c', q: '"I will call you." → He said he ___ call me.', o: ['will', 'would', 'shall', 'can'], a: 1, e: 'Will → would.' },
    { t: 'c', q: '"We have finished." → They said they ___ finished.', o: ['have', 'has', 'had', 'were'], a: 2, e: 'Present Perfect → Past Perfect: had finished.' },
    { t: 'c', q: '"Where do you live?" → She asked me where I ___.', o: ['do live', 'lived', 'did live', 'live'], a: 1, e: 'W pytaniu zależnym szyk twierdzący i cofnięcie czasu: where I lived.' },
    { t: 'c', q: 'He ___ me that he was busy.', o: ['said', 'told', 'spoke', 'talked'], a: 1, e: 'Tell somebody → told me; said (bez osoby).' },
    { t: 'c', q: '"Don\'t touch it!" → She told me ___ it.', o: ["don't touch", 'not touch', 'not to touch', 'to not touching'], a: 2, e: 'Zakaz w mowie zależnej: told me not to do.' },
    { t: 't', q: '"I can swim." → He said he ___ swim.', a: ['could'], e: 'Can → could.' },
    { t: 't', q: '"Are you ready?" → He asked ___ I was ready. (2 lub 7 liter)', a: ['if', 'whether'], e: 'Pytanie tak/nie → if / whether.' },
    { t: 'c', q: '"I saw him yesterday." → She said she had seen him ___.', o: ['yesterday', 'the day before', 'tomorrow', 'the next day'], a: 1, e: 'Yesterday → the day before / the previous day.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'She said that she was busy', e: 'Say + (that) + zdanie z cofniętym czasem.' },
  ]
},
{
  id: 'detective', place: 'Noir Detective Agency', short: 'DET', topic: 'Zdania względne', level: 'B2', tier: 3,
  block: [0, 7], lot: [0, 1],
  npc: 'Sam Noir, prywatny detektyw',
  story: "The rain never stops in this part of town, kid. I've got a case: a man who wore a grey coat, a car which vanished, a place where it all began. Connect the clues — with the right words.",
  storyPL: 'Detektyw łączy wskazówki — użyj właściwych zaimków względnych.',
  tip: '<b>who</b> — ludzie · <b>which</b> — rzeczy · <b>that</b> — ludzie/rzeczy (tylko w zdaniach definiujących)<br><b>whose</b> — czyj · <b>where</b> — gdzie · <b>when</b> — kiedy<br>Zdania niedefiniujące (dodatkowa informacja, w przecinkach): <b>nie</b> używamy "that" — <i>My brother, who lives in Oslo, …</i>',
  questions: [
    { t: 'c', q: 'The man ___ stole the car was tall.', o: ['which', 'who', 'whose', 'where'], a: 1, e: 'Osoba → who.' },
    { t: 'c', q: 'The car ___ was stolen is red.', o: ['who', 'whose', 'which', 'where'], a: 2, e: 'Rzecz → which (lub that).' },
    { t: 'c', q: "That's the woman ___ bag was stolen.", o: ['who', 'which', 'whose', "who's"], a: 2, e: 'Czyja torebka → whose.' },
    { t: 'c', q: 'This is the house ___ the crime happened.', o: ['which', 'where', 'when', 'who'], a: 1, e: 'Miejsce → where.' },
    { t: 'c', q: 'I remember the day ___ we met.', o: ['where', 'which', 'when', 'who'], a: 2, e: 'Czas → when.' },
    { t: 'c', q: 'The witness, ___ lives next door, called us.', o: ['that', 'who', 'which', 'whose'], a: 1, e: 'Zdanie niedefiniujące (w przecinkach) o osobie → who, nie "that".' },
    { t: 't', q: 'The detective ___ solved the case got a medal. (osoba)', a: ['who', 'that'], e: 'Osoba w zdaniu definiującym → who lub that.' },
    { t: 'c', q: 'The gun, ___ was found in the river, belonged to him.', o: ['that', 'who', 'which', 'what'], a: 2, e: 'Rzecz w zdaniu niedefiniującym → which.' },
    { t: 't', q: 'Paris is the city ___ I was born.', a: ['where'], e: 'Miejsce → where.' },
    { t: 'o', q: 'Ułóż zdanie z rozsypanki:', w: 'The man who called me was a detective', e: 'Who odnosi się do osoby (the man).' },
  ]
},
/* ============================ FINAL ============================ */
{
  id: 'cityhall', place: 'City Hall', short: 'HALL', topic: 'Egzamin końcowy — wszystkie tematy', level: 'FINAL', tier: 4,
  cityHall: [3, 3], final: true,
  npc: 'Mayor Johnson, burmistrz',
  story: "So you're the one everybody is talking about. You've helped the whole city. One last test — a bit of everything. Pass it and I'll give you the key to Grammar City.",
  storyPL: 'Burmistrz przygotował egzamin końcowy z każdego tematu. Zdaj go, a dostaniesz klucz do miasta.',
  tip: 'Egzamin losuje pytania ze <b>wszystkich 18 tematów</b>. Zanim zaczniesz, przypomnij sobie:<br>czasy (Present Simple/Continuous, Past Simple, Present Perfect, przyszłość), przedimki, stopniowanie, modalne, przyimki, gerund/bezokolicznik, tryby warunkowe, stronę bierną, mowę zależną i zdania względne.',
  questions: []
}
];

window.TIERS = [
  { name: 'A1', need: 0, color: '#45d483' },
  { name: 'A2', need: 3, color: '#4fb3ff' },
  { name: 'B1', need: 7, color: '#f2b632' },
  { name: 'B2', need: 10, color: '#ff7a4d' },
  { name: 'FINAL', need: 18, color: '#c77dff' },
];
